add_executable(bedrock_protocol_tests)
target_sources(bedrock_protocol_tests PRIVATE
        fixture.hpp
        test_enum.cpp
        test_094_sub_client_login.cpp
        test_008_resource_pack_client_response.cpp
        test_006_resource_packs_info.cpp
        test_145_creative_content.cpp
        test_052_crafting_data.cpp
        test_326_player_location.cpp
        test_325_player_update_entity_overrides.cpp
        test_180_dimension_data.cpp
        test_302_trim_data.cpp
        test_085_transfer.cpp
        test_086_play_sound.cpp
        test_141_anvil_damage.cpp
        test_packet.cpp
        test_001_login.cpp
        test_011_start_game.cpp
        test_030_inventory_transaction.cpp
        test_032_mob_armor_equipment.cpp
        test_049_inventory_content.cpp
        test_058_level_chunk.cpp
        test_074_boss_event.cpp
        test_122_biome_definition_list.cpp
        test_123_level_sound_event.cpp
        test_135_client_cache_blob_status.cpp
        test_156_packet_violation_warning.cpp
        test_175_sub_chunk_request.cpp
        test_193_request_network_settings.cpp
        test_315_serverbound_diagnostics.cpp
        test_328_primitive_shapes.cpp
        test_331_graphics_override_parameter.cpp
        test_345_attribute_layer_sync.cpp
        test_347_server_presence_info.cpp
        test_348_update_sound_data.cpp
)
target_link_libraries(bedrock_protocol_tests PRIVATE bedrock::protocol Catch2::Catch2WithMain)

include(Catch)
catch_discover_tests(bedrock_protocol_tests)
