#include <cstdint>
#include <string>
#include <vector>

#include <protocol/command.h>
#include <protocol/movement.h>

#include "fixture.hpp"

namespace {

bp::AvailableCommandsPacket_<2168> fill()
{
    bp::AvailableCommandsPacket_<2168> pkt;
    pkt.enum_values = {"true", "false"};
    pkt.chained_subcommand_values = {"as"};
    pkt.postfixes = {"L"};

    bp::AvailableCommandsPacket_<2168>::EnumData enum_data;
    enum_data.name = "Boolean";
    enum_data.values = {0, 1};
    pkt.enums.push_back(enum_data);

    bp::AvailableCommandsPacket_<2168>::ChainedSubcommandRelationship relationship;
    relationship.sub_command_first_value = 0;
    relationship.sub_command_second_value = 300;

    bp::AvailableCommandsPacket_<2168>::ChainedSubcommandData chained;
    chained.name = "execute";
    chained.values.push_back(relationship);
    pkt.chained_subcommands.push_back(chained);

    bp::AvailableCommandsPacket_<2168>::ParamData param;
    param.name = "arg";
    param.parse_symbol = 0x00100001;
    param.optional = true;
    param.param_options = 1;

    bp::AvailableCommandsPacket_<2168>::OverloadData overload;
    overload.is_chaining = true;
    overload.params.push_back(param);

    bp::AvailableCommandsPacket_<2168>::CommandData command;
    command.name = "test";
    command.description = "a test";
    command.flags = 0x0102;
    command.permission = bp::CommandPermissionLevel::ADMIN;
    command.alias_enum = -1;
    command.chained_subcommand_indexes = {0};
    command.overloads.push_back(overload);
    pkt.commands.push_back(command);

    bp::AvailableCommandsPacket_<2168>::SoftEnumData soft_enum;
    soft_enum.name = "soft";
    soft_enum.values = {"a"};
    pkt.soft_enums.push_back(soft_enum);

    bp::AvailableCommandsPacket_<2168>::ConstrainedValueData constraint;
    constraint.enum_value_symbol = 1;
    constraint.enum_symbol = 0;
    constraint.constraints = {0x00, 0x02};
    pkt.constraints.push_back(constraint);

    return pkt;
}

// generated by gophertunnel v1.57.1:
// &packet.AvailableCommands{EnumValues: []string{"true", "false"},
//   ChainedSubcommandValues: []string{"as"}, Suffixes: []string{"L"},
//   Enums: []protocol.CommandEnum{{Type: "Boolean", ValueIndices: []uint32{0, 1}}},
//   ChainedSubcommands: []protocol.ChainedSubcommand{{Name: "execute",
//     Values: []protocol.ChainedSubcommandValue{{Index: 0, Value: 300}}}},
//   Commands: []protocol.Command{{Name: "test", Description: "a test", Flags: 0x0102,
//     PermissionLevel: protocol.CommandPermissionLevelAdmin, AliasesOffset: 0xffffffff,
//     ChainedSubcommandOffsets: []uint32{0},
//     Overloads: []protocol.CommandOverload{{Chaining: true,
//       Parameters: []protocol.CommandParameter{{Name: "arg", Type: 0x00100001,
//         Optional: true, Options: 1}}}}}},
//   DynamicEnums: []protocol.DynamicEnum{{Type: "soft", Values: []string{"a"}}},
//   Constraints: []protocol.CommandEnumConstraint{{EnumValueIndex: 1, EnumIndex: 0,
//     Constraints: []byte{0x00, 0x02}}}}
// The permission level is name-coded, so the five bytes at offset 66 read "admin" there
// and "ADMIN" here: BDS lowercases before the lookup, and ADMIN carries no separator.
const std::string golden = bytes({
    0x02, 0x04, 0x74, 0x72, 0x75, 0x65, 0x05, 0x66, 0x61, 0x6c, 0x73, 0x65,
    0x01, 0x02, 0x61, 0x73, 0x01, 0x01, 0x4c, 0x01, 0x07, 0x42, 0x6f, 0x6f,
    0x6c, 0x65, 0x61, 0x6e, 0x02, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
    0x00, 0x01, 0x07, 0x65, 0x78, 0x65, 0x63, 0x75, 0x74, 0x65, 0x01, 0x00,
    0xac, 0x02, 0x01, 0x04, 0x74, 0x65, 0x73, 0x74, 0x06, 0x61, 0x20, 0x74,
    0x65, 0x73, 0x74, 0x02, 0x01, 0x05, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0xff,
    0xff, 0xff, 0xff, 0x01, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01, 0x03,
    0x61, 0x72, 0x67, 0x01, 0x00, 0x10, 0x00, 0x01, 0x01, 0x01, 0x04, 0x73,
    0x6f, 0x66, 0x74, 0x01, 0x01, 0x61, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x02, 0x00, 0x02,
});

// generated by gophertunnel v1.57.1: &packet.AvailableCommands{}
const std::string golden_empty = bytes({
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("AvailableCommandsPacket: packet id is 76")
{
    STATIC_REQUIRE(bp::AvailableCommandsPacket_<2168>::Id == 76);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 76>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 76>);
}

TEST_CASE("AvailableCommandsPacket: round-trips against the golden")
{
    REQUIRE(encode(fill()) == golden);

    const auto back = decode<bp::AvailableCommandsPacket_<2168>>(golden);
    REQUIRE(back.enum_values == std::vector<std::string>{"true", "false"});
    REQUIRE(back.chained_subcommand_values == std::vector<std::string>{"as"});
    REQUIRE(back.postfixes == std::vector<std::string>{"L"});

    REQUIRE(back.enums.size() == 1);
    REQUIRE(back.enums[0].name == "Boolean");
    REQUIRE(back.enums[0].values == std::vector<std::uint32_t>{0, 1});

    REQUIRE(back.chained_subcommands.size() == 1);
    REQUIRE(back.chained_subcommands[0].name == "execute");
    REQUIRE(back.chained_subcommands[0].values.size() == 1);
    REQUIRE(back.chained_subcommands[0].values[0].sub_command_first_value == 0);
    REQUIRE(back.chained_subcommands[0].values[0].sub_command_second_value == 300);

    REQUIRE(back.commands.size() == 1);
    REQUIRE(back.commands[0].name == "test");
    REQUIRE(back.commands[0].description == "a test");
    REQUIRE(back.commands[0].flags == 0x0102);
    REQUIRE(back.commands[0].permission == bp::CommandPermissionLevel::ADMIN);
    REQUIRE(back.commands[0].alias_enum == -1);
    REQUIRE(back.commands[0].chained_subcommand_indexes == std::vector<std::uint32_t>{0});
    REQUIRE(back.commands[0].overloads.size() == 1);
    REQUIRE(back.commands[0].overloads[0].is_chaining);
    REQUIRE(back.commands[0].overloads[0].params.size() == 1);
    REQUIRE(back.commands[0].overloads[0].params[0].name == "arg");
    REQUIRE(back.commands[0].overloads[0].params[0].parse_symbol == 0x00100001);
    REQUIRE(back.commands[0].overloads[0].params[0].optional);
    REQUIRE(back.commands[0].overloads[0].params[0].param_options == 1);

    REQUIRE(back.soft_enums.size() == 1);
    REQUIRE(back.soft_enums[0].name == "soft");
    REQUIRE(back.soft_enums[0].values == std::vector<std::string>{"a"});

    REQUIRE(back.constraints.size() == 1);
    REQUIRE(back.constraints[0].enum_value_symbol == 1);
    REQUIRE(back.constraints[0].enum_symbol == 0);
    REQUIRE(back.constraints[0].constraints == std::vector<std::uint8_t>{0x00, 0x02});
}

TEST_CASE("AvailableCommandsPacket: eight empty lists are eight zero bytes")
{
    REQUIRE(encode(bp::AvailableCommandsPacket_<2168>{}) == golden_empty);

    const auto back = decode<bp::AvailableCommandsPacket_<2168>>(golden_empty);
    REQUIRE(back.enum_values.empty());
    REQUIRE(back.chained_subcommand_values.empty());
    REQUIRE(back.postfixes.empty());
    REQUIRE(back.enums.empty());
    REQUIRE(back.chained_subcommands.empty());
    REQUIRE(back.commands.empty());
    REQUIRE(back.soft_enums.empty());
    REQUIRE(back.constraints.empty());
}

TEST_CASE("AvailableCommandsPacket: the subcommand relationship is varint where the enum indices are fixed")
{
    bp::AvailableCommandsPacket_<2168> pkt;

    bp::AvailableCommandsPacket_<2168>::EnumData enum_data;
    enum_data.values = {300};
    pkt.enums.push_back(enum_data);

    bp::AvailableCommandsPacket_<2168>::ChainedSubcommandRelationship relationship;
    relationship.sub_command_first_value = 300;
    relationship.sub_command_second_value = 300;

    bp::AvailableCommandsPacket_<2168>::ChainedSubcommandData chained;
    chained.values.push_back(relationship);
    pkt.chained_subcommands.push_back(chained);

    const auto wire = encode(pkt);
    REQUIRE(wire.size() == 8 + (1 + 1 + 4) + (1 + 1 + 2 + 2));

    const auto back = decode<bp::AvailableCommandsPacket_<2168>>(wire);
    REQUIRE(back.enums[0].values == std::vector<std::uint32_t>{300});
    REQUIRE(back.chained_subcommands[0].values[0].sub_command_first_value == 300);
    REQUIRE(back.chained_subcommands[0].values[0].sub_command_second_value == 300);
}
