#include <string>

#include <bedrock/protocol/scoreboard.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.SetDisplayObjective{DisplaySlot: "sidebar",
// ObjectiveName: "objective", DisplayName: "Scores", CriteriaName: "dummy",
// SortOrder: packet.ScoreboardSortOrderDescending}
const std::string golden = bytes({
    0x07, 0x73, 0x69, 0x64, 0x65, 0x62, 0x61, 0x72, 0x09, 0x6f, 0x62, 0x6a,
    0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x06, 0x53, 0x63, 0x6f, 0x72, 0x65,
    0x73, 0x05, 0x64, 0x75, 0x6d, 0x6d, 0x79, 0x02,
});

// generated by gophertunnel: &packet.SetDisplayObjective{}
const std::string golden_ascending = bytes({
    0x00, 0x00, 0x00, 0x00, 0x00,
});

// generated by gophertunnel:
// &packet.SetDisplayObjective{SortOrder: packet.ScoreboardSortOrderDescending}
const std::string golden_descending = bytes({
    0x00, 0x00, 0x00, 0x00, 0x02,
});

}  // namespace

TEST_CASE("packet id is 107")
{
    STATIC_REQUIRE(bp::SetDisplayObjectivePacket::Id == 107);
    STATIC_REQUIRE(bp::has_packet_v<1001, 107>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 107>);
}

TEST_CASE("set display objective round-trips against the golden")
{
    bp::SetDisplayObjectivePacket packet;
    packet.display_slot_name = "sidebar";
    packet.objective_name = "objective";
    packet.objective_display_name = "Scores";
    packet.criteria_name = "dummy";
    packet.sort_order = bp::ObjectiveSortOrder::Descending;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::SetDisplayObjectivePacket>(golden);
    REQUIRE(back.display_slot_name == "sidebar");
    REQUIRE(back.objective_name == "objective");
    REQUIRE(back.objective_display_name == "Scores");
    REQUIRE(back.criteria_name == "dummy");
    REQUIRE(back.sort_order == bp::ObjectiveSortOrder::Descending);
}

TEST_CASE("the sort order is a zigzag varint, not the enum's byte")
{
    bp::SetDisplayObjectivePacket ascending;
    ascending.sort_order = bp::ObjectiveSortOrder::Ascending;
    REQUIRE(encode(ascending) == golden_ascending);

    bp::SetDisplayObjectivePacket descending;
    descending.sort_order = bp::ObjectiveSortOrder::Descending;
    REQUIRE(encode(descending) == golden_descending);

    REQUIRE(decode<bp::SetDisplayObjectivePacket>(golden_descending).sort_order ==
            bp::ObjectiveSortOrder::Descending);
}

TEST_CASE("a display name over 127 bytes takes a two-byte length prefix")
{
    bp::SetDisplayObjectivePacket packet;
    packet.objective_display_name = std::string(200, 'x');
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 206);

    const auto back = decode<bp::SetDisplayObjectivePacket>(wire);
    REQUIRE(back.objective_display_name == std::string(200, 'x'));
    REQUIRE(back.criteria_name.empty());
}
