#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ClientCacheMissResponsePacket: round-trip")
{
    STATIC_REQUIRE(bp::ClientCacheMissResponsePacket::Id == 136);

    bp::ClientCacheMissResponsePacket pkt;
    pkt.blobs.push_back(bp::MissingBlobData{0xAAAABBBBCCCCDDDDULL, "blob"});

    // generated by gophertunnel:
    // packet.ClientCacheMissResponse{
    //   Blobs: []protocol.CacheBlob{{Hash: 0xAAAABBBBCCCCDDDD, Payload: []byte("blob")}}}
    const std::vector<std::uint8_t> golden{
        0x01, 0xDD, 0xDD, 0xCC, 0xCC, 0xBB, 0xBB, 0xAA, 0xAA, 0x04, 0x62, 0x6C,
        0x6F, 0x62,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ClientCacheMissResponsePacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->blobs.size() == 1);
    REQUIRE(rt->blobs[0].blob_id == 0xAAAABBBBCCCCDDDDULL);
    REQUIRE(rt->blobs[0].blob_data == "blob");
}
