#include <array>
#include <cstdint>
#include <string>

#include "fixture.hpp"

namespace {

using PacketV975 = bp::SubChunkPacket_<975>;
using PacketV1001 = bp::SubChunkPacket_<1001>;
using PacketV2168 = bp::SubChunkPacket_<2168>;

const std::string payload_a = std::string("\xaa", 1);

// generated by gophertunnel (0a2ecd563):
// packet.SubChunk{CacheEnabled: false, Dimension: 1,
//   Position: protocol.SubChunkPos{1, 2, 3},
//   SubChunkEntries: []protocol.SubChunkEntry{{
//     Offset: protocol.SubChunkOffset{-1, 0, 1},
//     Result: protocol.SubChunkResultSuccess, RawPayload: []byte{0xaa},
//     HeightMapType: protocol.HeightMapDataNone,
//     RenderHeightMapType: protocol.HeightMapDataNone}}}
const std::string golden_v1001_uncached = bytes({
    0x00, 0x02, 0x02, 0x04, 0x06, 0x01, 0x00, 0x00, 0x00, 0xff, 0x00, 0x01,
    0x01, 0x01, 0xaa, 0x00, 0x00,
});

// generated by gophertunnel (0a2ecd563): the same packet with CacheEnabled true
// and the entry's Result protocol.SubChunkResultSuccessAllAir, no RawPayload,
// HeightMapType protocol.HeightMapDataHasData carrying 256 bytes of 0x07, and
// BlobHash 9
const std::string golden_v1001_cached = bytes({
    0x01, 0x02, 0x02, 0x04, 0x06, 0x01, 0x00, 0x00, 0x00, 0xff, 0x00, 0x01,
    0x06, 0x01, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x00, 0x09, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00,
});

// generated by CloudburstMC Bedrock_v2168:
// SubChunkPacket{cacheEnabled: false, dimension: 1, centerPosition: (1, 2, 3),
//   subChunks: [SubChunkData{position: (-1, 0, 1), result: SUCCESS, data: aa,
//     heightMapType: NO_DATA, heightMapData: null,
//     renderHeightMapType: NO_DATA, renderHeightMapData: null, blobId: null}]}
const std::string golden_v2168_uncached = bytes({
    0x00, 0x02, 0x01, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x03, 0x00,
    0x00, 0x00, 0x01, 0xff, 0x00, 0x01, 0x01, 0x01, 0x01, 0xaa, 0x00, 0x00,
    0x00, 0x00, 0x00,
});

// generated by CloudburstMC Bedrock_v2168: the same packet with cacheEnabled
// true and the entry's result SUCCESS_ALL_AIR, data null, heightMapType HAS_DATA
// carrying 256 bytes of 0x07, and blobId 9
const std::string golden_v2168_cached = bytes({
    0x01, 0x02, 0x01, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x03, 0x00,
    0x00, 0x00, 0x01, 0xff, 0x00, 0x01, 0x06, 0x00, 0x01, 0x01, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07, 0x07,
    0x07, 0x07, 0x00, 0x00, 0x01, 0x09, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00,
});

using HeightMap = std::array<std::array<std::int8_t, 16>, 16>;

const HeightMap full_height_map = [] {
    HeightMap map{};
    for (auto &row : map) {
        row.fill(7);
    }
    return map;
}();

}  // namespace

TEST_CASE("packet id is 174 at every version")
{
    STATIC_REQUIRE(PacketV975::Id == 174);
    STATIC_REQUIRE(PacketV1001::Id == 174);
    STATIC_REQUIRE(PacketV2168::Id == 174);
}

// With the cache off BDS writes the entry payload unconditionally and appends no
// blob id, which is the shape the uncached entry list carries.
TEST_CASE("sub-chunk v1001 cache-off form round-trips against the golden")
{
    PacketV1001 packet;
    packet.cache_enabled = false;
    packet.dimension_type = static_cast<bp::DimensionType>(1);
    packet.center_pos_x = 1;
    packet.center_pos_y = 2;
    packet.center_pos_z = 3;

    PacketV1001::UncachedSubChunkPacketData entry;
    entry.sub_chunk_pos_offset = {.x = -1, .y = 0, .z = 1};
    entry.result = PacketV1001::SubChunkRequestResult::SUCCESS;
    entry.serialized_sub_chunk = payload_a;
    entry.height_map_data.height_map_type = PacketV1001::HeightMapDataType::NO_DATA;
    entry.height_map_data.render_height_map_type = PacketV1001::HeightMapDataType::NO_DATA;
    packet.uncached_sub_chunk_data.push_back(entry);

    REQUIRE(encode(packet) == golden_v1001_uncached);

    const auto back = decode<PacketV1001>(golden_v1001_uncached);
    REQUIRE(back.center_pos_x == 1);
    REQUIRE(back.center_pos_z == 3);
    REQUIRE(back.sub_chunk_data.empty());
    REQUIRE(back.uncached_sub_chunk_data.size() == 1);
    REQUIRE(back.uncached_sub_chunk_data[0].sub_chunk_pos_offset.x == -1);
    REQUIRE(back.uncached_sub_chunk_data[0].serialized_sub_chunk == payload_a);
}

// With the cache on the payload is dropped for SuccessAllAir and a blob id is
// appended. The height map is 256 bytes -- sixteen columns of sixteen.
TEST_CASE("sub-chunk v1001 cache-on form round-trips against the golden")
{
    PacketV1001 packet;
    packet.cache_enabled = true;
    packet.dimension_type = static_cast<bp::DimensionType>(1);
    packet.center_pos_x = 1;
    packet.center_pos_y = 2;
    packet.center_pos_z = 3;

    PacketV1001::SubChunkPacketData entry;
    entry.sub_chunk_pos_offset = {.x = -1, .y = 0, .z = 1};
    entry.result = PacketV1001::SubChunkRequestResult::SUCCESS_ALL_AIR;
    entry.height_map_data.height_map_type = PacketV1001::HeightMapDataType::HAS_DATA;
    entry.height_map_data.subchunk_height_map = full_height_map;
    entry.height_map_data.render_height_map_type = PacketV1001::HeightMapDataType::NO_DATA;
    entry.blob_id = 9;
    packet.sub_chunk_data.push_back(entry);

    REQUIRE(encode(packet) == golden_v1001_cached);

    const auto back = decode<PacketV1001>(golden_v1001_cached);
    REQUIRE(back.uncached_sub_chunk_data.empty());
    REQUIRE(back.sub_chunk_data.size() == 1);
    REQUIRE(back.sub_chunk_data[0].serialized_sub_chunk.empty());
    REQUIRE(back.sub_chunk_data[0].height_map_data.subchunk_height_map == full_height_map);
    REQUIRE(back.sub_chunk_data[0].height_map_data.subchunk_render_height_map == HeightMap{});
    REQUIRE(back.sub_chunk_data[0].blob_id == 9);
}

TEST_CASE("sub-chunk is unchanged between v975 and v1001")
{
    PacketV975 older;
    older.cache_enabled = false;
    older.dimension_type = static_cast<bp::DimensionType>(1);
    older.center_pos_x = 1;
    older.center_pos_y = 2;
    older.center_pos_z = 3;

    PacketV975::UncachedSubChunkPacketData entry;
    entry.sub_chunk_pos_offset = {.x = -1, .y = 0, .z = 1};
    entry.result = PacketV975::SubChunkRequestResult::SUCCESS;
    entry.serialized_sub_chunk = payload_a;
    entry.height_map_data.height_map_type = PacketV975::HeightMapDataType::NO_DATA;
    entry.height_map_data.render_height_map_type = PacketV975::HeightMapDataType::NO_DATA;
    older.uncached_sub_chunk_data.push_back(entry);

    REQUIRE(encode(older) == golden_v1001_uncached);
}

// The cerealised entry is one shape for both cache modes: every field BDS used
// to gate on the packet now carries its own presence byte.
TEST_CASE("sub-chunk v2168 cache-off form round-trips against the golden")
{
    PacketV2168 packet;
    packet.cache_enabled = false;
    packet.dimension_type = static_cast<bp::DimensionType>(1);
    packet.center_pos = {.x = 1, .y = 2, .z = 3};

    PacketV2168::SubChunkPacketData entry;
    entry.sub_chunk_pos_offset = {.x = -1, .y = 0, .z = 1};
    entry.result = PacketV2168::SubChunkRequestResult::SUCCESS;
    entry.serialized_sub_chunk = payload_a;
    entry.height_map_data.height_map_type = PacketV2168::HeightMapDataType::NO_DATA;
    entry.height_map_data.render_height_map_type = PacketV2168::HeightMapDataType::NO_DATA;
    packet.sub_chunk_data.push_back(entry);

    REQUIRE(encode(packet) == golden_v2168_uncached);

    const auto back = decode<PacketV2168>(golden_v2168_uncached);
    REQUIRE(back.center_pos.x == 1);
    REQUIRE(back.center_pos.z == 3);
    REQUIRE(back.sub_chunk_data.size() == 1);
    REQUIRE(back.sub_chunk_data[0].serialized_sub_chunk == payload_a);
    REQUIRE(back.sub_chunk_data[0].height_map_data.subchunk_height_map.has_value() == false);
    REQUIRE(back.sub_chunk_data[0].blob_id.has_value() == false);
}

TEST_CASE("sub-chunk v2168 cache-on form round-trips against the golden")
{
    PacketV2168 packet;
    packet.cache_enabled = true;
    packet.dimension_type = static_cast<bp::DimensionType>(1);
    packet.center_pos = {.x = 1, .y = 2, .z = 3};

    PacketV2168::SubChunkPacketData entry;
    entry.sub_chunk_pos_offset = {.x = -1, .y = 0, .z = 1};
    entry.result = PacketV2168::SubChunkRequestResult::SUCCESS_ALL_AIR;
    entry.height_map_data.height_map_type = PacketV2168::HeightMapDataType::HAS_DATA;
    entry.height_map_data.subchunk_height_map = full_height_map;
    entry.height_map_data.render_height_map_type = PacketV2168::HeightMapDataType::NO_DATA;
    entry.blob_id = 9;
    packet.sub_chunk_data.push_back(entry);

    REQUIRE(encode(packet) == golden_v2168_cached);

    const auto back = decode<PacketV2168>(golden_v2168_cached);
    REQUIRE(back.sub_chunk_data.size() == 1);
    REQUIRE(back.sub_chunk_data[0].serialized_sub_chunk.has_value() == false);
    REQUIRE(back.sub_chunk_data[0].height_map_data.subchunk_height_map == full_height_map);
    REQUIRE(back.sub_chunk_data[0].height_map_data.subchunk_render_height_map.has_value() == false);
    REQUIRE(back.sub_chunk_data[0].blob_id == 9);
}

// Three breaks at once: the centre position went from three varint32 to three
// fixed int32, the entry count from a fixed uint32 to a uvarint32, and every
// per-entry gate became an optional carrying a presence byte.
TEST_CASE("the cerealisation reshapes the wire in three places at once")
{
    REQUIRE(golden_v1001_uncached.size() == 17);
    REQUIRE(golden_v2168_uncached.size() == 27);
    REQUIRE(golden_v1001_cached.size() == 279);
    REQUIRE(golden_v2168_cached.size() == 289);

    // Neither era's body survives being read as the other: the fixed int32
    // centre swallows the varint entry count and the varint centre leaves the
    // fixed count misaligned, so both reads run off the end of the frame.
    REQUIRE(rejects<PacketV2168>(golden_v1001_uncached));
    REQUIRE(rejects<PacketV1001>(golden_v2168_uncached));
}
