#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

namespace {

// The user-data buffer gophertunnel emits for an item with no NBT, no
// can-place/can-break entries and no shield blocking tick: an int16 NBT-length
// of 0, then a uint32 can-place count of 0 and a uint32 can-break count of 0.
const std::string kEmptyUserData(10, '\0');

}  // namespace

namespace {

template <typename T>
std::vector<std::uint8_t> encode(const T &value)
{
    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, value);
    return buf;
}

}  // namespace

TEST_CASE("InventorySlotPacket v975: optional Container and StorageItem, cereal NewItem")
{
    STATIC_REQUIRE(bp::InventorySlotPacket::Id == 50);

    bp::InventorySlotPacket pkt;
    pkt.inventory_id = 1;
    pkt.slot = 3;
    pkt.full_container_name = bp::FullContainerName{};
    pkt.full_container_name->name = bp::ContainerEnumName::InventoryContainer;
    pkt.full_container_name->dynamic_id = 42;
    pkt.storage_item = bp::SerializedNetworkItemStackDescriptor{};
    pkt.storage_item->id = 7;
    pkt.storage_item->stack_size = 1;
    pkt.storage_item->aux_value = 0;
    pkt.storage_item->net_id_variant = std::nullopt;
    pkt.storage_item->block_runtime_id = 0;
    pkt.storage_item->user_data_buffer = kEmptyUserData;
    pkt.item.id = 10;
    pkt.item.stack_size = 1;
    pkt.item.aux_value = 0;
    pkt.item.net_id_variant = std::nullopt;
    pkt.item.block_runtime_id = 0;
    pkt.item.user_data_buffer = kEmptyUserData;

    // generated by gophertunnel:
    // packet.InventorySlot{WindowID: 1, Slot: 3, Container: protocol.Option(protocol.FullContainerName{ContainerID: 29, DynamicContainerID: protocol.Option[uint32](42)}), StorageItem: protocol.Option(protocol.ItemInstance{Stack: protocol.ItemStack{ItemType: protocol.ItemType{NetworkID: 7}, Count: 1}}), NewItem: protocol.ItemInstance{Stack: protocol.ItemStack{ItemType: protocol.ItemType{NetworkID: 10}, Count: 1}}}
    const std::vector<std::uint8_t> golden{
        0x01, 0x03, 0x01, 0x1D, 0x01, 0x2A, 0x00, 0x00, 0x00, 0x01, 0x07, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x0A, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x0A,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    };
    REQUIRE(encode(pkt) == golden);

    bp::BinaryReader in{golden};
    auto rt = bp::deserialize<bp::InventorySlotPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->full_container_name.has_value());
    REQUIRE(rt->full_container_name->name == bp::ContainerEnumName::InventoryContainer);
    REQUIRE(rt->full_container_name->dynamic_id.has_value());
    REQUIRE(*rt->full_container_name->dynamic_id == 42);
    REQUIRE(rt->storage_item.has_value());
    REQUIRE(rt->storage_item->id == 7);
    REQUIRE(rt->item.id == 10);
    REQUIRE(in.getUnreadLength() == 0);
}

TEST_CASE("InventorySlotPacket v944: Container is non-optional, items are legacy descriptors")
{
    bp::InventorySlotPacket_<944> pkt;
    pkt.inventory_id = 0;
    pkt.slot = 5;
    pkt.full_container_name.name = bp::ContainerEnumName::InventoryContainer;
    pkt.full_container_name.dynamic_id = std::nullopt;
    // air storage_item + air item -- the legacy descriptor's id == 0 shortcut omits the body.
    pkt.storage_item.id = 0;
    pkt.item.id = 0;

    // generated by gophertunnel @eed76a6:
    // packet.InventorySlot{WindowID: 0, Slot: 5, Container: protocol.FullContainerName{ContainerID: 29}, StorageItem: protocol.ItemInstance{}, NewItem: protocol.ItemInstance{}}
    const std::vector<std::uint8_t> golden{
        0x00, 0x05, 0x1D, 0x00, 0x00, 0x00,
    };
    REQUIRE(encode(pkt) == golden);

    bp::BinaryReader in{golden};
    auto rt = bp::deserialize<bp::InventorySlotPacket_<944>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->full_container_name.name == bp::ContainerEnumName::InventoryContainer);
    REQUIRE_FALSE(rt->full_container_name.dynamic_id.has_value());
    REQUIRE(rt->storage_item.id == 0);
    REQUIRE(rt->item.id == 0);
    REQUIRE(in.getUnreadLength() == 0);
}
