#include <cstdint>
#include <string>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

namespace {

template <class T>
std::vector<std::uint8_t> encode(const T &value)
{
    std::string buffer;
    bp::BinaryWriter writer{buffer};
    bp::Serializer<T>::serialize(writer, value);
    return {buffer.begin(), buffer.end()};
}

// StartGamePacket is still hand-written at 1001, so protocol-docs cannot describe
// it: r26_u3 IS network version 1001 and carries no StartGamePacket.json, while
// r26_u4 is network version 2168, already past the cerealisation that dropped
// is_chat_logging and rewrote the enums to uvarint32. gophertunnel is the wire.
template <class Packet>
void fill(Packet &packet)
{
    packet.entity_id = static_cast<bp::ActorUniqueID>(1);
    packet.runtime_id = static_cast<bp::ActorRuntimeID>(2);
    packet.entity_game_type = bp::GameType::SURVIVAL;
    packet.pos = {.x = 1.0f, .y = 2.0f, .z = 3.0f};
    packet.rot = {.x = 4.0f, .y = 5.0f};

    auto &s = packet.settings;
    s.seed = 7;
    s.spawn_settings = {.type = bp::SpawnBiomeType::DEFAULT,
                        .user_defined_biome_name = "",
                        .dimension = static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::OVERWORLD;
    s.game_type = bp::GameType::SURVIVAL;
    s.is_hardcore = false;
    s.game_difficulty = bp::Difficulty::NORMAL;
    s.default_spawn = {.x = 0, .y = 64, .z = 0};
    s.achievements_disabled = true;
    s.editor_world_type = bp::EditorWorldType::NON_EDITOR;
    s.is_created_in_editor = false;
    s.is_exported_from_editor = false;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::NONE;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::FRIENDS_ONLY;
    s.platform_broadcast_intent = bp::GamePublishSetting::FRIENDS_ONLY;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules.push_back({.name = "dodaylightcycle", .can_be_modified_by_player = false, .value = true});
    s.experiments_previously_toggled = false;
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::MEMBER;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.persona_disabled = false;
    s.custom_skins_disabled = false;
    s.emote_chat_muted = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::NORMAL;
    s.edu_shared_uri_resource = {.button_name = "", .link_uri = ""};
    s.override_force_experimental_gameplay = std::nullopt;
    s.chat_restriction_level = bp::ChatRestrictionLevel::NONE;
    s.disable_player_interactions = false;

    packet.level_id = "lvl";
    packet.level_name = "world";
    packet.template_content_identity = "";
    packet.is_trial = false;
    packet.movement_settings = {.rewind_history_size = 40, .server_authoritative_block_breaking = false};
    packet.level_current_time = 100;
    packet.enchantment_seed = 0;
    packet.multiplayer_correlation_id = "";
    packet.enable_item_stack_net_manager = true;
    packet.server_version = "1.21.0";
    packet.server_block_type_registry_checksum = 0;
    packet.world_template_id = {};
    packet.server_enabled_client_side_generation = false;
    packet.block_network_ids_are_hashes = true;
    packet.network_permissions = {.server_auth_sound_enabled = false};
    packet.server_configuration_join_info = std::nullopt;
    packet.server_telemetry_data = {};
}

}  // namespace

TEST_CASE("StartGamePacket: id")
{
    STATIC_REQUIRE(bp::StartGamePacket_<975>::Id == 11);
    STATIC_REQUIRE(bp::StartGamePacket_<1001>::Id == 11);
}

TEST_CASE("StartGamePacket: v1001 round-trip")
{
    using Packet = bp::StartGamePacket_<1001>;

    Packet pkt;
    fill(pkt);
    pkt.settings.server_editor_connection_policy = bp::ServerEditorConnectionPolicy::MATCH_WORLD_TYPE;
    pkt.settings.allow_anonymous_block_drops_in_editor_worlds = false;
    pkt.is_chat_logging = false;

    // generated by gophertunnel:
    // packet.StartGame{EntityUniqueID: 1, EntityRuntimeID: 2, PlayerGameMode: 0,
    //   PlayerPosition: {1, 2, 3}, Pitch: 4, Yaw: 5, WorldSeed: 7, Dimension: 0, Generator: 1,
    //   WorldGameMode: 0, Difficulty: 2, WorldSpawn: {0, 64, 0}, AchievementsDisabled: true,
    //   MultiPlayerGame: true, LANBroadcastEnabled: true, XBLBroadcastMode: 2,
    //   PlatformBroadcastMode: 2, CommandsEnabled: true,
    //   GameRules: []protocol.GameRule{{Name: "dodaylightcycle", Value: true}},
    //   PlayerPermissions: 1, ServerChunkTickRadius: 4, BaseGameVersion: "1.21.0",
    //   LevelID: "lvl", WorldName: "world",
    //   PlayerMovementSettings: {RewindHistorySize: 40}, Time: 100,
    //   ServerAuthoritativeInventory: true, GameVersion: "1.21.0",
    //   PropertyData: map[string]any{}, UseBlockNetworkIDHashes: true}
    const std::vector<std::uint8_t> golden{
        0x02, 0x02, 0x00, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40, 0x00,
        0x00, 0x40, 0x40, 0x00, 0x00, 0x80, 0x40, 0x00, 0x00, 0xA0, 0x40, 0x07,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
        0x00, 0x00, 0x04, 0x00, 0x80, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x01, 0x01, 0x04, 0x04, 0x01, 0x00, 0x01, 0x0F, 0x64, 0x6F, 0x64, 0x61,
        0x79, 0x6C, 0x69, 0x67, 0x68, 0x74, 0x63, 0x79, 0x63, 0x6C, 0x65, 0x00,
        0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x04, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03,
        0x6C, 0x76, 0x6C, 0x05, 0x77, 0x6F, 0x72, 0x6C, 0x64, 0x00, 0x00, 0x50,
        0x00, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x01, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x0A, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    };

    REQUIRE(encode(pkt) == golden);

    const std::string body{golden.begin(), golden.end()};
    bp::BinaryReader in{body};
    auto rt = bp::Serializer<Packet>::deserialize(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->settings.seed == 7);
    REQUIRE(rt->settings.game_rules.size() == 1);
    REQUIRE(std::get<1>(rt->settings.game_rules[0].value) == true);
    REQUIRE(rt->level_name == "world");
    REQUIRE(rt->is_chat_logging == false);
}

// 995 added is_chat_logging and 997 the two editor fields; nothing else moved, so
// the 975 body is the 1001 one minus exactly those three bytes.
TEST_CASE("StartGamePacket: v975 is the v1001 body less the 995 and 997 fields")
{
    using Packet = bp::StartGamePacket_<975>;

    Packet pkt;
    fill(pkt);
    const auto encoded = encode(pkt);

    using Packet1001 = bp::StartGamePacket_<1001>;
    Packet1001 newer;
    fill(newer);
    newer.settings.server_editor_connection_policy = bp::ServerEditorConnectionPolicy::MATCH_WORLD_TYPE;
    newer.settings.allow_anonymous_block_drops_in_editor_worlds = false;
    newer.is_chat_logging = false;
    REQUIRE(encoded.size() + 3 == encode(newer).size());

    const std::string body{encoded.begin(), encoded.end()};
    bp::BinaryReader in{body};
    auto rt = bp::Serializer<Packet>::deserialize(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->settings.seed == 7);
    REQUIRE(rt->level_name == "world");
}
