#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("RequestNetworkSettingsPacket: id + big-endian round-trip")
{
    STATIC_REQUIRE(bp::RequestNetworkSettingsPacket::Id == 193);

    bp::RequestNetworkSettingsPacket pkt{975};

    // generated by gophertunnel:
    // packet.RequestNetworkSettings{ClientProtocol: 975}
    const std::vector<std::uint8_t> golden{0x00, 0x00, 0x03, 0xCF};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::RequestNetworkSettingsPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->client_network_version == 975);
}
