#include <type_traits>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("DimensionDefinition: dimension_type added at v975")
{
    bp::DimensionDefinition_<503> pre{"minecraft:overworld", 320, -64, 1};
    REQUIRE(pre.generator_type == 1);

    bp::DimensionDefinition_<975> post{"minecraft:overworld", 320, -64, 1, 0};
    REQUIRE(post.dimension_type == 0);

    STATIC_REQUIRE(std::is_same_v<bp::DimensionDefinition_<503>,
                                  bp::DimensionDefinition_<974>>);
    STATIC_REQUIRE(!std::is_same_v<bp::DimensionDefinition_<974>,
                                   bp::DimensionDefinition_<975>>);
}

TEST_CASE("DimensionDataPacket: id + round-trip of a list of nested structs")
{
    STATIC_REQUIRE(bp::DimensionDataPacket_<503>::Id == 180);

    bp::DimensionDataPacket_<975> pkt;
    pkt.definitions = {bp::DimensionDefinition_<975>{"minecraft:nether", 128, 0, 3, 1}};

    // generated by gophertunnel:
    // packet.DimensionData{Definitions: []protocol.DimensionDefinition{{Name: "minecraft:nether", Range: [2]int32{128, 0}, Generator: 3, DimensionType: 1}}}
    const std::vector<std::uint8_t> golden{
        0x01, 0x10, 0x6D, 0x69, 0x6E, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3A,
        0x6E, 0x65, 0x74, 0x68, 0x65, 0x72, 0x80, 0x02, 0x00, 0x06, 0x02,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::DimensionDataPacket_<975>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->definitions.size() == 1);
    REQUIRE(rt->definitions[0].name == "minecraft:nether");
    REQUIRE(rt->definitions[0].dimension_type == 1);
}

TEST_CASE("BlockActorDataPacket: id + round-trip with an NBT CompoundTag")
{
    STATIC_REQUIRE(bp::BlockActorDataPacket::Id == 56);

    bp::BlockActorDataPacket pkt;
    pkt.block_position = {1, 2, 3};
    bp::ListTag levels;
    levels.elements = {bp::Tag{bp::IntTag{1}}, bp::Tag{bp::IntTag{2}},
                       bp::Tag{bp::IntTag{3}}};
    pkt.actor_data_tags.entries.emplace_back("levels", bp::Tag{levels});

    // generated by gophertunnel:
    // packet.BlockActorData{Position: {1, 2, 3}, NBTData: {"levels": []int32{1, 2, 3}}}
    const std::vector<std::uint8_t> golden{
        0x02, 0x04, 0x06, 0x0A, 0x00, 0x09, 0x06, 0x6C, 0x65, 0x76, 0x65, 0x6C,
        0x73, 0x03, 0x06, 0x02, 0x04, 0x06, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::BlockActorDataPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->actor_data_tags.entries.size() == 1);
    REQUIRE(rt->actor_data_tags.entries[0].first == "levels");
    const auto &list = std::get<bp::ListTag>(rt->actor_data_tags.entries[0].second.value);
    REQUIRE(list.elements.size() == 3);
    REQUIRE(std::get<bp::IntTag>(list.elements[2].value).value == 3);
}
