#include <string>

#include <bedrock/protocol/structure.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.GameTestRequest{MaxTestsPerBatch: 100,
// Repetitions: 2, Rotation: 1, StopOnError: true,
// Position: protocol.BlockPos{1, -2, 3}, TestsPerRow: 5, Name: "mytest"}
const std::string golden = bytes({
    0xc8, 0x01, 0x04, 0x01, 0x01, 0x02, 0x03, 0x06, 0x0a, 0x06, 0x6d, 0x79,
    0x74, 0x65, 0x73, 0x74,
});

// generated by gophertunnel: &packet.GameTestRequest{MaxTestsPerBatch: 300,
// Repetitions: -1, Rotation: 3, StopOnError: false,
// Position: protocol.BlockPos{0, 0, 0}, TestsPerRow: 0, Name: ""}
const std::string golden_wide = bytes({
    0xd8, 0x04, 0x01, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 194")
{
    STATIC_REQUIRE(bp::GameTestRequestPacket_<2168>::Id == 194);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 194>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 194>);
}

TEST_CASE("game-test request round-trips against the golden")
{
    bp::GameTestRequestPacket_<2168> packet;
    packet.max_tests_per_batch = 100;
    packet.repeat_count = 2;
    packet.rotation = bp::Rotation::ROTATE_90;
    packet.stop_on_failure = true;
    packet.test_pos = {.x = 1, .y = -2, .z = 3};
    packet.tests_per_row = 5;
    packet.test_name = "mytest";
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::GameTestRequestPacket_<2168>>(golden);
    REQUIRE(back.max_tests_per_batch == 100);
    REQUIRE(back.repeat_count == 2);
    REQUIRE(back.rotation == bp::Rotation::ROTATE_90);
    REQUIRE(back.stop_on_failure);
    REQUIRE(back.test_pos.x == 1);
    REQUIRE(back.test_pos.y == -2);
    REQUIRE(back.test_pos.z == 3);
    REQUIRE(back.tests_per_row == 5);
    REQUIRE(back.test_name == "mytest");
}

TEST_CASE("the game-test request counts are signed varints and the rotation stays one byte")
{
    bp::GameTestRequestPacket_<2168> packet;
    packet.max_tests_per_batch = 300;
    packet.repeat_count = -1;
    packet.rotation = bp::Rotation::ROTATE_270;
    packet.stop_on_failure = false;
    packet.test_pos = {.x = 0, .y = 0, .z = 0};
    packet.tests_per_row = 0;
    packet.test_name = "";
    REQUIRE(encode(packet) == golden_wide);

    const auto back = decode<bp::GameTestRequestPacket_<2168>>(golden_wide);
    REQUIRE(back.max_tests_per_batch == 300);
    REQUIRE(back.repeat_count == -1);
    REQUIRE(back.rotation == bp::Rotation::ROTATE_270);
    REQUIRE_FALSE(back.stop_on_failure);
    REQUIRE(back.tests_per_row == 0);
    REQUIRE(back.test_name.empty());
}
