#include <string>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

namespace {

template <class T>
std::string encode(const T &value)
{
    std::string buffer;
    bp::BinaryWriter writer{buffer};
    bp::Serializer<T>::serialize(writer, value);
    return buffer;
}

std::string bytes(std::initializer_list<int> raw)
{
    std::string out;
    for (int b : raw) {
        out.push_back(static_cast<char>(b));
    }
    return out;
}

using PacketV975 = bp::MobArmorEquipmentPacket_<975>;
using PacketV1001 = bp::MobArmorEquipmentPacket_<1001>;

std::string empty_item_blob()
{
    return std::string(10, '\0');
}

// The helmet carries a stack net id, so the net-id branch is on the wire -- the
// one place the two item forms differ beyond the id's width.
template <class Item>
Item helmet()
{
    Item item;
    item.id = 5;
    item.stack_size = 1;
    item.aux_value = 3;
    item.user_data_buffer = empty_item_blob();
    return item;
}

// generated by gophertunnel at 6353c49^ (de090ae, the last pre-1.26.30 commit):
// packet.MobArmourEquipment{EntityRuntimeID: 7} -- every slot air
const std::string golden_v975_empty = bytes({
    0x07,  // runtime_id = 7 (uvarint64)
    0x00,  // head = air (a lone zero byte)
    0x00,  // torso
    0x00,  // legs
    0x00,  // feet
    0x00,  // body
});

// generated by gophertunnel at 6353c49^ (de090ae):
// packet.MobArmourEquipment{EntityRuntimeID: 7, Helmet: {StackNetworkID: 9,
//   Stack: {ItemType: {NetworkID: 5, MetadataValue: 3}, Count: 1}}}
const std::string golden_v975_helmet = bytes({
    0x07,        // runtime_id = 7
    0x0a,        // head.id = 5 (varint32 zigzag)
    0x01, 0x00,  // head.stack_size = 1 (uint16)
    0x03,        // head.aux_value = 3 (uvarint32)
    0x01,        // head.net_id present
    0x12,        //   net_id.id = 9 (varint32 zigzag)
    0x00,        // head.block_runtime_id = 0 (varint32)
    0x0a,        // head.user_data_buffer length = 10
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,  // torso, legs, feet, body = air
});

// generated by gophertunnel (654cd5f):
// packet.MobArmourEquipment{EntityRuntimeID: 7} -- every slot air
const std::string golden_v1001_empty = bytes({
    0x07,  // runtime_id = 7 (uvarint64)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // head = air (eight bytes)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // torso
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // legs
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // feet
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // body
});

// generated by gophertunnel (654cd5f):
// packet.MobArmourEquipment{EntityRuntimeID: 7, Helmet: {StackNetworkID: 9,
//   Stack: {ItemType: {NetworkID: 5, MetadataValue: 3}, Count: 1}}}
const std::string golden_v1001_helmet = bytes({
    0x07,        // runtime_id = 7
    0x05, 0x00,  // head.id = 5 (int16)
    0x01, 0x00,  // head.stack_size = 1 (uint16)
    0x03,        // head.aux_value = 3 (uvarint32)
    0x01,        // head.net_id present
    0x00,        //   variant index 0 (ItemStackNetId)
    0x12,        //   id = 9 (varint32 zigzag)
    0x00,        // head.block_runtime_id = 0 (uvarint32)
    0x0a,        // head.user_data_buffer length = 10
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // torso = air
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // legs
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // feet
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // body
});

}  // namespace

TEST_CASE("packet id is 32 at both eras")
{
    STATIC_REQUIRE(PacketV975::Id == 32);
    STATIC_REQUIRE(PacketV1001::Id == 32);
}

// 988 cerealised the packet, but its own shape did not move: the five slots keep
// their order and only the item form underneath them changed.
TEST_CASE("mob-armor-equipment v975 round-trips against the goldens")
{
    PacketV975 packet;
    packet.runtime_id = static_cast<bp::ActorRuntimeID>(7);
    REQUIRE(encode(packet) == golden_v975_empty);

    packet.head = helmet<bp::base::SerializedNetworkItemStackDescriptor>();
    packet.head.net_id = bp::ItemStackNetId{.id = 9};
    REQUIRE(encode(packet) == golden_v975_helmet);

    bp::BinaryReader reader{golden_v975_helmet};
    auto back = bp::Serializer<PacketV975>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->head.id == 5);
    REQUIRE(back->head.net_id.has_value());
    REQUIRE(back->head.net_id->id == 9);
    REQUIRE(back->torso.id == 0);
}

TEST_CASE("mob-armor-equipment v1001 round-trips against the goldens")
{
    PacketV1001 packet;
    packet.runtime_id = static_cast<bp::ActorRuntimeID>(7);
    REQUIRE(encode(packet) == golden_v1001_empty);

    packet.head = helmet<bp::v1001::SerializedNetworkItemStackDescriptor>();
    packet.head.net_id_variant = bp::ItemStackNetId{.id = 9};
    REQUIRE(encode(packet) == golden_v1001_helmet);

    bp::BinaryReader reader{golden_v1001_helmet};
    auto back = bp::Serializer<PacketV1001>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->head.id == 5);
    REQUIRE(back->head.net_id_variant.has_value());
    REQUIRE(std::get<0>(*back->head.net_id_variant).id == 9);
    REQUIRE(back->torso.id == 0);
}
