#include <string>

#include <bedrock/protocol/game.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.SetPlayerGameType{GameType: packet.GameTypeSpectator}
const std::string golden = bytes({
    0x0c,
});

// generated by gophertunnel: &packet.SetPlayerGameType{GameType: -1}
const std::string golden_undefined = bytes({
    0x01,
});

}  // namespace

TEST_CASE("packet id is 62")
{
    STATIC_REQUIRE(bp::SetPlayerGameTypePacket::Id == 62);
    STATIC_REQUIRE(bp::has_packet_v<1001, 62>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 62>);
}

TEST_CASE("set-player-game-type round-trips against the golden")
{
    bp::SetPlayerGameTypePacket packet;
    packet.player_game_type = bp::GameType::Spectator;
    REQUIRE(encode(packet) == golden);

    REQUIRE(decode<bp::SetPlayerGameTypePacket>(golden).player_game_type == bp::GameType::Spectator);
}

TEST_CASE("the game type is a zigzag varint, so Undefined is one byte and not five")
{
    bp::SetPlayerGameTypePacket packet;
    packet.player_game_type = bp::GameType::Undefined;
    REQUIRE(encode(packet) == golden_undefined);

    REQUIRE(decode<bp::SetPlayerGameTypePacket>(golden_undefined).player_game_type == bp::GameType::Undefined);
    REQUIRE(rejects<bp::SetPlayerGameTypePacket>(std::string{}));
}
