#include <string>

#include "fixture.hpp"

namespace {

using PacketV975 = bp::MobArmorEquipmentPacket_<975>;
using PacketV1001 = bp::MobArmorEquipmentPacket_<1001>;
using PacketV2168 = bp::MobArmorEquipmentPacket_<2168>;

// The helmet carries a stack net id, so the net-id branch is on the wire -- the
// one place the two item forms differ beyond the id's width.
template <class Item>
Item helmet()
{
    Item item;
    item.id = 5;
    item.stack_size = 1;
    item.aux_value = 3;
    item.user_data_buffer = empty_item_blob();
    return item;
}

// generated by gophertunnel at 6353c49^ (de090ae, the last pre-1.26.30 commit):
// packet.MobArmourEquipment{EntityRuntimeID: 7} -- every slot air
const std::string golden_v975_empty = bytes({
    0x07, 0x00, 0x00, 0x00, 0x00, 0x00,
});

// generated by gophertunnel at 6353c49^ (de090ae):
// packet.MobArmourEquipment{EntityRuntimeID: 7, Helmet: {StackNetworkID: 9,
//   Stack: {ItemType: {NetworkID: 5, MetadataValue: 3}, Count: 1}}}
const std::string golden_v975_helmet = bytes({
    0x07, 0x0a, 0x01, 0x00, 0x03, 0x01, 0x12, 0x00, 0x0a, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

// generated by gophertunnel (654cd5f):
// packet.MobArmourEquipment{EntityRuntimeID: 7} -- every slot air
const std::string golden_v1001_empty = bytes({
    0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00,
});

// generated by gophertunnel (654cd5f):
// packet.MobArmourEquipment{EntityRuntimeID: 7, Helmet: {StackNetworkID: 9,
//   Stack: {ItemType: {NetworkID: 5, MetadataValue: 3}, Count: 1}}}
const std::string golden_v1001_helmet = bytes({
    0x07, 0x05, 0x00, 0x01, 0x00, 0x03, 0x01, 0x00, 0x12, 0x00, 0x0a, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00,
});

// generated by CloudburstMC Bedrock_v2168:
// MobArmorEquipmentPacket{runtimeEntityId: 7, every slot ItemData.AIR}
const std::string golden_v2168_empty = bytes({
    0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00,
});

// generated by CloudburstMC Bedrock_v2168:
// MobArmorEquipmentPacket{runtimeEntityId: 7, helmet: ItemData{definition runtimeId 5,
//   damage 3, count 1, usingNetId true, netId 9}, remaining slots ItemData.AIR}
const std::string golden_v2168_helmet = bytes({
    0x07, 0x05, 0x00, 0x01, 0x00, 0x03, 0x01, 0x12, 0x00, 0x0a, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
});

// generated by CloudburstMC Bedrock_v2168: the same packet with netId -3
const std::string golden_v2168_helmet_negative = bytes({
    0x07, 0x05, 0x00, 0x01, 0x00, 0x03, 0x01, 0x05, 0x00, 0x0a, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 32 at every version")
{
    STATIC_REQUIRE(PacketV975::Id == 32);
    STATIC_REQUIRE(PacketV1001::Id == 32);
    STATIC_REQUIRE(PacketV2168::Id == 32);
}

// 988 cerealised the packet, but its own shape did not move: the five slots keep
// their order and only the item form underneath them changed.
TEST_CASE("mob-armor-equipment v975 round-trips against the goldens")
{
    PacketV975 packet;
    packet.runtime_id = static_cast<bp::ActorRuntimeID>(7);
    REQUIRE(encode(packet) == golden_v975_empty);

    packet.head = helmet<bp::NetworkItemStackDescriptor>();
    packet.head.net_id = bp::ItemStackNetId{.raw_id = 9};
    REQUIRE(encode(packet) == golden_v975_helmet);

    const auto back = decode<PacketV975>(golden_v975_helmet);
    REQUIRE(back.head.id == 5);
    REQUIRE(back.head.net_id.has_value());
    REQUIRE(back.head.net_id->raw_id == 9);
    REQUIRE(back.torso.id == 0);
}

TEST_CASE("mob-armor-equipment v1001 round-trips against the goldens")
{
    PacketV1001 packet;
    packet.runtime_id = static_cast<bp::ActorRuntimeID>(7);
    REQUIRE(encode(packet) == golden_v1001_empty);

    packet.head = helmet<bp::v1001::SerializedNetworkItemStackDescriptor>();
    packet.head.net_id_variant = bp::ItemStackNetId{.raw_id = 9};
    REQUIRE(encode(packet) == golden_v1001_helmet);

    const auto back = decode<PacketV1001>(golden_v1001_helmet);
    REQUIRE(back.head.id == 5);
    REQUIRE(back.head.net_id_variant.has_value());
    REQUIRE(std::get<0>(*back.head.net_id_variant).raw_id == 9);
    REQUIRE(back.torso.id == 0);
}

TEST_CASE("mob-armor-equipment v2168 round-trips against the goldens")
{
    PacketV2168 packet;
    packet.runtime_id = static_cast<bp::ActorRuntimeID>(7);
    REQUIRE(encode(packet) == golden_v2168_empty);

    packet.head = helmet<bp::v2168::SerializedNetworkItemStackDescriptor>();
    packet.head.net_id_variant = 9;
    REQUIRE(encode(packet) == golden_v2168_helmet);

    const auto back = decode<PacketV2168>(golden_v2168_helmet);
    REQUIRE(back.head.id == 5);
    REQUIRE(back.head.net_id_variant.has_value());
    REQUIRE(*back.head.net_id_variant == 9);
    REQUIRE(back.torso.id == 0);
}

// The sign and parity say which id it is where 1001 spelled a tag: negative-odd
// is a client request id.
TEST_CASE("mob-armor-equipment v2168 carries a client request id as a negative net id")
{
    PacketV2168 packet;
    packet.runtime_id = static_cast<bp::ActorRuntimeID>(7);
    packet.head = helmet<bp::v2168::SerializedNetworkItemStackDescriptor>();
    packet.head.net_id_variant = -3;
    REQUIRE(encode(packet) == golden_v2168_helmet_negative);

    REQUIRE(*decode<PacketV2168>(golden_v2168_helmet_negative).head.net_id_variant == -3);
}

// Only the tag byte went, so an all-air packet is the same bytes either era --
// the break shows up solely on a stack that carries an id.
TEST_CASE("mob-armor-equipment agrees across 1001 and 2168 when no stack carries a net id")
{
    REQUIRE(golden_v2168_empty == golden_v1001_empty);
    REQUIRE(golden_v2168_helmet != golden_v1001_helmet);
    REQUIRE(golden_v2168_helmet.size() + 1 == golden_v1001_helmet.size());
}

// The tag is gone, so 1001's zero index is read as the net id itself and every
// later field slides one byte forward.
TEST_CASE("mob-armor-equipment a v1001 body does not decode as a v2168 one")
{
    const auto wrong = decode_partial<PacketV2168>(golden_v1001_helmet);
    REQUIRE(*wrong.head.net_id_variant == 0);
    REQUIRE(wrong.head.block_runtime_id == 18);

    // The other way the zigzagged net id lands where the variant index is read,
    // and 18 names no case.
    REQUIRE(rejects<PacketV1001>(golden_v2168_helmet));
}
