#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("NetworkSettingsPacket: id + round-trip with enum field")
{
    STATIC_REQUIRE(bp::NetworkSettingsPacket::Id == 143);

    bp::NetworkSettingsPacket pkt;
    pkt.compression_threshold = 256;
    pkt.compression_algorithm = bp::PacketCompressionAlgorithm::Snappy;
    pkt.client_throttle_enabled = true;
    pkt.client_throttle_threshold = 40;
    pkt.client_throttle_scalar = 0.75f;

    // generated by gophertunnel:
    // packet.NetworkSettings{CompressionThreshold: 256, CompressionAlgorithm: 1, ClientThrottle: true, ClientThrottleThreshold: 40, ClientThrottleScalar: 0.75}
    const std::vector<std::uint8_t> golden{
        0x00, 0x01, 0x01, 0x00, 0x01, 0x28, 0x00, 0x00, 0x40, 0x3F,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::NetworkSettingsPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->compression_threshold == 256);
    REQUIRE(rt->compression_algorithm == bp::PacketCompressionAlgorithm::Snappy);
    REQUIRE(rt->client_throttle_scalar == 0.75f);
}
