#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("CodeBuilderSourcePacket: id + round-trip with the v685 code_status byte")
{
    STATIC_REQUIRE(bp::CodeBuilderSourcePacket::Id == 178);

    bp::CodeBuilderSourcePacket pkt;
    pkt.operation = bp::CodeBuilderStorageQueryOptionsOperation::Get;
    pkt.category = bp::CodeBuilderStorageQueryOptionsCategory::CodeStatus;
    pkt.code_status = bp::CodeBuilderExecutionStateCodeStatus::Succeeded;

    // generated by gophertunnel:
    // packet.CodeBuilderSource{Operation: 1, Category: 1, CodeStatus: 5}
    const std::vector<std::uint8_t> golden{0x01, 0x01, 0x05};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::CodeBuilderSourcePacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->code_status == bp::CodeBuilderExecutionStateCodeStatus::Succeeded);
}
