#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ContainerSetDataPacket: id + round-trip")
{
    STATIC_REQUIRE(bp::ContainerSetDataPacket::Id == 51);

    bp::ContainerSetDataPacket pkt;
    pkt.container_id = static_cast<bp::ContainerID>(1);
    pkt.id = 0;
    pkt.value = 100;

    // generated by gophertunnel:
    // packet.ContainerSetData{WindowID: 1, Key: 0, Value: 100}
    const std::vector<std::uint8_t> golden{
        0x01, 0x00, 0xC8, 0x01,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ContainerSetDataPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->container_id == static_cast<bp::ContainerID>(1));
    REQUIRE(rt->id == 0);
    REQUIRE(rt->value == 100);
}
