#include <type_traits>
#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("RespawnPacket: state + runtime_id added at v388")
{
    STATIC_REQUIRE(bp::RespawnPacket_<0>::Id == 45);
    STATIC_REQUIRE(!std::is_same_v<bp::RespawnPacket_<387>,
                                   bp::RespawnPacket_<388>>);
}

TEST_CASE("RespawnPacket: id + round-trip with v388 state byte and uvarint64 runtime id")
{
    bp::RespawnPacket pkt;
    pkt.pos = bp::Vec3{1.5f, 80.0f, 2.5f};
    pkt.state = bp::PlayerRespawnState::ReadyToSpawn;
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(12345);

    // generated by gophertunnel:
    // packet.Respawn{Position: mgl32.Vec3{1.5, 80, 2.5}, State: 1, EntityRuntimeID: 12345}
    const std::vector<std::uint8_t> golden{
        0x00, 0x00, 0xC0, 0x3F, 0x00, 0x00, 0xA0, 0x42, 0x00, 0x00, 0x20, 0x40,
        0x01, 0xB9, 0x60,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::RespawnPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->pos.y == 80.0f);
    REQUIRE(rt->state == bp::PlayerRespawnState::ReadyToSpawn);
    REQUIRE(rt->runtime_id == 12345);
}
