#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ClientboundTextureShiftPacket: id + round-trip")
{
    STATIC_REQUIRE(bp::ClientboundTextureShiftPacket::Id == 336);

    bp::ClientboundTextureShiftPacket pkt;
    pkt.action = bp::ClientboundTextureShiftPacket::Action::Start;
    pkt.collection_name = "coll";
    pkt.from_step = "a";
    pkt.to_step = "b";
    pkt.all_steps = {"a", "b"};
    pkt.current_length_in_ticks = 5;
    pkt.total_length_in_ticks = 20;
    pkt.enabled = true;

    // generated by gophertunnel:
    // packet.ClientBoundTextureShift{ActionID: TextureShiftActionStart,
    //   CollectionName: "coll", FromStep: "a", ToStep: "b",
    //   AllSteps: ["a", "b"], CurrentLengthTicks: 5, TotalLengthTicks: 20,
    //   Enabled: true}
    const std::vector<std::uint8_t> golden{
        0x02, 0x04, 0x63, 0x6F, 0x6C, 0x6C, 0x01, 0x61, 0x01, 0x62, 0x02, 0x01,
        0x61, 0x01, 0x62, 0x05, 0x14, 0x01,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ClientboundTextureShiftPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->action == bp::ClientboundTextureShiftPacket::Action::Start);
    REQUIRE(rt->collection_name == "coll");
    REQUIRE(rt->all_steps.size() == 2);
    REQUIRE(rt->current_length_in_ticks == 5);
    REQUIRE(rt->enabled);
}
