#include <string>

#include <protocol/game.h>
#include <protocol/resource_pack.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ResourcePackStack{TexturePackRequired: true,
// TexturePacks: []protocol.StackResourcePack{{UUID: "5a1c", Version: "1.2.3", SubPackName:
// "hd"}, {UUID: "6b2d", Version: "0.0.1"}}, BaseGameVersion: "1.26.44", Experiments:
// []protocol.ExperimentData{{Name: "gametest", Enabled: true}, {Name: "data_driven_biomes"}},
// ExperimentsPreviouslyToggled: true, IncludeEditorPacks: true}
const std::string golden = bytes({
    0x01, 0x02, 0x04, 0x35, 0x61, 0x31, 0x63, 0x05, 0x31, 0x2e, 0x32, 0x2e,
    0x33, 0x02, 0x68, 0x64, 0x04, 0x36, 0x62, 0x32, 0x64, 0x05, 0x30, 0x2e,
    0x30, 0x2e, 0x31, 0x00, 0x07, 0x31, 0x2e, 0x32, 0x36, 0x2e, 0x34, 0x34,
    0x02, 0x00, 0x00, 0x00, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x73,
    0x74, 0x01, 0x12, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x64, 0x72, 0x69, 0x76,
    0x65, 0x6e, 0x5f, 0x62, 0x69, 0x6f, 0x6d, 0x65, 0x73, 0x00, 0x01, 0x01,
});

// generated by gophertunnel: &packet.ResourcePackStack{IncludeEditorPacks: true}
const std::string golden_editor_only = bytes({
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
});

}  // namespace

TEST_CASE("packet id is 7")
{
    STATIC_REQUIRE(bp::ResourcePackStackPacket_<2168>::Id == 7);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 7>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 7>);
}

TEST_CASE("resource-pack-stack round-trips against the golden")
{
    bp::ResourcePackStackPacket_<2168> packet;
    packet.texture_pack_required = true;
    packet.texture_pack_ids_and_versions = {
        {.pack_id = "5a1c", .version = "1.2.3", .subpack_name = "hd"},
        {.pack_id = "6b2d", .version = "0.0.1"},
    };
    packet.base_game_version = "1.26.44";
    packet.experiments.toggles = {
        {.name = "gametest", .enabled = true},
        {.name = "data_driven_biomes", .enabled = false},
    };
    packet.experiments.experiments_ever_toggled = true;
    packet.include_editor_packs = true;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::ResourcePackStackPacket_<2168>>(golden);
    REQUIRE(back.texture_pack_required);
    REQUIRE(back.texture_pack_ids_and_versions.size() == 2);
    REQUIRE(back.texture_pack_ids_and_versions[0].pack_id == "5a1c");
    REQUIRE(back.texture_pack_ids_and_versions[0].version == "1.2.3");
    REQUIRE(back.texture_pack_ids_and_versions[0].subpack_name == "hd");
    REQUIRE(back.texture_pack_ids_and_versions[1].pack_id == "6b2d");
    REQUIRE(back.texture_pack_ids_and_versions[1].version == "0.0.1");
    REQUIRE(back.texture_pack_ids_and_versions[1].subpack_name.empty());
    REQUIRE(back.base_game_version == "1.26.44");
    REQUIRE(back.experiments.toggles.size() == 2);
    REQUIRE(back.experiments.toggles[0].name == "gametest");
    REQUIRE(back.experiments.toggles[0].enabled);
    REQUIRE(back.experiments.toggles[1].name == "data_driven_biomes");
    REQUIRE_FALSE(back.experiments.toggles[1].enabled);
    REQUIRE(back.experiments.experiments_ever_toggled);
    REQUIRE(back.include_editor_packs);
}

TEST_CASE("an empty stack is nine bytes and does not swap its two trailing flags")
{
    bp::ResourcePackStackPacket_<2168> packet;
    packet.include_editor_packs = true;
    REQUIRE(encode(packet) == golden_editor_only);

    const auto back = decode<bp::ResourcePackStackPacket_<2168>>(golden_editor_only);
    REQUIRE_FALSE(back.texture_pack_required);
    REQUIRE(back.texture_pack_ids_and_versions.empty());
    REQUIRE(back.base_game_version.empty());
    REQUIRE(back.experiments.toggles.empty());
    REQUIRE_FALSE(back.experiments.experiments_ever_toggled);
    REQUIRE(back.include_editor_packs);
}

TEST_CASE("the pack count is a varint")
{
    bp::ResourcePackStackPacket_<2168> packet;
    packet.texture_pack_ids_and_versions.resize(300);
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 910);
    REQUIRE(decode<bp::ResourcePackStackPacket_<2168>>(wire).texture_pack_ids_and_versions.size() == 300);
}
