#include <string>

#include <bedrock/protocol/block.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.BlockEvent{Position: protocol.BlockPos{1, 2, 3},
// EventType: 1, EventData: 0}
const std::string golden = bytes({
    0x02, 0x04, 0x06, 0x02, 0x00,
});

// generated by gophertunnel: &packet.BlockEvent{Position: protocol.BlockPos{-2, 300, 3},
// EventType: -1, EventData: 200}
const std::string golden_wide = bytes({
    0x03, 0xd8, 0x04, 0x06, 0x01, 0x90, 0x03,
});

}  // namespace

TEST_CASE("packet id is 26")
{
    STATIC_REQUIRE(bp::BlockEventPacket::Id == 26);
    STATIC_REQUIRE(bp::has_packet_v<1001, 26>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 26>);
}

TEST_CASE("block event round-trips against the golden")
{
    bp::BlockEventPacket packet;
    packet.pos = {.x = 1, .y = 2, .z = 3};
    packet.b0 = 1;
    packet.b1 = 0;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::BlockEventPacket>(golden);
    REQUIRE(back.pos.x == 1);
    REQUIRE(back.pos.y == 2);
    REQUIRE(back.pos.z == 3);
    REQUIRE(back.b0 == 1);
    REQUIRE(back.b1 == 0);
}

TEST_CASE("all five fields are zigzag varints, not bytes and not unsigned")
{
    bp::BlockEventPacket packet;
    packet.pos = {.x = -2, .y = 300, .z = 3};
    packet.b0 = -1;
    packet.b1 = 200;
    REQUIRE(encode(packet) == golden_wide);

    const auto back = decode<bp::BlockEventPacket>(golden_wide);
    REQUIRE(back.pos.x == -2);
    REQUIRE(back.pos.y == 300);
    REQUIRE(back.pos.z == 3);
    REQUIRE(back.b0 == -1);
    REQUIRE(back.b1 == 200);
}
