#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ClientboundDataDrivenUICloseScreenPacket: id + round-trip with form_id set")
{
    STATIC_REQUIRE(bp::ClientboundDataDrivenUICloseScreenPacket::Id == 334);

    bp::ClientboundDataDrivenUICloseScreenPacket pkt;
    pkt.form_id = static_cast<std::uint32_t>(7);

    // generated by gophertunnel:
    // packet.ClientBoundDataDrivenUICloseScreen{FormID: protocol.Option(uint32(7))}
    const std::vector<std::uint8_t> golden{0x01, 0x07, 0x00, 0x00, 0x00};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ClientboundDataDrivenUICloseScreenPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->form_id.has_value());
    REQUIRE(*rt->form_id == 7);
}
