#include <optional>
#include <string>

#include <bedrock/protocol/actor.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.Animate{ActionType: packet.AnimateActionSwingArm,
// EntityRuntimeID: 300, Data: 1.5, SwingSource: packet.AnimateSwingSourceAttack}
const std::string golden = bytes({
    0x01, 0xac, 0x02, 0x00, 0x00, 0xc0, 0x3f, 0x01, 0x06, 0x61, 0x74, 0x74,
    0x61, 0x63, 0x6b,
});

// generated by gophertunnel: &packet.Animate{ActionType: packet.AnimateActionCriticalHit,
// EntityRuntimeID: 7}
const std::string golden_without_swing_source = bytes({
    0x04, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00,
});

// generated by gophertunnel: &packet.Animate{ActionType: 0, EntityRuntimeID: 1 << 32,
// SwingSource: packet.AnimateSwingSourceNone}
const std::string golden_none_swing_source = bytes({
    0x00, 0x80, 0x80, 0x80, 0x80, 0x10, 0x00, 0x00, 0x00, 0x00, 0x01, 0x04,
    0x6e, 0x6f, 0x6e, 0x65,
});

// generated by gophertunnel: &packet.Animate{ActionType: packet.AnimateActionMagicCriticalHit,
// EntityRuntimeID: 1, Data: -1, SwingSource: packet.AnimateSwingSourceUseItem}
const std::string golden_use_item_swing_source = bytes({
    0x05, 0x01, 0x00, 0x00, 0x80, 0xbf, 0x01, 0x07, 0x75, 0x73, 0x65, 0x69,
    0x74, 0x65, 0x6d,
});

// generated by gophertunnel at 312cff6 (the 844 bump): &packet.Animate{ActionType:
// packet.AnimateActionSwingArm, EntityRuntimeID: 300}, then the same with
// ActionType: 0x80 | 1 and BoatRowingTime: 1.5.
const std::string golden_v844 = bytes({0x02, 0xac, 0x02});
const std::string golden_v844_rowing = bytes({
    0x82, 0x02, 0xac, 0x02, 0x00, 0x00, 0xc0, 0x3f,
});

// generated by gophertunnel at 324ed88: &packet.Animate{ActionType:
// packet.AnimateActionSwingArm, EntityRuntimeID: 300, Data: 1.5}, then the same with
// ActionType: packet.AnimateActionRowLeft and RowingTime: 2.5.
const std::string golden_v859 = bytes({
    0x02, 0xac, 0x02, 0x00, 0x00, 0xc0, 0x3f,
});
const std::string golden_v859_rowing = bytes({
    0x82, 0x02, 0xac, 0x02, 0x00, 0x00, 0xc0, 0x3f, 0x00, 0x00, 0x20, 0x40,
});

}  // namespace

TEST_CASE("packet id is 44")
{
    STATIC_REQUIRE(bp::AnimatePacket::Id == 44);
    STATIC_REQUIRE(bp::has_packet_v<1001, 44>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 44>);
}

TEST_CASE("animate round-trips against the golden")
{
    bp::AnimatePacket packet;
    packet.action = bp::AnimatePacket::Action::Swing;
    packet.runtime_id = bp::ActorRuntimeID{300};
    packet.data = 1.5F;
    packet.swing_source = bp::ActorSwingSource::Attack;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::AnimatePacket>(golden);
    REQUIRE(back.action == bp::AnimatePacket::Action::Swing);
    REQUIRE(back.runtime_id == bp::ActorRuntimeID{300});
    REQUIRE(back.data == 1.5F);
    REQUIRE(back.swing_source.has_value());
    REQUIRE(*back.swing_source == bp::ActorSwingSource::Attack);
}

TEST_CASE("an absent swing source is one zero byte, not a name")
{
    bp::AnimatePacket packet;
    packet.action = bp::AnimatePacket::Action::CriticalHit;
    packet.runtime_id = bp::ActorRuntimeID{7};
    packet.data = 0.0F;
    packet.swing_source = std::nullopt;
    REQUIRE(encode(packet) == golden_without_swing_source);
    REQUIRE(encode(packet).size() == 7);

    const auto back = decode<bp::AnimatePacket>(golden_without_swing_source);
    REQUIRE(back.action == bp::AnimatePacket::Action::CriticalHit);
    REQUIRE(back.runtime_id == bp::ActorRuntimeID{7});
    REQUIRE_FALSE(back.swing_source.has_value());
}

TEST_CASE("a NONE swing source is present, and the animate runtime id survives past 32 bits")
{
    bp::AnimatePacket packet;
    packet.action = bp::AnimatePacket::Action::NoAction;
    packet.runtime_id = bp::ActorRuntimeID{1ULL << 32U};
    packet.data = 0.0F;
    packet.swing_source = bp::ActorSwingSource::None;
    REQUIRE(encode(packet) == golden_none_swing_source);

    const auto back = decode<bp::AnimatePacket>(golden_none_swing_source);
    REQUIRE(back.action == bp::AnimatePacket::Action::NoAction);
    REQUIRE(back.runtime_id == bp::ActorRuntimeID{1ULL << 32U});
    REQUIRE(back.swing_source.has_value());
    REQUIRE(*back.swing_source == bp::ActorSwingSource::None);
}

TEST_CASE("the use-item swing source reaches the wire without its underscore")
{
    bp::AnimatePacket packet;
    packet.action = bp::AnimatePacket::Action::MagicCriticalHit;
    packet.runtime_id = bp::ActorRuntimeID{1};
    packet.data = -1.0F;
    packet.swing_source = bp::ActorSwingSource::UseItem;
    REQUIRE(encode(packet) == golden_use_item_swing_source);

    const auto back = decode<bp::AnimatePacket>(golden_use_item_swing_source);
    REQUIRE(back.data == -1.0F);
    REQUIRE(back.swing_source.has_value());
    REQUIRE(*back.swing_source == bp::ActorSwingSource::UseItem);
}

// Hand-written until 898: the action is a zigzag varint and bit 7 is a rowing flag
// rather than an enumerator, so BDS reaches values a uint8 action could not carry.
TEST_CASE("v844 writes the float only behind the rowing bit")
{
    bp::AnimatePacket_<844> packet;
    packet.action = 1;
    packet.runtime_id = bp::ActorRuntimeID{300};
    packet.data = 1.5f;
    REQUIRE(encode(packet) == golden_v844);

    packet.action = 0x80 | 1;
    REQUIRE(encode(packet) == golden_v844_rowing);

    const auto back = decode<bp::AnimatePacket_<844>>(golden_v844_rowing);
    REQUIRE(back.action == (0x80 | 1));
    REQUIRE(back.data == 1.5f);
}

TEST_CASE("v859 writes the float unconditionally and adds a second behind the rowing bit")
{
    bp::AnimatePacket_<859> packet;
    packet.action = 1;
    packet.runtime_id = bp::ActorRuntimeID{300};
    packet.data = 1.5f;
    packet.rowing_time = 2.5f;
    REQUIRE(encode(packet) == golden_v859);

    packet.action = 0x80 | 1;
    REQUIRE(encode(packet) == golden_v859_rowing);

    const auto back = decode<bp::AnimatePacket_<859>>(golden_v859_rowing);
    REQUIRE(back.data == 1.5f);
    REQUIRE(back.rowing_time == 2.5f);
}

// The two eras differ by exactly the float 859 stopped gating, with the action held
// at a value whose varint width does not move.
TEST_CASE("859 is 844 plus the unconditional float")
{
    bp::AnimatePacket_<844> older;
    older.action = 1;
    older.runtime_id = bp::ActorRuntimeID{300};
    older.data = 1.5f;

    bp::AnimatePacket_<859> newer;
    newer.action = 1;
    newer.runtime_id = bp::ActorRuntimeID{300};
    newer.data = 1.5f;

    REQUIRE(encode(newer).size() == encode(older).size() + 4);
}
