#include <cstdint>
#include <string>
#include <variant>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

namespace {

template <class T>
std::string encode(const T &value)
{
    std::string buffer;
    bp::BinaryWriter writer{buffer};
    bp::Serializer<T>::serialize(writer, value);
    return buffer;
}

std::string bytes(std::initializer_list<int> raw)
{
    std::string out;
    for (int b : raw) {
        out.push_back(static_cast<char>(b));
    }
    return out;
}

using PacketV975 = bp::PrimitiveShapesPacket_<bp::ProtocolVersion::V975>;
using PacketV1001 = bp::PrimitiveShapesPacket_<bp::ProtocolVersion::V1001>;

// mce::Color packs ARGB into an int32: A=0x44, R=0x55, G=0x66, B=0x77.
constexpr auto argb = static_cast<bp::Color>(0x44556677);

// The three shapes below are shaped identically at both eras, so each is built once
// against whichever snapshot's payload the caller wants. The type enum gained members
// at 1001, so it is versioned alongside the payload and comes from it.
template <class Payload>
using ShapeTypeOf = typename decltype(Payload::shape_type)::value_type;

// Every optional left empty: the shape is cleared, and the variant sits on its
// std::monostate case.
template <class Payload>
Payload cleared_shape()
{
    Payload shape;
    shape.network_id = 1;
    return shape;
}

template <class Payload>
Payload sphere_shape()
{
    Payload shape;
    shape.network_id = 3;
    shape.shape_type = ShapeTypeOf<Payload>::SPHERE;
    shape.location = bp::Vec3{.x = 1.0f, .y = 2.0f, .z = 3.0f};
    shape.scale = 0.5f;
    shape.rotation = bp::Vec3{.x = 0.0f, .y = 0.25f, .z = 0.0f};
    shape.time_left_total_sec = 2.0f;
    shape.max_render_distance = 64.0f;
    shape.color = argb;
    shape.dimension_id = static_cast<bp::DimensionType>(1);
    shape.attached_to_id = static_cast<bp::ActorUniqueID>(-7);
    shape.extra_data_payload = bp::SphereDataPayload{.num_segments = 12};
    return shape;
}

template <class Payload>
Payload text_shape()
{
    Payload shape;
    shape.network_id = 4;
    shape.shape_type = ShapeTypeOf<Payload>::TEXT;
    shape.extra_data_payload = bp::TextDataPayload{
        .text = "hi",
        .use_rotation = true,
        .background_color = argb,
        .depth_test = true,
        .show_backface = false,
        .show_text_backface = true,
    };
    return shape;
}

// generated by gophertunnel at 6353c49^ (de090ae, the last pre-1.26.30 commit):
// packet.PrimitiveShapes{Shapes: []protocol.PrimitiveShape{
//   {NetworkID: 1, ExtraShapeData: &protocol.LastShape{}},
//   {NetworkID: 3, Type: Option(PrimitiveShapeSphere), Location: Option(Vec3{1,2,3}),
//    Scale: Option(0.5), Rotation: Option(Vec3{0,0.25,0}), TotalTimeLeft: Option(2),
//    MaxRenderDistance: Option(64), Colour: Option(RGBA{A:0x44,R:0x55,G:0x66,B:0x77}),
//    DimensionID: Option(1), AttachedToEntityID: Option(-7),
//    ExtraShapeData: &protocol.SphereShape{Segments: 12}},
//   {NetworkID: 4, Type: Option(PrimitiveShapeText), ExtraShapeData: &protocol.TextShape{
//    Text: "hi", UseRotation: true, BackgroundColour: Option(argb), DepthTest: true,
//    ShowBackface: false, ShowBackfaceText: true}}}}
const std::string golden_v975 = bytes({
    0x03,                    // shapes: count = 3 (uvarint32)
    // -- cleared
    0x01,                    //   network_id = 1 (uvarint64)
    0x00, 0x00, 0x00, 0x00,  //   shape_type, location, scale, rotation absent
    0x00, 0x00, 0x00, 0x00,  //   time_left_total_sec, max_render_distance, color,
    0x00,                    //   dimension_id, attached_to_id absent
    0x00,                    //   extra_data_payload index 0 (monostate)
    // -- sphere
    0x03,                    //   network_id = 3
    0x01, 0x02,              //   shape_type present, SPHERE (uint8)
    0x01,                    //   location present
    0x00, 0x00, 0x80, 0x3f,  //     x = 1.0f
    0x00, 0x00, 0x00, 0x40,  //     y = 2.0f
    0x00, 0x00, 0x40, 0x40,  //     z = 3.0f
    0x01, 0x00, 0x00, 0x00, 0x3f,  //   scale present, 0.5f
    0x01,                    //   rotation present
    0x00, 0x00, 0x00, 0x00,  //     x = 0.0f
    0x00, 0x00, 0x80, 0x3e,  //     y = 0.25f
    0x00, 0x00, 0x00, 0x00,  //     z = 0.0f
    0x01, 0x00, 0x00, 0x00, 0x40,  //   time_left_total_sec present, 2.0f
    0x01, 0x00, 0x00, 0x80, 0x42,  //   max_render_distance present, 64.0f
    0x01, 0x77, 0x66, 0x55, 0x44,  //   color present, 0x44556677 (int32)
    0x01, 0x02,              //   dimension_id present, 1 (varint32 zigzag)
    0x01, 0x0d,              //   attached_to_id present, -7 (varint64 zigzag)
    0x05,                    //   extra_data_payload index 5 (Sphere)
    0x0c,                    //     num_segments = 12
    // -- text
    0x04,                    //   network_id = 4
    0x01, 0x04,              //   shape_type present, TEXT
    0x00, 0x00, 0x00, 0x00,  //   the eight remaining optionals absent
    0x00, 0x00, 0x00, 0x00,  //
    0x02,                    //   extra_data_payload index 2 (Text)
    0x02, 0x68, 0x69,        //     text = "hi"
    0x01,                    //     use_rotation = true
    0x01, 0x77, 0x66, 0x55, 0x44,  //     background_color present, 0x44556677
    0x01,                    //     depth_test = true
    0x00,                    //     show_backface = false
    0x01,                    //     show_text_backface = true
});

// generated by gophertunnel (654cd5f): the three shapes above, plus the two 989 added
// -- a cylinder and a pyramid, at variant indices 6 and 7.
//   {NetworkID: 5, Type: Option(PrimitiveShapeCylinder), ExtraShapeData:
//    &protocol.CylinderShape{RadiusX: Vec2{1,0}, RadiusZ: Vec2{0,1}, Height: 3, NumSegments: 8}},
//   {NetworkID: 6, Type: Option(PrimitiveShapePyramid), ExtraShapeData:
//    &protocol.PyramidShape{Width: 2, Depth: Option(4), Height: 6}}
const std::string golden_v1001_tail = bytes({
    // -- cylinder
    0x05,                    //   network_id = 5
    0x01, 0x06,              //   shape_type present, CYLINDER (uint8)
    0x00, 0x00, 0x00, 0x00,  //   the eight remaining optionals absent
    0x00, 0x00, 0x00, 0x00,  //
    0x06,                    //   extra_data_payload index 6 (Cylinder)
    0x00, 0x00, 0x80, 0x3f,  //     radius_x.x = 1.0f
    0x00, 0x00, 0x00, 0x00,  //     radius_x.y = 0.0f
    0x00, 0x00, 0x00, 0x00,  //     radius_z.x = 0.0f
    0x00, 0x00, 0x80, 0x3f,  //     radius_z.y = 1.0f
    0x00, 0x00, 0x40, 0x40,  //     height = 3.0f
    0x08,                    //     num_segments = 8
    // -- pyramid
    0x06,                    //   network_id = 6
    0x01, 0x07,              //   shape_type present, PYRAMID (uint8)
    0x00, 0x00, 0x00, 0x00,  //   the eight remaining optionals absent
    0x00, 0x00, 0x00, 0x00,  //
    0x07,                    //   extra_data_payload index 7 (Pyramid)
    0x00, 0x00, 0x00, 0x40,  //     width = 2.0f
    0x01, 0x00, 0x00, 0x80, 0x40,  //     depth present, 4.0f
    0x00, 0x00, 0xc0, 0x40,  //     height = 6.0f
});

// Only the shape count and the appended shapes differ, so the v1001 golden is the
// v975 one with a new count and the two extra bodies.
const std::string golden_v1001 = bytes({0x05}) + golden_v975.substr(1) + golden_v1001_tail;

}  // namespace

TEST_CASE("packet id is 328 at both eras")
{
    STATIC_REQUIRE(PacketV975::Id == 328);
    STATIC_REQUIRE(PacketV1001::Id == 328);
}

TEST_CASE("primitive shapes v975 round-trips against the golden")
{
    using Payload = bp::base::PrimitiveShapeDataPayload;

    PacketV975 packet;
    packet.shapes = {cleared_shape<Payload>(), sphere_shape<Payload>(), text_shape<Payload>()};
    REQUIRE(encode(packet) == golden_v975);

    bp::BinaryReader reader{golden_v975};
    auto back = bp::Serializer<PacketV975>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->shapes.size() == 3);
    REQUIRE(back->shapes[0].extra_data_payload.index() == 0);  // monostate: shape cleared
    REQUIRE_FALSE(back->shapes[0].shape_type.has_value());
    REQUIRE(back->shapes[1].attached_to_id == static_cast<bp::ActorUniqueID>(-7));
    REQUIRE(back->shapes[1].color == argb);
    REQUIRE(std::get<5>(back->shapes[1].extra_data_payload).num_segments == 12);
    REQUIRE(std::get<2>(back->shapes[2].extra_data_payload).text == "hi");
}

// 989 appended Cylinder, Pyramid, Ellipsoid and Cone to the variant. They take indices
// 6..9, so every earlier case keeps the tag it had at 975.
TEST_CASE("primitive shapes v1001 round-trips against the golden")
{
    using Payload = bp::v1001::PrimitiveShapeDataPayload;

    Payload cylinder;
    cylinder.network_id = 5;
    cylinder.shape_type = bp::ScriptPrimitiveShapeType::CYLINDER;
    cylinder.extra_data_payload = bp::CylinderDataPayload{
        .radius_x = {.x = 1.0f, .y = 0.0f},
        .radius_z = {.x = 0.0f, .y = 1.0f},
        .height = 3.0f,
        .num_segments = 8,
    };

    Payload pyramid;
    pyramid.network_id = 6;
    pyramid.shape_type = bp::ScriptPrimitiveShapeType::PYRAMID;
    pyramid.extra_data_payload = bp::PyramidDataPayload{.width = 2.0f, .depth = 4.0f, .height = 6.0f};

    PacketV1001 packet;
    packet.shapes = {cleared_shape<Payload>(), sphere_shape<Payload>(), text_shape<Payload>(), cylinder, pyramid};
    REQUIRE(encode(packet) == golden_v1001);

    bp::BinaryReader reader{golden_v1001};
    auto back = bp::Serializer<PacketV1001>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->shapes.size() == 5);
    REQUIRE(std::get<5>(back->shapes[1].extra_data_payload).num_segments == 12);

    const auto &read_cylinder = std::get<6>(back->shapes[3].extra_data_payload);
    REQUIRE(read_cylinder.radius_x.x == 1.0f);
    REQUIRE(read_cylinder.radius_z.y == 1.0f);
    REQUIRE(read_cylinder.height == 3.0f);
    REQUIRE(read_cylinder.num_segments == 8);

    const auto &read_pyramid = std::get<7>(back->shapes[4].extra_data_payload);
    REQUIRE(read_pyramid.width == 2.0f);
    REQUIRE(read_pyramid.depth == 4.0f);
    REQUIRE(read_pyramid.height == 6.0f);
}
