#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("BlockPickRequestPacket: id + round-trip")
{
    STATIC_REQUIRE(bp::BlockPickRequestPacket::Id == 34);

    bp::BlockPickRequestPacket pkt;
    pkt.pos = bp::BlockPos{10, 64, -3};
    pkt.with_data = true;
    pkt.max_slots = 5;

    // generated by gophertunnel:
    // packet.BlockPickRequest{Position: {10, 64, -3}, AddBlockNBT: true, HotBarSlot: 5}
    const std::vector<std::uint8_t> golden{0x14, 0x80, 0x01, 0x05, 0x01, 0x05};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::BlockPickRequestPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->pos.x == 10);
    REQUIRE(rt->pos.y == 64);
    REQUIRE(rt->pos.z == -3);
    REQUIRE(rt->with_data == true);
    REQUIRE(rt->max_slots == 5);
}
