#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("InventoryContentPacket: id + round-trip with empty slots and inventory container")
{
    STATIC_REQUIRE(bp::InventoryContentPacket::Id == 49);

    bp::InventoryContentPacket pkt;
    pkt.inventory_id = 1;
    pkt.slots = {};
    pkt.full_container_name.name = bp::ContainerEnumName::InventoryContainer;
    pkt.full_container_name.dynamic_id = std::nullopt;
    pkt.storage_item.id = 0;

    // generated by gophertunnel:
    // packet.InventoryContent{WindowID: 1, Content: [],
    //   Container: protocol.FullContainerName{ContainerID: 29},
    //   StorageItem: protocol.ItemInstance{}}
    const std::vector<std::uint8_t> golden{
        0x01, 0x00, 0x1D, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::InventoryContentPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->inventory_id == 1);
    REQUIRE(rt->slots.empty());
    REQUIRE(rt->full_container_name.name == bp::ContainerEnumName::InventoryContainer);
    REQUIRE_FALSE(rt->full_container_name.dynamic_id.has_value());
    REQUIRE(rt->storage_item.id == 0);
}
