#include <string>

#include <bedrock/protocol/inventory.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ContainerClose{WindowID: 120,
// ContainerType: 18, ServerSide: true}
const std::string golden = bytes({
    0x78, 0x12, 0x01,
});

// generated by gophertunnel: &packet.ContainerClose{WindowID: 255,
// ContainerType: 247, ServerSide: false}
const std::string golden_none = bytes({
    0xff, 0xf7, 0x00,
});

}  // namespace

TEST_CASE("packet id is 47")
{
    STATIC_REQUIRE(bp::ContainerClosePacket_<2168>::Id == 47);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 47>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 47>);
}

TEST_CASE("container-close round-trips against the golden")
{
    bp::ContainerClosePacket_<2168> packet;
    packet.container_id = bp::ContainerID::ARMOR;
    packet.container_type = bp::ContainerType::ARMOR;
    packet.server_initiated_close = true;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::ContainerClosePacket_<2168>>(golden);
    REQUIRE(back.container_id == bp::ContainerID::ARMOR);
    REQUIRE(back.container_type == bp::ContainerType::ARMOR);
    REQUIRE(back.server_initiated_close);
}

TEST_CASE("each negative sentinel costs one signed byte, not a varint")
{
    bp::ContainerClosePacket_<2168> packet;
    packet.container_id = bp::ContainerID::NONE;
    packet.container_type = bp::ContainerType::NONE;
    packet.server_initiated_close = false;
    REQUIRE(encode(packet) == golden_none);

    const auto back = decode<bp::ContainerClosePacket_<2168>>(golden_none);
    REQUIRE(back.container_id == bp::ContainerID::NONE);
    REQUIRE(back.container_type == bp::ContainerType::NONE);
    REQUIRE_FALSE(back.server_initiated_close);
}
