#include <cstdint>
#include <string>
#include <type_traits>
#include <variant>

#include <bedrock/protocol/data_store.h>
#include <bedrock/protocol/network.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ClientBoundDataStore{Updates: []protocol.DataStoreChangeEntry{
// {ChangeType: protocol.DataStoreChangeTypeUpdate, Update: protocol.DataStoreUpdate{
// DataStoreName: "hud", Property: "opacity", ControlType: protocol.DataStoreControlDouble,
// DoubleValue: 0.5, PropertyUpdateCount: 1}},
// {ChangeType: protocol.DataStoreChangeTypeChange, Change: protocol.DataStoreChange{
// DataStoreName: "form", Property: "title", UpdateCount: 7, NewValue: protocol.DataStorePropertyValue{
// Type: protocol.DataStorePropertyTypeString, StringValue: "Chest"}}},
// {ChangeType: protocol.DataStoreChangeTypeRemoval, Removal: protocol.DataStoreRemoval{
// DataStoreName: "form"}}}}
const std::string golden = bytes({
    0x03, 0x00, 0x03, 0x68, 0x75, 0x64, 0x07, 0x6f, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xe0, 0x3f, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x01, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x07, 0x00, 0x00, 0x00,
    0x04, 0x00, 0x00, 0x00, 0x05, 0x43, 0x68, 0x65, 0x73, 0x74, 0x02, 0x04, 0x66, 0x6f, 0x72, 0x6d,
});

// generated by gophertunnel: &packet.ClientBoundDataStore{Updates: []protocol.DataStoreChangeEntry{
// {ChangeType: protocol.DataStoreChangeTypeChange, Change: protocol.DataStoreChange{
// DataStoreName: "form", Property: "state", UpdateCount: 2, NewValue: protocol.DataStorePropertyValue{
// Type: protocol.DataStorePropertyTypeMap, MapValue: []protocol.DataStoreMapEntry{
// {Key: "flag", Value: {Type: protocol.DataStorePropertyTypeBool, BoolValue: true}},
// {Key: "items", Value: {Type: protocol.DataStorePropertyTypeList, ListValue: []protocol.DataStorePropertyValue{
// {Type: protocol.DataStorePropertyTypeString, StringValue: "a"},
// {Type: protocol.DataStorePropertyTypeInt64, Int64Value: 7}}}},
// {Key: "nothing", Value: {Type: protocol.DataStorePropertyTypeNone}},
// {Key: "ratio", Value: {Type: protocol.DataStorePropertyTypeDouble, DoubleValue: 0.25}}}}}}}}
const std::string golden_nested = bytes({
    0x01, 0x01, 0x04, 0x66, 0x6f, 0x72, 0x6d, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x02, 0x00, 0x00, 0x00, 0x06, 0x00,
    0x00, 0x00, 0x04, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x01, 0x00, 0x00, 0x00, 0x01, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73,
    0x05, 0x00, 0x00, 0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x01, 0x61, 0x02, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x07, 0x6e, 0x6f, 0x74, 0x68, 0x69, 0x6e, 0x67, 0x00, 0x00, 0x00, 0x00, 0x05, 0x72, 0x61,
    0x74, 0x69, 0x6f, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xd0, 0x3f,
});

bp::DynamicValue nested_state()
{
    return bp::DynamicValue::Object{
        {"flag", bp::DynamicValue{true}},
        {"items", bp::DynamicValue::Array{bp::DynamicValue{"a"}, bp::DynamicValue{bp::DynamicValue::Integer{7}}}},
        {"nothing", bp::DynamicValue{}},
        {"ratio", bp::DynamicValue{0.25}},
    };
}

}  // namespace

TEST_CASE("packet id is 330")
{
    STATIC_REQUIRE(bp::ClientboundDataStorePacket::Id == 330);
    STATIC_REQUIRE(bp::has_packet_v<1001, 330>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 330>);
}

// Id 330 changes owner rather than arriving: DataStoreSyncPacket holds it from 859,
// and 898 hands it to ClientboundDataStorePacket while adding 332 alongside. The
// header walks EndId 330 / 332 / 333 across r21_u11 / r21_u12 / r21_u13.
TEST_CASE("id 330 changes owner at 898, and 332 arrives there")
{
    STATIC_REQUIRE_FALSE(bp::has_packet_v<858, 330>);
    STATIC_REQUIRE(bp::has_packet_v<859, 330>);
    STATIC_REQUIRE(std::is_same_v<bp::packet_of_t<897, 330>, bp::DataStoreSyncPacket_<897>>);
    STATIC_REQUIRE(std::is_same_v<bp::packet_of_t<898, 330>, bp::ClientboundDataStorePacket_<898>>);

    STATIC_REQUIRE_FALSE(bp::has_packet_v<897, 332>);
    STATIC_REQUIRE(bp::has_packet_v<898, 332>);
    STATIC_REQUIRE(static_cast<int>(bp::MinecraftPacketIds_<858>::EndId) == 330);
    STATIC_REQUIRE(static_cast<int>(bp::MinecraftPacketIds_<897>::EndId) == 332);
    STATIC_REQUIRE(static_cast<int>(bp::MinecraftPacketIds_<898>::EndId) == 333);
}

// The 859 sync packet carries a two-case variant; 898 inserts DataStoreUpdate at
// index 0, renumbering both survivors -- which is why these are two classes.
TEST_CASE("the 859 sync packet variant has two cases")
{
    using Packet = bp::DataStoreSyncPacket_<897>;

    Packet packet;
    packet.updates = {bp::DataStoreRemoval{.data_store_name = "ds"}};
    const auto wire = encode(packet);
    REQUIRE(static_cast<unsigned char>(wire[1]) == 0x01);

    REQUIRE(decode<Packet>(wire).updates.size() == 1);
}

TEST_CASE("every data store change type round-trips against the golden")
{
    bp::DataStoreUpdate update;
    update.data_store_name = "hud";
    update.property = "opacity";
    update.data = 0.5;
    update.property_update_count = 1;

    bp::DataStoreChange change;
    change.data_store_name = "form";
    change.property = "title";
    change.update_count = 7;
    change.new_data = bp::DynamicValue{"Chest"};

    bp::DataStoreRemoval removal;
    removal.data_store_name = "form";

    bp::ClientboundDataStorePacket packet;
    packet.updates = {update, change, removal};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::ClientboundDataStorePacket>(golden);
    REQUIRE(back.updates.size() == 3);
    REQUIRE(std::get<0>(back.updates[0]).property == "opacity");
    REQUIRE(std::get<0>(std::get<0>(back.updates[0]).data) == 0.5);
    REQUIRE(std::get<1>(back.updates[1]).update_count == 7);
    REQUIRE(std::get<1>(back.updates[1]).new_data.get<bp::DynamicValue::String>() == "Chest");
    REQUIRE(std::get<2>(back.updates[2]).data_store_name == "form");
}

TEST_CASE("a dynamic value nests arrays and objects")
{
    bp::DataStoreChange change;
    change.data_store_name = "form";
    change.property = "state";
    change.update_count = 2;
    change.new_data = nested_state();

    bp::ClientboundDataStorePacket packet;
    packet.updates = {change};
    REQUIRE(encode(packet) == golden_nested);

    const auto back = decode<bp::ClientboundDataStorePacket>(golden_nested);
    REQUIRE(std::get<1>(back.updates[0]).new_data == nested_state());
}

TEST_CASE("a dynamic value tags each arm with four little-endian bytes")
{
    const auto null_value = encode(bp::DynamicValue{});
    REQUIRE(null_value == bytes({0x00, 0x00, 0x00, 0x00}));
    REQUIRE(encode(bp::DynamicValue{true}).size() == null_value.size() + 1);
    REQUIRE(encode(bp::DynamicValue{std::int64_t{7}}).size() == null_value.size() + 8);
    REQUIRE(encode(bp::DynamicValue{0.25}).size() == null_value.size() + 8);

    REQUIRE(rejects<bp::DynamicValue>(bytes({0x07, 0x00, 0x00, 0x00})));
}
