#include <optional>
#include <string>

#include "fixture.hpp"

namespace {

// AddPlayerPacket cerealised at 2168; r26_u3 carries no AddPlayerPacket.json. Field for
// field the 1001 and 2168 forms are the same packet -- gophertunnel's add_player.go and
// CloudburstMC's AddPlayerSerializer_v557 (which v2168 does not override) agree on the
// order, and the r26_u4 dump matches both. The wire delta is in the closure: the entity
// data list gained a restated type byte per item, and the carried item cerealised.
template <class Packet>
void fill(Packet &packet)
{
    packet.uuid = {.most_significant_bits = 1, .least_significant_bits = 2};
    packet.name = "Steve";
    packet.runtime_id = static_cast<bp::ActorRuntimeID>(2);
    packet.platform_online_id = "chat";
    packet.pos = {.x = 1.0f, .y = 2.0f, .z = 3.0f};
    packet.velocity = {.x = 4.0f, .y = 5.0f, .z = 6.0f};
    packet.rot = {.x = 7.0f, .y = 8.0f};
    packet.y_head_rot = 9.0f;
    packet.carried_item.id = 5;
    packet.carried_item.stack_size = 1;
    packet.carried_item.aux_value = 0;
    packet.carried_item.net_id_variant = std::nullopt;
    packet.carried_item.block_runtime_id = 0;
    packet.carried_item.user_data_buffer = empty_item_blob();
    packet.player_game_type = bp::GameType::SURVIVAL;
    packet.synched_properties.int_entries.push_back({.property_index = 1, .data = -2});
    packet.synched_properties.float_entries.push_back({.property_index = 2, .data = 0.5f});
    packet.abilities.target_player = static_cast<bp::ActorUniqueID>(1);
    packet.abilities.player_permissions = bp::PlayerPermissionLevel::MEMBER;
    packet.abilities.command_permissions = bp::CommandPermissionLevel::ANY;
    packet.abilities.layers.push_back({.serialized_layer = bp::SerializedAbilitiesData::SerializedAbilitiesLayer::BASE,
                                       .abilities_set = 0,
                                       .ability_values = 0,
                                       .fly_speed = 0.05f,
                                       .vertical_fly_speed = 1.0f,
                                       .walk_speed = 0.1f});
    packet.links.push_back({.a = static_cast<bp::ActorUniqueID>(1),
                            .b = static_cast<bp::ActorUniqueID>(2),
                            .type = bp::ActorLinkType::RIDING,
                            .immediate = true,
                            .passenger_initiated = false,
                            .vehicle_angular_velocity = 1.5f});
    packet.device_id = "dev";
    packet.build_platform = bp::BuildPlatform::WIN32;
}

}  // namespace

TEST_CASE("packet id is 12 at both versions")
{
    STATIC_REQUIRE(bp::AddPlayerPacket_<1001>::Id == 12);
    STATIC_REQUIRE(bp::AddPlayerPacket_<2168>::Id == 12);
}

TEST_CASE("AddPlayerPacket: v2168 round-trip")
{
    using Packet = bp::AddPlayerPacket_<2168>;

    Packet pkt;
    fill(pkt);
    pkt.unpack.data.push_back(
        {.id = 38, .payload = bp::DataItemFloatPayload_<2168>{.type = bp::DataItemType::FLOAT, .value = 0.5f}});

    // generated by CloudburstMC Bedrock_v2168:
    // AddPlayerPacket{uuid: 00000000-0000-0001-0000-000000000002, username: "Steve",
    //   uniqueEntityId: 1, runtimeEntityId: 2, platformChatId: "chat",
    //   position: (1, 2, 3), motion: (4, 5, 6), rotation: (7, 8, 9),
    //   hand: ItemData(minecraft:stone runtimeId 5, count 1, damage 0),
    //   gameType: SURVIVAL, metadata: {SCALE: 0.5f},
    //   properties: EntityProperties(int: [(1, -2)], float: [(2, 0.5)]),
    //   playerPermission: MEMBER, commandPermission: ANY,
    //   abilityLayers: [AbilityLayer(BASE, {}, {}, fly 0.05, verticalFly 1.0, walk 0.1)],
    //   entityLinks: [EntityLinkData(1, 2, RIDER, true, false, 1.5)],
    //   deviceId: "dev", buildPlatform: WIN32}
    const std::string golden = bytes({
        0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x05, 0x53, 0x74, 0x65, 0x76, 0x65, 0x02, 0x04,
        0x63, 0x68, 0x61, 0x74, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40,
        0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x80, 0x40, 0x00, 0x00, 0xA0, 0x40,
        0x00, 0x00, 0xC0, 0x40, 0x00, 0x00, 0xE0, 0x40, 0x00, 0x00, 0x00, 0x41,
        0x00, 0x00, 0x10, 0x41, 0x05, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x0A,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
        0x26, 0x03, 0x03, 0x00, 0x00, 0x00, 0x3F, 0x01, 0x01, 0x03, 0x01, 0x02,
        0x00, 0x00, 0x00, 0x3F, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x01, 0x00, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0xCD, 0xCC, 0x4C, 0x3D, 0x00, 0x00, 0x80, 0x3F, 0xCD, 0xCC, 0xCC,
        0x3D, 0x01, 0x02, 0x04, 0x01, 0x01, 0x00, 0x00, 0x00, 0xC0, 0x3F, 0x03,
        0x64, 0x65, 0x76, 0x08, 0x00, 0x00, 0x00,
    });

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.name == "Steve");
    REQUIRE(rt.platform_online_id == "chat");
    REQUIRE(rt.carried_item.id == 5);
    REQUIRE_FALSE(rt.carried_item.net_id_variant.has_value());
    REQUIRE(rt.unpack.data.size() == 1);
    REQUIRE(std::get<3>(rt.unpack.data[0].payload).type == bp::DataItemType::FLOAT);
    REQUIRE(rt.abilities.target_player == static_cast<bp::ActorUniqueID>(1));
    REQUIRE(rt.abilities.layers.size() == 1);
    REQUIRE(rt.abilities.layers[0].walk_speed == 0.1f);
    REQUIRE(rt.device_id == "dev");
    REQUIRE(rt.build_platform == bp::BuildPlatform::WIN32);
}

// TODO: confirm against BDS -- structural rather than golden, because neither codec can
// produce the 1001 bytes this schema encodes. AddPlayerPacket does not cerealise until
// 2168, so below 2168 BDS writes NetworkItemStackDescriptor::write for the carried item;
// gophertunnel's add_player.go (io.ItemInstance) and CloudburstMC v1001 (writeItem
// inherited from v431) both do exactly that. The shared SerializedNetworkItemStackDescriptor
// declaration resolves to the cerealised body at the 1001 snapshot instead, which makes a
// gophertunnel golden disagree over the whole item. See protocol/movement.py.
TEST_CASE("AddPlayerPacket: v1001 round-trips and is one data-item byte shorter")
{
    using Packet = bp::AddPlayerPacket_<1001>;

    Packet pkt;
    fill(pkt);
    pkt.unpack.data.push_back({.id = 38, .payload = bp::DataItemFloatPayload_<1001>{.value = 0.5f}});

    const auto encoded = encode(pkt);

    bp::AddPlayerPacket_<2168> newer;
    fill(newer);
    newer.unpack.data.push_back(
        {.id = 38, .payload = bp::DataItemFloatPayload_<2168>{.type = bp::DataItemType::FLOAT, .value = 0.5f}});
    REQUIRE(encoded.size() + 1 == encode(newer).size());

    const auto rt = decode<Packet>(encoded);
    REQUIRE(rt.name == "Steve");
    REQUIRE(rt.carried_item.id == 5);
    REQUIRE(rt.unpack.data.size() == 1);
    REQUIRE(std::get<3>(rt.unpack.data[0].payload).value == 0.5f);
    REQUIRE(rt.abilities.command_permissions == bp::CommandPermissionLevel::ANY);
    REQUIRE(rt.build_platform == bp::BuildPlatform::WIN32);

    REQUIRE(rejects<Packet>(encode(newer)));
}
