#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("CodeBuilderPacket: id + round-trip with a single URL + open flag")
{
    STATIC_REQUIRE(bp::CodeBuilderPacket::Id == 150);

    bp::CodeBuilderPacket pkt;
    pkt.url = "ws://x";
    pkt.should_open_code_builder = true;

    // generated by gophertunnel:
    // packet.CodeBuilder{URL: "ws://x", ShouldOpenCodeBuilder: true}
    const std::vector<std::uint8_t> golden{
        0x06, 0x77, 0x73, 0x3A, 0x2F, 0x2F, 0x78, 0x01,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::CodeBuilderPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->url == "ws://x");
    REQUIRE(rt->should_open_code_builder);
}
