#include <string>

#include <protocol/actor.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.SetActorLink{EntityLink: protocol.EntityLink{
// RiddenEntityUniqueID: -1, RiderEntityUniqueID: 300, Type: protocol.EntityLinkPassenger,
// Immediate: false, RiderInitiated: true, VehicleAngularVelocity: -2.5}}
const std::string golden = bytes({
    0x01, 0xd8, 0x04, 0x02, 0x00, 0x01, 0x00, 0x00, 0x20, 0xc0,
});

}  // namespace

TEST_CASE("packet id is 41")
{
    STATIC_REQUIRE(bp::SetActorLinkPacket_<2168>::Id == 41);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 41>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 41>);
}

TEST_CASE("set actor link round-trips against the golden")
{
    bp::SetActorLinkPacket_<2168> packet;
    packet.link.a = static_cast<bp::ActorUniqueID>(-1);
    packet.link.b = static_cast<bp::ActorUniqueID>(300);
    packet.link.type = bp::ActorLinkType::PASSENGER;
    packet.link.immediate = false;
    packet.link.passenger_initiated = true;
    packet.link.vehicle_angular_velocity = -2.5F;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::SetActorLinkPacket_<2168>>(golden);
    REQUIRE(back.link.a == static_cast<bp::ActorUniqueID>(-1));
    REQUIRE(back.link.b == static_cast<bp::ActorUniqueID>(300));
    REQUIRE(back.link.type == bp::ActorLinkType::PASSENGER);
    REQUIRE_FALSE(back.link.immediate);
    REQUIRE(back.link.passenger_initiated);
    REQUIRE(back.link.vehicle_angular_velocity == -2.5F);
}

TEST_CASE("the target ids are 64-bit varints")
{
    bp::SetActorLinkPacket_<2168> packet;
    packet.link.a = static_cast<bp::ActorUniqueID>(4294967296LL);
    packet.link.b = static_cast<bp::ActorUniqueID>(0);
    packet.link.type = bp::ActorLinkType::NONE;
    packet.link.immediate = false;
    packet.link.passenger_initiated = false;
    packet.link.vehicle_angular_velocity = 0.0F;

    const auto wire = encode(packet);
    REQUIRE(wire.size() == 13);
    REQUIRE(decode<bp::SetActorLinkPacket_<2168>>(wire).link.a == static_cast<bp::ActorUniqueID>(4294967296LL));
}

