#include <string>

#include <bedrock/protocol/actor.h>
#include <bedrock/protocol/block.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.UpdateSubChunkBlocks{Position: protocol.BlockPos{4, -5, 6},
// Blocks: []protocol.BlockChangeEntry{{BlockPos: protocol.BlockPos{1, 2, 3}, BlockRuntimeID: 300,
// Flags: 200, SyncedUpdateEntityUniqueID: 9, SyncedUpdateType: 2}},
// Extra: []protocol.BlockChangeEntry{{BlockPos: protocol.BlockPos{-1, 0, 1}, BlockRuntimeID: 5}}}
const std::string golden = bytes({
    0x08, 0x09, 0x0c, 0x01, 0x02, 0x04, 0x06, 0xac, 0x02, 0xc8, 0x01, 0x09,
    0x02, 0x01, 0x01, 0x00, 0x02, 0x05, 0x00, 0x00, 0x00,
});

// generated by gophertunnel: &packet.UpdateSubChunkBlocks{Position: protocol.BlockPos{0, 64, 0}}
const std::string golden_empty = bytes({
    0x00, 0x80, 0x01, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 172")
{
    STATIC_REQUIRE(bp::UpdateSubChunkBlocksPacket_<2168>::Id == 172);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 172>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 172>);
}

TEST_CASE("update-sub-chunk-blocks round-trips against the golden")
{
    bp::UpdateSubChunkBlocksPacket_<2168> packet;
    packet.sub_chunk_block_position = {.x = 4, .y = -5, .z = 6};
    packet.blocks_changed.standards.push_back({
        .pos = {.x = 1, .y = 2, .z = 3},
        .runtime_id = 300,
        .update_flags = 200,
        .entity_unique_id = bp::ActorUniqueID{9},
        .message = bp::ActorBlockSyncMessage::MessageId::DESTROY,
    });
    packet.blocks_changed.extras.push_back({
        .pos = {.x = -1, .y = 0, .z = 1},
        .runtime_id = 5,
        .update_flags = 0,
        .entity_unique_id = bp::ActorUniqueID{0},
        .message = bp::ActorBlockSyncMessage::MessageId::NONE,
    });
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::UpdateSubChunkBlocksPacket_<2168>>(golden);
    REQUIRE(back.sub_chunk_block_position.x == 4);
    REQUIRE(back.sub_chunk_block_position.y == -5);
    REQUIRE(back.sub_chunk_block_position.z == 6);
    REQUIRE(back.blocks_changed.standards.size() == 1);
    REQUIRE(back.blocks_changed.standards.at(0).pos.x == 1);
    REQUIRE(back.blocks_changed.standards.at(0).pos.y == 2);
    REQUIRE(back.blocks_changed.standards.at(0).pos.z == 3);
    REQUIRE(back.blocks_changed.standards.at(0).runtime_id == 300);
    REQUIRE(back.blocks_changed.standards.at(0).update_flags == 200);
    REQUIRE(back.blocks_changed.standards.at(0).entity_unique_id == bp::ActorUniqueID{9});
    REQUIRE(back.blocks_changed.standards.at(0).message == bp::ActorBlockSyncMessage::MessageId::DESTROY);
    REQUIRE(back.blocks_changed.extras.size() == 1);
    REQUIRE(back.blocks_changed.extras.at(0).pos.x == -1);
    REQUIRE(back.blocks_changed.extras.at(0).pos.y == 0);
    REQUIRE(back.blocks_changed.extras.at(0).pos.z == 1);
    REQUIRE(back.blocks_changed.extras.at(0).runtime_id == 5);
    REQUIRE(back.blocks_changed.extras.at(0).message == bp::ActorBlockSyncMessage::MessageId::NONE);
}

TEST_CASE("empty update-sub-chunk-blocks layers are two zero length prefixes")
{
    bp::UpdateSubChunkBlocksPacket_<2168> packet;
    packet.sub_chunk_block_position = {.x = 0, .y = 64, .z = 0};
    REQUIRE(encode(packet) == golden_empty);

    const auto back = decode<bp::UpdateSubChunkBlocksPacket_<2168>>(golden_empty);
    REQUIRE(back.sub_chunk_block_position.y == 64);
    REQUIRE(back.blocks_changed.standards.empty());
    REQUIRE(back.blocks_changed.extras.empty());
}

TEST_CASE("an update-sub-chunk-blocks body missing its extras list is rejected")
{
    REQUIRE(rejects<bp::UpdateSubChunkBlocksPacket_<2168>>(golden.substr(0, 13)));
    REQUIRE(rejects<bp::UpdateSubChunkBlocksPacket_<2168>>(golden.substr(0, 4)));
}
