#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("CreativeContentPacket: id + round-trip with empty groups and contents")
{
    STATIC_REQUIRE(bp::CreativeContentPacket::Id == 145);

    bp::CreativeContentPacket pkt;
    pkt.groups = {};
    pkt.contents = {};

    // generated by gophertunnel:
    // packet.CreativeContent{Groups: [], Items: []}
    const std::vector<std::uint8_t> golden{
        0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::CreativeContentPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->groups.empty());
    REQUIRE(rt->contents.empty());
}
