#include <cstdint>
#include <string>
#include <vector>

#include "fixture.hpp"

namespace {

using PacketV975 = bp::ClientCacheBlobStatusPacket_<975>;
using PacketV1001 = bp::ClientCacheBlobStatusPacket_<1001>;

// generated by gophertunnel at 6353c49^ (de090ae, the last pre-1.26.30 commit):
// packet.ClientCacheBlobStatus{MissHashes: []uint64{1, 2}, HitHashes: []uint64{3}}
const std::string golden_v975 = bytes({
    0x02, 0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00,
});

// generated by gophertunnel (654cd5f): the same two lists, each now carrying its own
// count immediately ahead of its elements.
const std::string golden_v1001 = bytes({
    0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00,
});

// generated by gophertunnel at both commits: packet.ClientCacheBlobStatus{}
const std::string golden_empty = bytes({0x00, 0x00});

}  // namespace

TEST_CASE("packet id is 135 at both eras")
{
    STATIC_REQUIRE(PacketV975::Id == 135);
    STATIC_REQUIRE(PacketV1001::Id == 135);
}

// Pre-cereal both counts are written up front, so neither list carries a prefix of its
// own and the read recomputes each length from the count field it already filled in.
TEST_CASE("client-cache-blob-status v975 round-trips against the golden")
{
    PacketV975 packet;
    packet.missing_count = 2;
    packet.found_count = 1;
    packet.missing_ids = {1, 2};
    packet.found_ids = {3};
    REQUIRE(encode(packet) == golden_v975);

    const auto back = decode<PacketV975>(golden_v975);
    REQUIRE(back.missing_ids == std::vector<std::uint64_t>{1, 2});
    REQUIRE(back.found_ids == std::vector<std::uint64_t>{3});
}

TEST_CASE("client-cache-blob-status v1001 round-trips against the golden")
{
    PacketV1001 packet;
    packet.missing_ids = {1, 2};
    packet.found_ids = {3};
    REQUIRE(encode(packet) == golden_v1001);

    const auto back = decode<PacketV1001>(golden_v1001);
    REQUIRE(back.missing_ids == std::vector<std::uint64_t>{1, 2});
    REQUIRE(back.found_ids == std::vector<std::uint64_t>{3});
}

// Two empty lists are two zeroes either way, so an idle client's packet is the one
// place the reshape is invisible.
TEST_CASE("client-cache-blob-status is byte-identical across eras when empty")
{
    REQUIRE(encode(PacketV975{}) == golden_empty);
    REQUIRE(encode(PacketV1001{}) == golden_empty);
}
