#include <string>

#include <bedrock/protocol/attributes.h>
#include <bedrock/protocol/chunk.h>

#include "fixture.hpp"

namespace {

using PacketV975 = bp::LevelChunkPacket_<975>;
using PacketV1001 = bp::LevelChunkPacket_<1001>;
using PacketV2168 = bp::LevelChunkPacket_<2168>;

const std::string payload_ab = std::string("\xaa\xbb", 2);
const std::string payload_a = std::string("\xaa", 1);

// generated by gophertunnel (0a2ecd563):
// packet.LevelChunk{Position: protocol.ChunkPos{2, 3}, Dimension: 0,
//   SubChunkCount: 5, CacheEnabled: false, RawPayload: []byte{0xaa, 0xbb}}
const std::string golden_v1001_full = bytes({
    0x04, 0x06, 0x00, 0x05, 0x00, 0x02, 0xaa, 0xbb,
});

// generated by gophertunnel (0a2ecd563):
// packet.LevelChunk{Position: protocol.ChunkPos{2, 3}, Dimension: 1,
//   SubChunkCount: protocol.SubChunkRequestModeLimited, HighestSubChunk: 7,
//   CacheEnabled: true, BlobHashes: []uint64{1, 2}, RawPayload: []byte{0xaa}}
const std::string golden_v1001_limited = bytes({
    0x04, 0x06, 0x02, 0xfe, 0xff, 0xff, 0xff, 0x0f, 0x07, 0x00, 0x01, 0x02,
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x01, 0xaa,
});

// generated by gophertunnel (0a2ecd563):
// packet.LevelChunk{Position: protocol.ChunkPos{2, 3}, Dimension: 0,
//   SubChunkCount: protocol.SubChunkRequestModeLimitless, CacheEnabled: false,
//   RawPayload: []byte{0xaa}}
const std::string golden_v1001_limitless = bytes({
    0x04, 0x06, 0x00, 0xff, 0xff, 0xff, 0xff, 0x0f, 0x00, 0x01, 0xaa,
});

// generated by CloudburstMC Bedrock_v2168:
// LevelChunkPacket{chunkX: 2, chunkZ: 3, dimension: 0, subChunksLength: 5,
//   requestSubChunks: false, cachingEnabled: false, blobIds: [], data: aa bb}
const std::string golden_v2168_full = bytes({
    0x04, 0x06, 0x00, 0x05, 0x00, 0x00, 0x00, 0x02, 0xaa, 0xbb,
});

// generated by CloudburstMC Bedrock_v2168:
// LevelChunkPacket{chunkX: 2, chunkZ: 3, dimension: 1, subChunksLength: 0,
//   requestSubChunks: true, subChunkLimit: 7, cachingEnabled: true,
//   blobIds: [1, 2], data: aa}
const std::string golden_v2168_limited = bytes({
    0x04, 0x06, 0x02, 0x00, 0x01, 0x0e, 0x01, 0x02, 0x01, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x01, 0xaa,
});

// generated by CloudburstMC Bedrock_v2168:
// LevelChunkPacket{chunkX: 2, chunkZ: 3, dimension: 0, subChunksLength: 0,
//   requestSubChunks: true, subChunkLimit: -1, cachingEnabled: false,
//   blobIds: [], data: aa}
const std::string golden_v2168_limitless = bytes({
    0x04, 0x06, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0xaa,
});

}  // namespace

TEST_CASE("packet id is 58 at every version")
{
    STATIC_REQUIRE(PacketV975::Id == 58);
    STATIC_REQUIRE(PacketV1001::Id == 58);
    STATIC_REQUIRE(PacketV2168::Id == 58);
}

TEST_CASE("level-chunk v1001 full form round-trips against the golden")
{
    PacketV1001 packet;
    packet.pos = {.x = 2, .z = 3};
    packet.dimension_id = bp::DimensionType{0};
    packet.sub_chunks_count = 5;
    packet.cache_enabled = false;
    packet.serialized_chunk = payload_ab;
    REQUIRE(encode(packet) == golden_v1001_full);

    const auto back = decode<PacketV1001>(golden_v1001_full);
    REQUIRE(back.pos.x == 2);
    REQUIRE(back.pos.z == 3);
    REQUIRE(back.sub_chunks_count == 5);
    REQUIRE(back.cache_enabled == false);
    REQUIRE(back.cache_metadata.empty());
    REQUIRE(back.serialized_chunk == payload_ab);
}

// 0xfffffffe is LevelChunkPacket::PARTIAL_SUBCHUNK_COUNT_WHEN_CLIENT_REQUESTING:
// the count doubles as a request marker, and only that value puts the limit on
// the wire. The cache flag independently gates the blob list.
TEST_CASE("level-chunk v1001 partial-request form round-trips against the golden")
{
    PacketV1001 packet;
    packet.pos = {.x = 2, .z = 3};
    packet.dimension_id = bp::DimensionType{1};
    packet.sub_chunks_count = 0xfffffffe;
    packet.client_request_sub_chunk_limit = 7;
    packet.cache_enabled = true;
    packet.cache_metadata.push_back({.blob_id = 1});
    packet.cache_metadata.push_back({.blob_id = 2});
    packet.serialized_chunk = payload_a;
    REQUIRE(encode(packet) == golden_v1001_limited);

    const auto back = decode<PacketV1001>(golden_v1001_limited);
    REQUIRE(back.sub_chunks_count == 0xfffffffe);
    REQUIRE(back.client_request_sub_chunk_limit == 7);
    REQUIRE(back.cache_metadata.size() == 2);
    REQUIRE(back.cache_metadata[1].blob_id == 2);
    REQUIRE(back.serialized_chunk == payload_a);
}

// 0xffffffff is SUBCHUNK_COUNT_WHEN_CLIENT_REQUESTING: a request with no limit,
// so the sixteen-bit limit is absent even though the packet is a request.
TEST_CASE("level-chunk v1001 unlimited-request form round-trips against the golden")
{
    PacketV1001 packet;
    packet.pos = {.x = 2, .z = 3};
    packet.dimension_id = bp::DimensionType{0};
    packet.sub_chunks_count = 0xffffffff;
    packet.cache_enabled = false;
    packet.serialized_chunk = payload_a;
    REQUIRE(encode(packet) == golden_v1001_limitless);

    const auto back = decode<PacketV1001>(golden_v1001_limitless);
    REQUIRE(back.sub_chunks_count == 0xffffffff);
    REQUIRE(back.serialized_chunk == payload_a);
}

TEST_CASE("level-chunk is unchanged between v975 and v1001")
{
    PacketV975 older;
    older.pos = {.x = 2, .z = 3};
    older.dimension_id = bp::DimensionType{0};
    older.sub_chunks_count = 5;
    older.cache_enabled = false;
    older.serialized_chunk = payload_ab;
    REQUIRE(encode(older) == golden_v1001_full);
}

TEST_CASE("level-chunk v2168 full form round-trips against the golden")
{
    PacketV2168 packet;
    packet.pos = {.x = 2, .z = 3};
    packet.dimension_id = bp::DimensionType{0};
    packet.sub_chunks_count = 5;
    packet.cache_enabled = false;
    packet.serialized_chunk = payload_ab;
    REQUIRE(encode(packet) == golden_v2168_full);

    const auto back = decode<PacketV2168>(golden_v2168_full);
    REQUIRE(back.pos.x == 2);
    REQUIRE(back.sub_chunks_count == 5);
    REQUIRE(back.client_request_sub_chunk_limit.has_value() == false);
    REQUIRE(back.cache_enabled == false);
    REQUIRE(back.cache_metadata.empty());
    REQUIRE(back.serialized_chunk == payload_ab);
}

TEST_CASE("level-chunk v2168 partial-request form round-trips against the golden")
{
    PacketV2168 packet;
    packet.pos = {.x = 2, .z = 3};
    packet.dimension_id = bp::DimensionType{1};
    packet.sub_chunks_count = 0;
    packet.client_request_sub_chunk_limit = 7;
    packet.cache_enabled = true;
    packet.cache_metadata.push_back({.blob_id = 1});
    packet.cache_metadata.push_back({.blob_id = 2});
    packet.serialized_chunk = payload_a;
    REQUIRE(encode(packet) == golden_v2168_limited);

    const auto back = decode<PacketV2168>(golden_v2168_limited);
    REQUIRE(back.client_request_sub_chunk_limit == 7);
    REQUIRE(back.cache_metadata.size() == 2);
    REQUIRE(back.cache_metadata[1].blob_id == 2);
    REQUIRE(back.serialized_chunk == payload_a);
}

// -1 is what the sentinel used to say: a request with no limit. It now rides in
// the payload of the same optional, so the request marker no longer collides
// with the sub-chunk count.
TEST_CASE("level-chunk v2168 unlimited-request form round-trips against the golden")
{
    PacketV2168 packet;
    packet.pos = {.x = 2, .z = 3};
    packet.dimension_id = bp::DimensionType{0};
    packet.sub_chunks_count = 0;
    packet.client_request_sub_chunk_limit = -1;
    packet.cache_enabled = false;
    packet.serialized_chunk = payload_a;
    REQUIRE(encode(packet) == golden_v2168_limitless);

    const auto back = decode<PacketV2168>(golden_v2168_limitless);
    REQUIRE(back.client_request_sub_chunk_limit == -1);
    REQUIRE(back.cache_metadata.empty());
}

// The cerealisation is a wire break in both directions: the request limit moved
// from a count sentinel plus a conditional uint16 to a real optional, and the
// blob list lost its cache-flag gate, so the same chunk costs two more bytes.
TEST_CASE("the cerealisation reshapes the wire, not just the field widths")
{
    REQUIRE(golden_v1001_full.size() + 2 == golden_v2168_full.size());
    REQUIRE(golden_v1001_limited != golden_v2168_limited);
    REQUIRE(golden_v1001_limitless != golden_v2168_limitless);

    // A v1001 body read as v2168 desynchronises at the optional: the cache flag
    // lands on the presence byte and the payload's first byte is taken for a
    // blob count that runs off the end of the frame.
    REQUIRE(rejects<PacketV2168>(golden_v1001_full));

    // The other direction reads short rather than failing -- the extra blob
    // count is consumed as the chunk payload's length prefix.
    const auto stale = decode_partial<PacketV1001>(golden_v2168_full);
    REQUIRE(stale.serialized_chunk.empty());
}
