#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ClientCacheBlobStatusPacket: round-trip")
{
    STATIC_REQUIRE(bp::ClientCacheBlobStatusPacket::Id == 135);

    bp::ClientCacheBlobStatusPacket pkt;
    pkt.missing_count = 2;
    pkt.found_count = 1;
    pkt.missing_ids = {0x1111111111111111ULL, 0x2222222222222222ULL};
    pkt.found_ids = {0x3333333333333333ULL};

    // generated by gophertunnel:
    // packet.ClientCacheBlobStatus{
    //   MissHashes: []uint64{0x1111111111111111, 0x2222222222222222},
    //   HitHashes:  []uint64{0x3333333333333333}}
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x22, 0x22,
        0x22, 0x22, 0x22, 0x22, 0x22, 0x22, 0x33, 0x33, 0x33, 0x33, 0x33, 0x33,
        0x33, 0x33,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ClientCacheBlobStatusPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->missing_count == 2);
    REQUIRE(rt->found_count == 1);
    REQUIRE(rt->missing_ids.size() == 2);
    REQUIRE(rt->missing_ids[0] == 0x1111111111111111ULL);
    REQUIRE(rt->found_ids.size() == 1);
    REQUIRE(rt->found_ids[0] == 0x3333333333333333ULL);
}
