#include <cstdint>
#include <string>
#include <type_traits>

#include "fixture.hpp"

namespace {

using PacketV975 = bp::GameRulesChangedPacket_<975>;
using PacketV1001 = bp::GameRulesChangedPacket_<1001>;
using PacketV2168 = bp::GameRulesChangedPacket_<2168>;

PacketV2168 sample_v2168()
{
    PacketV2168 packet;
    packet.rule_data.rules.push_back({.name = "showcoordinates", .can_be_modified_by_player = true, .value = true});
    packet.rule_data.rules.push_back({.name = "maxcommandchainlength",
                                      .can_be_modified_by_player = false,
                                      .value = std::int32_t{131070}});
    packet.rule_data.rules.push_back({.name = "playerssleepingpercentage",
                                      .can_be_modified_by_player = true,
                                      .value = std::int32_t{100}});
    return packet;
}

// The same three rules, where the integer case is a varint rather than a fixed int32.
PacketV1001 sample_v1001()
{
    PacketV1001 packet;
    packet.rule_data.rules.push_back({.name = "showcoordinates", .can_be_modified_by_player = true, .value = true});
    packet.rule_data.rules.push_back({.name = "maxcommandchainlength",
                                      .can_be_modified_by_player = false,
                                      .value = std::uint32_t{131070}});
    packet.rule_data.rules.push_back({.name = "playerssleepingpercentage",
                                      .can_be_modified_by_player = true,
                                      .value = std::uint32_t{100}});
    return packet;
}

// generated by CloudburstMC Bedrock_v2168:
// GameRulesChangedPacket{gameRules: [GameRuleData("showcoordinates", true, true),
//   GameRuleData("maxcommandchainlength", false, 131070),
//   GameRuleData("playerssleepingpercentage", true, 100)]}
const std::string golden_v2168 = bytes({
    0x03, 0x0F, 0x73, 0x68, 0x6F, 0x77, 0x63, 0x6F, 0x6F, 0x72, 0x64, 0x69,
    0x6E, 0x61, 0x74, 0x65, 0x73, 0x01, 0x01, 0x01, 0x15, 0x6D, 0x61, 0x78,
    0x63, 0x6F, 0x6D, 0x6D, 0x61, 0x6E, 0x64, 0x63, 0x68, 0x61, 0x69, 0x6E,
    0x6C, 0x65, 0x6E, 0x67, 0x74, 0x68, 0x00, 0x02, 0xFE, 0xFF, 0x01, 0x00,
    0x19, 0x70, 0x6C, 0x61, 0x79, 0x65, 0x72, 0x73, 0x73, 0x6C, 0x65, 0x65,
    0x70, 0x69, 0x6E, 0x67, 0x70, 0x65, 0x72, 0x63, 0x65, 0x6E, 0x74, 0x61,
    0x67, 0x65, 0x01, 0x02, 0x64, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("GameRulesChangedPacket: packet id is 72 at every version")
{
    STATIC_REQUIRE(PacketV975::Id == 72);
    STATIC_REQUIRE(PacketV1001::Id == 72);
    STATIC_REQUIRE(PacketV2168::Id == 72);
    STATIC_REQUIRE(bp::has_packet_v<975, 72>);
    STATIC_REQUIRE(bp::has_packet_v<1001, 72>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 72>);
}

TEST_CASE("GameRulesChangedPacket: 975 and 1001 are one shape")
{
    STATIC_REQUIRE(std::is_same_v<PacketV975, PacketV1001>);
}

TEST_CASE("GameRulesChangedPacket: v2168 round-trips against the golden")
{
    REQUIRE(encode(sample_v2168()) == golden_v2168);

    const auto rt = decode<PacketV2168>(golden_v2168);
    REQUIRE(rt.rule_data.rules.size() == 3);
    REQUIRE(rt.rule_data.rules[0].name == "showcoordinates");
    REQUIRE(rt.rule_data.rules[0].can_be_modified_by_player);
    REQUIRE(std::get<1>(rt.rule_data.rules[0].value) == true);
    REQUIRE(rt.rule_data.rules[1].name == "maxcommandchainlength");
    REQUIRE_FALSE(rt.rule_data.rules[1].can_be_modified_by_player);
    REQUIRE(std::get<2>(rt.rule_data.rules[1].value) == 131070);
    REQUIRE(rt.rule_data.rules[2].name == "playerssleepingpercentage");
    REQUIRE(std::get<2>(rt.rule_data.rules[2].value) == 100);
}

// TODO: confirm against BDS -- there is no golden for the v1001 shape because no codec
// produces it. gophertunnel's game_rules_changed.go calls Writer.GameRule, whose integer
// case is a fixed Uint32, and reserves Writer.GameRuleLegacy, whose integer case is a
// Varuint32, for start_game.go; at CurrentProtocol 1001 it therefore writes this packet
// with a fixed integer. CloudburstMC's v975, v1001 and v2168 codecs encode it identically
// to each other. Both references say the integer case below 2168 is fixed where the schema
// writes a varint, so the assertions here are structural and describe only what the schema
// encodes.
TEST_CASE("GameRulesChangedPacket: the v1001 integer case is a varint")
{
    const auto encoded = encode(sample_v1001());

    // 131070 costs three varint bytes and 100 costs one, against four each when fixed
    REQUIRE(encoded.size() + 4 == golden_v2168.size());
    REQUIRE(encoded != golden_v2168);

    const auto rt = decode<PacketV1001>(encoded);
    REQUIRE(rt.rule_data.rules.size() == 3);
    REQUIRE(std::get<2>(rt.rule_data.rules[1].value) == 131070);
    REQUIRE(std::get<2>(rt.rule_data.rules[2].value) == 100);
}

TEST_CASE("GameRulesChangedPacket: neither shape decodes as the other")
{
    REQUIRE(rejects<PacketV2168>(encode(sample_v1001())));
    REQUIRE(rejects<PacketV1001>(golden_v2168));
}
