#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("SetTimePacket: id + round-trip of a single varint32 time")
{
    STATIC_REQUIRE(bp::SetTimePacket::Id == 10);

    bp::SetTimePacket pkt;
    pkt.time = 12345;

    // generated by gophertunnel:
    // packet.SetTime{Time: 12345}
    const std::vector<std::uint8_t> golden{
        0xF2, 0xC0, 0x01,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::SetTimePacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->time == 12345);
}
