#include <string>

#include <bedrock/protocol/network.h>

#include "fixture.hpp"

namespace {

using Packet = bp::LoginPacket;

// generated by gophertunnel (v1.57.1):
// packet.Login{ClientProtocol: 1001, ConnectionRequest: []byte("abc")}
const std::string golden = bytes({
    0x00, 0x00, 0x03, 0xe9, 0x03, 0x61, 0x62, 0x63,
});

}  // namespace

TEST_CASE("packet id is 1")
{
    STATIC_REQUIRE(Packet::Id == 1);
}

// The version is big-endian, as in RequestNetworkSettings. The connection request is
// a length-prefixed blob here, since nothing in the schema reads into it.
TEST_CASE("login round-trips against the golden")
{
    REQUIRE(encode(Packet{.client_network_version = 1001, .connection_request = "abc"}) == golden);

    const auto back = decode<Packet>(golden);
    REQUIRE(back.client_network_version == 1001);
    REQUIRE(back.connection_request == "abc");
}

TEST_CASE("login rejects a connection request shorter than its prefix claims")
{
    REQUIRE(rejects<Packet>(golden.substr(0, golden.size() - 1)));
}
