#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ActorEventPacket: v975 appends an optional Vec3 fire_at_position")
{
    STATIC_REQUIRE(bp::ActorEventPacket::Id == 27);

    bp::ActorEventPacket pkt;
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(42);
    pkt.event_id = bp::ActorEvent::HurtWithoutReceivingDamage;
    pkt.data = 7;
    pkt.fire_at_position = bp::Vec3{1.5f, 64.0f, -3.25f};

    // generated by gophertunnel:
    // packet.ActorEvent{EntityRuntimeID: 42, EventType: byte(ActorEventHurtWithoutReceivingDamage),
    //                   EventData: 7, FireAtPosition: protocol.Option(mgl32.Vec3{1.5, 64, -3.25})}
    const std::vector<std::uint8_t> golden{
        0x2A, 0x51, 0x0E, 0x01, 0x00, 0x00, 0xC0, 0x3F, 0x00, 0x00, 0x80, 0x42,
        0x00, 0x00, 0x50, 0xC0,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ActorEventPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->event_id == bp::ActorEvent::HurtWithoutReceivingDamage);
    REQUIRE(rt->fire_at_position.has_value());
    REQUIRE(rt->fire_at_position->y == 64.0f);
}
