#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("SubClientLoginPacket: id + connection-request blob round-trip")
{
    STATIC_REQUIRE(bp::SubClientLoginPacket::Id == 94);

    bp::SubClientLoginPacket pkt{"hello"};

    // generated by gophertunnel:
    // packet.SubClientLogin{ConnectionRequest: []byte("hello")}
    const std::vector<std::uint8_t> golden{0x05, 0x68, 0x65, 0x6C, 0x6C, 0x6F};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::SubClientLoginPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->connection_request == "hello");
}
