#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("RemoveActorPacket: id + round-trip")
{
    STATIC_REQUIRE(bp::RemoveActorPacket::Id == 14);

    bp::RemoveActorPacket pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(-7);

    // generated by gophertunnel:
    // packet.RemoveActor{EntityUniqueID: -7}
    const std::vector<std::uint8_t> golden{0x0D};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::RemoveActorPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->entity_id == static_cast<bp::ActorUniqueID>(-7));
}
