#include <string>

#include <protocol/actor.h>

#include "fixture.hpp"

namespace {

// AddActorPacket cerealised at 2168, so protocol-docs describes only the 2168 form:
// r26_u3 carries no AddActorPacket.json. The 1001 form is gophertunnel's Marshal.
// Both eras hold the same fields in the same order; the one delta is inside
// SynchedActorData::CopyableDataList, whose entries gained a second, restated type
// byte behind the variant index.
template <class Packet>
void fill(Packet &packet)
{
    packet.entity_id = bp::ActorUniqueID{1};
    packet.runtime_id = bp::ActorRuntimeID{2};
    packet.actor_type = "minecraft:pig";
    packet.pos = {.x = 1.0f, .y = 2.0f, .z = 3.0f};
    packet.velocity = {.x = 4.0f, .y = 5.0f, .z = 6.0f};
    packet.rot = {.x = 7.0f, .y = 8.0f};
    packet.y_head_rotation = 9.0f;
    packet.y_body_rotation = 10.0f;
    packet.attributes.push_back(
        {.name = "minecraft:health", .min_value = 0.0f, .current_value = 20.0f, .max_value = 20.0f});
    packet.synched_properties.int_entries.push_back({.property_index = 1, .data = -2});
    packet.synched_properties.float_entries.push_back({.property_index = 2, .data = 0.5f});
    packet.links.push_back({.a = bp::ActorUniqueID{1},
                            .b = bp::ActorUniqueID{2},
                            .type = bp::ActorLinkType::RIDING,
                            .immediate = true,
                            .passenger_initiated = false,
                            .vehicle_angular_velocity = 1.5f});
}

}  // namespace

TEST_CASE("packet id is 13 at both versions")
{
    STATIC_REQUIRE(bp::AddActorPacket_<1001>::Id == 13);
    STATIC_REQUIRE(bp::AddActorPacket_<2168>::Id == 13);
}

TEST_CASE("AddActorPacket: v1001 round-trip")
{
    using Packet = bp::AddActorPacket_<1001>;

    Packet pkt;
    fill(pkt);
    pkt.data.data.push_back({.id = 38, .payload = bp::DataItemFloatPayload_<1001>{.value = 0.5f}});

    // generated by gophertunnel:
    // packet.AddActor{EntityUniqueID: 1, EntityRuntimeID: 2, EntityType: "minecraft:pig",
    //   Position: {1, 2, 3}, Velocity: {4, 5, 6}, Pitch: 7, Yaw: 8, HeadYaw: 9, BodyYaw: 10,
    //   Attributes: []protocol.AttributeValue{{Name: "minecraft:health", Min: 0, Value: 20, Max: 20}},
    //   EntityMetadata: protocol.EntityMetadata{38: float32(0.5)},
    //   EntityProperties: protocol.EntityProperties{
    //     IntegerProperties: []protocol.IntegerEntityProperty{{Index: 1, Value: -2}},
    //     FloatProperties: []protocol.FloatEntityProperty{{Index: 2, Value: 0.5}}},
    //   EntityLinks: []protocol.EntityLink{{RiddenEntityUniqueID: 1, RiderEntityUniqueID: 2,
    //     Type: 1, Immediate: true, VehicleAngularVelocity: 1.5}}}
    const std::string golden = bytes({
        0x02, 0x02, 0x0D, 0x6D, 0x69, 0x6E, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74,
        0x3A, 0x70, 0x69, 0x67, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40,
        0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x80, 0x40, 0x00, 0x00, 0xA0, 0x40,
        0x00, 0x00, 0xC0, 0x40, 0x00, 0x00, 0xE0, 0x40, 0x00, 0x00, 0x00, 0x41,
        0x00, 0x00, 0x10, 0x41, 0x00, 0x00, 0x20, 0x41, 0x01, 0x10, 0x6D, 0x69,
        0x6E, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3A, 0x68, 0x65, 0x61, 0x6C,
        0x74, 0x68, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xA0, 0x41, 0x00, 0x00,
        0xA0, 0x41, 0x01, 0x26, 0x03, 0x00, 0x00, 0x00, 0x3F, 0x01, 0x01, 0x03,
        0x01, 0x02, 0x00, 0x00, 0x00, 0x3F, 0x01, 0x02, 0x04, 0x01, 0x01, 0x00,
        0x00, 0x00, 0xC0, 0x3F,
    });

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.actor_type == "minecraft:pig");
    REQUIRE(rt.y_body_rotation == 10.0f);
    REQUIRE(rt.attributes.size() == 1);
    REQUIRE(rt.attributes[0].name == "minecraft:health");
    REQUIRE(rt.data.data.size() == 1);
    REQUIRE(rt.data.data[0].id == 38);
    REQUIRE(std::get<3>(rt.data.data[0].payload).value == 0.5f);
    REQUIRE(rt.synched_properties.int_entries[0].data == -2);
    REQUIRE(rt.links[0].type == bp::ActorLinkType::RIDING);
}

TEST_CASE("AddActorPacket: v2168 round-trip")
{
    using Packet = bp::AddActorPacket_<2168>;

    Packet pkt;
    fill(pkt);
    pkt.data.data.push_back(
        {.id = 38, .payload = bp::DataItemFloatPayload_<2168>{.type = bp::DataItemType::FLOAT, .value = 0.5f}});

    // generated by CloudburstMC Bedrock_v2168:
    // AddEntityPacket{uniqueEntityId: 1, runtimeEntityId: 2, identifier: "minecraft:pig",
    //   position: (1, 2, 3), motion: (4, 5, 6), rotation: (7, 8), headRotation: 9,
    //   bodyRotation: 10, attributes: [AttributeData("minecraft:health", 0, 20, 20, 20)],
    //   metadata: {SCALE: 0.5f},
    //   properties: EntityProperties(int: [(1, -2)], float: [(2, 0.5)]),
    //   entityLinks: [EntityLinkData(1, 2, RIDER, true, false, 1.5)]}
    const std::string golden = bytes({
        0x02, 0x02, 0x0D, 0x6D, 0x69, 0x6E, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74,
        0x3A, 0x70, 0x69, 0x67, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40,
        0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x80, 0x40, 0x00, 0x00, 0xA0, 0x40,
        0x00, 0x00, 0xC0, 0x40, 0x00, 0x00, 0xE0, 0x40, 0x00, 0x00, 0x00, 0x41,
        0x00, 0x00, 0x10, 0x41, 0x00, 0x00, 0x20, 0x41, 0x01, 0x10, 0x6D, 0x69,
        0x6E, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3A, 0x68, 0x65, 0x61, 0x6C,
        0x74, 0x68, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xA0, 0x41, 0x00, 0x00,
        0xA0, 0x41, 0x01, 0x26, 0x03, 0x03, 0x00, 0x00, 0x00, 0x3F, 0x01, 0x01,
        0x03, 0x01, 0x02, 0x00, 0x00, 0x00, 0x3F, 0x01, 0x02, 0x04, 0x01, 0x01,
        0x00, 0x00, 0x00, 0xC0, 0x3F,
    });

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.actor_type == "minecraft:pig");
    REQUIRE(rt.data.data.size() == 1);
    REQUIRE(std::get<3>(rt.data.data[0].payload).type == bp::DataItemType::FLOAT);
    REQUIRE(std::get<3>(rt.data.data[0].payload).value == 0.5f);
    REQUIRE(rt.links[0].vehicle_angular_velocity == 1.5f);
}

// The whole 1001 -> 2168 delta on this packet is one byte per data item: the
// variant index still leads, and the payload now restates it as a uint8. Cloudburst's
// v2168 reader rejects a body where the two disagree, so both really are on the wire.
TEST_CASE("AddActorPacket: the data-item type byte is the only wire delta")
{
    bp::AddActorPacket_<1001> older;
    fill(older);
    older.data.data.push_back({.id = 38, .payload = bp::DataItemFloatPayload_<1001>{.value = 0.5f}});

    bp::AddActorPacket_<2168> newer;
    fill(newer);
    newer.data.data.push_back(
        {.id = 38, .payload = bp::DataItemFloatPayload_<2168>{.type = bp::DataItemType::FLOAT, .value = 0.5f}});

    REQUIRE(encode(older).size() + 1 == encode(newer).size());
    REQUIRE(rejects<bp::AddActorPacket_<1001>>(encode(newer)));
}

TEST_CASE("AddActorPacket: an empty data list encodes identically at both versions")
{
    bp::AddActorPacket_<1001> older;
    fill(older);

    bp::AddActorPacket_<2168> newer;
    fill(newer);

    REQUIRE(encode(older) == encode(newer));
}
