#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("AddVolumeEntityPacket: id + round-trip (v944+ wire shape with BlockPos bounds)")
{
    STATIC_REQUIRE(bp::AddVolumeEntityPacket::Id == 166);

    bp::AddVolumeEntityPacket pkt;
    pkt.entity_net_id = 7;
    pkt.components.emplace("tag", bp::ByteTag{1});
    pkt.json_identifier = "minecraft:test";
    pkt.instance_name = "instname";
    pkt.min_bounds = bp::BlockPos{1, 2, 3};
    pkt.max_bounds = bp::BlockPos{4, 5, 6};
    pkt.dimension_type = static_cast<bp::DimensionType>(0);  // Overworld
    pkt.min_engine_version = "1.21.0";

    // generated by gophertunnel:
    // packet.AddVolumeEntity{EntityRuntimeID: 7,
    //   EntityMetadata: {"tag": byte(1)}, EncodingIdentifier: "minecraft:test",
    //   InstanceIdentifier: "instname", Bounds: {{1, 2, 3}, {4, 5, 6}},
    //   Dimension: 0, EngineVersion: "1.21.0"}
    const std::vector<std::uint8_t> golden{
        0x07, 0x0A, 0x00, 0x01, 0x03, 0x74, 0x61, 0x67, 0x01, 0x00, 0x0E, 0x6D,
        0x69, 0x6E, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3A, 0x74, 0x65, 0x73,
        0x74, 0x08, 0x69, 0x6E, 0x73, 0x74, 0x6E, 0x61, 0x6D, 0x65, 0x02, 0x04,
        0x06, 0x08, 0x0A, 0x0C, 0x00, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::AddVolumeEntityPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->json_identifier == "minecraft:test");
    REQUIRE(rt->instance_name == "instname");
    REQUIRE(rt->min_bounds.x == 1);
    REQUIRE(rt->max_bounds.z == 6);
    REQUIRE(rt->min_engine_version == "1.21.0");
}
