#include <string>

#include <bedrock/protocol/network.h>

#include "fixture.hpp"

namespace {

using Packet = bp::RequestNetworkSettingsPacket;

// generated by gophertunnel (v1.57.1):
// packet.RequestNetworkSettings{ClientProtocol: 1001}
const std::string golden_1001 = bytes({
    0x00, 0x00, 0x03, 0xe9,
});

// generated by gophertunnel (v1.57.1):
// packet.RequestNetworkSettings{ClientProtocol: 975}
const std::string golden_975 = bytes({
    0x00, 0x00, 0x03, 0xcf,
});

}  // namespace

TEST_CASE("packet id is 193")
{
    STATIC_REQUIRE(Packet::Id == 193);
}

// The version is the packet's one field, and one of the few Bedrock sends big-endian.
TEST_CASE("request-network-settings round-trips against the golden")
{
    REQUIRE(encode(Packet{.client_network_version = 1001}) == golden_1001);
    REQUIRE(encode(Packet{.client_network_version = 975}) == golden_975);

    const auto back = decode<Packet>(golden_1001);
    REQUIRE(back.client_network_version == 1001);
}

TEST_CASE("request-network-settings rejects a truncated version")
{
    REQUIRE(rejects<Packet>(golden_1001.substr(0, 3)));
}
