#include <string>

#include <bedrock/protocol/script.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ScriptMessage{Identifier: "endstone:ping",
// Data: []byte("hello")}
const std::string golden = bytes({
    0x0d, 0x65, 0x6e, 0x64, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x3a, 0x70, 0x69,
    0x6e, 0x67, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f,
});

}  // namespace

TEST_CASE("packet id is 177")
{
    STATIC_REQUIRE(bp::ScriptMessagePacket::Id == 177);
    STATIC_REQUIRE(bp::has_packet_v<1001, 177>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 177>);
}

TEST_CASE("script-message round-trips against the golden")
{
    bp::ScriptMessagePacket packet;
    packet.message_id = "endstone:ping";
    packet.message_value = "hello";
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::ScriptMessagePacket>(golden);
    REQUIRE(back.message_id == "endstone:ping");
    REQUIRE(back.message_value == "hello");
}

TEST_CASE("a 200-byte value takes a two-byte varint length prefix")
{
    bp::ScriptMessagePacket packet;
    packet.message_value = std::string(200, 'x');
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 203);
    REQUIRE(wire[0] == '\0');
    REQUIRE(wire[1] == static_cast<char>(0xc8));
    REQUIRE(wire[2] == static_cast<char>(0x01));

    const auto back = decode<bp::ScriptMessagePacket>(wire);
    REQUIRE(back.message_id.empty());
    REQUIRE(back.message_value == std::string(200, 'x'));
}
