#include <string>

#include <bedrock/protocol/attribute.h>
#include <bedrock/protocol/dimension.h>
#include <bedrock/protocol/game.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.DimensionData{Definitions:
// []protocol.DimensionDefinition{{Name: "test:dim", Range: [2]int32{320, -64},
// Generator: protocol.GeneratorOverworld, DimensionType: 1000}}}
const std::string golden_v1001 = bytes({
    0x01, 0x08, 0x74, 0x65, 0x73, 0x74, 0x3a, 0x64, 0x69, 0x6d, 0x80, 0x05,
    0x7f, 0x02, 0xd0, 0x0f,
});

// generated by CloudburstMC Bedrock_v2168: DimensionDataPacket carrying
// DimensionDefinition("test:dim", 320, -64, 1, 1000,
// UUID 01020304-0506-0708-090a-0b0c0d0e0f10)
const std::string golden_v2168 = bytes({
    0x01, 0x08, 0x74, 0x65, 0x73, 0x74, 0x3a, 0x64, 0x69, 0x6d, 0x80, 0x05,
    0x7f, 0x02, 0xd0, 0x0f, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01,
    0x10, 0x0f, 0x0e, 0x0d, 0x0c, 0x0b, 0x0a, 0x09,
});

}  // namespace

TEST_CASE("packet id is 180 at both versions")
{
    STATIC_REQUIRE(bp::DimensionDataPacket_<1001>::Id == 180);
    STATIC_REQUIRE(bp::DimensionDataPacket_<2168>::Id == 180);
}

TEST_CASE("dimension-data v1001 form round-trips against the golden")
{
    using Packet = bp::DimensionDataPacket_<1001>;

    Packet packet;
    packet.dimension_definitions["test:dim"] = {
        .height_maximum = 320,
        .height_minimum = -64,
        .generator_type = bp::GeneratorType::Overworld,
        .dimension_type = bp::DimensionType{1000},
    };
    REQUIRE(encode(packet) == golden_v1001);

    const auto back = decode<Packet>(golden_v1001);
    REQUIRE(back.dimension_definitions.size() == 1);
    const auto &definition = back.dimension_definitions.at("test:dim");
    REQUIRE(definition.height_maximum == 320);
    REQUIRE(definition.height_minimum == -64);
    REQUIRE(definition.generator_type == bp::GeneratorType::Overworld);
    REQUIRE(definition.dimension_type == bp::DimensionType{1000});
}

TEST_CASE("dimension-data v2168 form round-trips against the golden")
{
    using Packet = bp::DimensionDataPacket_<2168>;

    Packet packet;
    packet.dimension_definitions["test:dim"] = {
        .height_maximum = 320,
        .height_minimum = -64,
        .generator_type = bp::GeneratorType::Overworld,
        .dimension_type = bp::DimensionType{1000},
        .pack_id = {0x0102030405060708ULL, 0x090a0b0c0d0e0f10ULL},
    };
    REQUIRE(encode(packet) == golden_v2168);

    const auto back = decode<Packet>(golden_v2168);
    const auto &definition = back.dimension_definitions.at("test:dim");
    REQUIRE(definition.height_maximum == 320);
    REQUIRE(definition.pack_id.most_significant_bits == 0x0102030405060708ULL);
    REQUIRE(definition.pack_id.least_significant_bits == 0x090a0b0c0d0e0f10ULL);
}

// The pack id is appended per definition, so a v1001 entry runs the v2168 read off
// the end of the frame.
TEST_CASE("a v1001 dimension-data body does not decode as a v2168 one")
{
    REQUIRE(rejects<bp::DimensionDataPacket_<2168>>(golden_v1001));
    REQUIRE(decode_partial<bp::DimensionDataPacket_<1001>>(golden_v2168).dimension_definitions.size() == 1);
}

// 2192 renamed the leading pair and appended the default biome; 2208 adds the cloud
// height and the flag that draws them. No golden -- gophertunnel and CloudburstMC both
// stop at 2168 -- so the 2192 body is the reference.
TEST_CASE("dimension-data v2208 appends the cloud height and its flag")
{
    bp::DimensionDataPacket_<2192> older;
    older.dimension_definitions["test:dim"] = {
        .minimum_y = -64,
        .height_range = 384,
        .generator_type = bp::GeneratorType::Overworld,
        .dimension_type = bp::DimensionType{1000},
        .pack_id = {0x0102030405060708ULL, 0x090a0b0c0d0e0f10ULL},
        .default_biome = "plains",
    };

    bp::DimensionDataPacket_<2208> newer;
    newer.dimension_definitions["test:dim"] = {
        .minimum_y = -64,
        .height_range = 384,
        .generator_type = bp::GeneratorType::Overworld,
        .dimension_type = bp::DimensionType{1000},
        .pack_id = {0x0102030405060708ULL, 0x090a0b0c0d0e0f10ULL},
        .default_biome = "plains",
        .cloud_height = 192,
        .render_clouds = true,
    };

    // 192 zigzags to 384, which is a two-byte varint, and the flag is one byte.
    REQUIRE(encode(newer).size() == encode(older).size() + 3);

    const auto decoded = decode<bp::DimensionDataPacket_<2208>>(encode(newer));
    const auto &definition = decoded.dimension_definitions.at("test:dim");
    REQUIRE(definition.default_biome == "plains");
    REQUIRE(definition.cloud_height == 192);
    REQUIRE(definition.render_clouds);
}
