#include <string>

#include <bedrock/protocol/crafting.h>

#include "fixture.hpp"

namespace {

template <class Item>
Item plank()
{
    Item out;
    out.id = 7;
    out.stack_size = 4;
    out.aux_value = 0;
    out.block_runtime_id = 9;
    out.user_data_buffer = empty_item_blob();
    return out;
}

bp::CreativeContentPacket_<1001> fill_1001()
{
    bp::CreativeContentPacket_<1001> pkt;

    bp::CreativeGroupInfoPayload_<1001> group;
    group.creative_item_category = bp::CreativeItemCategory::Nature;
    group.name = "itemGroup.name.planks";
    group.icon = plank<bp::SerializedNetworkItemInstanceDescriptor_<1001>>();
    pkt.groups.push_back(group);

    bp::CreativeItemEntryPayload_<1001> entry;
    entry.creative_item_net_id = {.raw_id = 1};
    entry.item_descriptor = plank<bp::SerializedNetworkItemInstanceDescriptor_<1001>>();
    entry.group_index = 0;
    pkt.entries.push_back(entry);
    return pkt;
}

bp::CreativeContentPacket_<2168> fill_2168()
{
    bp::CreativeContentPacket_<2168> pkt;

    bp::CreativeGroupInfoPayload_<2168> group;
    group.creative_item_category = bp::CreativeItemCategory::Nature;
    group.name = "itemGroup.name.planks";
    group.icon = plank<bp::SerializedNetworkItemInstanceDescriptor_<2168>>();
    pkt.groups.push_back(group);

    bp::CreativeItemEntryPayload_<2168> entry;
    entry.creative_item_net_id = {.raw_id = 1};
    entry.item_descriptor = plank<bp::SerializedNetworkItemInstanceDescriptor_<2168>>();
    entry.group_index = 0;
    pkt.entries.push_back(entry);
    return pkt;
}

}  // namespace

TEST_CASE("CreativeContentPacket: id")
{
    STATIC_REQUIRE(bp::CreativeContentPacket_<975>::Id == 145);
    STATIC_REQUIRE(bp::CreativeContentPacket_<1001>::Id == 145);
    STATIC_REQUIRE(bp::CreativeContentPacket_<2168>::Id == 145);
}

TEST_CASE("CreativeContentPacket: v1001 round-trip")
{
    using Packet = bp::CreativeContentPacket_<1001>;

    const Packet pkt = fill_1001();

    // generated by gophertunnel:
    // packet.CreativeContent{
    //   Groups: []protocol.CreativeGroup{{Category: protocol.CreativeCategoryNature,
    //     Name: "itemGroup.name.planks",
    //     Icon: protocol.ItemStack{ItemType: protocol.ItemType{NetworkID: 7},
    //       Count: 4, BlockRuntimeID: 9}}},
    //   Items: []protocol.CreativeItem{{CreativeItemNetworkID: 1, Item: <same>, GroupIndex: 0}}}
    const std::string golden = bytes({
    0x01, 0x02, 0x00, 0x00, 0x00, 0x15, 0x69, 0x74, 0x65, 0x6D, 0x47, 0x72,
    0x6F, 0x75, 0x70, 0x2E, 0x6E, 0x61, 0x6D, 0x65, 0x2E, 0x70, 0x6C, 0x61,
    0x6E, 0x6B, 0x73, 0x0E, 0x04, 0x00, 0x00, 0x12, 0x0A, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x0E, 0x04, 0x00,
    0x00, 0x12, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00,
});

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.groups.size() == 1);
    REQUIRE(rt.groups[0].creative_item_category == bp::CreativeItemCategory::Nature);
    REQUIRE(rt.groups[0].name == "itemGroup.name.planks");
    REQUIRE(rt.entries[0].creative_item_net_id.raw_id == 1);
    REQUIRE(rt.entries[0].item_descriptor.block_runtime_id == 9);
}

TEST_CASE("CreativeContentPacket: v2168 round-trip")
{
    using Packet = bp::CreativeContentPacket_<2168>;

    const Packet pkt = fill_2168();

    // generated by CloudburstMC Bedrock_v2168:
    // CreativeContentPacket{
    //   groups: [CreativeItemGroup(NATURE, "itemGroup.name.planks",
    //     ItemData(SimpleItemDefinition("minecraft:planks", 7), damage 0, count 4,
    //       SimpleBlockDefinition("minecraft:planks", 9)))],
    //   contents: [CreativeItemData(<same item>, netId 1, groupId 0)]}
    const std::string golden = bytes({
    0x01, 0x02, 0x15, 0x69, 0x74, 0x65, 0x6D, 0x47, 0x72, 0x6F, 0x75, 0x70,
    0x2E, 0x6E, 0x61, 0x6D, 0x65, 0x2E, 0x70, 0x6C, 0x61, 0x6E, 0x6B, 0x73,
    0x0E, 0x04, 0x00, 0x00, 0x12, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x0E, 0x04, 0x00, 0x00, 0x12, 0x0A,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.groups.size() == 1);
    REQUIRE(rt.groups[0].creative_item_category == bp::CreativeItemCategory::Nature);
    REQUIRE(rt.groups[0].name == "itemGroup.name.planks");
    REQUIRE(rt.entries[0].creative_item_net_id.raw_id == 1);
    REQUIRE(rt.entries[0].item_descriptor.block_runtime_id == 9);
}

// The only wire break is the group category: a fixed int32 at 1001, its uint8_t
// underlying at 2168. Everything from the group name on is byte-identical.
TEST_CASE("CreativeContentPacket: only the group category changed width")
{
    const auto old_bytes = encode(fill_1001());
    const auto new_bytes = encode(fill_2168());

    REQUIRE(old_bytes.size() == new_bytes.size() + 3);
    REQUIRE(old_bytes.substr(5) == new_bytes.substr(2));
}
