#include <string>

#include <bedrock/protocol/ui.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ServerBoundLoadingScreen{Type: 1,
// LoadingScreenID: protocol.Option[uint32](9)}
const std::string golden = bytes({
    0x02, 0x01, 0x09, 0x00, 0x00, 0x00,
});

// generated by gophertunnel: &packet.ServerBoundLoadingScreen{Type: 2}
const std::string golden_absent = bytes({
    0x04, 0x00,
});

}  // namespace

TEST_CASE("packet id is 312")
{
    STATIC_REQUIRE(bp::ServerboundLoadingScreenPacket_<2168>::Id == 312);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 312>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 312>);
}

TEST_CASE("serverbound loading screen round-trips against the golden")
{
    bp::ServerboundLoadingScreenPacket_<2168> packet;
    packet.loading_screen_packet_type = bp::ServerboundLoadingScreenPacketType::START_LOADING_SCREEN;
    packet.loading_screen_id = 9;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::ServerboundLoadingScreenPacket_<2168>>(golden);
    REQUIRE(back.loading_screen_packet_type == bp::ServerboundLoadingScreenPacketType::START_LOADING_SCREEN);
    REQUIRE(back.loading_screen_id == 9);
}

TEST_CASE("an absent screen id is one zero byte, and the type still zigzags")
{
    bp::ServerboundLoadingScreenPacket_<2168> packet;
    packet.loading_screen_packet_type = bp::ServerboundLoadingScreenPacketType::END_LOADING_SCREEN;
    REQUIRE(encode(packet) == golden_absent);
    REQUIRE_FALSE(decode<bp::ServerboundLoadingScreenPacket_<2168>>(golden_absent).loading_screen_id.has_value());
}
