#include <string>
#include <type_traits>

#include <bedrock/protocol/network.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel, and byte for byte again at de090ae (the last pre-1.26.30
// commit, CurrentProtocol 975):
// packet.SubClientLogin{ConnectionRequest: []byte("sub-client-jwt")}
const std::string golden = bytes({
    0x0e, 0x73, 0x75, 0x62, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2d,
    0x6a, 0x77, 0x74,
});

}  // namespace

TEST_CASE("packet id is 94 at every version")
{
    STATIC_REQUIRE(bp::SubClientLoginPacket::Id == 94);
    STATIC_REQUIRE(std::is_same_v<bp::packet_of_t<975, 94>, bp::SubClientLoginPacket>);
    STATIC_REQUIRE(std::is_same_v<bp::packet_of_t<1001, 94>, bp::SubClientLoginPacket>);
    STATIC_REQUIRE(std::is_same_v<bp::packet_of_t<2168, 94>, bp::SubClientLoginPacket>);
}

// 2168 cerealised the packet, and the one member came out the other side unchanged: the
// connection request is a varuint32-prefixed blob either era.
TEST_CASE("sub-client-login round-trips against the golden")
{
    bp::SubClientLoginPacket packet;
    packet.connection_request = "sub-client-jwt";
    REQUIRE(encode(packet) == golden);

    REQUIRE(decode<bp::SubClientLoginPacket>(golden).connection_request == "sub-client-jwt");
}

TEST_CASE("sub-client-login carries an empty request as a lone zero")
{
    REQUIRE(encode(bp::SubClientLoginPacket{}) == bytes({0x00}));
}
