#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ContainerRegistryCleanupPacket: id + round-trip with empty removed list")
{
    STATIC_REQUIRE(bp::ContainerRegistryCleanupPacket::Id == 317);

    bp::ContainerRegistryCleanupPacket pkt;
    pkt.removed_containers = {};

    // generated by gophertunnel:
    // packet.ContainerRegistryCleanup{RemovedContainers: []}
    const std::vector<std::uint8_t> golden{
        0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ContainerRegistryCleanupPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->removed_containers.empty());
}
