#include <string>

#include <bedrock/protocol/sound.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.PlaySound{SoundName: "note.harp",
// Position: mgl32.Vec3{1, 2, 3}, Volume: 0.5, Pitch: 1.5,
// Handle: protocol.Option(uint64(42))}. io.SoundPos scales the vector by 8 and
// writes it as a BlockPos, so {1,2,3} reaches the wire as {8,16,24}.
const std::string golden_v1001 = bytes({
    0x09, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x68, 0x61, 0x72, 0x70, 0x10, 0x20,
    0x30, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x00, 0xc0, 0x3f, 0x01, 0x2a, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

// generated by gophertunnel: the same packet with Handle left zero-valued.
const std::string golden_v1001_no_handle = bytes({
    0x09, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x68, 0x61, 0x72, 0x70, 0x10, 0x20,
    0x30, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x00, 0xc0, 0x3f, 0x00,
});

// TODO: confirm against BDS. CloudburstMC PlaySoundSerializer_v2168 writes the
// loop count with VarInts.writeUnsignedInt, where the r26_u4 dump types the field
// varint32. For 3 that is 0x03 against the schema's zigzagged 0x06; every other
// byte agrees.
//
// The handle optional costs one framing byte at both versions: the 0x01 sits
// directly before the eight handle bytes here and in the v1001 golden above, with
// no always-true member-present marker ahead of it.
//
// generated by CloudburstMC Bedrock_v2168: PlaySoundPacket{sound=note.harp,
// position=Vector3f.from(1, 2, 3), volume=0.5, pitch=1.5, loopCount=3,
// serverSoundHandle=42}
const std::string golden_v2168 = bytes({
    0x09, 0x6e, 0x6f, 0x74, 0x65, 0x2e, 0x68, 0x61, 0x72, 0x70, 0x10, 0x20,
    0x30, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x00, 0xc0, 0x3f,
    0x06,  // TODO: patched, confirm against BDS
    0x01, 0x2a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

template <class Packet>
Packet make()
{
    Packet packet;
    packet.name = "note.harp";
    packet.pos = {.x = 8, .y = 16, .z = 24};
    packet.volume = 0.5F;
    packet.pitch = 1.5F;
    packet.server_sound_handle = bp::ServerSoundHandle{.value = 42};
    return packet;
}

}  // namespace

TEST_CASE("packet id is 86 at both versions")
{
    STATIC_REQUIRE(bp::PlaySoundPacket_<1001>::Id == 86);
    STATIC_REQUIRE(bp::PlaySoundPacket_<2168>::Id == 86);
}

TEST_CASE("play-sound v1001 form round-trips against the golden")
{
    using Packet = bp::PlaySoundPacket_<1001>;

    REQUIRE(encode(make<Packet>()) == golden_v1001);

    const auto back = decode<Packet>(golden_v1001);
    REQUIRE(back.name == "note.harp");
    REQUIRE(back.pos.x == 8);
    REQUIRE(back.pos.y == 16);
    REQUIRE(back.pos.z == 24);
    REQUIRE(back.volume == 0.5F);
    REQUIRE(back.pitch == 1.5F);
    REQUIRE(back.server_sound_handle.has_value());
    REQUIRE(back.server_sound_handle->value == 42);
}

TEST_CASE("play-sound v1001 encodes an absent handle as a bare flag")
{
    using Packet = bp::PlaySoundPacket_<1001>;

    auto packet = make<Packet>();
    packet.server_sound_handle.reset();
    REQUIRE(encode(packet) == golden_v1001_no_handle);
    REQUIRE_FALSE(decode<Packet>(golden_v1001_no_handle).server_sound_handle.has_value());
}

TEST_CASE("play-sound v2168 form round-trips against the golden")
{
    using Packet = bp::PlaySoundPacket_<2168>;

    auto packet = make<Packet>();
    packet.loop_count = 3;
    REQUIRE(encode(packet) == golden_v2168);

    const auto back = decode<Packet>(golden_v2168);
    REQUIRE(back.name == "note.harp");
    REQUIRE(back.loop_count == 3);
    REQUIRE(back.server_sound_handle.has_value());
    REQUIRE(back.server_sound_handle->value == 42);
}

// The loop count sits ahead of the handle, so it shifts the optional and its
// payload rather than appending to the frame.
TEST_CASE("a v1001 play-sound body does not decode as a v2168 one")
{
    REQUIRE(golden_v1001.size() + 1 == golden_v2168.size());
    REQUIRE(rejects<bp::PlaySoundPacket_<2168>>(golden_v1001));
    REQUIRE(decode_partial<bp::PlaySoundPacket_<1001>>(golden_v2168).server_sound_handle.has_value());
}
