#include <string>

#include <bedrock/protocol/network.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.NetworkSettings{CompressionThreshold: 1024,
// CompressionAlgorithm: packet.CompressionAlgorithmSnappy, ClientThrottle: true,
// ClientThrottleThreshold: 200, ClientThrottleScalar: 0.5}
const std::string golden = bytes({
    0x00, 0x04, 0x01, 0x00, 0x01, 0xc8, 0x00, 0x00, 0x00, 0x3f,
});

// generated by gophertunnel: &packet.NetworkSettings{CompressionAlgorithm:
// packet.CompressionAlgorithmNone}
const std::string golden_none = bytes({
    0x00, 0x00, 0xff, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 143")
{
    STATIC_REQUIRE(bp::NetworkSettingsPacket::Id == 143);
    STATIC_REQUIRE(bp::has_packet_v<1001, 143>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 143>);
}

TEST_CASE("network-settings round-trips against the golden")
{
    bp::NetworkSettingsPacket packet;
    packet.compression_threshold = 1024;
    packet.compression_algorithm = bp::PacketCompressionAlgorithm::Snappy;
    packet.client_throttle_enabled = true;
    packet.client_throttle_threshold = 200;
    packet.client_throttle_scalar = 0.5F;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::NetworkSettingsPacket>(golden);
    REQUIRE(back.compression_threshold == 1024);
    REQUIRE(back.compression_algorithm == bp::PacketCompressionAlgorithm::Snappy);
    REQUIRE(back.client_throttle_enabled);
    REQUIRE(back.client_throttle_threshold == 200);
    REQUIRE(back.client_throttle_scalar == 0.5F);
}

TEST_CASE("the network-settings compression algorithm is two fixed bytes, not a varint")
{
    bp::NetworkSettingsPacket packet;
    packet.compression_algorithm = bp::PacketCompressionAlgorithm::None;
    REQUIRE(encode(packet) == golden_none);
    REQUIRE(encode(packet).size() == 10);

    const auto back = decode<bp::NetworkSettingsPacket>(golden_none);
    REQUIRE(back.compression_algorithm == bp::PacketCompressionAlgorithm::None);
    REQUIRE(back.compression_threshold == 0);
}
