#include <string>

#include <bedrock/protocol/pack.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ResourcePackDataInfo{UUID:
// "0a0b0c0d-0e0f-1011-1213-141516171819", DataChunkSize: 1048576, ChunkCount: 16,
// Size: 15925248, Hash: []byte{0xde, 0xad, 0xbe, 0xef}, Premium: true,
// PackType: packet.ResourcePackTypeResources}
const std::string golden = bytes({
    0x24, 0x30, 0x61, 0x30, 0x62, 0x30, 0x63, 0x30, 0x64, 0x2d, 0x30, 0x65,
    0x30, 0x66, 0x2d, 0x31, 0x30, 0x31, 0x31, 0x2d, 0x31, 0x32, 0x31, 0x33,
    0x2d, 0x31, 0x34, 0x31, 0x35, 0x31, 0x36, 0x31, 0x37, 0x31, 0x38, 0x31,
    0x39, 0x00, 0x00, 0x10, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0xf3,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0xde, 0xad, 0xbe, 0xef, 0x01, 0x06,
});

// generated by gophertunnel: &packet.ResourcePackDataInfo{UUID: "", DataChunkSize: 128,
// ChunkCount: 300, Size: 0x0102030405060708, Hash: nil, Premium: false,
// PackType: packet.ResourcePackTypeWorldTemplate}
const std::string golden_fixed_widths = bytes({
    0x00, 0x80, 0x00, 0x00, 0x00, 0x2c, 0x01, 0x00, 0x00, 0x08, 0x07, 0x06,
    0x05, 0x04, 0x03, 0x02, 0x01, 0x00, 0x00, 0x08,
});

}  // namespace

TEST_CASE("packet id is 82")
{
    STATIC_REQUIRE(bp::ResourcePackDataInfoPacket::Id == 82);
    STATIC_REQUIRE(bp::has_packet_v<1001, 82>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 82>);
}

TEST_CASE("resource-pack-data-info round-trips against the golden")
{
    bp::ResourcePackDataInfoPacket packet;
    packet.resource_name = "0a0b0c0d-0e0f-1011-1213-141516171819";
    packet.chunk_size = 1048576;
    packet.nb_chunks = 16;
    packet.file_size = 15925248;
    packet.file_hash = bytes({0xde, 0xad, 0xbe, 0xef});
    packet.is_premium = true;
    packet.pack_type = bp::PackType::Resources;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::ResourcePackDataInfoPacket>(golden);
    REQUIRE(back.resource_name == "0a0b0c0d-0e0f-1011-1213-141516171819");
    REQUIRE(back.chunk_size == 1048576);
    REQUIRE(back.nb_chunks == 16);
    REQUIRE(back.file_size == 15925248);
    REQUIRE(back.file_hash == bytes({0xde, 0xad, 0xbe, 0xef}));
    REQUIRE(back.is_premium);
    REQUIRE(back.pack_type == bp::PackType::Resources);
}

TEST_CASE("the sizes are fixed-width and the hash carries its own length")
{
    bp::ResourcePackDataInfoPacket packet;
    packet.chunk_size = 128;
    packet.nb_chunks = 300;
    packet.file_size = 0x0102030405060708ULL;
    packet.is_premium = false;
    packet.pack_type = bp::PackType::WorldTemplate;
    REQUIRE(encode(packet) == golden_fixed_widths);
    REQUIRE(encode(packet).size() == 20);

    const auto back = decode<bp::ResourcePackDataInfoPacket>(golden_fixed_widths);
    REQUIRE(back.resource_name.empty());
    REQUIRE(back.chunk_size == 128);
    REQUIRE(back.nb_chunks == 300);
    REQUIRE(back.file_size == 0x0102030405060708ULL);
    REQUIRE(back.file_hash.empty());
    REQUIRE_FALSE(back.is_premium);
    REQUIRE(back.pack_type == bp::PackType::WorldTemplate);
}
