#include <string>

#include <bedrock/protocol/network.h>

#include "fixture.hpp"

namespace {

template <int V>
bp::PacketViolationWarningPacket_<V> terminating()
{
    return {
        .violation_type = bp::PacketViolationType::PacketMalformed,
        .violation_severity = bp::PacketViolationSeverity::TerminatingConnection,
        .violating_packet_id = bp::MinecraftPacketIds_<V>::InventoryTransaction,
        .violation_context = "malformed packet",
    };
}

// generated by gophertunnel (v1.57.1):
// packet.PacketViolationWarning{Type: ViolationTypeMalformed, Severity:
// ViolationSeverityTerminatingConnection, PacketID: 30, ViolationContext: "malformed packet"}
const std::string golden = bytes({
    0x00, 0x04, 0x3c, 0x10, 0x6d, 0x61, 0x6c, 0x66, 0x6f, 0x72, 0x6d, 0x65,
    0x64, 0x20, 0x70, 0x61, 0x63, 0x6b, 0x65, 0x74,
});

// generated by gophertunnel (v1.57.1):
// packet.PacketViolationWarning{Type: -1, Severity: -1, PacketID: 156, ViolationContext: ""}
const std::string golden_unknown = bytes({
    0x01, 0x01, 0xb8, 0x02, 0x00,
});

}  // namespace

TEST_CASE("packet id is 156 at both versions")
{
    STATIC_REQUIRE(bp::PacketViolationWarningPacket_<975>::Id == 156);
    STATIC_REQUIRE(bp::PacketViolationWarningPacket_<1001>::Id == 156);
}

TEST_CASE("packet-violation-warning round-trips against the golden")
{
    using Packet = bp::PacketViolationWarningPacket_<1001>;

    REQUIRE(encode(terminating<1001>()) == golden);

    const auto back = decode<Packet>(golden);
    REQUIRE(back.violation_type == bp::PacketViolationType::PacketMalformed);
    REQUIRE(back.violation_severity == bp::PacketViolationSeverity::TerminatingConnection);
    REQUIRE(back.violating_packet_id == bp::MinecraftPacketIds_<1001>::InventoryTransaction);
    REQUIRE(back.violation_context == "malformed packet");
}

// MinecraftPacketIds gained three members at 1001, which splits the packet's C++
// type; the bytes are the same on both sides of the split.
TEST_CASE("the wire form is unchanged across the version split")
{
    REQUIRE(encode(terminating<975>()) == golden);
    REQUIRE(encode(terminating<1001>()) == golden);

    STATIC_REQUIRE(static_cast<int>(bp::MinecraftPacketIds_<975>::EndId) == 348);
    STATIC_REQUIRE(static_cast<int>(bp::MinecraftPacketIds_<1001>::EndId) == 351);
}

// Both enums carry an Unknown = -1 sentinel, which only survives the round trip
// because the wire is zigzag: read unsigned it would come back as 4294967295.
TEST_CASE("the unknown sentinel round-trips")
{
    using Packet = bp::PacketViolationWarningPacket_<1001>;

    Packet packet;
    packet.violation_type = bp::PacketViolationType::Unknown;
    packet.violation_severity = bp::PacketViolationSeverity::Unknown;
    packet.violating_packet_id = bp::MinecraftPacketIds_<1001>::PacketViolationWarning;
    REQUIRE(encode(packet) == golden_unknown);

    const auto back = decode<Packet>(golden_unknown);
    REQUIRE(back.violation_type == bp::PacketViolationType::Unknown);
    REQUIRE(back.violation_severity == bp::PacketViolationSeverity::Unknown);
    REQUIRE(back.violating_packet_id == bp::MinecraftPacketIds_<1001>::PacketViolationWarning);
    REQUIRE(back.violation_context.empty());
}

TEST_CASE("packet-violation-warning rejects a truncated context")
{
    using Packet = bp::PacketViolationWarningPacket_<1001>;

    REQUIRE(rejects<Packet>(golden.substr(0, golden.size() - 1)));
}
