#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("CameraAimAssistPacket: id + round-trip with the v776+ preset prefix")
{
    STATIC_REQUIRE(bp::CameraAimAssistPacket::Id == 316);

    bp::CameraAimAssistPacket pkt;
    pkt.preset_id = "x";
    pkt.view_angle = bp::Vec2{1, 2};
    pkt.distance = 3.0f;
    pkt.target_mode = bp::CameraAimAssistPacket::TargetMode::Angle;
    pkt.action = bp::CameraAimAssistPacket::Action::Set;
    pkt.show_debug_render = false;

    // generated by gophertunnel:
    // packet.CameraAimAssist{Preset: "x", Angle: mgl32.Vec2{1, 2}, Distance: 3.0,
    //                        TargetMode: 0, Action: 0, ShowDebugRender: false}
    const std::vector<std::uint8_t> golden{
        0x01, 0x78, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00,
        0x40, 0x40, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::CameraAimAssistPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->preset_id == "x");
    REQUIRE(rt->action == bp::CameraAimAssistPacket::Action::Set);
}
