#include <cstdint>
#include <string>

#include <protocol/biome.h>

#include "fixture.hpp"

namespace {

// Golden derived from gophertunnel's BiomeDefinitionList.Marshal (654cd5f):
// protocol.Slice writes a varuint32 count then each BiomeDefinition, whose Marshal
// leads with Int16(NameIndex) -- BDS's map key -- before the definition body, so the
// slice and BDS's std::map<unsigned short, BiomeDefinitionData> are the same bytes.
// Then Int16(BiomeID), five Float32 (fixed LE), Int32(MapWaterColour), Bool(Rain),
// OptionalFunc(Tags) and OptionalMarshaler(ChunkGeneration) -- each a bool flag then
// payload. FuncSlice(StringList, io.String) is a varuint32 count of varuint32-length
// strings, which is exactly BiomeStringList's own body.
const std::string golden = bytes({
    0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x00, 0x80,
    0x3e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x80,
    0x3f, 0x77, 0x66, 0x55, 0x44, 0x01, 0x01, 0x02, 0x02, 0x00, 0x03, 0x00,
    0x00, 0x02, 0x06, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x73, 0x03, 0x74, 0x61,
    0x67,
});

// BiomeNoiseGradientSurfaceData is the one part of the packet 981 reshaped, and it
// sits three optionals deep: chunk_gen_data, then surface_builder_data, then
// noise_gradient_surface. The two goldens below are the same definition either side
// of that reshape, so the gradient is exercised where it actually rides.

// generated by gophertunnel at 6353c49^ (de090ae, the last pre-1.26.30 commit):
// packet.BiomeDefinitionList{BiomeDefinitions: []protocol.BiomeDefinition{{BiomeID: 1,
//   Temperature: 0.5, Downfall: 0.25, Depth: 0.125, Scale: 1, MapWaterColour: 0x44556677,
//   Rain: true, ChunkGeneration: Option(BiomeChunkGeneration{SurfaceBuilder:
//   Option(BiomeSurfaceBuilder{NoiseGradientSurface: Option(BiomeNoiseGradientSurface{
//   NonReplaceableBlocks: []uint32{7}, GradientBlocks: []uint32{9}, NoiseSeedString: "seed",
//   FirstOctave: -3, Amplitudes: []float32{1, 0.5}})})}}}}, StringList: []string{"plains", "tag"}}
const std::string golden_gradient_v975 = bytes({
    0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x00, 0x80,
    0x3e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x80,
    0x3f, 0x77, 0x66, 0x55, 0x44, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x01, 0x07, 0x00, 0x00, 0x00, 0x01, 0x09, 0x00, 0x00, 0x00,
    0x04, 0x73, 0x65, 0x65, 0x64, 0xfd, 0xff, 0xff, 0xff, 0x02, 0x00, 0x00,
    0x80, 0x3f, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x02, 0x06, 0x70, 0x6c, 0x61,
    0x69, 0x6e, 0x73, 0x03, 0x74, 0x61, 0x67,
});

// generated by gophertunnel (654cd5f): the same definition, with the 981 gradient.
const std::string golden_gradient_v1001 = bytes({
    0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x00, 0x80,
    0x3e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x3e, 0x00, 0x00, 0x80,
    0x3f, 0x77, 0x66, 0x55, 0x44, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x01, 0x07, 0x00, 0x00, 0x00, 0x01, 0x01, 0x6e, 0x00, 0x00,
    0x80, 0x3e, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3f, 0x09, 0x00,
    0x00, 0x00, 0x04, 0x73, 0x65, 0x65, 0x64, 0xfd, 0xff, 0xff, 0xff, 0x02,
    0x00, 0x00, 0x80, 0x3f, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x02, 0x06, 0x70,
    0x6c, 0x61, 0x69, 0x6e, 0x73, 0x03, 0x74, 0x61, 0x67,
});

}  // namespace

TEST_CASE("biome definition list round-trips against the golden")
{
    using Packet = bp::BiomeDefinitionListPacket;

    Packet packet;
    packet.biome_data[static_cast<bp::BiomeStringIndex>(0)] = {
        .id = 1,
        .temperature = 0.5f,
        .downfall = 0.25f,
        .foliage_snow = 0.0f,
        .depth = 0.125f,
        .scale = 1.0f,
        .map_water_color_argb = 0x44556677,
        .rain = true,
        .tags = bp::BiomeTagsData{.tags = {2, 3}},
    };
    packet.string_list.strings = {"plains", "tag"};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<Packet>(golden);
    REQUIRE(back.biome_data.size() == 1);

    const auto &definition = back.biome_data.at(static_cast<bp::BiomeStringIndex>(0));
    REQUIRE(definition.id == 1);
    REQUIRE(definition.temperature == 0.5f);
    REQUIRE(definition.map_water_color_argb == 0x44556677);
    REQUIRE(definition.rain);
    REQUIRE(definition.tags.has_value());
    REQUIRE(definition.tags->tags == std::vector<std::uint16_t>{2, 3});
    REQUIRE_FALSE(definition.chunk_gen_data.has_value());
    REQUIRE(back.string_list.strings == std::vector<std::string>{"plains", "tag"});
}

// Each key immediately precedes its own value, and std::map orders the entries by
// key regardless of insertion order.
TEST_CASE("the biome definition map writes ascending key/value pairs")
{
    bp::BiomeDefinitionListPacket packet;
    packet.biome_data[static_cast<bp::BiomeStringIndex>(5)] = {.id = 50};
    packet.biome_data[static_cast<bp::BiomeStringIndex>(2)] = {.id = 20};

    // key + id + 5 floats + colour + rain + both optionals absent.
    constexpr int entry = 2 + 2 + (5 * 4) + 4 + 1 + 1 + 1;

    const std::string wire = encode(packet);
    REQUIRE(wire.size() == 1 + (2 * entry) + 1);  // count, both entries, empty pool
    REQUIRE(wire[0] == 0x02);                     // count
    REQUIRE(wire[1] == 0x02);                     // first key = 2, not the 5 inserted first
    REQUIRE(wire[3] == 20);                       //   its own id follows immediately
    REQUIRE(wire[1 + entry] == 0x05);
    REQUIRE(wire[3 + entry] == 50);
}

TEST_CASE("biome definition list v975 carries the pre-981 noise gradient")
{
    using Packet = bp::BiomeDefinitionListPacket_<975>;

    bp::base::BiomeNoiseGradientSurfaceData gradient;
    gradient.non_replaceable_blocks = {7};
    gradient.gradient_blocks = {9};
    gradient.noise_seed_string = "seed";
    gradient.first_octave = -3;
    gradient.amplitudes = {1.0f, 0.5f};

    bp::base::BiomeSurfaceBuilderData surface;
    surface.noise_gradient_surface = gradient;
    bp::base::BiomeDefinitionChunkGenData chunk_gen;
    chunk_gen.surface_builder_data = surface;

    Packet packet;
    auto &definition = packet.biome_data[static_cast<bp::BiomeStringIndex>(0)];
    definition.id = 1;
    definition.temperature = 0.5f;
    definition.downfall = 0.25f;
    definition.depth = 0.125f;
    definition.scale = 1.0f;
    definition.map_water_color_argb = 0x44556677;
    definition.rain = true;
    definition.chunk_gen_data = chunk_gen;
    packet.string_list.strings = {"plains", "tag"};
    REQUIRE(encode(packet) == golden_gradient_v975);

    const auto back = decode<Packet>(golden_gradient_v975);
    const auto &read_back = back.biome_data.at(static_cast<bp::BiomeStringIndex>(0))
                                .chunk_gen_data->surface_builder_data->noise_gradient_surface;
    REQUIRE(read_back.has_value());
    REQUIRE(read_back->gradient_blocks == std::vector<std::uint32_t>{9});
    REQUIRE(read_back->noise_seed_string == "seed");
    REQUIRE(read_back->first_octave == -3);
    REQUIRE(read_back->amplitudes.size() == 2);
}

TEST_CASE("biome definition list v1001 carries the reshaped noise gradient")
{
    using Packet = bp::BiomeDefinitionListPacket_<1001>;

    bp::v1001::BiomeNoiseGradientSurfaceData gradient;
    gradient.non_replaceable_blocks = {7};
    gradient.gradient_block_ranges.push_back({.noise = "n",
                                              .threshold = 0.25f,
                                              .range = {.min = 0.0f, .max = 1.0f},
                                              .block_runtime_id = 9});
    gradient.noise_descriptor = {.name = "seed", .first_octave = -3, .amplitudes = {1.0f, 0.5f}};

    bp::v1001::BiomeSurfaceBuilderData surface;
    surface.noise_gradient_surface = gradient;
    bp::v1001::BiomeDefinitionChunkGenData chunk_gen;
    chunk_gen.surface_builder_data = surface;

    Packet packet;
    auto &definition = packet.biome_data[static_cast<bp::BiomeStringIndex>(0)];
    definition.id = 1;
    definition.temperature = 0.5f;
    definition.downfall = 0.25f;
    definition.depth = 0.125f;
    definition.scale = 1.0f;
    definition.map_water_color_argb = 0x44556677;
    definition.rain = true;
    definition.chunk_gen_data = chunk_gen;
    packet.string_list.strings = {"plains", "tag"};
    REQUIRE(encode(packet) == golden_gradient_v1001);

    const auto back = decode<Packet>(golden_gradient_v1001);
    const auto &read_back = back.biome_data.at(static_cast<bp::BiomeStringIndex>(0))
                                .chunk_gen_data->surface_builder_data->noise_gradient_surface;
    REQUIRE(read_back.has_value());
    REQUIRE(read_back->gradient_block_ranges.size() == 1);
    REQUIRE(read_back->gradient_block_ranges[0].noise == "n");
    REQUIRE(read_back->gradient_block_ranges[0].range.max == 1.0f);
    REQUIRE(read_back->gradient_block_ranges[0].block_runtime_id == 9);
    REQUIRE(read_back->noise_descriptor.name == "seed");
    REQUIRE(read_back->noise_descriptor.amplitudes.size() == 2);
}

// 981 rewrote the type around its one surviving field: the two packets are identical
// down through non_replaceable_blocks and the block list's count, and diverge on that
// list's first element -- a uint32 block id at v975, a specifier's noise name at v1001.
TEST_CASE("the 981 reshape changes the wire past the gradient's first field")
{
    constexpr std::size_t shared = 56;
    REQUIRE(golden_gradient_v975.substr(0, shared) == golden_gradient_v1001.substr(0, shared));
    REQUIRE(golden_gradient_v975[shared] != golden_gradient_v1001[shared]);
}
