#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("AddPaintingPacket: id + round-trip (v975 wire shape with float Vec3 position)")
{
    STATIC_REQUIRE(bp::AddPaintingPacket::Id == 22);

    bp::AddPaintingPacket pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(-3);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(4);
    pkt.pos = bp::Vec3{1.5f, 64.0f, -2.25f};
    pkt.dir = 2;
    pkt.motif = "Kebab";

    // generated by gophertunnel:
    // packet.AddPainting{EntityUniqueID: -3, EntityRuntimeID: 4,
    //   Position: mgl32.Vec3{1.5, 64, -2.25}, Direction: 2, Title: "Kebab"}
    const std::vector<std::uint8_t> golden{
        0x05, 0x04, 0x00, 0x00, 0xC0, 0x3F, 0x00, 0x00, 0x80, 0x42, 0x00, 0x00,
        0x10, 0xC0, 0x04, 0x05, 0x4B, 0x65, 0x62, 0x61, 0x62,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::AddPaintingPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->entity_id == static_cast<bp::ActorUniqueID>(-3));
    REQUIRE(rt->runtime_id == static_cast<bp::ActorRuntimeID>(4));
    REQUIRE(rt->motif == "Kebab");
    REQUIRE(rt->dir == 2);
}
