#include <string>
#include <variant>

#include <bedrock/protocol/actor.h>
#include <bedrock/protocol/command.h>
#include <bedrock/protocol/common.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.CommandBlockUpdate{Block: true,
// Position: protocol.BlockPos{1, -2, 300}, Mode: packet.CommandBlockChain,
// NeedsRedstone: true, Conditional: false, Command: "say hi", LastOutput: "done",
// Name: "greeter", FilteredName: "greeter", ShouldTrackOutput: true, TickDelay: 300,
// ExecuteOnFirstTick: true}
const std::string golden_block = bytes({
    0x01, 0x02, 0x03, 0xd8, 0x04, 0x02, 0x01, 0x00, 0x06, 0x73, 0x61, 0x79,
    0x20, 0x68, 0x69, 0x04, 0x64, 0x6f, 0x6e, 0x65, 0x07, 0x67, 0x72, 0x65,
    0x65, 0x74, 0x65, 0x72, 0x07, 0x67, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72,
    0x01, 0x2c, 0x01, 0x00, 0x00, 0x01,
});

// generated by gophertunnel: &packet.CommandBlockUpdate{Block: false,
// MinecartEntityRuntimeID: 300}
const std::string golden_entity = bytes({
    0x00, 0xac, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00,
});

}  // namespace

TEST_CASE("CommandBlockUpdatePacket: packet id is 78")
{
    STATIC_REQUIRE(bp::CommandBlockUpdatePacket_<2168>::Id == 78);
    STATIC_REQUIRE(bp::has_packet_v<1001, 78>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 78>);
}

TEST_CASE("CommandBlockUpdatePacket: a block target round-trips against the golden")
{
    bp::CommandBlockUpdatePacket_<2168>::BlockCommandData block;
    block.block_pos = {.x = 1, .y = -2, .z = 300};
    block.mode = bp::CommandBlockMode::CHAIN;
    block.redstone_mode = true;
    block.is_conditional = false;

    bp::CommandBlockUpdatePacket_<2168> packet;
    packet.target = block;
    packet.command = "say hi";
    packet.last_output = "done";
    packet.name = "greeter";
    packet.filtered_name = "greeter";
    packet.track_output = true;
    packet.tick_delay = 300;
    packet.execute_on_first_tick = true;
    REQUIRE(encode(packet) == golden_block);

    const auto back = decode<bp::CommandBlockUpdatePacket_<2168>>(golden_block);
    REQUIRE(back.target.index() == 1);
    const auto &back_block = std::get<bp::CommandBlockUpdatePacket_<2168>::BlockCommandData>(back.target);
    REQUIRE(back_block.block_pos.x == 1);
    REQUIRE(back_block.block_pos.y == -2);
    REQUIRE(back_block.block_pos.z == 300);
    REQUIRE(back_block.mode == bp::CommandBlockMode::CHAIN);
    REQUIRE(back_block.redstone_mode);
    REQUIRE_FALSE(back_block.is_conditional);
    REQUIRE(back.command == "say hi");
    REQUIRE(back.last_output == "done");
    REQUIRE(back.name == "greeter");
    REQUIRE(back.filtered_name == "greeter");
    REQUIRE(back.track_output);
    REQUIRE(back.tick_delay == 300);
    REQUIRE(back.execute_on_first_tick);
}

TEST_CASE("CommandBlockUpdatePacket: an entity target takes case index 0 and no block data")
{
    bp::CommandBlockUpdatePacket_<2168>::EntityCommandTarget entity;
    entity.entity_id = bp::ActorRuntimeID{300};

    bp::CommandBlockUpdatePacket_<2168> packet;
    packet.target = entity;
    packet.tick_delay = 0;
    REQUIRE(encode(packet) == golden_entity);
    REQUIRE(encode(packet).size() == 13);

    const auto back = decode<bp::CommandBlockUpdatePacket_<2168>>(golden_entity);
    REQUIRE(back.target.index() == 0);
    REQUIRE(std::get<bp::CommandBlockUpdatePacket_<2168>::EntityCommandTarget>(back.target).entity_id ==
            bp::ActorRuntimeID{300});
    REQUIRE(back.command.empty());
    REQUIRE(back.last_output.empty());
    REQUIRE(back.name.empty());
    REQUIRE(back.filtered_name.empty());
    REQUIRE_FALSE(back.track_output);
    REQUIRE(back.tick_delay == 0);
    REQUIRE_FALSE(back.execute_on_first_tick);
}

TEST_CASE("CommandBlockUpdatePacket: the tick delay is four fixed bytes, not a varint")
{
    bp::CommandBlockUpdatePacket_<2168>::EntityCommandTarget entity;
    entity.entity_id = bp::ActorRuntimeID{0};

    bp::CommandBlockUpdatePacket_<2168> packet;
    packet.target = entity;
    packet.tick_delay = -1;
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 12);
    REQUIRE(wire.substr(7, 4) == bytes({0xff, 0xff, 0xff, 0xff}));
    REQUIRE(decode<bp::CommandBlockUpdatePacket_<2168>>(wire).tick_delay == -1);
}
