#include <string>
#include <variant>

#include <bedrock/protocol/item.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.BookEdit{InventorySlot: 3,
// ActionType: packet.BookActionReplacePage, PageNumber: 200, Text: "hello",
// PhotoName: "photo.png"}
const std::string golden_replace_page = bytes({
    0x06, 0x00, 0x90, 0x03, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x09, 0x70,
    0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6e, 0x67,
});

// generated by gophertunnel: &packet.BookEdit{InventorySlot: 3,
// ActionType: packet.BookActionAddPage, PageNumber: 200, Text: "hello",
// PhotoName: "photo.png"}
const std::string golden_add_page = bytes({
    0x06, 0x01, 0x90, 0x03, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x09, 0x70,
    0x68, 0x6f, 0x74, 0x6f, 0x2e, 0x70, 0x6e, 0x67,
});

// generated by gophertunnel: &packet.BookEdit{InventorySlot: 3,
// ActionType: packet.BookActionDeletePage, PageNumber: 1}
const std::string golden_delete_page = bytes({
    0x06, 0x02, 0x02,
});

// generated by gophertunnel: &packet.BookEdit{InventorySlot: 3,
// ActionType: packet.BookActionSwapPages, PageNumber: 1, SecondaryPageNumber: 2}
const std::string golden_swap_pages = bytes({
    0x06, 0x03, 0x02, 0x04,
});

// generated by gophertunnel: &packet.BookEdit{InventorySlot: -1,
// ActionType: packet.BookActionSign, Title: "Diary", Author: "Steve",
// XUID: "2535465"}
const std::string golden_finalize = bytes({
    0x01, 0x04, 0x05, 0x44, 0x69, 0x61, 0x72, 0x79, 0x05, 0x53, 0x74, 0x65,
    0x76, 0x65, 0x07, 0x32, 0x35, 0x33, 0x35, 0x34, 0x36, 0x35,
});

// generated by gophertunnel (898): &packet.BookEdit{ActionType: packet.BookActionReplacePage,
// InventorySlot: 2, PageNumber: 3, Text: "hi", PhotoName: "p"}
const std::string golden_v898_replace = bytes({
    0x00, 0x02, 0x03, 0x02, 0x68, 0x69, 0x01, 0x70,
});

// generated by gophertunnel (898): &packet.BookEdit{ActionType: packet.BookActionDeletePage,
// InventorySlot: 2, PageNumber: 3}
const std::string golden_v898_delete = bytes({
    0x02, 0x02, 0x03,
});

// generated by gophertunnel (898): &packet.BookEdit{ActionType: packet.BookActionSwapPages,
// InventorySlot: 2, PageNumber: 3, SecondaryPageNumber: 4}
const std::string golden_v898_swap = bytes({
    0x03, 0x02, 0x03, 0x04,
});

// generated by gophertunnel (898): &packet.BookEdit{ActionType: packet.BookActionSign,
// InventorySlot: 2, Title: "t", Author: "a", XUID: "x"}
const std::string golden_v898_sign = bytes({
    0x04, 0x02, 0x01, 0x74, 0x01, 0x61, 0x01, 0x78,
});

}  // namespace

TEST_CASE("packet id is 97 at every version")
{
    STATIC_REQUIRE(bp::BookEditPacket::Id == 97);
    STATIC_REQUIRE(bp::BookEditPacket_<898>::Id == 97);
    STATIC_REQUIRE(bp::has_packet_v<898, 97>);
    STATIC_REQUIRE(bp::has_packet_v<1001, 97>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 97>);
}

// BDS wrote this packet by hand until 924 -- BookEditPacket::write in the 1.21.132
// build dispatches a five-arm function_ref table -- and cerealised it there. The
// pre-cereal form leads with the action, and its slot and page indices are single
// bytes where the cereal form takes varints behind a uvarint32 case tag.
TEST_CASE("book-edit v898 leads with the action and writes byte indices")
{
    using Packet = bp::BookEditPacket_<898>;

    Packet packet;
    packet.action = bp::BookEditAction::ReplacePage;
    packet.book_slot = 2;
    packet.page_index = 3;
    packet.page_text = "hi";
    packet.photo_name = "p";
    REQUIRE(encode(packet) == golden_v898_replace);

    const auto back = decode<Packet>(golden_v898_replace);
    REQUIRE(back.action == bp::BookEditAction::ReplacePage);
    REQUIRE(back.book_slot == 2);
    REQUIRE(back.page_index == 3);
    REQUIRE(back.page_text == "hi");
    REQUIRE(back.photo_name == "p");
}

// Each arm writes a different tail, and nothing marks the absent fields.
TEST_CASE("book-edit v898 arms carry only their own tail")
{
    using Packet = bp::BookEditPacket_<898>;

    Packet del;
    del.action = bp::BookEditAction::DeletePage;
    del.book_slot = 2;
    del.page_index = 3;
    REQUIRE(encode(del) == golden_v898_delete);

    Packet swap;
    swap.action = bp::BookEditAction::SwapPages;
    swap.book_slot = 2;
    swap.page_index = 3;
    swap.swap_with_index = 4;
    REQUIRE(encode(swap) == golden_v898_swap);

    Packet sign;
    sign.action = bp::BookEditAction::Finalize;
    sign.book_slot = 2;
    sign.title = "t";
    sign.author = "a";
    sign.xuid = "x";
    REQUIRE(encode(sign) == golden_v898_sign);

    REQUIRE(decode<Packet>(golden_v898_sign).xuid == "x");
    REQUIRE(decode<Packet>(golden_v898_swap).swap_with_index == 4);
}

TEST_CASE("book-edit replace-page round-trips against the golden")
{
    bp::BookEditPacket packet;
    packet.book_slot = 3;
    packet.operation =
        bp::ReplacePage{.page_index = 200, .page_text = "hello", .photo_name = "photo.png"};
    REQUIRE(encode(packet) == golden_replace_page);

    const auto back = decode<bp::BookEditPacket>(golden_replace_page);
    REQUIRE(back.book_slot == 3);
    const auto &page = std::get<bp::ReplacePage>(back.operation);
    REQUIRE(page.page_index == 200);
    REQUIRE(page.page_text == "hello");
    REQUIRE(page.photo_name == "photo.png");
}

TEST_CASE("the book-edit add-page arm differs from replace-page in its index alone")
{
    bp::BookEditPacket packet;
    packet.book_slot = 3;
    packet.operation =
        bp::AddPage{.page_index = 200, .page_text = "hello", .photo_name = "photo.png"};
    REQUIRE(encode(packet) == golden_add_page);
    REQUIRE(golden_add_page.substr(2) == golden_replace_page.substr(2));

    const auto add = decode<bp::BookEditPacket>(golden_add_page);
    REQUIRE(std::holds_alternative<bp::AddPage>(add.operation));
    const auto replace = decode<bp::BookEditPacket>(golden_replace_page);
    REQUIRE(std::holds_alternative<bp::ReplacePage>(replace.operation));
}

TEST_CASE("book-edit delete-page reads one index where swap-pages reads two")
{
    bp::BookEditPacket del;
    del.book_slot = 3;
    del.operation = bp::DeletePage{.page_index = 1};
    REQUIRE(encode(del) == golden_delete_page);
    REQUIRE(decode<bp::BookEditPacket>(golden_delete_page).book_slot == 3);

    bp::BookEditPacket swap;
    swap.book_slot = 3;
    swap.operation = bp::SwapPages{.page_index = 1, .swap_with_index = 2};
    REQUIRE(encode(swap) == golden_swap_pages);

    const auto back = decode<bp::BookEditPacket>(golden_swap_pages);
    REQUIRE(std::get<bp::SwapPages>(back.operation).page_index == 1);
    REQUIRE(std::get<bp::SwapPages>(back.operation).swap_with_index == 2);
    REQUIRE(rejects<bp::BookEditPacket>(golden_swap_pages.substr(0, 3)));
}

TEST_CASE("book-edit finalize takes the last case index and a signed book slot")
{
    bp::BookEditPacket packet;
    packet.book_slot = -1;
    packet.operation = bp::Finalize{.title = "Diary", .author = "Steve", .xuid = "2535465"};
    REQUIRE(encode(packet) == golden_finalize);

    const auto back = decode<bp::BookEditPacket>(golden_finalize);
    REQUIRE(back.book_slot == -1);
    const auto &finalize = std::get<bp::Finalize>(back.operation);
    REQUIRE(finalize.title == "Diary");
    REQUIRE(finalize.author == "Steve");
    REQUIRE(finalize.xuid == "2535465");
}
