#include <string>

#include <bedrock/protocol/edu.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.EducationSettings{CodeBuilderDefaultURI: "https://code.builder/",
// CodeBuilderTitle: "Code Builder", CanResizeCodeBuilder: true, DisableLegacyTitleBar: false,
// PostProcessFilter: "sepia", ScreenshotBorderPath: "textures/ui/edu_border",
// CanModifyBlocks: protocol.Option(true), OverrideURI: protocol.Option("https://override/"),
// HasQuiz: false, ExternalLinkSettings: protocol.Option(protocol.EducationExternalLinkSettings{
// URL: "https://link/", DisplayName: "Link"})}
// patched: gophertunnel flattens AgentCapabilities to a lone Optional[bool] and writes one
// presence byte where BDS writes two, so a 0x01 is inserted ahead of the can-modify-blocks
// flag -- serialize<EducationLevelSettings>::write in 1.26.40 writes the optional<AgentCapabilities>
// marker before the optional<bool> member's own.
const std::string golden = bytes({
    0x15, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x63, 0x6f, 0x64,
    0x65, 0x2e, 0x62, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x2f, 0x0c, 0x43,
    0x6f, 0x64, 0x65, 0x20, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x65, 0x72, 0x01,
    0x00, 0x05, 0x73, 0x65, 0x70, 0x69, 0x61, 0x16, 0x74, 0x65, 0x78, 0x74,
    0x75, 0x72, 0x65, 0x73, 0x2f, 0x75, 0x69, 0x2f, 0x65, 0x64, 0x75, 0x5f,
    0x62, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x01, 0x01, 0x01, 0x01, 0x11, 0x68,
    0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f, 0x2f, 0x6f, 0x76, 0x65, 0x72, 0x72,
    0x69, 0x64, 0x65, 0x2f, 0x00, 0x01, 0x0d, 0x68, 0x74, 0x74, 0x70, 0x73,
    0x3a, 0x2f, 0x2f, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x04, 0x4c, 0x69, 0x6e,
    0x6b,
});

// generated by gophertunnel: &packet.EducationSettings{}
const std::string golden_unset = bytes({
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 137")
{
    STATIC_REQUIRE(bp::EducationSettingsPacket_<2168>::Id == 137);
    STATIC_REQUIRE(bp::has_packet_v<1001, 137>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 137>);
}

TEST_CASE("education settings round-trips against the golden")
{
    bp::EducationSettingsPacket_<2168> packet;
    packet.education_level_settings.code_builder_default_uri = "https://code.builder/";
    packet.education_level_settings.code_builder_title = "Code Builder";
    packet.education_level_settings.can_resize_code_builder = true;
    packet.education_level_settings.disable_legacy_title_bar = false;
    packet.education_level_settings.post_process_filter = "sepia";
    packet.education_level_settings.screenshot_border_resource_path = "textures/ui/edu_border";
    packet.education_level_settings.agent_capabilities = bp::AgentCapabilities{.can_modify_blocks = true};
    packet.education_level_settings.local_settings.code_builder_override_uri = "https://override/";
    packet.education_level_settings.external_link_settings =
        bp::ExternalLinkSettings{.url = "https://link/", .display_name = "Link"};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::EducationSettingsPacket_<2168>>(golden);
    REQUIRE(back.education_level_settings.code_builder_default_uri == "https://code.builder/");
    REQUIRE(back.education_level_settings.code_builder_title == "Code Builder");
    REQUIRE(back.education_level_settings.can_resize_code_builder);
    REQUIRE_FALSE(back.education_level_settings.disable_legacy_title_bar);
    REQUIRE(back.education_level_settings.post_process_filter == "sepia");
    REQUIRE(back.education_level_settings.screenshot_border_resource_path == "textures/ui/edu_border");
    REQUIRE(back.education_level_settings.agent_capabilities.has_value());
    REQUIRE(back.education_level_settings.agent_capabilities->can_modify_blocks.has_value());
    REQUIRE(*back.education_level_settings.agent_capabilities->can_modify_blocks);
    REQUIRE(back.education_level_settings.local_settings.code_builder_override_uri.has_value());
    REQUIRE(*back.education_level_settings.local_settings.code_builder_override_uri == "https://override/");
    REQUIRE(back.education_level_settings.external_link_settings.has_value());
    REQUIRE(back.education_level_settings.external_link_settings->url == "https://link/");
    REQUIRE(back.education_level_settings.external_link_settings->display_name == "Link");
}

TEST_CASE("an education settings body with nothing set is ten zero bytes")
{
    bp::EducationSettingsPacket_<2168> packet;
    packet.education_level_settings.can_resize_code_builder = false;
    packet.education_level_settings.disable_legacy_title_bar = false;
    REQUIRE(encode(packet) == golden_unset);

    const auto back = decode<bp::EducationSettingsPacket_<2168>>(golden_unset);
    REQUIRE(back.education_level_settings.code_builder_default_uri.empty());
    REQUIRE(back.education_level_settings.screenshot_border_resource_path.empty());
    REQUIRE_FALSE(back.education_level_settings.agent_capabilities.has_value());
    REQUIRE_FALSE(back.education_level_settings.local_settings.code_builder_override_uri.has_value());
    REQUIRE_FALSE(back.education_level_settings.external_link_settings.has_value());

    std::string deprecated_set = golden_unset;
    deprecated_set[8] = 0x01;
    REQUIRE(rejects<bp::EducationSettingsPacket_<2168>>(deprecated_set));
}

TEST_CASE("agent capabilities carry a presence byte ahead of the can-modify-blocks flag")
{
    bp::EducationSettingsPacket_<2168> packet;
    packet.education_level_settings.can_resize_code_builder = false;
    packet.education_level_settings.disable_legacy_title_bar = false;
    packet.education_level_settings.agent_capabilities = bp::AgentCapabilities{};
    const auto wire = encode(packet);
    REQUIRE(wire.size() == golden_unset.size() + 1);
    REQUIRE(wire[6] == 0x01);
    REQUIRE(wire[7] == 0x00);

    const auto back = decode<bp::EducationSettingsPacket_<2168>>(wire);
    REQUIRE(back.education_level_settings.agent_capabilities.has_value());
    REQUIRE_FALSE(back.education_level_settings.agent_capabilities->can_modify_blocks.has_value());
}
