#include <string>

#include <protocol/camera.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.CameraAimAssistPresets{Categories:
// []protocol.CameraAimAssistCategory{{Name: "cat", Priorities: protocol.CameraAimAssistPriorities{
// Entities: []protocol.CameraAimAssistPriority{{"minecraft:cow", 10}, {"minecraft:pig", 100}},
// Blocks: []protocol.CameraAimAssistPriority{{"minecraft:stone", 1}},
// EntityDefault: protocol.Option[int32](5)}}},
// Presets: []protocol.CameraAimAssistPreset{{Identifier: "preset",
// BlockExclusions: []string{"minecraft:air"}, BlockTagExclusions: []string{"wood"},
// LiquidTargets: []string{"minecraft:water"},
// ItemSettings: []protocol.CameraAimAssistItemSettings{{"minecraft:bow", "cat"}},
// DefaultItemSettings: protocol.Option("cat")}}, Operation: 1}
const std::string golden = bytes({
    0x01, 0x03, 0x63, 0x61, 0x74, 0x02, 0x0d, 0x6d, 0x69, 0x6e, 0x65, 0x63,
    0x72, 0x61, 0x66, 0x74, 0x3a, 0x63, 0x6f, 0x77, 0x0a, 0x00, 0x00, 0x00,
    0x0d, 0x6d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3a, 0x70,
    0x69, 0x67, 0x64, 0x00, 0x00, 0x00, 0x01, 0x0f, 0x6d, 0x69, 0x6e, 0x65,
    0x63, 0x72, 0x61, 0x66, 0x74, 0x3a, 0x73, 0x74, 0x6f, 0x6e, 0x65, 0x01,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x05, 0x00, 0x00, 0x00, 0x00, 0x01,
    0x06, 0x70, 0x72, 0x65, 0x73, 0x65, 0x74, 0x01, 0x0d, 0x6d, 0x69, 0x6e,
    0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3a, 0x61, 0x69, 0x72, 0x00, 0x01,
    0x04, 0x77, 0x6f, 0x6f, 0x64, 0x00, 0x01, 0x0f, 0x6d, 0x69, 0x6e, 0x65,
    0x63, 0x72, 0x61, 0x66, 0x74, 0x3a, 0x77, 0x61, 0x74, 0x65, 0x72, 0x01,
    0x0d, 0x6d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3a, 0x62,
    0x6f, 0x77, 0x03, 0x63, 0x61, 0x74, 0x01, 0x03, 0x63, 0x61, 0x74, 0x00,
    0x01,
});

// generated by gophertunnel: &packet.CameraAimAssistPresets{Operation: 0}
const std::string golden_empty = bytes({
    0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 320")
{
    STATIC_REQUIRE(bp::CameraAimAssistPresetsPacket_<2168>::Id == 320);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 320>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 320>);
}

TEST_CASE("camera aim-assist presets round-trips against the golden")
{
    bp::CameraAimAssistPresetsPacket_<2168> packet;

    bp::CameraAimAssistCategoryDefinition category;
    category.name = "cat";
    category.priorities.entities["minecraft:cow"] = 10;
    category.priorities.entities["minecraft:pig"] = 100;
    category.priorities.blocks["minecraft:stone"] = 1;
    category.priorities.entity_default = 5;
    packet.categories.push_back(category);

    bp::CameraAimAssistPresetDefinition preset;
    preset.identifier = "preset";
    preset.exclusion_settings.block_exclusion_list.emplace_back("minecraft:air");
    preset.exclusion_settings.block_tag_exclusion_list.emplace_back("wood");
    preset.liquid_targeting_list.emplace_back("minecraft:water");
    preset.item_settings["minecraft:bow"] = "cat";
    preset.default_item_settings = "cat";
    packet.presets.push_back(preset);

    packet.operation = bp::CameraAimAssistPresetsPacketOperation::ADD_TO_EXISTING;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::CameraAimAssistPresetsPacket_<2168>>(golden);
    REQUIRE(back.categories.size() == 1);
    REQUIRE(back.categories[0].name == "cat");
    REQUIRE(back.categories[0].priorities.entities.size() == 2);
    REQUIRE(back.categories[0].priorities.entities.at("minecraft:cow") == 10);
    REQUIRE(back.categories[0].priorities.entities.at("minecraft:pig") == 100);
    REQUIRE(back.categories[0].priorities.blocks.at("minecraft:stone") == 1);
    REQUIRE(back.categories[0].priorities.block_tags.empty());
    REQUIRE(back.categories[0].priorities.entity_type_families.empty());
    REQUIRE(back.categories[0].priorities.entity_default == 5);
    REQUIRE_FALSE(back.categories[0].priorities.block_default.has_value());
    REQUIRE(back.presets.size() == 1);
    REQUIRE(back.presets[0].identifier == "preset");
    REQUIRE(back.presets[0].exclusion_settings.block_exclusion_list.size() == 1);
    REQUIRE(back.presets[0].exclusion_settings.block_exclusion_list[0] == "minecraft:air");
    REQUIRE(back.presets[0].exclusion_settings.actor_exclusion_list.empty());
    REQUIRE(back.presets[0].exclusion_settings.block_tag_exclusion_list.size() == 1);
    REQUIRE(back.presets[0].exclusion_settings.block_tag_exclusion_list[0] == "wood");
    REQUIRE(back.presets[0].exclusion_settings.entity_type_family_exclusion_list.empty());
    REQUIRE(back.presets[0].liquid_targeting_list.size() == 1);
    REQUIRE(back.presets[0].liquid_targeting_list[0] == "minecraft:water");
    REQUIRE(back.presets[0].item_settings.at("minecraft:bow") == "cat");
    REQUIRE(back.presets[0].default_item_settings == "cat");
    REQUIRE_FALSE(back.presets[0].hand_settings.has_value());
    REQUIRE(back.operation == bp::CameraAimAssistPresetsPacketOperation::ADD_TO_EXISTING);
}

TEST_CASE("an empty aim-assist registry is two counts and the operation byte")
{
    bp::CameraAimAssistPresetsPacket_<2168> packet;
    packet.operation = bp::CameraAimAssistPresetsPacketOperation::SET;
    REQUIRE(encode(packet) == golden_empty);

    const auto back = decode<bp::CameraAimAssistPresetsPacket_<2168>>(golden_empty);
    REQUIRE(back.categories.empty());
    REQUIRE(back.presets.empty());
    REQUIRE(back.operation == bp::CameraAimAssistPresetsPacketOperation::SET);
}

TEST_CASE("the aim-assist operation byte is not optional on the frame")
{
    REQUIRE(rejects<bp::CameraAimAssistPresetsPacket_<2168>>(bytes({0x00, 0x00})));
}
