#include <cstdint>
#include <string>
#include <type_traits>
#include <vector>

#include <bedrock/protocol/diagnostics.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel:
// ServerBoundDiagnostics{AverageFramesPerSecond: 60, AverageServerSimTickTime: 1,
// AverageClientSimTickTime: 2, AverageBeginFrameTime: 3, AverageInputTime: 4,
// AverageRenderTime: 5, AverageEndFrameTime: 6, AverageRemainderTimePercent: 7,
// AverageUnaccountedTimePercent: 8, MemoryCategoryValues: [{MemoryCategoryOreUI, 1024}],
// EntityDiagnostics: [{"Zombie", "minecraft:zombie", 500, 50}],
// SystemDiagnostics: [{"Physics", 3, 250, 25}]}
// gophertunnel has no pre-1001 shape, so its trailing empty WhiskerScopes count is dropped.
const std::string golden_base = bytes({
    0x00, 0x00, 0x70, 0x42, 0x00, 0x00, 0x80, 0x3f, 0x00, 0x00, 0x00, 0x40,
    0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x80, 0x40, 0x00, 0x00, 0xa0, 0x40,
    0x00, 0x00, 0xc0, 0x40, 0x00, 0x00, 0xe0, 0x40, 0x00, 0x00, 0x00, 0x41,
    0x01, 0x35, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x06,
    0x5a, 0x6f, 0x6d, 0x62, 0x69, 0x65, 0x10, 0x6d, 0x69, 0x6e, 0x65, 0x63,
    0x72, 0x61, 0x66, 0x74, 0x3a, 0x7a, 0x6f, 0x6d, 0x62, 0x69, 0x65, 0xf4,
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x32, 0x01, 0x07, 0x50, 0x68,
    0x79, 0x73, 0x69, 0x63, 0x73, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0xfa, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x19,
});

// Cloudburst's MemoryCategoryCounter.Category is one ungated list whose ordinals cannot
// be right at both versions; it also adds a BALANCER the dump has at neither version,
// keeps a trailing VR, and omits LightVolumeManager. ORE_UI's ordinal 54 does match the
// r26_u4 dump, which is why these bytes are usable.
// generated by CloudburstMC Bedrock_v2168:
// ServerboundDiagnosticsPacket{avgFps: 60, avgServerSimTickTimeMS: 1,
// avgClientSimTickTimeMS: 2, avgBeginFrameTimeMS: 3, avgInputTimeMS: 4,
// avgRenderTimeMS: 5, avgEndFrameTimeMS: 6, avgRemainderTimePercent: 7,
// avgUnaccountedTimePercent: 8, memoryCategoryValues: [MemoryCategoryCounter(ORE_UI, 1024)],
// entityDiagnostics: [EntityDiagnosticTimingInfo("Zombie", "minecraft:zombie", 500, 50)],
// systemDiagnostics: [SystemDiagnosticTimingInfo("Physics", 3, 250, 25)]}
// with the trailing empty systemCategories and whiskerScopes counts dropped.
const std::string golden_base_v2168 = bytes({
    0x00, 0x00, 0x70, 0x42, 0x00, 0x00, 0x80, 0x3f, 0x00, 0x00, 0x00, 0x40,
    0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x80, 0x40, 0x00, 0x00, 0xa0, 0x40,
    0x00, 0x00, 0xc0, 0x40, 0x00, 0x00, 0xe0, 0x40, 0x00, 0x00, 0x00, 0x41,
    0x01, 0x36, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x06,
    0x5a, 0x6f, 0x6d, 0x62, 0x69, 0x65, 0x10, 0x6d, 0x69, 0x6e, 0x65, 0x63,
    0x72, 0x61, 0x66, 0x74, 0x3a, 0x7a, 0x6f, 0x6d, 0x62, 0x69, 0x65, 0xf4,
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x32, 0x01, 0x07, 0x50, 0x68,
    0x79, 0x73, 0x69, 0x63, 0x73, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0xfa, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x19,
});

// generated by gophertunnel: the same packet with
// WhiskerScopes: [{"Frame", "  ", 900, 600, 300}] -- its trailing bytes.
const std::string golden_whisker = bytes({
    0x01, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x02, 0x20, 0x20, 0x84, 0x03,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x58, 0x02, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x2c, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

const std::string golden = golden_base + golden_whisker;

// generated by CloudburstMC Bedrock_v2168:
// ServerboundDiagnosticsPacket{systemCategories: [SystemCategory("Movement", 3)]}
// One patch: CloudburstMC writes the system categories as a bare varuint32 count with no
// presence flag, where the r26_u4 dump marks the member optional -- one leading flag byte
// and no second one, since ServerboundDiagnosticsPacket.json carries no always-true
// member-present marker. So the leading 0x01 is patched in and the rest is the codec's
// own output.
const std::string golden_system_categories = bytes({
    0x01, 0x01, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x03,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

const std::string golden_v2168 = golden_base_v2168 + golden_system_categories + golden_whisker;

template <class Packet>
void fill_base(Packet &packet)
{
    using Counter = typename decltype(packet.category_counters)::value_type;
    using Category = decltype(Counter{}.category);

    packet.avg_fps = 60.0f;
    packet.avg_server_sim_tick_time_ms = 1.0f;
    packet.avg_client_sim_tick_time_ms = 2.0f;
    packet.avg_begin_frame_time_ms = 3.0f;
    packet.avg_input_time_ms = 4.0f;
    packet.avg_render_time_ms = 5.0f;
    packet.avg_end_frame_time_ms = 6.0f;
    packet.avg_remainder_time_percent = 7.0f;
    packet.avg_unaccounted_time_percent = 8.0f;
    packet.category_counters.push_back({.category = Category::ORE_UI, .current_bytes = 1024});
    packet.entity_timings.push_back(
        {.display_name = "Zombie", .entity = "minecraft:zombie", .time_in_ns = 500, .percent_of_total = 50});
    packet.system_timings.push_back(
        {.display_name = "Physics", .system_index = 3, .time_in_ns = 250, .percent_of_total = 25});
}

}  // namespace

TEST_CASE("packet id is 315")
{
    STATIC_REQUIRE(bp::ServerboundDiagnosticsPacket_<975>::Id == 315);
    STATIC_REQUIRE(bp::ServerboundDiagnosticsPacket_<1001>::Id == 315);
    STATIC_REQUIRE(bp::ServerboundDiagnosticsPacket_<2168>::Id == 315);
}

TEST_CASE("the memory categories are renumbered at v2168")
{
    STATIC_REQUIRE(std::is_same_v<bp::MemoryCategory_<975>, bp::MemoryCategory_<1001>>);
    STATIC_REQUIRE(!std::is_same_v<bp::MemoryCategory_<1001>, bp::MemoryCategory_<2168>>);

    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<1001>::COUNT) == 92);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<2168>::COUNT) == 111);

    // Only 0..6 survive unchanged; Blobs takes 7 and everything after it moves.
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<1001>::BIOME_STORAGE) == 6);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<2168>::BIOME_STORAGE) == 6);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<1001>::CEREAL) == 7);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<2168>::BLOBS) == 7);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<2168>::CEREAL) == 8);

    // Persona is gone at v2168, replaced by six Persona_* members.
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<1001>::PERSONA) == 54);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<2168>::PERSONA_PIECES) == 56);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<2168>::PERSONA_REPO) == 61);

    // The Rendering block reorders as well: Library moves ahead of RenderRegistry.
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<1001>::RENDERING_RENDER_REGISTRY) == 60);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<1001>::RENDERING_LIBRARY) == 61);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<2168>::RENDERING_LIBRARY) == 72);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<2168>::RENDERING_RENDER_REGISTRY) == 75);

    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<1001>::GAMEFACE_SCRIPT_ENGINE) == 91);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<2168>::GAMEFACE_SCRIPT_ENGINE) == 108);
    STATIC_REQUIRE(static_cast<int>(bp::MemoryCategory_<2168>::GAMEFACE_LAYOUT) == 110);
}

TEST_CASE("serverbound-diagnostics round-trips against the golden")
{
    using Packet = bp::ServerboundDiagnosticsPacket_<1001>;

    Packet packet;
    fill_base(packet);
    packet.whisker_data.push_back({.label = "Frame",
                                   .indentation = "  ",
                                   .total_high_cost_ns = 900,
                                   .total_mid_cost_ns = 600,
                                   .total_low_cost_ns = 300});
    REQUIRE(encode(packet) == golden);

    const auto back = decode<Packet>(golden);
    REQUIRE(back.avg_fps == 60.0f);
    REQUIRE(back.category_counters.size() == 1);
    REQUIRE(back.category_counters[0].category == bp::MemoryCategory_<1001>::ORE_UI);
    REQUIRE(back.category_counters[0].current_bytes == 1024);
    REQUIRE(back.entity_timings.size() == 1);
    REQUIRE(back.entity_timings[0].entity == "minecraft:zombie");
    REQUIRE(back.system_timings.size() == 1);
    REQUIRE(back.system_timings[0].system_index == 3);
    REQUIRE(back.whisker_data.size() == 1);
    REQUIRE(back.whisker_data[0].label == "Frame");
    REQUIRE(back.whisker_data[0].total_high_cost_ns == 900);
    REQUIRE(back.whisker_data[0].total_mid_cost_ns == 600);
    REQUIRE(back.whisker_data[0].total_low_cost_ns == 300);
}

TEST_CASE("serverbound-diagnostics v2168 form round-trips against the golden")
{
    using Packet = bp::ServerboundDiagnosticsPacket_<2168>;

    Packet packet;
    fill_base(packet);
    packet.system_categories = std::vector<bp::SystemCategory>{{.category_name = "Movement", .system_index = 3}};
    packet.whisker_data.push_back({.label = "Frame",
                                   .indentation = "  ",
                                   .total_high_cost_ns = 900,
                                   .total_mid_cost_ns = 600,
                                   .total_low_cost_ns = 300});
    REQUIRE(encode(packet) == golden_v2168);

    const auto back = decode<Packet>(golden_v2168);
    REQUIRE(back.category_counters[0].category == bp::MemoryCategory_<2168>::ORE_UI);
    REQUIRE(back.system_categories.has_value());
    REQUIRE(back.system_categories->size() == 1);
    REQUIRE((*back.system_categories)[0].category_name == "Movement");
    REQUIRE((*back.system_categories)[0].system_index == 3);
    REQUIRE(back.whisker_data.size() == 1);
    REQUIRE(back.whisker_data[0].label == "Frame");
}

// The same category is a different byte either side of v2168, and a v1001 byte read under
// the v2168 numbering silently names a different category.
TEST_CASE("a v1001 category byte reads as another category at v2168")
{
    REQUIRE(golden_base.size() == golden_base_v2168.size());
    REQUIRE(golden_base != golden_base_v2168);

    const auto back = decode<bp::ServerboundDiagnosticsPacket_<1001>>(golden);
    const auto category = back.category_counters[0].category;
    REQUIRE(category == bp::MemoryCategory_<1001>::ORE_UI);
    REQUIRE(static_cast<int>(category) == static_cast<int>(bp::MemoryCategory_<2168>::MOLANG));
}

TEST_CASE("absent system categories are a lone flag ahead of the whisker scopes")
{
    using Packet = bp::ServerboundDiagnosticsPacket_<2168>;

    Packet packet;
    fill_base(packet);
    REQUIRE(encode(packet) == golden_base_v2168 + bytes({0x00, 0x00}));
}

// The categories land between the system diagnostics and the whisker scopes, so
// every byte of the tail shifts and neither form reads the other's bytes.
TEST_CASE("a v1001 diagnostics body does not decode as a v2168 one")
{
    REQUIRE(golden != golden_v2168);
    REQUIRE(rejects<bp::ServerboundDiagnosticsPacket_<2168>>(golden));
    REQUIRE(rejects<bp::ServerboundDiagnosticsPacket_<1001>>(golden_v2168));
}

TEST_CASE("before v1001 the whisker scopes are absent from the wire")
{
    using Packet = bp::ServerboundDiagnosticsPacket_<975>;

    Packet packet;
    fill_base(packet);
    REQUIRE(encode(packet) == golden_base);

    const auto back = decode<Packet>(golden_base);
    REQUIRE(back.system_timings.size() == 1);
    REQUIRE(back.system_timings[0].display_name == "Physics");
}
