#include <string>
#include <variant>

#include "fixture.hpp"

namespace {

bp::SerializedSkinRef_<2168> skin()
{
    bp::SerializedSkinRef_<2168> out;
    out.id = "sid";
    out.play_fab_id = "pfid";
    out.resource_patch = "patch";
    out.image_data = {.width = 1, .height = 1, .image_bytes = std::string(4, '\0')};
    out.cape_image_data = {.width = 1, .height = 1, .image_bytes = std::string(4, '\0')};
    out.geometry_data = "geo";
    out.geometry_data_min_engine_version = "1.0.0";
    out.animation_data = "anim";
    out.cape_id = "cid";
    out.full_id = "fid";
    out.arm_size = bp::ArmSizeType::WIDE;
    out.skin_color = static_cast<bp::Color>(0x01020304);
    out.is_premium = true;
    out.is_persona = false;
    out.is_persona_cape_on_classic_skin = false;
    out.is_primary_user = true;
    out.overrides_player_appearance = false;
    out.trusted_skin_flag = bp::TrustedSkinFlag::TRUE;
    out.profile_hash = "hash";
    return out;
}

bp::PlayerListPacket_<2168> fill()
{
    bp::PlayerListPacket_<2168> pkt;

    bp::PlayerListPacketPayload_<2168>::AddEntry add;
    add.action = bp::PlayerListPacketType::ADD;
    add.uuid = {.most_significant_bits = 0, .least_significant_bits = 1};
    add.actor_unique_id = static_cast<bp::ActorUniqueID>(7);
    add.name = "Steve";
    add.xuid = "xuid";
    add.platform_online_id = "pcid";
    add.build_platform = bp::BuildPlatform::WIN32;
    add.skin = skin();
    add.is_teacher = false;
    add.is_host = true;
    add.is_sub_client = false;
    add.color = static_cast<bp::Color>(0x05060708);
    pkt.entries.emplace_back(add);

    bp::PlayerListPacketPayload_<2168>::RemoveEntry remove;
    remove.action = bp::PlayerListPacketType::REMOVE;
    remove.uuid = {.most_significant_bits = 0, .least_significant_bits = 2};
    pkt.entries.emplace_back(remove);

    return pkt;
}

}  // namespace

TEST_CASE("PlayerListPacket: id")
{
    STATIC_REQUIRE(bp::PlayerListPacket_<2168>::Id == 63);
}

TEST_CASE("PlayerListPacket: v2168 round-trip")
{
    using Packet = bp::PlayerListPacket_<2168>;

    const Packet pkt = fill();

    // generated by CloudburstMC Bedrock_v2168:
    // PlayerListPacket{entries: [
    //   Entry(action ADD, uuid 0-1, entityId 7, name "Steve", xuid "xuid",
    //     platformChatId "pcid", buildPlatform WIN32, teacher false, host true,
    //     subClient false, color 0x05060708,
    //     skin SerializedSkin(skinId "sid", playFabId "pfid", skinResourcePatch "patch",
    //       skinData 1x1, animations [], capeData 1x1, geometryData "geo",
    //       geometryDataEngineVersion "1.0.0", animationData "anim", capeId "cid",
    //       fullSkinId "fid", armSize "wide", color 0x01020304, personaPieces [],
    //       tintColors [], premium true, persona false, capeOnClassic false,
    //       primaryUser true, overridingPlayerAppearance false, trusted true,
    //       profileHash "hash")),
    //   Entry(action REMOVE, uuid 0-2)]}
    // The trusted-skin flag is name-coded: Cloudburst writes Boolean.toString, so the
    // four payload bytes read "true" there and "TRUE" here.
    const std::string golden = bytes({
    0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0E, 0x05, 0x53, 0x74, 0x65,
    0x76, 0x65, 0x04, 0x78, 0x75, 0x69, 0x64, 0x04, 0x70, 0x63, 0x69, 0x64,
    0x08, 0x00, 0x00, 0x00, 0x03, 0x73, 0x69, 0x64, 0x04, 0x70, 0x66, 0x69,
    0x64, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x01, 0x00, 0x00, 0x00, 0x01,
    0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
    0x00, 0x01, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x03, 0x67,
    0x65, 0x6F, 0x05, 0x31, 0x2E, 0x30, 0x2E, 0x30, 0x04, 0x61, 0x6E, 0x69,
    0x6D, 0x03, 0x63, 0x69, 0x64, 0x03, 0x66, 0x69, 0x64, 0x01, 0x04, 0x03,
    0x02, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, 0x04, 0x54, 0x52,
    0x55, 0x45, 0x04, 0x68, 0x61, 0x73, 0x68, 0x00, 0x01, 0x00, 0x08, 0x07,
    0x06, 0x05, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.entries.size() == 2);

    const auto &add = std::get<bp::PlayerListPacketPayload_<2168>::AddEntry>(rt.entries[0]);
    REQUIRE(add.action == bp::PlayerListPacketType::ADD);
    REQUIRE(add.name == "Steve");
    REQUIRE(add.build_platform == bp::BuildPlatform::WIN32);
    REQUIRE(add.skin.profile_hash == "hash");

    const auto &remove = std::get<bp::PlayerListPacketPayload_<2168>::RemoveEntry>(rt.entries[1]);
    REQUIRE(remove.action == bp::PlayerListPacketType::REMOVE);
    REQUIRE(remove.uuid.least_significant_bits == 2);
}

// The variant index and the payload's own action member are both on the wire and they
// disagree: index 0 selects RemoveEntry, whose action is Remove = 1, and index 1
// selects AddEntry, whose action is Add = 0.
TEST_CASE("PlayerListPacket: the variant index is not the action value")
{
    bp::PlayerListPacket_<2168> pkt;
    bp::PlayerListPacketPayload_<2168>::RemoveEntry remove;
    remove.action = bp::PlayerListPacketType::REMOVE;
    remove.uuid = {};
    pkt.entries.emplace_back(remove);

    const auto encoded = encode(pkt);
    REQUIRE(encoded.size() == 19);
    REQUIRE(static_cast<unsigned char>(encoded[0]) == 1);
    REQUIRE(static_cast<unsigned char>(encoded[1]) == 0);
    REQUIRE(static_cast<unsigned char>(encoded[2]) == 1);
}
