#include <string>

#include <protocol/player.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.PlayerFog{Stack: []string{"minecraft:fog_ocean",
// "minecraft:fog_hell"}}
const std::string golden = bytes({
    0x02, 0x13, 0x6d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3a,
    0x66, 0x6f, 0x67, 0x5f, 0x6f, 0x63, 0x65, 0x61, 0x6e, 0x12, 0x6d, 0x69,
    0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3a, 0x66, 0x6f, 0x67, 0x5f,
    0x68, 0x65, 0x6c, 0x6c,
});

// generated by gophertunnel: &packet.PlayerFog{}
const std::string golden_empty = bytes({
    0x00,
});

}  // namespace

TEST_CASE("packet id is 160")
{
    STATIC_REQUIRE(bp::PlayerFogPacket_<2168>::Id == 160);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 160>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 160>);
}

TEST_CASE("player fog round-trips against the golden")
{
    bp::PlayerFogPacket_<2168> packet;
    packet.fog_stack = {"minecraft:fog_ocean", "minecraft:fog_hell"};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::PlayerFogPacket_<2168>>(golden);
    REQUIRE(back.fog_stack.size() == 2);
    REQUIRE(back.fog_stack[0] == "minecraft:fog_ocean");
    REQUIRE(back.fog_stack[1] == "minecraft:fog_hell");
}

TEST_CASE("an empty fog stack is a lone zero count")
{
    REQUIRE(encode(bp::PlayerFogPacket_<2168>{}) == golden_empty);
    REQUIRE(decode<bp::PlayerFogPacket_<2168>>(golden_empty).fog_stack.empty());
}
