#include <optional>
#include <string>

#include "fixture.hpp"

namespace {

// AddItemActorPacket cerealised at 2168; r26_u3 carries no AddItemActorPacket.json.
// gophertunnel's add_item_actor.go and CloudburstMC's AddItemEntitySerializer_v291
// (which v2168 does not override) hold the same seven fields in the same order as the
// r26_u4 dump, so the wire delta is entirely in the closure: the entity data list and
// the item descriptor.
template <class Packet>
void fill(Packet &packet)
{
    packet.id = static_cast<bp::ActorUniqueID>(1);
    packet.runtime_id = static_cast<bp::ActorRuntimeID>(2);
    packet.item.id = 5;
    packet.item.stack_size = 1;
    packet.item.aux_value = 0;
    packet.item.net_id_variant = std::nullopt;
    packet.item.block_runtime_id = 0;
    packet.item.user_data_buffer = empty_item_blob();
    packet.pos = {.x = 1.0f, .y = 2.0f, .z = 3.0f};
    packet.velocity = {.x = 4.0f, .y = 5.0f, .z = 6.0f};
    packet.is_from_fishing = true;
}

}  // namespace

TEST_CASE("packet id is 15 at both versions")
{
    STATIC_REQUIRE(bp::AddItemActorPacket_<1001>::Id == 15);
    STATIC_REQUIRE(bp::AddItemActorPacket_<2168>::Id == 15);
}

TEST_CASE("AddItemActorPacket: v2168 round-trip")
{
    using Packet = bp::AddItemActorPacket_<2168>;

    Packet pkt;
    fill(pkt);
    pkt.data.data.push_back(
        {.id = 38, .payload = bp::DataItemFloatPayload_<2168>{.type = bp::DataItemType::FLOAT, .value = 0.5f}});

    // generated by CloudburstMC Bedrock_v2168:
    // AddItemEntityPacket{uniqueEntityId: 1, runtimeEntityId: 2,
    //   itemInHand: ItemData(minecraft:stone runtimeId 5, count 1, damage 0),
    //   position: (1, 2, 3), motion: (4, 5, 6), metadata: {SCALE: 0.5f},
    //   fromFishing: true}
    const std::string golden = bytes({
        0x02, 0x02, 0x05, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3F,
        0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x80, 0x40,
        0x00, 0x00, 0xA0, 0x40, 0x00, 0x00, 0xC0, 0x40, 0x01, 0x26, 0x03, 0x03,
        0x00, 0x00, 0x00, 0x3F, 0x01,
    });

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.id == static_cast<bp::ActorUniqueID>(1));
    REQUIRE(rt.item.id == 5);
    REQUIRE(rt.item.stack_size == 1);
    REQUIRE(rt.item.user_data_buffer == empty_item_blob());
    REQUIRE(rt.data.data.size() == 1);
    REQUIRE(std::get<3>(rt.data.data[0].payload).type == bp::DataItemType::FLOAT);
    REQUIRE(rt.is_from_fishing);
}

// TODO: confirm against BDS -- structural rather than golden, for the same reason as
// test_012_add_player.cpp: this packet does not cerealise until 2168, so below 2168 BDS
// writes NetworkItemStackDescriptor::write for the item. gophertunnel's add_item_actor.go
// (io.ItemInstance) and CloudburstMC v1001 (writeItem inherited from v431) both write
// that legacy form, while the shared SerializedNetworkItemStackDescriptor declaration
// resolves to the cerealised body at the 1001 snapshot. See protocol/movement.py.
TEST_CASE("AddItemActorPacket: v1001 round-trips and is one data-item byte shorter")
{
    using Packet = bp::AddItemActorPacket_<1001>;

    Packet pkt;
    fill(pkt);
    pkt.data.data.push_back({.id = 38, .payload = bp::DataItemFloatPayload_<1001>{.value = 0.5f}});

    const auto encoded = encode(pkt);

    bp::AddItemActorPacket_<2168> newer;
    fill(newer);
    newer.data.data.push_back(
        {.id = 38, .payload = bp::DataItemFloatPayload_<2168>{.type = bp::DataItemType::FLOAT, .value = 0.5f}});
    REQUIRE(encoded.size() + 1 == encode(newer).size());

    const auto rt = decode<Packet>(encoded);
    REQUIRE(rt.item.id == 5);
    REQUIRE(rt.data.data.size() == 1);
    REQUIRE(std::get<3>(rt.data.data[0].payload).value == 0.5f);
    REQUIRE(rt.is_from_fishing);

    // The extra type byte shifts the data item's value along, so a 2168 body still reads
    // as a 1001 one -- with a corrupt payload and a byte left over.
    const auto wrong = decode_partial<Packet>(encode(newer));
    REQUIRE(std::get<3>(wrong.data.data[0].payload).value != 0.5f);
}
