#include <string>

#include <protocol/inventory.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.GUIDataPickItem{ItemName: "minecraft:diamond_sword",
// ItemEffects: "Sharpness V", HotBarSlot: 300}
const std::string golden = bytes({
    0x17, 0x6d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3a, 0x64,
    0x69, 0x61, 0x6d, 0x6f, 0x6e, 0x64, 0x5f, 0x73, 0x77, 0x6f, 0x72, 0x64,
    0x0b, 0x53, 0x68, 0x61, 0x72, 0x70, 0x6e, 0x65, 0x73, 0x73, 0x20, 0x56,
    0x2c, 0x01, 0x00, 0x00,
});

// generated by gophertunnel: &packet.GUIDataPickItem{HotBarSlot: -1}
const std::string golden_negative_slot = bytes({
    0x00, 0x00, 0xff, 0xff, 0xff, 0xff,
});

}  // namespace

TEST_CASE("packet id is 54")
{
    STATIC_REQUIRE(bp::GuiDataPickItemPacket_<2168>::Id == 54);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 54>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 54>);
}

TEST_CASE("gui data pick item round-trips against the golden")
{
    bp::GuiDataPickItemPacket_<2168> packet;
    packet.item_name = "minecraft:diamond_sword";
    packet.item_effect_name = "Sharpness V";
    packet.slot = 300;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::GuiDataPickItemPacket_<2168>>(golden);
    REQUIRE(back.item_name == "minecraft:diamond_sword");
    REQUIRE(back.item_effect_name == "Sharpness V");
    REQUIRE(back.slot == 300);
}

TEST_CASE("the slot is four fixed bytes, not a varint, behind two empty strings")
{
    bp::GuiDataPickItemPacket_<2168> packet;
    packet.slot = -1;
    REQUIRE(encode(packet) == golden_negative_slot);

    const auto back = decode<bp::GuiDataPickItemPacket_<2168>>(golden_negative_slot);
    REQUIRE(back.item_name.empty());
    REQUIRE(back.item_effect_name.empty());
    REQUIRE(back.slot == -1);
}
