#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("AvailableActorIdentifiersPacket: id + round-trip with the CompoundTag body")
{
    STATIC_REQUIRE(bp::AvailableActorIdentifiersPacket::Id == 119);

    // Mojang's docs describe the body as a CompoundTag holding one named
    // ListTag "idlist" of ActorInfo entries (rid, id, bid, hasspawnegg,
    // summonable). One entry is enough to exercise the framing.
    bp::CompoundTag entry{
        {"rid", bp::IntTag{1}},         {"id", bp::StringTag{"minecraft:player"}},
        {"bid", bp::StringTag{""}},     {"hasspawnegg", bp::ByteTag{0}},
        {"summonable", bp::ByteTag{0}},
    };
    bp::AvailableActorIdentifiersPacket pkt;
    pkt.identifier_list.emplace("idlist", bp::ListTag{std::move(entry)});

    // generated by gophertunnel:
    // packet.AvailableActorIdentifiers{SerialisedEntityIdentifiers: nbt.Marshal(
    //   struct{Idlist []actorInfo `nbt:"idlist"`}{Idlist: []actorInfo{{
    //     Bid: "", HasSpawnEgg: 0, Id: "minecraft:player", Rid: 1, Summonable: 0,
    //   }}}, nbt.NetworkLittleEndian)}
    //
    // Inner ActorInfo keys are declared bid/hasspawnegg/id/rid/summonable
    // (alphabetical) to match our CompoundTag's sorted-key iteration on the
    // write side; the wire layout is otherwise identical.
    const std::vector<std::uint8_t> golden{
        0x0A, 0x00, 0x09, 0x06, 0x69, 0x64, 0x6C, 0x69, 0x73, 0x74, 0x0A, 0x02, 0x08, 0x03, 0x62,
        0x69, 0x64, 0x00, 0x01, 0x0B, 0x68, 0x61, 0x73, 0x73, 0x70, 0x61, 0x77, 0x6E, 0x65, 0x67,
        0x67, 0x00, 0x08, 0x02, 0x69, 0x64, 0x10, 0x6D, 0x69, 0x6E, 0x65, 0x63, 0x72, 0x61, 0x66,
        0x74, 0x3A, 0x70, 0x6C, 0x61, 0x79, 0x65, 0x72, 0x03, 0x03, 0x72, 0x69, 0x64, 0x02, 0x01,
        0x0A, 0x73, 0x75, 0x6D, 0x6D, 0x6F, 0x6E, 0x61, 0x62, 0x6C, 0x65, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::AvailableActorIdentifiersPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    const auto &idlist = rt->identifier_list.at("idlist").get<bp::ListTag>();
    REQUIRE(idlist.size() == 1);
    const auto &decoded = idlist[0].get<bp::CompoundTag>();
    REQUIRE(decoded.at("rid").get<bp::IntTag>().value() == 1);
    REQUIRE(decoded.at("id").get<bp::StringTag>().value() == "minecraft:player");
    REQUIRE(decoded.at("hasspawnegg").get<bp::ByteTag>().value() == 0);
}
