#include <string>

#include <bedrock/protocol/inventory.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.PlayerToggleCrafterSlotRequest{PosX: 1, PosY: -2,
// PosZ: 300, Slot: 200, Disabled: true}
const std::string golden = bytes({
    0x01, 0x00, 0x00, 0x00, 0xfe, 0xff, 0xff, 0xff, 0x2c, 0x01, 0x00, 0x00,
    0xc8, 0x01,
});

// generated by gophertunnel: &packet.PlayerToggleCrafterSlotRequest{}
const std::string golden_zero = bytes({
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 306")
{
    STATIC_REQUIRE(bp::PlayerToggleCrafterSlotRequestPacket_<2168>::Id == 306);
    STATIC_REQUIRE(bp::has_packet_v<1001, 306>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 306>);
}

TEST_CASE("player-toggle-crafter-slot-request round-trips against the golden")
{
    bp::PlayerToggleCrafterSlotRequestPacket_<2168> packet;
    packet.pos_x = 1;
    packet.pos_y = -2;
    packet.pos_z = 300;
    packet.slot_index = 200;
    packet.is_disabled = true;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::PlayerToggleCrafterSlotRequestPacket_<2168>>(golden);
    REQUIRE(back.pos_x == 1);
    REQUIRE(back.pos_y == -2);
    REQUIRE(back.pos_z == 300);
    REQUIRE(back.slot_index == 200);
    REQUIRE(back.is_disabled);
}

TEST_CASE("the position is three fixed int32s and the slot index one byte")
{
    bp::PlayerToggleCrafterSlotRequestPacket_<2168> packet;
    packet.pos_x = 0;
    packet.pos_y = 0;
    packet.pos_z = 0;
    packet.slot_index = 0;
    packet.is_disabled = false;
    REQUIRE(encode(packet) == golden_zero);

    const auto varint_body = bytes({0x02, 0x03, 0xa8, 0x04, 0xc8, 0x01, 0x01});
    REQUIRE(rejects<bp::PlayerToggleCrafterSlotRequestPacket_<2168>>(varint_body));

    const auto back = decode<bp::PlayerToggleCrafterSlotRequestPacket_<2168>>(golden_zero);
    REQUIRE(back.slot_index == 0);
    REQUIRE_FALSE(back.is_disabled);
}
