#include <cstdint>
#include <optional>
#include <string>
#include <variant>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

namespace {

template <class T>
std::string encode(const T &value)
{
    std::string buffer;
    bp::BinaryWriter writer{buffer};
    bp::Serializer<T>::serialize(writer, value);
    return buffer;
}

std::string bytes(std::initializer_list<int> raw)
{
    std::string out;
    for (int b : raw) {
        out.push_back(static_cast<char>(b));
    }
    return out;
}

using Packet = bp::InventoryTransactionPacket_<1001>;

// The cerealised item extra-data blob: Int16(0) NBT-length, then two empty
// uint32-counted string lists (can-place-on / can-break). All zero.
std::string empty_item_blob()
{
    return std::string(10, '\0');
}

bp::SerializedNetworkItemStackDescriptor air()
{
    return {};  // id 0 -> the whole descriptor is 8 zero bytes
}

bp::SerializedNetworkItemStackDescriptor stone()
{
    bp::SerializedNetworkItemStackDescriptor item;
    item.id = 1;
    item.stack_size = 64;
    item.block_runtime_id = 7;
    item.user_data_buffer = empty_item_blob();
    return item;
}

// generated by gophertunnel (654cd5f):
// packet.InventoryTransaction{TransactionData: &protocol.NormalTransactionData{}}
const std::string golden_normal_empty = bytes({
    0x00,  // legacy_request_id = 0 (varint32)
    0x00,  // legacy_set_item_slots absent
    0x01,  // transaction present
    0x00,  // variant index 0 (Normal)
    0x01,  // actions present
    0x00,  // actions count 0
});

// generated by gophertunnel (654cd5f):
// InventoryTransaction{Actions: [{SourceType: Container, WindowID: 12, InventorySlot: 3,
//   OldItem: air, NewItem: stone(id 1, count 64, block 7)}], NormalTransactionData}
const std::string golden_normal_action = bytes({
    0x00,                          // legacy_request_id = 0
    0x00,                          // legacy_set_item_slots absent
    0x01,                          // transaction present
    0x00,                          // variant index 0 (Normal)
    0x01,                          // actions present
    0x01,                          // actions count 1
    0x00,                          //   source_type = CONTAINER_INVENTORY (uvarint32)
    0x01, 0x01, 0x0c,              //   container_id: present, present, 12 (int8)
    0x01, 0x00,                    //   flags: present, absent
    0x03,                          //   slot = 3 (uvarint32)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  //   from_item = air
    0x01, 0x00,                    //   to_item.id = 1 (int16)
    0x40, 0x00,                    //   to_item.stack_size = 64 (uint16)
    0x00,                          //   to_item.aux_value = 0
    0x00,                          //   to_item.net_id absent
    0x07,                          //   to_item.block_runtime_id = 7
    0x0a,                          //   to_item.user_data_buffer length = 10
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

// generated by gophertunnel (654cd5f):
// InventoryTransaction{UseItemTransactionData{ActionType: 0, TriggerType: 1,
//   BlockPosition: {1,2,3}, BlockFace: 4, HotBarSlot: 5, HeldItem: air, BlockRuntimeID: 9}}
const std::string golden_use_item = bytes({
    0x00,              // legacy_request_id = 0
    0x00,              // legacy_set_item_slots absent
    0x01,              // transaction present
    0x02,              // variant index 2 (ItemUse)
    0x01, 0x00,        //   actions: present, count 0
    0x00,              //   action_type = PLACE (uvarint32)
    0x01,              //   trigger_type = PLAYER_INPUT (uvarint32)
    0x02, 0x04, 0x06,  //   pos = (1,2,3) (varint32 zigzag)
    0x04,              //   face = 4 (uvarint32)
    0x0a,              //   slot = 5 (varint32 zigzag)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  //   item = air
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  //   from_pos = (0,0,0)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  //   click_pos = (0,0,0)
    0x09,              //   target_block_id = 9 (uvarint32)
    0x00,              //   client_predicted_result = FAILURE (uint8)
    0x00,              //   client_cooldown_state = OFF (uint8)
});

using PacketV975 = bp::InventoryTransactionPacket_<975>;

bp::base::SerializedNetworkItemStackDescriptor air_v975()
{
    return {};  // id 0 -> the write returns early, so air is a lone zero byte
}

bp::base::SerializedNetworkItemStackDescriptor stone_v975()
{
    bp::base::SerializedNetworkItemStackDescriptor item;
    item.id = 1;
    item.stack_size = 64;
    item.block_runtime_id = 7;
    item.user_data_buffer = empty_item_blob();
    return item;
}

// generated by gophertunnel at 6353c49^ (de090ae, the last pre-1.26.30 commit):
// packet.InventoryTransaction{TransactionData: &protocol.NormalTransactionData{}}
const std::string golden_v975_normal_empty = bytes({
    0x00,  // legacy_request_id = 0 (varint32) -- zero, so no legacy_set_item_slots
    0x00,  // variant index 0 (Normal)
    0x00,  // actions count 0
});

// generated by gophertunnel at 6353c49^ (de090ae):
// packet.InventoryTransaction{Actions: []protocol.InventoryAction{{SourceType: Container,
//   WindowID: 12, InventorySlot: 3, OldItem: air, NewItem: stone(id 1, count 64, block 7)}},
//   TransactionData: &protocol.NormalTransactionData{}}
const std::string golden_v975_normal_action = bytes({
    0x00,        // legacy_request_id = 0
    0x00,        // variant index 0 (Normal)
    0x01,        // actions count 1
    0x00,        //   source_type = CONTAINER_INVENTORY (uvarint32)
    0x18,        //   container_id = 12 (varint32 zigzag)
    0x03,        //   slot = 3 (uvarint32)
    0x00,        //   from_item = air (one byte)
    0x02,        //   to_item.id = 1 (varint32 zigzag)
    0x40, 0x00,  //   to_item.stack_size = 64 (uint16)
    0x00,        //   to_item.aux_value = 0
    0x00,        //   to_item.net_id absent
    0x0e,        //   to_item.block_runtime_id = 7 (varint32 zigzag)
    0x0a,        //   to_item.user_data_buffer length = 10
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

// generated by gophertunnel at 6353c49^ (de090ae):
// packet.InventoryTransaction{TransactionData: &protocol.UseItemTransactionData{ActionType: 0,
//   TriggerType: 1, BlockPosition: {1,2,3}, BlockFace: 4, HotBarSlot: 5, HeldItem: air,
//   BlockRuntimeID: 9}}
const std::string golden_v975_use_item = bytes({
    0x00,              // legacy_request_id = 0
    0x02,              // variant index 2 (ItemUse)
    0x00,              //   actions count 0
    0x00,              //   action_type = PLACE (uvarint32)
    0x01,              //   trigger_type = PLAYER_INPUT (uvarint32)
    0x02, 0x04, 0x06,  //   pos = (1,2,3) (varint32 zigzag)
    0x08,              //   face = 4 (varint32 zigzag)
    0x0a,              //   slot = 5 (varint32 zigzag)
    0x00,              //   item = air
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  //   from_pos = (0,0,0)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  //   click_pos = (0,0,0)
    0x09,              //   target_block_id = 9 (uvarint32)
    0x00,              //   client_predicted_result = FAILURE (uvarint32)
    0x00,              //   client_cooldown_state = OFF (uint8)
});

// generated by gophertunnel at 6353c49^ (de090ae):
// packet.InventoryTransaction{LegacyRequestID: 7, LegacySetItemSlots:
//   []protocol.LegacySetItemSlot{{ContainerID: 12, Slots: []byte{3, 4}}},
//   TransactionData: &protocol.NormalTransactionData{}}
const std::string golden_v975_legacy_request = bytes({
    0x0e,        // legacy_request_id = 7 (varint32 zigzag) -- non-zero, so the slots follow
    0x01,        // legacy_set_item_slots count 1
    0x0c,        //   container_enum = COMBINED_HOTBAR_AND_INVENTORY_CONTAINER (uint8)
    0x02,        //   slots length 2
    0x03, 0x04,  //   slots
    0x00,        // variant index 0 (Normal)
    0x00,        // actions count 0
});

}  // namespace

TEST_CASE("packet id is 30 at v1001")
{
    STATIC_REQUIRE(Packet::Id == 30);
}

TEST_CASE("inventory-transaction normal (no actions) round-trips against the golden")
{
    Packet packet;
    packet.legacy_request_id = 0;
    bp::NormalTransactionData normal;
    normal.actions.actions = std::vector<bp::InventoryAction>{};  // present, empty
    packet.transaction = normal;
    REQUIRE(encode(packet) == golden_normal_empty);

    bp::BinaryReader reader{golden_normal_empty};
    auto back = bp::Serializer<Packet>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->transaction.has_value());
    REQUIRE(back->transaction->index() == 0);
}

// A container source exercises the double-bool presence wrapper: the wire carries
// an always-true marker plus the optional's own flag, but the C++ collapses to a
// single std::optional. container_id is engaged (12); flags is absent.
TEST_CASE("inventory-transaction normal with a container action round-trips")
{
    bp::InventoryAction action;
    action.source.source_type = bp::InventorySourceType::CONTAINER_INVENTORY;
    action.source.container_id = static_cast<bp::ContainerID>(12);
    action.slot = 3;
    action.from_item = air();
    action.to_item = stone();

    Packet packet;
    bp::NormalTransactionData normal;
    normal.actions.actions = std::vector<bp::InventoryAction>{action};
    packet.transaction = normal;
    REQUIRE(encode(packet) == golden_normal_action);

    bp::BinaryReader reader{golden_normal_action};
    auto back = bp::Serializer<Packet>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);

    const auto &normal_back = std::get<0>(*back->transaction);
    REQUIRE(normal_back.actions.actions.has_value());
    const auto &actions = *normal_back.actions.actions;
    REQUIRE(actions.size() == 1);
    // one std::optional each: container_id engaged at 12, flags absent
    REQUIRE(actions[0].source.container_id.has_value());
    REQUIRE(*actions[0].source.container_id == static_cast<bp::ContainerID>(12));
    REQUIRE_FALSE(actions[0].source.flags.has_value());
    REQUIRE(actions[0].to_item.id == 1);
    REQUIRE(actions[0].to_item.block_runtime_id == 7);
}

TEST_CASE("inventory-transaction use-item round-trips against the golden")
{
    bp::ItemUseInventoryTransaction use;
    use.actions.actions = std::vector<bp::InventoryAction>{};
    use.action_type = bp::ItemUseInventoryTransaction::ActionType::PLACE;
    use.trigger_type = bp::ItemUseInventoryTransaction::TriggerType::PLAYER_INPUT;
    use.pos = {.x = 1, .y = 2, .z = 3};
    use.face = 4;
    use.slot = 5;
    use.item = air();
    use.target_block_id = 9;

    Packet packet;
    packet.transaction = use;
    REQUIRE(encode(packet) == golden_use_item);

    bp::BinaryReader reader{golden_use_item};
    auto back = bp::Serializer<Packet>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->transaction->index() == 2);
    const auto &use_back = std::get<2>(*back->transaction);
    REQUIRE(use_back.pos.x == 1);
    REQUIRE(use_back.pos.z == 3);
    REQUIRE(use_back.target_block_id == 9);
    REQUIRE(use_back.trigger_type == bp::ItemUseInventoryTransaction::TriggerType::PLAYER_INPUT);
}

TEST_CASE("packet id is 30 at v975")
{
    STATIC_REQUIRE(PacketV975::Id == 30);
}

// Pre-cereal, the transaction type and the action list sit on the packet itself,
// which lands on the wire as the variant tag followed by each case's leading
// InventoryTransaction -- the same bytes, one shape later.
TEST_CASE("inventory-transaction v975 normal (no actions) round-trips against the golden")
{
    PacketV975 packet;
    packet.transaction = bp::base::NormalTransactionData{};
    REQUIRE(encode(packet) == golden_v975_normal_empty);

    bp::BinaryReader reader{golden_v975_normal_empty};
    auto back = bp::Serializer<PacketV975>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->transaction.index() == 0);
    REQUIRE(std::get<0>(back->transaction).actions.actions.empty());
}

// The 975 source is a switch, not a pair of presence bools: a container source
// puts its window id on the wire as a varint32 and writes no flags at all.
TEST_CASE("inventory-transaction v975 normal with a container action round-trips")
{
    bp::base::InventoryAction action;
    action.source.source_type = bp::InventorySourceType::CONTAINER_INVENTORY;
    action.source.container_id = static_cast<bp::ContainerID>(12);
    action.slot = 3;
    action.from_item = air_v975();
    action.to_item = stone_v975();

    PacketV975 packet;
    bp::base::NormalTransactionData normal;
    normal.actions.actions = std::vector<bp::base::InventoryAction>{action};
    packet.transaction = normal;
    REQUIRE(encode(packet) == golden_v975_normal_action);

    bp::BinaryReader reader{golden_v975_normal_action};
    auto back = bp::Serializer<PacketV975>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);

    const auto &actions = std::get<0>(back->transaction).actions.actions;
    REQUIRE(actions.size() == 1);
    REQUIRE(actions[0].source.container_id == static_cast<bp::ContainerID>(12));
    REQUIRE(actions[0].to_item.id == 1);
    REQUIRE(actions[0].to_item.block_runtime_id == 7);
    REQUIRE(actions[0].from_item.id == 0);  // air: nothing past the id was read
    REQUIRE(actions[0].from_item.user_data_buffer.empty());
}

TEST_CASE("inventory-transaction v975 use-item round-trips against the golden")
{
    bp::base::ItemUseInventoryTransaction use;
    use.action_type = bp::ItemUseInventoryTransaction::ActionType::PLACE;
    use.trigger_type = bp::ItemUseInventoryTransaction::TriggerType::PLAYER_INPUT;
    use.pos = {.x = 1, .y = 2, .z = 3};
    use.face = 4;
    use.slot = 5;
    use.item = air_v975();
    use.target_block_id = 9;

    PacketV975 packet;
    packet.transaction = use;
    REQUIRE(encode(packet) == golden_v975_use_item);

    bp::BinaryReader reader{golden_v975_use_item};
    auto back = bp::Serializer<PacketV975>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->transaction.index() == 2);
    const auto &use_back = std::get<2>(back->transaction);
    REQUIRE(use_back.pos.x == 1);
    REQUIRE(use_back.face == 4);
    REQUIRE(use_back.target_block_id == 9);
}

// The legacy slots ride on a non-zero request id, with nothing on the wire to
// mark them present.
TEST_CASE("inventory-transaction v975 legacy request id carries the set-item slots")
{
    PacketV975 packet;
    packet.legacy_request_id = 7;
    packet.legacy_set_item_slots = {
        {.container_enum = bp::ContainerEnumName::COMBINED_HOTBAR_AND_INVENTORY_CONTAINER, .slots = "\x03\x04"},
    };
    packet.transaction = bp::base::NormalTransactionData{};
    REQUIRE(encode(packet) == golden_v975_legacy_request);

    bp::BinaryReader reader{golden_v975_legacy_request};
    auto back = bp::Serializer<PacketV975>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->legacy_set_item_slots.size() == 1);
    REQUIRE(back->legacy_set_item_slots[0].slots == "\x03\x04");
    REQUIRE(std::get<0>(back->transaction).actions.actions.empty());
}
