#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("SetDifficultyPacket: id + round-trip of a single uvarint32 enum")
{
    STATIC_REQUIRE(bp::SetDifficultyPacket::Id == 60);

    bp::SetDifficultyPacket pkt;
    pkt.difficulty = bp::Difficulty::Normal;

    // generated by gophertunnel:
    // packet.SetDifficulty{Difficulty: 2}
    const std::vector<std::uint8_t> golden{
        0x02,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::SetDifficultyPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->difficulty == bp::Difficulty::Normal);
}
