#include <string>

#include <protocol/network.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ClientCacheMissResponse{Blobs: []protocol.CacheBlob{
// {Hash: 0x0102030405060708, Payload: []byte("chunk")}, {Hash: 300}}}
const std::string golden = bytes({
    0x02, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01, 0x05, 0x63, 0x68,
    0x75, 0x6e, 0x6b, 0x2c, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

// generated by gophertunnel: &packet.ClientCacheMissResponse{}
const std::string golden_empty = bytes({
    0x00,
});

}  // namespace

TEST_CASE("packet id is 136")
{
    STATIC_REQUIRE(bp::ClientCacheMissResponsePacket_<2168>::Id == 136);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 136>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 136>);
}

TEST_CASE("client-cache-miss-response round-trips against the golden")
{
    bp::ClientCacheMissResponsePacket_<2168> packet;
    packet.blobs.push_back({.blob_id = 0x0102030405060708ULL, .blob_data = "chunk"});
    packet.blobs.push_back({.blob_id = 300, .blob_data = ""});
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::ClientCacheMissResponsePacket_<2168>>(golden);
    REQUIRE(back.blobs.size() == 2);
    REQUIRE(back.blobs[0].blob_id == 0x0102030405060708ULL);
    REQUIRE(back.blobs[0].blob_data == "chunk");
    REQUIRE(back.blobs[1].blob_id == 300);
    REQUIRE(back.blobs[1].blob_data.empty());
}

TEST_CASE("an empty client-cache-miss-response is a lone zero count")
{
    const auto wire = encode(bp::ClientCacheMissResponsePacket_<2168>{});
    REQUIRE(wire == golden_empty);
    REQUIRE(decode<bp::ClientCacheMissResponsePacket_<2168>>(golden_empty).blobs.empty());
}

TEST_CASE("a blob payload past 127 bytes takes a two-byte length prefix")
{
    const std::string payload(200, 'x');

    bp::ClientCacheMissResponsePacket_<2168> packet;
    packet.blobs.push_back({.blob_id = 300, .blob_data = payload});
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 211);

    const auto back = decode<bp::ClientCacheMissResponsePacket_<2168>>(wire);
    REQUIRE(back.blobs.size() == 1);
    REQUIRE(back.blobs[0].blob_id == 300);
    REQUIRE(back.blobs[0].blob_data == payload);
}
