#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include <bedrock/protocol/actor.h>
#include <bedrock/protocol/common.h>
#include <bedrock/protocol/map.h>

#include "fixture.hpp"

namespace {

using Packet1001 = bp::ClientboundMapItemDataPacket_<1001>;
using Packet2168 = bp::ClientboundMapItemDataPacket_<2168>;

Packet1001 fill_v1001()
{
    Packet1001 packet;
    packet.map_id = bp::ActorUniqueID{1};
    packet.type = 2 | 4 | 8;
    packet.dimension = 0;
    packet.locked = true;
    packet.map_origin = {.x = 1, .y = 2, .z = 3};
    packet.map_ids = {bp::ActorUniqueID{7}};
    packet.scale = 4;
    packet.unique_ids = {
        {.type = bp::base::MapItemTrackedActor::Type::Entity, .key_entity_id = bp::ActorUniqueID{9}},
        {.type = bp::base::MapItemTrackedActor::Type::BlockEntity, .key_block_pos = {.x = 4, .y = 5, .z = 6}},
    };
    packet.decorations = {{.image = bp::base::MapDecoration::Type::MarkerRed,
                           .rotation = 3,
                           .x = 4,
                           .y = 5,
                           .label = "hi",
                           .color = bp::Color{0x04030201}}};
    packet.width = 2;
    packet.height = 2;
    packet.start_x = 0;
    packet.start_y = 0;
    packet.map_pixels = {1, 2, 3, 4};
    return packet;
}

Packet2168 fill_v2168()
{
    Packet2168 packet;
    packet.map_id = bp::ActorUniqueID{1};
    packet.dimension = 0;
    packet.locked = true;
    packet.map_origin = {.x = 1, .y = 2, .z = 3};
    packet.creation_map_ids = std::vector<bp::ActorUniqueID>{bp::ActorUniqueID{7}};
    packet.scale = 4;
    packet.unique_ids = std::vector<bp::v2168::MapItemTrackedActor::UniqueId>{
        {.type = bp::v2168::MapItemTrackedActor::Type::Entity, .key_entity_id = bp::ActorUniqueID{9}},
        {.type = bp::v2168::MapItemTrackedActor::Type::BlockEntity, .key_block_pos = bp::BlockPos{.x = 4, .y = 5, .z = 6}},
    };
    packet.decorations = std::vector<bp::v2168::MapDecoration>{{.image = bp::v2168::MapDecoration::Type::MarkerRed,
                                                                .rotation = 3,
                                                                .x = 4,
                                                                .y = 5,
                                                                .label = "hi",
                                                                .color = bp::Color{0x04030201}}};
    packet.width = 2;
    packet.height = 2;
    packet.start_x = 0;
    packet.start_y = 0;
    packet.map_pixels = std::vector<std::uint32_t>{1, 2, 3, 4};
    return packet;
}

// generated by gophertunnel:
// packet.ClientBoundMapItemData{MapID: 1, UpdateFlags: 2 | 4 | 8, Dimension: 0,
//   LockedMap: true, Origin: protocol.BlockPos{1, 2, 3}, Scale: 4,
//   MapsIncludedIn: []int64{7},
//   TrackedObjects: []protocol.MapTrackedObject{{Type: 0, EntityUniqueID: 9},
//     {Type: 1, BlockPosition: protocol.BlockPos{4, 5, 6}}},
//   Decorations: []protocol.MapDecoration{{Type: 2, Rotation: 3, X: 4, Y: 5, Label: "hi",
//     Colour: color.RGBA{R: 1, G: 2, B: 3, A: 4}}},
//   Width: 2, Height: 2, XOffset: 0, YOffset: 0,
//   Pixels: []color.RGBA{{R: 1}, {R: 2}, {R: 3}, {R: 4}}}
const std::string golden_v1001 = bytes({
    0x02, 0x0E, 0x00, 0x01, 0x02, 0x04, 0x06, 0x01, 0x0E, 0x04, 0x02, 0x00,
    0x00, 0x00, 0x00, 0x12, 0x01, 0x00, 0x00, 0x00, 0x08, 0x0A, 0x0C, 0x01,
    0x02, 0x03, 0x04, 0x05, 0x02, 0x68, 0x69, 0x81, 0x84, 0x8C, 0x20, 0x04,
    0x04, 0x00, 0x00, 0x04, 0x01, 0x02, 0x03, 0x04,
});

// generated by CloudburstMC Bedrock_v2168:
// ClientboundMapItemDataPacket{uniqueMapId: 1, dimensionId: 0, locked: true,
//   origin: (1, 2, 3), trackedEntityIds: [7], scale: 4,
//   trackedObjects: [MapTrackedObject(9), MapTrackedObject((4, 5, 6))],
//   decorations: [MapDecoration(2, 3, 4, 5, "hi", 0x04030201)],
//   width: 2, height: 2, xOffset: 0, yOffset: 0, colors: [1, 2, 3, 4]}
const std::string golden_v2168 = bytes({
    0x02, 0x00, 0x01, 0x02, 0x04, 0x06, 0x01, 0x01, 0x0E, 0x01, 0x04, 0x01,
    0x02, 0x00, 0x00, 0x00, 0x00, 0x01, 0x12, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x08, 0x0A, 0x0C, 0x01, 0x01, 0x02, 0x03, 0x04, 0x05, 0x02,
    0x68, 0x69, 0x01, 0x02, 0x03, 0x04, 0x01, 0x04, 0x01, 0x04, 0x01, 0x00,
    0x01, 0x00, 0x01, 0x04, 0x01, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00,
    0x03, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("ClientboundMapItemDataPacket: id")
{
    STATIC_REQUIRE(bp::ClientboundMapItemDataPacket_<975>::Id == 67);
    STATIC_REQUIRE(bp::ClientboundMapItemDataPacket_<1001>::Id == 67);
    STATIC_REQUIRE(bp::ClientboundMapItemDataPacket_<2168>::Id == 67);
}

TEST_CASE("ClientboundMapItemDataPacket: v1001 round-trip")
{
    REQUIRE(encode(fill_v1001()) == golden_v1001);

    const auto rt = decode<Packet1001>(golden_v1001);
    REQUIRE(rt.type == 14);
    REQUIRE(rt.map_ids.size() == 1);
    REQUIRE(rt.scale == 4);
    REQUIRE(rt.unique_ids.size() == 2);
    REQUIRE(rt.unique_ids[1].key_block_pos.z == 6);
    REQUIRE(rt.decorations.size() == 1);
    REQUIRE(rt.decorations[0].label == "hi");
    REQUIRE(rt.map_pixels.size() == 4);
}

TEST_CASE("ClientboundMapItemDataPacket: v2168 round-trip")
{
    REQUIRE(encode(fill_v2168()) == golden_v2168);

    const auto rt = decode<Packet2168>(golden_v2168);
    REQUIRE(rt.creation_map_ids.has_value());
    REQUIRE(rt.scale == 4);
    REQUIRE(rt.unique_ids.has_value());
    REQUIRE(rt.unique_ids->at(0).key_entity_id.has_value());
    REQUIRE_FALSE(rt.unique_ids->at(0).key_block_pos.has_value());
    REQUIRE(rt.decorations->at(0).label == "hi");
    REQUIRE(rt.map_pixels->size() == 4);
}

// The 1001 flags word gated every group at once; 2168 gives each an independent
// presence byte, so an all-absent 2168 body is six header bytes plus nine bare
// flags -- one per optional group, and exactly one byte each.
TEST_CASE("ClientboundMapItemDataPacket: an absent v2168 group is a single flag")
{
    Packet2168 packet;
    packet.map_id = bp::ActorUniqueID{0};

    const auto encoded = encode(packet);
    REQUIRE(encoded.size() == 6 + 9);
    REQUIRE(encoded == std::string(15, '\0'));
}

TEST_CASE("ClientboundMapItemDataPacket: a v1001 body does not decode as a v2168 one")
{
    REQUIRE(golden_v1001.size() != golden_v2168.size());

    // The dropped flags word slides every later field forward: 14 lands in dimension.
    const auto wrong = decode_partial<Packet2168>(golden_v1001);
    REQUIRE(wrong.dimension == 14);

    const auto other = decode_partial<Packet1001>(golden_v2168);
    REQUIRE(other.type == 0);
    REQUIRE(other.decorations.empty());
}
