#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("BlockActorDataPacket: id + round-trip with an NBT CompoundTag")
{
    STATIC_REQUIRE(bp::BlockActorDataPacket::Id == 56);

    bp::BlockActorDataPacket pkt;
    pkt.pos = {1, 2, 3};
    pkt.data.emplace(
        "levels", bp::Tag{bp::ListTag{bp::IntTag{1}, bp::IntTag{2}, bp::IntTag{3}}});

    // generated by gophertunnel:
    // packet.BlockActorData{Position: {1, 2, 3}, NBTData: {"levels": []int32{1, 2, 3}}}
    const std::vector<std::uint8_t> golden{
        0x02, 0x04, 0x06, 0x0A, 0x00, 0x09, 0x06, 0x6C, 0x65, 0x76, 0x65, 0x6C,
        0x73, 0x03, 0x06, 0x02, 0x04, 0x06, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::BlockActorDataPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->data.size() == 1);
    const auto &levels = rt->data.at("levels").get<bp::ListTag>();
    REQUIRE(levels.size() == 3);
    REQUIRE(levels[2].get<bp::IntTag>().value() == 3);
}
