#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ServerboundLoadingScreenPacket: id + round-trip with the START action")
{
    STATIC_REQUIRE(bp::ServerboundLoadingScreenPacket::Id == 312);

    bp::ServerboundLoadingScreenPacket pkt;
    pkt.type = bp::ServerboundLoadingScreenPacketType::StartLoadingScreen;
    pkt.loading_screen_id = static_cast<std::uint32_t>(42);

    // generated by gophertunnel:
    // packet.ServerBoundLoadingScreen{Type: 1, LoadingScreenID: protocol.Option(uint32(42))}
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x2A, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ServerboundLoadingScreenPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->type == bp::ServerboundLoadingScreenPacketType::StartLoadingScreen);
    REQUIRE(rt->loading_screen_id.has_value());
    REQUIRE(*rt->loading_screen_id == 42);
}
