#include <string>

#include <bedrock/protocol/item.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ClientStartItemCooldown{Category: "minecraft:shield",
// Duration: 300}
const std::string golden = bytes({
    0x10, 0x6d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3a, 0x73,
    0x68, 0x69, 0x65, 0x6c, 0x64, 0xd8, 0x04,
});

// generated by gophertunnel: &packet.ClientStartItemCooldown{Category: "", Duration: -1}
const std::string golden_negative = bytes({
    0x00, 0x01,
});

}  // namespace

TEST_CASE("packet id is 176")
{
    STATIC_REQUIRE(bp::PlayerStartItemCooldownPacket::Id == 176);
    STATIC_REQUIRE(bp::has_packet_v<1001, 176>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 176>);
}

TEST_CASE("player-start-item-cooldown round-trips against the golden")
{
    bp::PlayerStartItemCooldownPacket packet;
    packet.item_category = "minecraft:shield";
    packet.duration_ticks = 300;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::PlayerStartItemCooldownPacket>(golden);
    REQUIRE(back.item_category == "minecraft:shield");
    REQUIRE(back.duration_ticks == 300);
}

TEST_CASE("an empty category and a negative duration round-trip against the golden")
{
    bp::PlayerStartItemCooldownPacket packet;
    packet.item_category = "";
    packet.duration_ticks = -1;
    REQUIRE(encode(packet) == golden_negative);

    const auto back = decode<bp::PlayerStartItemCooldownPacket>(golden_negative);
    REQUIRE(back.item_category.empty());
    REQUIRE(back.duration_ticks == -1);
}

TEST_CASE("a category over 127 bytes takes a two-byte length prefix")
{
    bp::PlayerStartItemCooldownPacket packet;
    packet.item_category = std::string(200, 'a');
    packet.duration_ticks = 1;
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 203);

    const auto back = decode<bp::PlayerStartItemCooldownPacket>(wire);
    REQUIRE(back.item_category.size() == 200);
    REQUIRE(back.duration_ticks == 1);
}
