#include <string>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

namespace {

template <class T>
std::string encode(const T &value)
{
    std::string buffer;
    bp::BinaryWriter writer{buffer};
    bp::Serializer<T>::serialize(writer, value);
    return buffer;
}

std::string bytes(std::initializer_list<int> raw)
{
    std::string out;
    for (int b : raw) {
        out.push_back(static_cast<char>(b));
    }
    return out;
}

using PacketV975 = bp::LevelSoundEventPacket_<975>;
using PacketV1001 = bp::LevelSoundEventPacket_<1001>;

// Everything the two eras share, which is every field but the sound itself.
template <class Packet>
Packet sample()
{
    Packet packet;
    packet.pos = {.x = 1.0f, .y = 2.0f, .z = 3.0f};
    packet.data = -1;
    packet.actor_identifier = "minecraft:pig";
    packet.is_baby = true;
    packet.is_global = false;
    packet.actor = static_cast<bp::ActorUniqueID>(7);
    packet.fire_at_position = bp::Vec3{.x = 4.0f, .y = 5.0f, .z = 6.0f};
    return packet;
}

// The tail every era writes the same way, from the position onwards.
const std::string golden_tail = bytes({
    0x00, 0x00, 0x80, 0x3f, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x40, 0x40,
    0x01, 0x0d, 0x6d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3a,
    0x70, 0x69, 0x67, 0x01, 0x00, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x00, 0x00, 0x80, 0x40, 0x00, 0x00, 0xa0, 0x40, 0x00, 0x00,
    0xc0, 0x40,
});

// generated by gophertunnel at 6353c49^ (de090ae, the last pre-1.26.30 commit):
// packet.LevelSoundEvent{SoundType: 258, Position: mgl32.Vec3{1, 2, 3}, ExtraData: -1,
//   EntityType: "minecraft:pig", BabyMob: true, DisableRelativeVolume: false,
//   EntityUniqueID: 7, FireAtPosition: Option(mgl32.Vec3{4, 5, 6})}
const std::string golden_v975 = bytes({
    0x82, 0x02,
}) + golden_tail;

// generated by gophertunnel (654cd5f): the same packet with SoundType: "block.bell.hit".
// 993 replaced the ordinal with the sound's own name, so what BDS holds as a variant of
// legacy enum or string reaches the wire as a plain string either way.
const std::string golden_v1001 = bytes({
    0x0e, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2e, 0x62, 0x65, 0x6c, 0x6c, 0x2e,
    0x68, 0x69, 0x74,
}) + golden_tail;

}  // namespace

TEST_CASE("packet id is 123 at both eras")
{
    STATIC_REQUIRE(PacketV975::Id == 123);
    STATIC_REQUIRE(PacketV1001::Id == 123);
}

TEST_CASE("level-sound-event v975 round-trips against the golden")
{
    auto packet = sample<PacketV975>();
    packet.event_id = bp::LevelSoundEvent_<975>::BELL;
    REQUIRE(encode(packet) == golden_v975);

    bp::BinaryReader reader{golden_v975};
    auto back = bp::Serializer<PacketV975>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->event_id == bp::LevelSoundEvent_<975>::BELL);
    REQUIRE(back->data == -1);
    REQUIRE(back->actor_identifier == "minecraft:pig");
    REQUIRE(back->actor == static_cast<bp::ActorUniqueID>(7));
    REQUIRE(back->fire_at_position->z == 6.0f);
}

TEST_CASE("level-sound-event v1001 round-trips against the golden")
{
    auto packet = sample<PacketV1001>();
    packet.sound_event = "block.bell.hit";
    REQUIRE(encode(packet) == golden_v1001);

    bp::BinaryReader reader{golden_v1001};
    auto back = bp::Serializer<PacketV1001>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->sound_event == "block.bell.hit");
    REQUIRE(back->is_baby);
    REQUIRE_FALSE(back->is_global);
    REQUIRE(back->actor == static_cast<bp::ActorUniqueID>(7));
}

// Only the leading sound moved, so both eras share the rest of the body byte for byte.
TEST_CASE("the 993 change is confined to the leading sound field")
{
    REQUIRE(golden_v975.substr(2) == golden_v1001.substr(15));
}
