#include <string>

#include <bedrock/protocol/ability.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.UpdateAdventureSettings{NoPvM: true, NoMvP: false,
// ImmutableWorld: true, ShowNameTags: false, AutoJump: true}
const std::string golden = bytes({
    0x01, 0x00, 0x01, 0x00, 0x01,
});

}  // namespace

TEST_CASE("packet id is 188")
{
    STATIC_REQUIRE(bp::UpdateAdventureSettingsPacket_<2168>::Id == 188);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 188>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 188>);
}

TEST_CASE("adventure settings round-trip against the golden")
{
    bp::UpdateAdventureSettingsPacket_<2168> packet;
    packet.adventure_settings = {.no_pv_m = true,
                                 .no_mv_p = false,
                                 .immutable_world = true,
                                 .show_name_tags = false,
                                 .auto_jump = true};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::UpdateAdventureSettingsPacket_<2168>>(golden);
    REQUIRE(back.adventure_settings.no_pv_m);
    REQUIRE_FALSE(back.adventure_settings.no_mv_p);
    REQUIRE(back.adventure_settings.auto_jump);
}

TEST_CASE("all five flags are separate bytes, not a bitfield")
{
    REQUIRE(encode(bp::UpdateAdventureSettingsPacket_<2168>{}) == bytes({0, 0, 0, 0, 0}));
}
