#include <string>

#include <bedrock/protocol/party.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.PartyDestinationCookieResponse{Cookie: "party-cookie",
// Accepted: true}
const std::string golden = bytes({
    0x0c, 0x70, 0x61, 0x72, 0x74, 0x79, 0x2d, 0x63, 0x6f, 0x6f, 0x6b, 0x69,
    0x65, 0x01,
});

// generated by gophertunnel: &packet.PartyDestinationCookieResponse{Cookie: "",
// Accepted: false}
const std::string golden_declined = bytes({
    0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 350")
{
    STATIC_REQUIRE(bp::PartyDestinationCookieResponsePacket_<2168>::Id == 350);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 350>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 350>);
}

TEST_CASE("party destination cookie response round-trips against the golden")
{
    bp::PartyDestinationCookieResponsePacket_<2168> packet;
    packet.cookie = "party-cookie";
    packet.accepted = true;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::PartyDestinationCookieResponsePacket_<2168>>(golden);
    REQUIRE(back.cookie == "party-cookie");
    REQUIRE(back.accepted);
}

TEST_CASE("an empty cookie is a lone length prefix and the flag still follows")
{
    bp::PartyDestinationCookieResponsePacket_<2168> packet;
    packet.cookie = "";
    packet.accepted = false;
    REQUIRE(encode(packet) == golden_declined);

    const auto back = decode<bp::PartyDestinationCookieResponsePacket_<2168>>(golden_declined);
    REQUIRE(back.cookie.empty());
    REQUIRE_FALSE(back.accepted);
}

TEST_CASE("the cookie length prefix is a varint, not a byte")
{
    bp::PartyDestinationCookieResponsePacket_<2168> packet;
    packet.cookie = std::string(200, 'c');
    packet.accepted = true;
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 203);
    REQUIRE(static_cast<unsigned char>(wire[0]) == 0xc8);
    REQUIRE(static_cast<unsigned char>(wire[1]) == 0x01);

    const auto back = decode<bp::PartyDestinationCookieResponsePacket_<2168>>(wire);
    REQUIRE(back.cookie == std::string(200, 'c'));
    REQUIRE(back.accepted);
}
