#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ContainerOpenPacket: id + round-trip")
{
    STATIC_REQUIRE(bp::ContainerOpenPacket::Id == 46);

    bp::ContainerOpenPacket pkt;
    pkt.container_id = static_cast<bp::ContainerID>(1);
    pkt.type = bp::ContainerType::Container;
    pkt.pos = bp::BlockPos{10, 20, 30};
    pkt.entity_unique_id = static_cast<bp::ActorUniqueID>(-1);

    // generated by gophertunnel:
    // packet.ContainerOpen{WindowID: 1, ContainerType: 0,
    //   ContainerPosition: protocol.BlockPos{10, 20, 30},
    //   ContainerEntityUniqueID: -1}
    const std::vector<std::uint8_t> golden{
        0x01, 0x00, 0x14, 0x28, 0x3C, 0x01,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ContainerOpenPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->container_id == static_cast<bp::ContainerID>(1));
    REQUIRE(rt->type == bp::ContainerType::Container);
    REQUIRE(rt->pos.x == 10);
    REQUIRE(rt->entity_unique_id == static_cast<bp::ActorUniqueID>(-1));
}
