#include <string>

#include "fixture.hpp"

namespace {

using Packet1001 = bp::SetScorePacket_<1001>;
using Packet2168 = bp::SetScorePacket_<2168>;

Packet1001 fill_v1001_change()
{
    Packet1001 packet;
    packet.type = bp::ScorePacketType::CHANGE;
    packet.score_info = {
        {.scoreboard_id = {.raw_id = 1},
         .objective_name = "obj",
         .score_value = 5,
         .identity_type = bp::IdentityDefinition::Type::PLAYER,
         .player_id = {.actor_unique_id = 9}},
        {.scoreboard_id = {.raw_id = 2},
         .objective_name = "obj",
         .score_value = 6,
         .identity_type = bp::IdentityDefinition::Type::ENTITY,
         .entity_id = static_cast<bp::ActorUniqueID>(11)},
        {.scoreboard_id = {.raw_id = 3},
         .objective_name = "obj",
         .score_value = 7,
         .identity_type = bp::IdentityDefinition::Type::FAKE_PLAYER,
         .fake_player_name = "fake"},
    };
    return packet;
}

Packet2168 fill_v2168()
{
    Packet2168 packet;
    packet.score_info = {
        bp::v2168::RemoveScore{.action = bp::ScorePacketEntryAction::REMOVE,
                               .scoreboard_id = {.raw_id = 1},
                               .objective_name = "rm"},
        bp::v2168::ChangePlayerScore{.action = bp::ScorePacketEntryAction::CHANGE_PLAYER,
                                     .scoreboard_id = {.raw_id = 2},
                                     .objective_name = "obj",
                                     .score_value = 5,
                                     .player_id = {.actor_unique_id = 9}},
        bp::v2168::ChangeEntityScore{.action = bp::ScorePacketEntryAction::CHANGE_ENTITY,
                                     .scoreboard_id = {.raw_id = 3},
                                     .objective_name = "obj",
                                     .score_value = 6,
                                     .entity_id = static_cast<bp::ActorUniqueID>(11)},
        bp::v2168::ChangeFakePlayerScore{.action = bp::ScorePacketEntryAction::CHANGE_FAKE_PLAYER,
                                         .scoreboard_id = {.raw_id = 4},
                                         .objective_name = "obj",
                                         .score_value = 7,
                                         .fake_player_name = "fake"},
    };
    return packet;
}

// generated by gophertunnel:
// packet.SetScore{ActionType: packet.ScoreboardActionModify,
//   Entries: []protocol.ScoreboardEntry{
//     {EntryID: 1, ObjectiveName: "obj", Score: 5,
//      IdentityType: protocol.ScoreboardIdentityPlayer, EntityUniqueID: 9},
//     {EntryID: 2, ObjectiveName: "obj", Score: 6,
//      IdentityType: protocol.ScoreboardIdentityEntity, EntityUniqueID: 11},
//     {EntryID: 3, ObjectiveName: "obj", Score: 7,
//      IdentityType: protocol.ScoreboardIdentityFakePlayer, DisplayName: "fake"}}}
const std::string golden_v1001_change = bytes({
    0x00, 0x03, 0x02, 0x03, 0x6F, 0x62, 0x6A, 0x05, 0x00, 0x00, 0x00, 0x01,
    0x12, 0x04, 0x03, 0x6F, 0x62, 0x6A, 0x06, 0x00, 0x00, 0x00, 0x02, 0x16,
    0x06, 0x03, 0x6F, 0x62, 0x6A, 0x07, 0x00, 0x00, 0x00, 0x03, 0x04, 0x66,
    0x61, 0x6B, 0x65,
});

// generated by gophertunnel:
// packet.SetScore{ActionType: packet.ScoreboardActionRemove,
//   Entries: []protocol.ScoreboardEntry{{EntryID: 1, ObjectiveName: "rm", Score: 0}}}
const std::string golden_v1001_remove = bytes({
    0x01, 0x01, 0x02, 0x02, 0x72, 0x6D, 0x00, 0x00, 0x00, 0x00,
});

// generated by CloudburstMC Bedrock_v2168, with the restated action cased the way BDS
// spells it -- Cloudburst writes "remove" / "changeplayer" / ..., BDS cereal writes its
// verbatim member name, and BDS lower-cases before the lookup, so the case is free:
// SetScorePacket{infos: [ScoreInfo(1, "rm", 0), ScoreInfo(2, "obj", 5, PLAYER, 9),
//   ScoreInfo(3, "obj", 6, ENTITY, 11), ScoreInfo(4, "obj", 7, "fake")]}
const std::string golden_v2168 = bytes({
    0x04, 0x00, 0x06, 0x52, 0x65, 0x6D, 0x6F, 0x76, 0x65, 0x02, 0x01, 0x02,
    0x72, 0x6D, 0x01, 0x0C, 0x43, 0x68, 0x61, 0x6E, 0x67, 0x65, 0x50, 0x6C,
    0x61, 0x79, 0x65, 0x72, 0x04, 0x03, 0x6F, 0x62, 0x6A, 0x05, 0x00, 0x00,
    0x00, 0x12, 0x02, 0x0C, 0x43, 0x68, 0x61, 0x6E, 0x67, 0x65, 0x45, 0x6E,
    0x74, 0x69, 0x74, 0x79, 0x06, 0x03, 0x6F, 0x62, 0x6A, 0x06, 0x00, 0x00,
    0x00, 0x16, 0x03, 0x10, 0x43, 0x68, 0x61, 0x6E, 0x67, 0x65, 0x46, 0x61,
    0x6B, 0x65, 0x50, 0x6C, 0x61, 0x79, 0x65, 0x72, 0x08, 0x03, 0x6F, 0x62,
    0x6A, 0x07, 0x00, 0x00, 0x00, 0x04, 0x66, 0x61, 0x6B, 0x65,
});

}  // namespace

TEST_CASE("SetScorePacket: id")
{
    STATIC_REQUIRE(bp::SetScorePacket_<975>::Id == 108);
    STATIC_REQUIRE(bp::SetScorePacket_<1001>::Id == 108);
    STATIC_REQUIRE(bp::SetScorePacket_<2168>::Id == 108);
}

TEST_CASE("SetScorePacket: v1001 change round-trip")
{
    REQUIRE(encode(fill_v1001_change()) == golden_v1001_change);

    const auto rt = decode<Packet1001>(golden_v1001_change);
    REQUIRE(rt.type == bp::ScorePacketType::CHANGE);
    REQUIRE(rt.score_info.size() == 3);
    REQUIRE(rt.score_info[0].player_id.actor_unique_id == 9);
    REQUIRE(rt.score_info[2].fake_player_name == "fake");
    REQUIRE(rt.removed_score_info.empty());
}

TEST_CASE("SetScorePacket: v1001 remove round-trip")
{
    Packet1001 packet;
    packet.type = bp::ScorePacketType::REMOVE;
    packet.removed_score_info = {{.scoreboard_id = {.raw_id = 1}, .objective_name = "rm", .score_value = 0}};
    REQUIRE(encode(packet) == golden_v1001_remove);

    const auto rt = decode<Packet1001>(golden_v1001_remove);
    REQUIRE(rt.type == bp::ScorePacketType::REMOVE);
    REQUIRE(rt.score_info.empty());
    REQUIRE(rt.removed_score_info.size() == 1);
    REQUIRE(rt.removed_score_info[0].objective_name == "rm");
}

TEST_CASE("SetScorePacket: v2168 round-trip")
{
    REQUIRE(encode(fill_v2168()) == golden_v2168);

    const auto rt = decode<Packet2168>(golden_v2168);
    REQUIRE(rt.score_info.size() == 4);
    REQUIRE(rt.score_info[0].index() == 0);
    REQUIRE(std::get<0>(rt.score_info[0]).objective_name == "rm");
    REQUIRE(std::get<1>(rt.score_info[1]).player_id.actor_unique_id == 9);
    REQUIRE(std::get<2>(rt.score_info[2]).entity_id == static_cast<bp::ActorUniqueID>(11));
    REQUIRE(std::get<3>(rt.score_info[3]).fake_player_name == "fake");
}

// The 2168 remove case carries an optional objective name, which the 1001 form has
// no way to leave out.
TEST_CASE("SetScorePacket: a v2168 remove entry may drop its objective name")
{
    Packet2168 packet;
    packet.score_info = {bp::v2168::RemoveScore{.action = bp::ScorePacketEntryAction::REMOVE,
                                                .scoreboard_id = {.raw_id = 1},
                                                .objective_name = std::nullopt}};

    const auto encoded = encode(packet);

    Packet2168 present = packet;
    std::get<0>(present.score_info[0]).objective_name = "rm";
    REQUIRE(encode(present).size() == encoded.size() + 3);

    const auto rt = decode<Packet2168>(encoded);
    REQUIRE_FALSE(std::get<0>(rt.score_info[0]).objective_name.has_value());
}

// 1001 spent one action byte on the whole packet; 2168 moved it into every entry and
// restated it as a name-coded string, so the leading byte means different things and
// neither body survives the other's reader.
TEST_CASE("SetScorePacket: a v1001 body does not decode as a v2168 one")
{
    const auto wrong = decode_partial<Packet2168>(golden_v1001_change);
    REQUIRE(wrong.score_info.empty());

    const auto other = decode_partial<Packet1001>(golden_v2168);
    REQUIRE(other.score_info.empty());
    REQUIRE(other.removed_score_info.empty());
}
