#include <string>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

namespace {

template <class T>
std::string encode(const T &value)
{
    std::string buffer;
    bp::BinaryWriter writer{buffer};
    bp::Serializer<T>::serialize(writer, value);
    return buffer;
}

std::string bytes(std::initializer_list<int> raw)
{
    std::string out;
    for (int b : raw) {
        out.push_back(static_cast<char>(b));
    }
    return out;
}

using PacketV975 = bp::GraphicsOverrideParameterPacket_<975>;
using PacketV1001 = bp::GraphicsOverrideParameterPacket_<1001>;

// Everything but the player id, which only exists at 1001.
template <class Packet>
Packet sample()
{
    Packet packet;
    packet.keyframes[0.5f] = bp::Vec3{.x = 1.0f, .y = 2.0f, .z = 3.0f};
    packet.float_value = 0.25f;
    packet.biome_id = "plains";
    packet.parameter_id = bp::GraphicsOverrideParameterType::WAVES_DEPTH;
    packet.reset_parameter = true;
    return packet;
}

// generated by gophertunnel at 6353c49^ (de090ae, the last pre-1.26.30 commit):
// packet.GraphicsOverrideParameter{Values: []protocol.ParameterKeyframeValue{{Time: 0.5,
//   Value: mgl32.Vec3{1, 2, 3}}}, FloatValue: Option[float32](0.25),
//   BiomeIdentifier: "plains", ParameterType: GraphicsOverrideParameterTypeWavesDepth,
//   Reset: true}
const std::string golden_v975 = bytes({
    0x01,                    // keyframes: count = 1 (uvarint32)
    0x00, 0x00, 0x00, 0x3f,  //   [0] key = 0.5f
    0x00, 0x00, 0x80, 0x3f,  //   [0] value.x = 1.0f
    0x00, 0x00, 0x00, 0x40,  //   [0] value.y = 2.0f
    0x00, 0x00, 0x40, 0x40,  //   [0] value.z = 3.0f
    0x01, 0x00, 0x00, 0x80, 0x3e,  // float_value present, 0.25f
    0x00,                    // vec3_value absent
    0x06, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x73,  // biome_id = "plains"
    0x0d,                    // parameter_id = WAVES_DEPTH (uint8)
    0x01,                    // reset_parameter = true
});

// generated by gophertunnel (654cd5f): the same packet with 990's player id, which
// lands between the biome id and the parameter id rather than at the end.
const std::string golden_v1001 = bytes({
    0x01,                    // keyframes: count = 1 (uvarint32)
    0x00, 0x00, 0x00, 0x3f,  //   [0] key = 0.5f
    0x00, 0x00, 0x80, 0x3f,  //   [0] value.x = 1.0f
    0x00, 0x00, 0x00, 0x40,  //   [0] value.y = 2.0f
    0x00, 0x00, 0x40, 0x40,  //   [0] value.z = 3.0f
    0x01, 0x00, 0x00, 0x80, 0x3e,  // float_value present, 0.25f
    0x00,                    // vec3_value absent
    0x06, 0x70, 0x6c, 0x61, 0x69, 0x6e, 0x73,  // biome_id = "plains"
    0x01,                    // player_id present
    0x05, 0x73, 0x74, 0x65, 0x76, 0x65,        //   = "steve"
    0x0d,                    // parameter_id = WAVES_DEPTH (uint8)
    0x01,                    // reset_parameter = true
});

}  // namespace

TEST_CASE("packet id is 331 at both eras")
{
    STATIC_REQUIRE(PacketV975::Id == 331);
    STATIC_REQUIRE(PacketV1001::Id == 331);
}

TEST_CASE("graphics-override-parameter v975 round-trips against the golden")
{
    REQUIRE(encode(sample<PacketV975>()) == golden_v975);

    bp::BinaryReader reader{golden_v975};
    auto back = bp::Serializer<PacketV975>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->keyframes.size() == 1);
    REQUIRE(back->keyframes.at(0.5f).z == 3.0f);
    REQUIRE(back->float_value == 0.25f);
    REQUIRE_FALSE(back->vec3_value.has_value());
    REQUIRE(back->biome_id == "plains");
    REQUIRE(back->parameter_id == bp::GraphicsOverrideParameterType::WAVES_DEPTH);
    REQUIRE(back->reset_parameter);
}

TEST_CASE("graphics-override-parameter v1001 round-trips against the golden")
{
    auto packet = sample<PacketV1001>();
    packet.player_id = "steve";
    REQUIRE(encode(packet) == golden_v1001);

    bp::BinaryReader reader{golden_v1001};
    auto back = bp::Serializer<PacketV1001>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->player_id == "steve");
    REQUIRE(back->parameter_id == bp::GraphicsOverrideParameterType::WAVES_DEPTH);
    REQUIRE(back->reset_parameter);
}

// A per-player override leaves the id absent, which costs one byte.
TEST_CASE("graphics-override-parameter v1001 omits an absent player id")
{
    auto packet = sample<PacketV1001>();
    REQUIRE(encode(packet) == golden_v975.substr(0, 30) + bytes({0x00}) + golden_v975.substr(30));
}

// 990 inserted the field ahead of the parameter id rather than appending it, so the
// two goldens share a prefix and a suffix.
TEST_CASE("the 990 player id is an insertion, not an append")
{
    const std::string player = bytes({0x01, 0x05, 0x73, 0x74, 0x65, 0x76, 0x65});
    REQUIRE(golden_v1001 == golden_v975.substr(0, 30) + player + golden_v975.substr(30));
}
