#include <string>

#include <bedrock/protocol/pack.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ResourcePackChunkRequest{
// UUID: "0575c61f-a5da-4b7f-9961-ffda2908861e_1.0.0", ChunkIndex: 300}
const std::string golden = bytes({
    0x2a, 0x30, 0x35, 0x37, 0x35, 0x63, 0x36, 0x31, 0x66, 0x2d, 0x61, 0x35,
    0x64, 0x61, 0x2d, 0x34, 0x62, 0x37, 0x66, 0x2d, 0x39, 0x39, 0x36, 0x31,
    0x2d, 0x66, 0x66, 0x64, 0x61, 0x32, 0x39, 0x30, 0x38, 0x38, 0x36, 0x31,
    0x65, 0x5f, 0x31, 0x2e, 0x30, 0x2e, 0x30, 0x2c, 0x01, 0x00, 0x00,
});

// generated by gophertunnel: &packet.ResourcePackChunkRequest{UUID: "", ChunkIndex: 0}
const std::string golden_empty = bytes({
    0x00, 0x00, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 84")
{
    STATIC_REQUIRE(bp::ResourcePackChunkRequestPacket_<2168>::Id == 84);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 84>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 84>);
}

TEST_CASE("resource-pack chunk request round-trips against the golden")
{
    bp::ResourcePackChunkRequestPacket_<2168> packet;
    packet.resource_name = "0575c61f-a5da-4b7f-9961-ffda2908861e_1.0.0";
    packet.chunk = 300;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::ResourcePackChunkRequestPacket_<2168>>(golden);
    REQUIRE(back.resource_name == "0575c61f-a5da-4b7f-9961-ffda2908861e_1.0.0");
    REQUIRE(back.chunk == 300);
}

TEST_CASE("the chunk index keeps its four bytes when it is zero")
{
    bp::ResourcePackChunkRequestPacket_<2168> packet;
    packet.resource_name = "";
    packet.chunk = 0;
    REQUIRE(encode(packet) == golden_empty);

    const auto back = decode<bp::ResourcePackChunkRequestPacket_<2168>>(golden_empty);
    REQUIRE(back.resource_name.empty());
    REQUIRE(back.chunk == 0);
}

TEST_CASE("the resource name's length prefix is a varint")
{
    bp::ResourcePackChunkRequestPacket_<2168> packet;
    packet.resource_name = std::string(200, 'a');
    packet.chunk = 7;
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 206);

    const auto back = decode<bp::ResourcePackChunkRequestPacket_<2168>>(wire);
    REQUIRE(back.resource_name.size() == 200);
    REQUIRE(back.chunk == 7);
}
