#include <cstdint>
#include <string>
#include <vector>

#include "fixture.hpp"

namespace {

// Golden derived from gophertunnel's ServerBoundDiagnostics.Marshal: nine
// io.Float32 (fixed LE), then protocol.Slice over MemoryCategoryCounter,
// EntityDiagnosticTimingInfo and SystemDiagnosticTimingInfo (each a varuint32
// count then per-element Marshal). io.Uint8 is one byte, io.Uint64 fixed LE,
// io.String a varuint32-length-prefixed string.
const std::string golden_base = bytes({
    0x00, 0x00, 0x70, 0x42, 0x00, 0x00, 0x80, 0x3f, 0x00, 0x00, 0x00, 0x40,
    0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x80, 0x40, 0x00, 0x00, 0xa0, 0x40,
    0x00, 0x00, 0xc0, 0x40, 0x00, 0x00, 0xe0, 0x40, 0x00, 0x00, 0x00, 0x41,
    0x01, 0x02, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x06,
    0x5a, 0x6f, 0x6d, 0x62, 0x69, 0x65, 0x10, 0x6d, 0x69, 0x6e, 0x65, 0x63,
    0x72, 0x61, 0x66, 0x74, 0x3a, 0x7a, 0x6f, 0x6d, 0x62, 0x69, 0x65, 0xf4,
    0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x32, 0x01, 0x07, 0x50, 0x68,
    0x79, 0x73, 0x69, 0x63, 0x73, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0xfa, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x19,
});

// The 978 addition, gated at the 1001 snapshot: a trailing protocol.Slice over
// ScopeDataSummary -- io.String label + io.String indentation + three io.Uint64.
const std::string golden_whisker = bytes({
    0x01, 0x05, 0x46, 0x72, 0x61, 0x6d, 0x65, 0x02, 0x20, 0x20, 0x84, 0x03,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x58, 0x02, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x2c, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

const std::string golden = golden_base + golden_whisker;

// TODO: confirm against BDS. CloudburstMC writes the system categories as a bare
// varuint32 count with no presence flag; the r26_u4 dump marks the member optional,
// which is a leading flag byte. No r26_u4 headers exist to break the tie, so the
// leading 0x01 below is patched in and the rest is the codec's own output.
// generated by CloudburstMC Bedrock_v2168:
// ServerboundDiagnosticsPacket{systemCategories: [SystemCategory("Movement", 3)]}
const std::string golden_system_categories = bytes({
    0x01,  // TODO: patched, confirm against BDS
    0x01, 0x08, 0x4d, 0x6f, 0x76, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x03, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

const std::string golden_v2168 = golden_base + golden_system_categories + golden_whisker;

template <class Packet>
void fill_base(Packet &packet)
{
    packet.avg_fps = 60.0f;
    packet.avg_server_sim_tick_time_ms = 1.0f;
    packet.avg_client_sim_tick_time_ms = 2.0f;
    packet.avg_begin_frame_time_ms = 3.0f;
    packet.avg_input_time_ms = 4.0f;
    packet.avg_render_time_ms = 5.0f;
    packet.avg_end_frame_time_ms = 6.0f;
    packet.avg_remainder_time_percent = 7.0f;
    packet.avg_unaccounted_time_percent = 8.0f;
    packet.memory_category_values.push_back({.category = bp::MemoryCategory::ACTOR, .current_bytes = 1024});
    packet.entity_diagnostics.push_back(
        {.display_name = "Zombie", .entity = "minecraft:zombie", .time_in_ns = 500, .percent_of_total = 50});
    packet.system_diagnostics.push_back(
        {.display_name = "Physics", .system_index = 3, .time_in_ns = 250, .percent_of_total = 25});
}

}  // namespace

TEST_CASE("packet id is 315")
{
    STATIC_REQUIRE(bp::ServerboundDiagnosticsPacket_<975>::Id == 315);
    STATIC_REQUIRE(bp::ServerboundDiagnosticsPacket_<1001>::Id == 315);
    STATIC_REQUIRE(bp::ServerboundDiagnosticsPacket_<2168>::Id == 315);
}

TEST_CASE("serverbound-diagnostics round-trips against the golden")
{
    using Packet = bp::ServerboundDiagnosticsPacket_<1001>;

    Packet packet;
    fill_base(packet);
    packet.whisker_scopes.push_back({.label = "Frame",
                                     .indentation = "  ",
                                     .total_high_cost_ns = 900,
                                     .total_mid_cost_ns = 600,
                                     .total_low_cost_ns = 300});
    REQUIRE(encode(packet) == golden);

    const auto back = decode<Packet>(golden);
    REQUIRE(back.avg_fps == 60.0f);
    REQUIRE(back.memory_category_values.size() == 1);
    REQUIRE(back.memory_category_values[0].category == bp::MemoryCategory::ACTOR);
    REQUIRE(back.memory_category_values[0].current_bytes == 1024);
    REQUIRE(back.entity_diagnostics.size() == 1);
    REQUIRE(back.entity_diagnostics[0].entity == "minecraft:zombie");
    REQUIRE(back.system_diagnostics.size() == 1);
    REQUIRE(back.system_diagnostics[0].system_index == 3);
    REQUIRE(back.whisker_scopes.size() == 1);
    REQUIRE(back.whisker_scopes[0].label == "Frame");
    REQUIRE(back.whisker_scopes[0].total_high_cost_ns == 900);
    REQUIRE(back.whisker_scopes[0].total_mid_cost_ns == 600);
    REQUIRE(back.whisker_scopes[0].total_low_cost_ns == 300);
}

TEST_CASE("serverbound-diagnostics v2168 form round-trips against the golden")
{
    using Packet = bp::ServerboundDiagnosticsPacket_<2168>;

    Packet packet;
    fill_base(packet);
    packet.system_categories = std::vector<bp::SystemCategory>{{.category_name = "Movement", .system_index = 3}};
    packet.whisker_scopes.push_back({.label = "Frame",
                                     .indentation = "  ",
                                     .total_high_cost_ns = 900,
                                     .total_mid_cost_ns = 600,
                                     .total_low_cost_ns = 300});
    REQUIRE(encode(packet) == golden_v2168);

    const auto back = decode<Packet>(golden_v2168);
    REQUIRE(back.system_categories.has_value());
    REQUIRE(back.system_categories->size() == 1);
    REQUIRE((*back.system_categories)[0].category_name == "Movement");
    REQUIRE((*back.system_categories)[0].system_index == 3);
    REQUIRE(back.whisker_scopes.size() == 1);
    REQUIRE(back.whisker_scopes[0].label == "Frame");
}

TEST_CASE("absent system categories are a lone flag ahead of the whisker scopes")
{
    using Packet = bp::ServerboundDiagnosticsPacket_<2168>;

    Packet packet;
    fill_base(packet);
    REQUIRE(encode(packet) == golden_base + bytes({0x00, 0x00}));
}

// The categories land between the system diagnostics and the whisker scopes, so
// every byte of the tail shifts and neither form reads the other's bytes.
TEST_CASE("a v1001 diagnostics body does not decode as a v2168 one")
{
    REQUIRE(golden != golden_v2168);
    REQUIRE(rejects<bp::ServerboundDiagnosticsPacket_<2168>>(golden));
    REQUIRE(rejects<bp::ServerboundDiagnosticsPacket_<1001>>(golden_v2168));
}

TEST_CASE("before v1001 the whisker scopes are absent from the wire")
{
    using Packet = bp::ServerboundDiagnosticsPacket_<975>;

    Packet packet;
    fill_base(packet);
    REQUIRE(encode(packet) == golden_base);

    const auto back = decode<Packet>(golden_base);
    REQUIRE(back.system_diagnostics.size() == 1);
    REQUIRE(back.system_diagnostics[0].display_name == "Physics");
}
