#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

namespace {

template <typename T>
std::vector<std::uint8_t> encode(const T &value)
{
    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, value);
    return buf;
}

}  // namespace

TEST_CASE("ClientboundAttributeLayerSyncPacket: id matches CloudburstMC v975")
{
    STATIC_REQUIRE(bp::ClientboundAttributeLayerSyncPacket::Id == 345);
}

TEST_CASE("ClientboundAttributeLayerSyncPacket: case 1 UpdateAttributeLayerSettings")
{
    bp::ClientboundAttributeLayerSyncPacket pkt;
    bp::UpdateAttributeLayerSettingsData inner;
    inner.layer_name = "wet";
    inner.layer_dimension_id = static_cast<bp::DimensionType>(0);
    inner.attribute_layer_settings = bp::AttributeLayerSettings{10, 0.5f, true, false};
    pkt.data = inner;

    // generated by gophertunnel:
    // packet.ClientBoundAttributeLayerSync{
    //   PayloadType: protocol.AttributeLayerPayloadTypeUpdateSettings,
    //   LayerName: "wet", DimensionID: 0,
    //   Settings: protocol.AttributeLayerSettings{
    //       Priority: 10, FloatWeight: 0.5, Enabled: true, TransitionsPaused: false}}
    const std::vector<std::uint8_t> golden{
        0x01, 0x03, 0x77, 0x65, 0x74, 0x00, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x3F, 0x01, 0x00,
    };

    REQUIRE(encode(pkt) == golden);

    bp::BinaryReader in{golden};
    auto rt = bp::deserialize<bp::ClientboundAttributeLayerSyncPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->data.index() == 1);
    const auto &settings = std::get<bp::UpdateAttributeLayerSettingsData>(rt->data);
    REQUIRE(settings.layer_name == "wet");
    REQUIRE(settings.attribute_layer_settings.priority == 10);
    REQUIRE(settings.attribute_layer_settings.weight == 0.5f);
    REQUIRE(settings.attribute_layer_settings.enabled);
}

TEST_CASE("ClientboundAttributeLayerSyncPacket: case 3 RemoveEnvironmentAttributes")
{
    bp::ClientboundAttributeLayerSyncPacket pkt;
    bp::RemoveEnvironmentAttributesData inner;
    inner.layer_name = "wet";
    inner.layer_dimension_id = static_cast<bp::DimensionType>(1);
    inner.attributes = {"foo", "bar"};
    pkt.data = inner;

    // generated by gophertunnel:
    // packet.ClientBoundAttributeLayerSync{
    //   PayloadType: protocol.AttributeLayerPayloadTypeRemoveEnvironment,
    //   LayerName: "wet", DimensionID: 1, RemoveAttributeNames: {"foo", "bar"}}
    const std::vector<std::uint8_t> golden{
        0x03, 0x03, 0x77, 0x65, 0x74, 0x02, 0x02, 0x03, 0x66, 0x6F, 0x6F, 0x03,
        0x62, 0x61, 0x72,
    };

    REQUIRE(encode(pkt) == golden);

    bp::BinaryReader in{golden};
    auto rt = bp::deserialize<bp::ClientboundAttributeLayerSyncPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->data.index() == 3);
    const auto &rm = std::get<bp::RemoveEnvironmentAttributesData>(rt->data);
    REQUIRE(rm.layer_name == "wet");
    REQUIRE(rm.attributes.size() == 2);
    REQUIRE(rm.attributes[0] == "foo");
}
