#include <string>

#include <bedrock/protocol/structure.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.CurrentStructureFeature{CurrentFeature:
// "minecraft:ancient_city"}
const std::string golden = bytes({
    0x16, 0x6d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3a, 0x61,
    0x6e, 0x63, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x63, 0x69, 0x74, 0x79,
});

// generated by gophertunnel: &packet.CurrentStructureFeature{CurrentFeature: ""}
const std::string golden_empty = bytes({
    0x00,
});

}  // namespace

TEST_CASE("packet id is 314")
{
    STATIC_REQUIRE(bp::CurrentStructureFeaturePacket_<2168>::Id == 314);
    STATIC_REQUIRE(bp::has_packet_v<1001, 314>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 314>);
}

TEST_CASE("current-structure-feature round-trips against the golden")
{
    bp::CurrentStructureFeaturePacket_<2168> packet;
    packet.current_structure_feature = "minecraft:ancient_city";
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::CurrentStructureFeaturePacket_<2168>>(golden);
    REQUIRE(back.current_structure_feature == "minecraft:ancient_city");
}

TEST_CASE("a player in no structure is a lone length prefix")
{
    bp::CurrentStructureFeaturePacket_<2168> packet;
    REQUIRE(encode(packet) == golden_empty);
    REQUIRE(decode<bp::CurrentStructureFeaturePacket_<2168>>(golden_empty).current_structure_feature.empty());
}

TEST_CASE("the feature name's length prefix is a varint, not a byte")
{
    bp::CurrentStructureFeaturePacket_<2168> packet;
    packet.current_structure_feature = std::string(200, 'a');
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 202);
    REQUIRE(static_cast<unsigned char>(wire[0]) == 0xc8);
    REQUIRE(static_cast<unsigned char>(wire[1]) == 0x01);
    REQUIRE(decode<bp::CurrentStructureFeaturePacket_<2168>>(wire).current_structure_feature ==
            packet.current_structure_feature);
}
