#include <type_traits>
#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("StartGamePacket: id")
{
    STATIC_REQUIRE(bp::StartGamePacket::Id == 11);
}

TEST_CASE("StartGamePacket: LevelSettings forks at known wire breakpoints")
{
    // Adjacent versions on either side of a known field gate:
    // seed widens from varint32 to uint64 at 503, is_hardcore and
    // editor_world_type land at 671, and ServerConfigurationJoinInfo
    // replaces the flat telemetry id quartet at 924.
    STATIC_REQUIRE(std::is_same_v<bp::LevelSettings_<502>, bp::LevelSettings_<466>>);
    STATIC_REQUIRE(!std::is_same_v<bp::LevelSettings_<502>, bp::LevelSettings_<503>>);
    STATIC_REQUIRE(!std::is_same_v<bp::LevelSettings_<670>, bp::LevelSettings_<671>>);
    STATIC_REQUIRE(!std::is_same_v<bp::LevelSettings_<923>, bp::LevelSettings_<924>>);
}

TEST_CASE("StartGamePacket: v975 baseline round-trip")
{
    bp::StartGamePacket pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = static_cast<bp::LevelSeed64>(12345);
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.is_hardcore = false;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.editor_world_type = bp::EditorWorldType::NonEditor;
    s.is_created_in_editor = false;
    s.is_exported_from_editor = false;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.persona_disabled = false;
    s.custom_skins_disabled = false;
    s.emote_chat_muted = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;
    s.chat_restriction_level = bp::ChatRestrictionLevel::None;
    s.disable_player_interactions = false;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";
    pkt.player_property_data = bp::CompoundTag{};
    pkt.server_block_type_registry_checksum = 0;
    pkt.world_template_id = bp::UUID{};
    pkt.server_enabled_client_side_generation = false;
    pkt.block_network_ids_are_hashes = false;
    pkt.network_permissions = bp::NetworkPermissions{false};
    pkt.server_configuration_join_info = std::nullopt;
    pkt.server_telemetry_data = bp::ServerTelemetryData{};

    // generated by gophertunnel:
    // packet.StartGame{EntityUniqueID: 1, EntityRuntimeID: 1, PlayerGameMode: 0, PlayerPosition: {0, 64, 0},
    //   WorldSeed: 12345, Dimension: 0, Generator: 1, WorldGameMode: 0, Difficulty: 1, WorldSpawn: {0, -32, 0},
    //   AchievementsDisabled: true, EditorWorldType: 0, MultiPlayerGame: true, LANBroadcastEnabled: true,
    //   CommandsEnabled: true, PlayerPermissions: 1, ServerChunkTickRadius: 4, BaseGameVersion: "1.21.0",
    //   LevelID: "leveltest", WorldName: "Test World", PlayerMovementSettings: {RewindHistorySize: 0},
    //   MultiPlayerCorrelationID: "corr", ServerAuthoritativeInventory: true, GameVersion: "1.21.0",
    //   PropertyData: map[string]any{}}
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x39,
        0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
        0x00, 0x00, 0x02, 0x00, 0x3F, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
        0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x09, 0x6C, 0x65, 0x76, 0x65, 0x6C, 0x74, 0x65, 0x73, 0x74, 0x0A,
        0x54, 0x65, 0x73, 0x74, 0x20, 0x57, 0x6F, 0x72, 0x6C, 0x64, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x04, 0x63, 0x6F, 0x72, 0x72, 0x01, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E,
        0x30, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->level_id == "leveltest");
    REQUIRE(rt->level_name == "Test World");
    REQUIRE(rt->settings.seed == static_cast<bp::LevelSeed64>(12345));
    REQUIRE(rt->settings.generator == bp::GeneratorType::Overworld);
    REQUIRE(rt->settings.default_permissions == bp::PlayerPermissionLevel::Member);
    REQUIRE(rt->settings.nether_type == bp::NetherWorldType::Normal);
    REQUIRE(rt->multiplayer_correlation_id == "corr");
    REQUIRE_FALSE(rt->server_configuration_join_info.has_value());
}

TEST_CASE("StartGamePacket: v419 baseline round-trip")
{
    // v419 (1.16.100) introduced Experiments and the lone
    // ServerAuthoritativeMovementMode varint (which the v428 struct then
    // absorbs into SyncedPlayerMovementSettings). Value 0 (Client) encodes
    // identically as signed-zigzag varint (CloudburstMC, our DSL) or as
    // unsigned varint (what gophertunnel-at-v419 emits) -- both produce 0x00.
    bp::StartGamePacket_<419> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = 12345;
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<419>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.override_force_experimental_gameplay_flag = std::nullopt;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.authoritative_movement_mode = 0;
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.items = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;

    // generated by gophertunnel @cc6c432
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF2,
        0xC0, 0x01, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x02, 0x00, 0xE0, 0xFF,
        0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x04, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32,
        0x31, 0x2E, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x09, 0x6C, 0x65, 0x76, 0x65, 0x6C, 0x74, 0x65, 0x73, 0x74, 0x0A,
        0x54, 0x65, 0x73, 0x74, 0x20, 0x57, 0x6F, 0x72, 0x6C, 0x64, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x04, 0x63, 0x6F, 0x72, 0x72, 0x01,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<419>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
}

TEST_CASE("StartGamePacket: v428 baseline round-trip")
{
    // v428 (1.16.210) replaced the lone ServerAuthoritativeMovementMode varint
    // with SyncedPlayerMovementSettings (movement type + rewind history +
    // server-auth block breaking). EduSharedUriResource hasn't landed (v465).
    bp::StartGamePacket_<428> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = 12345;
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<428>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.override_force_experimental_gameplay_flag = std::nullopt;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings_<428>{0, 0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.items = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;

    // generated by gophertunnel @44101ba
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF2,
        0xC0, 0x01, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x02, 0x00, 0xE0, 0xFF,
        0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x04, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32,
        0x31, 0x2E, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x09, 0x6C, 0x65, 0x76, 0x65, 0x6C, 0x74, 0x65, 0x73, 0x74, 0x0A,
        0x54, 0x65, 0x73, 0x74, 0x20, 0x57, 0x6F, 0x72, 0x6C, 0x64, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x04, 0x63, 0x6F, 0x72, 0x72, 0x01,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<428>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
}

TEST_CASE("StartGamePacket: v465 baseline round-trip")
{
    // v465 (1.17.30) introduced server_version (GameVersion) and
    // edu_shared_uri_resource. server_block_type_registry_checksum hasn't
    // landed (v475).
    bp::StartGamePacket_<465> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = 12345;
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<465>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings_<465>{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.items = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";

    // generated by gophertunnel @abce8bf
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF2,
        0xC0, 0x01, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x02, 0x00, 0xE0, 0xFF,
        0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x04, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32,
        0x31, 0x2E, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x09, 0x6C, 0x65, 0x76, 0x65, 0x6C, 0x74, 0x65, 0x73,
        0x74, 0x0A, 0x54, 0x65, 0x73, 0x74, 0x20, 0x57, 0x6F, 0x72, 0x6C, 0x64,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x04, 0x63, 0x6F, 0x72, 0x72, 0x01, 0x06, 0x31,
        0x2E, 0x32, 0x31, 0x2E, 0x30,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<465>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->server_version == "1.21.0");
}

TEST_CASE("StartGamePacket: v475 baseline round-trip")
{
    // v475 (1.18.0) added server_block_type_registry_checksum at the tail.
    // WorldSeed is still Varint32 (widens to Uint64 at v503).
    bp::StartGamePacket_<475> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = 12345;
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<475>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings_<475>{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.items = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";
    pkt.server_block_type_registry_checksum = 0;

    // generated by gophertunnel @212f6f7
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xF2,
        0xC0, 0x01, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00, 0x02, 0x00, 0xE0, 0xFF,
        0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x04, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32,
        0x31, 0x2E, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x09, 0x6C, 0x65, 0x76, 0x65, 0x6C, 0x74, 0x65, 0x73,
        0x74, 0x0A, 0x54, 0x65, 0x73, 0x74, 0x20, 0x57, 0x6F, 0x72, 0x6C, 0x64,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x04, 0x63, 0x6F, 0x72, 0x72, 0x01, 0x06, 0x31,
        0x2E, 0x32, 0x31, 0x2E, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<475>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->settings.seed == 12345);
}

TEST_CASE("StartGamePacket: v503 baseline round-trip")
{
    // v503 (1.18.30) is the WorldSeed widening point: it goes from Varint32
    // (3 bytes for 12345) to Uint64 (8 bytes). PropertyData NBT and
    // WorldTemplateID UUID don't land until v527.
    bp::StartGamePacket_<503> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = static_cast<bp::LevelSeed64>(12345);
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<503>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings_<503>{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.items = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";
    pkt.server_block_type_registry_checksum = 0;

    // generated by gophertunnel @2cbb27a
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x39,
        0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
        0x00, 0x02, 0x00, 0xE0, 0xFF, 0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
        0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x6C, 0x65, 0x76,
        0x65, 0x6C, 0x74, 0x65, 0x73, 0x74, 0x0A, 0x54, 0x65, 0x73, 0x74, 0x20,
        0x57, 0x6F, 0x72, 0x6C, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x63, 0x6F,
        0x72, 0x72, 0x01, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<503>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
}

TEST_CASE("StartGamePacket: v527 baseline round-trip")
{
    // v527 (1.19.0) added PropertyData NBT compound and WorldTemplateID UUID
    // at the tail of the packet. EditorWorld doesn't land until v534 (per
    // CloudburstMC); persona / customSkins / chatRestriction / etc. are v544+.
    bp::StartGamePacket_<527> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = static_cast<bp::LevelSeed64>(12345);
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<527>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings_<527>{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.items = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";
    pkt.player_property_data = bp::CompoundTag{};
    pkt.server_block_type_registry_checksum = 0;
    pkt.world_template_id = bp::UUID{};

    // generated by gophertunnel @56ec96a: packet.StartGame{...}
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x39,
        0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
        0x00, 0x02, 0x00, 0xE0, 0xFF, 0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
        0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x6C, 0x65, 0x76,
        0x65, 0x6C, 0x74, 0x65, 0x73, 0x74, 0x0A, 0x54, 0x65, 0x73, 0x74, 0x20,
        0x57, 0x6F, 0x72, 0x6C, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x63, 0x6F,
        0x72, 0x72, 0x01, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x0A, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<527>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
}

TEST_CASE("StartGamePacket: v544 baseline round-trip")
{
    // v544 (1.19.20) introduced PersonaDisabled, CustomSkinsDisabled,
    // ChatRestrictionLevel, DisablePlayerInteractions, and
    // server_enabled_client_side_generation. EmoteChatMuted lands at v567.
    // PlayerPermissions defaults to Visitor (0) here -- gophertunnel-at-v544
    // wrongly emits Uint8 for this field (a self-inflicted regression fixed
    // at v554; CloudburstMC has it as VarInt all along, matching our DSL);
    // value 0 happens to encode the same byte (0x00) in both, sidestepping
    // the divergence without papering over it.
    bp::StartGamePacket_<544> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = static_cast<bp::LevelSeed64>(12345);
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.editor_world = false;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<544>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Visitor;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.persona_disabled = false;
    s.custom_skins_disabled = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;
    s.chat_restriction_level = bp::ChatRestrictionLevel::None;
    s.disable_player_interactions = false;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings_<544>{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.items = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";
    pkt.player_property_data = bp::CompoundTag{};
    pkt.server_block_type_registry_checksum = 0;
    pkt.world_template_id = bp::UUID{};
    pkt.server_enabled_client_side_generation = false;

    // generated by gophertunnel @af691b8: packet.StartGame{... no EmoteChatMuted}
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x39,
        0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
        0x00, 0x02, 0x00, 0xE0, 0xFF, 0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x09, 0x6C, 0x65, 0x76, 0x65, 0x6C, 0x74, 0x65, 0x73, 0x74, 0x0A,
        0x54, 0x65, 0x73, 0x74, 0x20, 0x57, 0x6F, 0x72, 0x6C, 0x64, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x04, 0x63, 0x6F, 0x72, 0x72, 0x01, 0x06, 0x31, 0x2E, 0x32,
        0x31, 0x2E, 0x30, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<544>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->settings.default_permissions == bp::PlayerPermissionLevel::Visitor);
}

TEST_CASE("StartGamePacket: v567 baseline round-trip")
{
    // v567 (1.19.60) introduced EmoteChatMuted. CreatedInEditor,
    // ExportedFromEditor, and UseBlockNetworkIDHashes won't land until v582.
    bp::StartGamePacket_<567> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = static_cast<bp::LevelSeed64>(12345);
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.editor_world = false;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<567>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.persona_disabled = false;
    s.custom_skins_disabled = false;
    s.emote_chat_muted = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;
    s.chat_restriction_level = bp::ChatRestrictionLevel::None;
    s.disable_player_interactions = false;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings_<567>{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.items = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";
    pkt.player_property_data = bp::CompoundTag{};
    pkt.server_block_type_registry_checksum = 0;
    pkt.world_template_id = bp::UUID{};
    pkt.server_enabled_client_side_generation = false;

    // generated by gophertunnel @d0046b4: packet.StartGame{...}
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x39,
        0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
        0x00, 0x02, 0x00, 0xE0, 0xFF, 0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x09, 0x6C, 0x65, 0x76, 0x65, 0x6C, 0x74, 0x65, 0x73, 0x74,
        0x0A, 0x54, 0x65, 0x73, 0x74, 0x20, 0x57, 0x6F, 0x72, 0x6C, 0x64, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x04, 0x63, 0x6F, 0x72, 0x72, 0x01, 0x06, 0x31, 0x2E,
        0x32, 0x31, 0x2E, 0x30, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<567>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->level_name == "Test World");
}

TEST_CASE("StartGamePacket: v582 baseline round-trip")
{
    // v582 (1.19.80) introduced is_created_in_editor, is_exported_from_editor,
    // and block_network_ids_are_hashes. NetworkPermissions is not yet a thing
    // (lands at v589 as ServerAuthoritativeSound bool).
    bp::StartGamePacket_<582> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = static_cast<bp::LevelSeed64>(12345);
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.editor_world = false;
    s.is_created_in_editor = false;
    s.is_exported_from_editor = false;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<582>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.persona_disabled = false;
    s.custom_skins_disabled = false;
    s.emote_chat_muted = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;
    s.chat_restriction_level = bp::ChatRestrictionLevel::None;
    s.disable_player_interactions = false;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings_<582>{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.items = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";
    pkt.player_property_data = bp::CompoundTag{};
    pkt.server_block_type_registry_checksum = 0;
    pkt.world_template_id = bp::UUID{};
    pkt.server_enabled_client_side_generation = false;
    pkt.block_network_ids_are_hashes = false;

    // generated by gophertunnel @f10711f: packet.StartGame{... no
    // ServerAuthoritativeSound at this vintage}
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x39,
        0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
        0x00, 0x02, 0x00, 0xE0, 0xFF, 0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32, 0x31,
        0x2E, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x09, 0x6C, 0x65, 0x76, 0x65, 0x6C, 0x74, 0x65,
        0x73, 0x74, 0x0A, 0x54, 0x65, 0x73, 0x74, 0x20, 0x57, 0x6F, 0x72, 0x6C,
        0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x63, 0x6F, 0x72, 0x72, 0x01, 0x06,
        0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<582>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE_FALSE(rt->settings.is_created_in_editor);
    REQUIRE_FALSE(rt->block_network_ids_are_hashes);
}

TEST_CASE("StartGamePacket: v589 baseline round-trip")
{
    // v589 (1.20.0) is the introduction point of NetworkPermissions. At this
    // vintage editor_world is still a bool (widens to EditorWorldType varint32
    // at v671 per CloudburstMC), Hardcore hasn't landed, and server_id /
    // world_id / scenario_id are not yet part of LevelSettings.
    bp::StartGamePacket_<589> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = static_cast<bp::LevelSeed64>(12345);
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.editor_world = false;
    s.is_created_in_editor = false;
    s.is_exported_from_editor = false;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<589>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.persona_disabled = false;
    s.custom_skins_disabled = false;
    s.emote_chat_muted = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;
    s.chat_restriction_level = bp::ChatRestrictionLevel::None;
    s.disable_player_interactions = false;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings_<589>{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.items = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";
    pkt.player_property_data = bp::CompoundTag{};
    pkt.server_block_type_registry_checksum = 0;
    pkt.world_template_id = bp::UUID{};
    pkt.server_enabled_client_side_generation = false;
    pkt.block_network_ids_are_hashes = false;
    pkt.network_permissions = bp::NetworkPermissions_<589>{false};

    // generated by gophertunnel @fa4fd39: packet.StartGame{... (analog of v685);
    // WorldSpawn: {0, -32, 0}; EditorWorld: false; no Hardcore/ServerID/WorldID/ScenarioID}
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x39,
        0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
        0x00, 0x02, 0x00, 0xE0, 0xFF, 0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32, 0x31,
        0x2E, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x09, 0x6C, 0x65, 0x76, 0x65, 0x6C, 0x74, 0x65,
        0x73, 0x74, 0x0A, 0x54, 0x65, 0x73, 0x74, 0x20, 0x57, 0x6F, 0x72, 0x6C,
        0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x63, 0x6F, 0x72, 0x72, 0x01, 0x06,
        0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<589>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->settings.editor_world == false);
    REQUIRE(rt->items.empty());
}

TEST_CASE("StartGamePacket: v685 baseline round-trip")
{
    // v685 introduced server_id / world_id / scenario_id at the tail of
    // LevelSettings (they move out to StartGamePacket's ServerTelemetryData
    // at v924). NetworkPermissions is already a struct in the DSL though
    // it's a single bool on the wire. The legacy items list is still
    // present here -- it was dropped at v776.
    bp::StartGamePacket_<685> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = static_cast<bp::LevelSeed64>(12345);
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.is_hardcore = false;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.editor_world_type = bp::EditorWorldType::NonEditor;
    s.is_created_in_editor = false;
    s.is_exported_from_editor = false;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<685>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.persona_disabled = false;
    s.custom_skins_disabled = false;
    s.emote_chat_muted = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;
    s.chat_restriction_level = bp::ChatRestrictionLevel::None;
    s.disable_player_interactions = false;
    s.server_id = "";
    s.world_id = "";
    s.scenario_id = "";

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings_<685>{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.items = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";
    pkt.player_property_data = bp::CompoundTag{};
    pkt.server_block_type_registry_checksum = 0;
    pkt.world_template_id = bp::UUID{};
    pkt.server_enabled_client_side_generation = false;
    pkt.block_network_ids_are_hashes = false;
    pkt.network_permissions = bp::NetworkPermissions_<685>{false};

    // generated by gophertunnel @082917e: packet.StartGame{... (analog of v924);
    // WorldSpawn: {0, -32, 0}; Items: nil; no ServerJoinInformation / OwnerID
    // / TickDeathSystemsEnabled at this vintage}
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x39,
        0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
        0x00, 0x00, 0x02, 0x00, 0xE0, 0xFF, 0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32,
        0x31, 0x2E, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x6C, 0x65, 0x76,
        0x65, 0x6C, 0x74, 0x65, 0x73, 0x74, 0x0A, 0x54, 0x65, 0x73, 0x74, 0x20,
        0x57, 0x6F, 0x72, 0x6C, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x63, 0x6F,
        0x72, 0x72, 0x01, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x0A, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<685>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->settings.seed == static_cast<bp::LevelSeed64>(12345));
    REQUIRE(rt->settings.server_id == "");
    REQUIRE(rt->items.empty());
}

TEST_CASE("StartGamePacket: v975 with ServerConfigurationJoinInfo populated")
{
    // Replays the baseline test data with the v924+ optional present,
    // exercising the gathering / store / presence option triple.
    bp::StartGamePacket pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = static_cast<bp::LevelSeed64>(12345);
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.is_hardcore = false;
    s.game_difficulty = bp::Difficulty::Easy;
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.editor_world_type = bp::EditorWorldType::NonEditor;
    s.is_created_in_editor = false;
    s.is_exported_from_editor = false;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.persona_disabled = false;
    s.custom_skins_disabled = false;
    s.emote_chat_muted = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;
    s.chat_restriction_level = bp::ChatRestrictionLevel::None;
    s.disable_player_interactions = false;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";
    pkt.player_property_data = bp::CompoundTag{};
    pkt.server_block_type_registry_checksum = 0;
    pkt.world_template_id = bp::UUID{};
    pkt.server_enabled_client_side_generation = false;
    pkt.block_network_ids_are_hashes = false;
    pkt.network_permissions = bp::NetworkPermissions{false};

    bp::ServerConfigurationJoinInfo join;
    bp::ServerConfiguration::GatheringsConfigurationJoinInfo gathering;
    gathering.experience_id = bp::UUID{0, 1};
    gathering.experience_name = "exp";
    gathering.experience_world_id = bp::UUID{0, 2};
    gathering.experience_world_name = "world";
    gathering.creator_id = "creator";
    gathering.target_id = bp::UUID{0, 3};
    gathering.scenario_id = "scenario";
    gathering.server_id = "server";
    join.gatherings_configuration_join_info = gathering;
    join.client_store_entrypoint_configuration = std::nullopt;
    join.presence_configuration = std::nullopt;
    pkt.server_configuration_join_info = join;
    pkt.server_telemetry_data = bp::ServerTelemetryData{};

    // generated by gophertunnel:
    // packet.StartGame{..., WorldSpawn: {0, -32, 0}, ServerJoinInformation:
    //   protocol.Option(protocol.ServerJoinInformation{
    //   GatheringJoinInfo: protocol.Option(protocol.GatheringJoinInfo{
    //     ExperienceID: 0...01, ExperienceName: "exp",
    //     ExperienceWorldID: 0...02, ExperienceWorldName: "world",
    //     CreatorID: "creator", TargetID: 0...03,
    //     ScenarioID: "scenario", ServerID: "server"})})}
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x39,
        0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
        0x00, 0x00, 0x02, 0x00, 0x3F, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
        0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E, 0x30, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x09, 0x6C, 0x65, 0x76, 0x65, 0x6C, 0x74, 0x65, 0x73, 0x74, 0x0A,
        0x54, 0x65, 0x73, 0x74, 0x20, 0x57, 0x6F, 0x72, 0x6C, 0x64, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x04, 0x63, 0x6F, 0x72, 0x72, 0x01, 0x06, 0x31, 0x2E, 0x32, 0x31, 0x2E,
        0x30, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x03, 0x65, 0x78, 0x70, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x05, 0x77, 0x6F,
        0x72, 0x6C, 0x64, 0x07, 0x63, 0x72, 0x65, 0x61, 0x74, 0x6F, 0x72, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x08, 0x73, 0x63, 0x65, 0x6E, 0x61, 0x72, 0x69, 0x6F,
        0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->server_configuration_join_info.has_value());
    const auto &g = rt->server_configuration_join_info->gatherings_configuration_join_info;
    REQUIRE(g.has_value());
    REQUIRE(g->experience_name == "exp");
    REQUIRE(g->scenario_id == "scenario");
    REQUIRE_FALSE(rt->server_configuration_join_info
                      ->client_store_entrypoint_configuration.has_value());
    REQUIRE_FALSE(rt->server_configuration_join_info->presence_configuration.has_value());
}

TEST_CASE("StartGamePacket: v924 baseline round-trip")
{
    // v924 is the introduction point of ServerConfigurationJoinInfo /
    // ServerTelemetryData. The v924 StartGamePacket struct lacks the v944
    // additions (target_id in gatherings, plus the client_store and presence
    // optionals on the join info wrapper). default_spawn is {0,0,0} here
    // because gophertunnel-at-v924 used UBlockPos (varuint Y) for the world
    // spawn and that bug was undone in v944+; signed/unsigned varint encode
    // 0 identically, so we sidestep the divergence at the test boundary.
    bp::StartGamePacket_<924> pkt;
    pkt.entity_id = static_cast<bp::ActorUniqueID>(1);
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.entity_game_type = bp::GameType::Survival;
    pkt.pos = {0.0f, 64.0f, 0.0f};
    pkt.rot = {0.0f, 0.0f};

    auto &s = pkt.settings;
    s.seed = static_cast<bp::LevelSeed64>(12345);
    s.spawn_settings = bp::SpawnSettings{bp::SpawnBiomeType::Default, "",
                                         static_cast<bp::DimensionType>(0)};
    s.generator = bp::GeneratorType::Overworld;
    s.game_type = bp::GameType::Survival;
    s.is_hardcore = false;
    s.game_difficulty = bp::Difficulty::Easy;
    // v924 uses NetworkBlockPos: uvarint Y on the wire (via the
    // field(type=uvarint32) override), int32_t Y in C++. Y=128 exercises
    // multi-byte varuint encoding.
    s.default_spawn = {0, -32, 0};
    s.achievements_disabled = true;
    s.editor_world_type = bp::EditorWorldType::NonEditor;
    s.is_created_in_editor = false;
    s.is_exported_from_editor = false;
    s.time = 0;
    s.education_edition_offer = bp::EducationEditionOffer::None;
    s.education_features_enabled = false;
    s.education_product_id = "";
    s.rain_level = 0.0f;
    s.lightning_level = 0.0f;
    s.confirmed_platform_locked_content = false;
    s.multiplayer_game_intent = true;
    s.lan_broadcast_intent = true;
    s.xbl_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.platform_broadcast_intent = bp::GamePublishSetting::NoMultiPlay;
    s.commands_enabled = true;
    s.texture_packs_required = false;
    s.game_rules = bp::GameRules_<924>{};
    s.experiments = bp::Experiments{};
    s.bonus_chest_enabled = false;
    s.start_with_map_enabled = false;
    s.default_permissions = bp::PlayerPermissionLevel::Member;
    s.server_chunk_tick_range = 4;
    s.has_locked_behavior_pack = false;
    s.has_locked_resource_pack = false;
    s.is_from_locked_template = false;
    s.use_msa_gamertags_only = false;
    s.is_from_world_template = false;
    s.is_world_template_option_locked = false;
    s.spawn_v1_villagers = false;
    s.persona_disabled = false;
    s.custom_skins_disabled = false;
    s.emote_chat_muted = false;
    s.base_game_version = "1.21.0";
    s.limited_world_width = 0;
    s.limited_world_depth = 0;
    s.nether_type = bp::NetherWorldType::Normal;
    s.edu_shared_uri_resource = bp::EduSharedUriResource{};
    s.override_force_experimental_gameplay_flag = std::nullopt;
    s.chat_restriction_level = bp::ChatRestrictionLevel::None;
    s.disable_player_interactions = false;

    pkt.level_id = "leveltest";
    pkt.level_name = "Test World";
    pkt.template_content_identity = "";
    pkt.is_trial = false;
    pkt.movement_settings = bp::SyncedPlayerMovementSettings_<924>{0, false};
    pkt.level_current_time = 0;
    pkt.enchantment_seed = 0;
    pkt.block_properties = {};
    pkt.multiplayer_correlation_id = "corr";
    pkt.enable_item_stack_net_manager = true;
    pkt.server_version = "1.21.0";
    pkt.player_property_data = bp::CompoundTag{};
    pkt.server_block_type_registry_checksum = 0;
    pkt.world_template_id = bp::UUID{};
    pkt.server_enabled_client_side_generation = false;
    pkt.block_network_ids_are_hashes = false;
    pkt.network_permissions = bp::NetworkPermissions_<924>{false};
    pkt.server_configuration_join_info = std::nullopt;
    pkt.server_telemetry_data = bp::ServerTelemetryData_<924>{};

    // generated by gophertunnel @0381a95: packet.StartGame{... (see v975 baseline);
    // WorldSpawn: {0, -32, 0}; ForceExperimentalGameplay: false}
    const std::vector<std::uint8_t> golden{
        0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x42, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x39,
        0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
        0x00, 0x00, 0x02, 0x00, 0xE0, 0xFF, 0xFF, 0xFF, 0x0F, 0x00, 0x01, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06, 0x31, 0x2E, 0x32,
        0x31, 0x2E, 0x30, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x09, 0x6C, 0x65, 0x76, 0x65, 0x6C, 0x74,
        0x65, 0x73, 0x74, 0x0A, 0x54, 0x65, 0x73, 0x74, 0x20, 0x57, 0x6F, 0x72,
        0x6C, 0x64, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x04, 0x63, 0x6F, 0x72, 0x72, 0x01, 0x06, 0x31,
        0x2E, 0x32, 0x31, 0x2E, 0x30, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::StartGamePacket_<924>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->settings.seed == static_cast<bp::LevelSeed64>(12345));
    REQUIRE_FALSE(rt->server_configuration_join_info.has_value());
}
