#include <type_traits>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("DimensionDefinition: dimension_type added at v975")
{
    bp::DimensionDefinition_<503> pre{"minecraft:overworld", 320, -64, 1};
    REQUIRE(pre.generator_type == 1);

    bp::DimensionDefinition_<975> post{"minecraft:overworld", 320, -64, 1,
                                       static_cast<bp::DimensionType>(0)};
    REQUIRE(post.dimension_type == static_cast<bp::DimensionType>(0));

    STATIC_REQUIRE(std::is_same_v<bp::DimensionDefinition_<503>,
                                  bp::DimensionDefinition_<974>>);
    STATIC_REQUIRE(!std::is_same_v<bp::DimensionDefinition_<974>,
                                   bp::DimensionDefinition_<975>>);
}

TEST_CASE("DimensionDataPacket: id + round-trip of a list of nested structs")
{
    STATIC_REQUIRE(bp::DimensionDataPacket_<503>::Id == 180);

    bp::DimensionDataPacket_<975> pkt;
    pkt.definitions = {bp::DimensionDefinition_<975>{
        "minecraft:nether", 128, 0, 3, static_cast<bp::DimensionType>(1)}};

    // generated by gophertunnel:
    // packet.DimensionData{Definitions: []protocol.DimensionDefinition{{Name: "minecraft:nether", Range: [2]int32{128, 0}, Generator: 3, DimensionType: 1}}}
    const std::vector<std::uint8_t> golden{
        0x01, 0x10, 0x6D, 0x69, 0x6E, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3A,
        0x6E, 0x65, 0x74, 0x68, 0x65, 0x72, 0x80, 0x02, 0x00, 0x06, 0x02,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::DimensionDataPacket_<975>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->definitions.size() == 1);
    REQUIRE(rt->definitions[0].name == "minecraft:nether");
    REQUIRE(rt->definitions[0].dimension_type == static_cast<bp::DimensionType>(1));
}

TEST_CASE("SubChunkRequestPacket: offset list added at v486")
{
    STATIC_REQUIRE(bp::SubChunkRequestPacket_<471>::Id == 175);
    STATIC_REQUIRE(std::is_same_v<bp::SubChunkRequestPacket_<471>,
                                  bp::SubChunkRequestPacket_<485>>);
    STATIC_REQUIRE(!std::is_same_v<bp::SubChunkRequestPacket_<485>,
                                   bp::SubChunkRequestPacket_<486>>);
}

TEST_CASE("SubChunkRequestPacket: round-trip with a uint32-prefixed offset list")
{
    bp::SubChunkRequestPacket pkt;
    pkt.dimension_type = static_cast<bp::DimensionType>(0);
    pkt.center_pos = {1, 2, 3};
    pkt.sub_chunk_pos_offsets = {bp::SubChunkPosOffset{1, -1, 0}};

    // generated by gophertunnel:
    // packet.SubChunkRequest{Dimension: 0, Position: protocol.SubChunkPos{1, 2, 3}, Offsets: []protocol.SubChunkOffset{{1, -1, 0}}}
    const std::vector<std::uint8_t> golden{
        0x00, 0x02, 0x04, 0x06, 0x01, 0x00, 0x00, 0x00, 0x01, 0xFF, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::SubChunkRequestPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->center_pos.z == 3);
    REQUIRE(rt->sub_chunk_pos_offsets.size() == 1);
    REQUIRE(rt->sub_chunk_pos_offsets[0].y == -1);
}

TEST_CASE("BlockActorDataPacket: id + round-trip with an NBT CompoundTag")
{
    STATIC_REQUIRE(bp::BlockActorDataPacket::Id == 56);

    bp::BlockActorDataPacket pkt;
    pkt.pos = {1, 2, 3};
    pkt.data.emplace(
        "levels", bp::Tag{bp::ListTag{bp::IntTag{1}, bp::IntTag{2}, bp::IntTag{3}}});

    // generated by gophertunnel:
    // packet.BlockActorData{Position: {1, 2, 3}, NBTData: {"levels": []int32{1, 2, 3}}}
    const std::vector<std::uint8_t> golden{
        0x02, 0x04, 0x06, 0x0A, 0x00, 0x09, 0x06, 0x6C, 0x65, 0x76, 0x65, 0x6C,
        0x73, 0x03, 0x06, 0x02, 0x04, 0x06, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::BlockActorDataPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->data.size() == 1);
    const auto &levels = rt->data.at("levels").get<bp::ListTag>();
    REQUIRE(levels.size() == 3);
    REQUIRE(levels[2].get<bp::IntTag>().value() == 3);
}
