#include <string>

#include <bedrock/protocol/inventory.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ContainerSetData{WindowID: 5, Key: 1, Value: 200}
const std::string golden = bytes({
    0x05, 0x02, 0x90, 0x03,
});

// generated by gophertunnel: &packet.ContainerSetData{WindowID: 0xff, Key: 4, Value: -1}
const std::string golden_none = bytes({
    0xff, 0x08, 0x01,
});

// generated by gophertunnel: &packet.ContainerSetData{WindowID: 0, Key: -1, Value: 300}
const std::string golden_wide = bytes({
    0x00, 0x01, 0xd8, 0x04,
});

}  // namespace

TEST_CASE("packet id is 51")
{
    STATIC_REQUIRE(bp::ContainerSetDataPacket::Id == 51);
    STATIC_REQUIRE(bp::has_packet_v<1001, 51>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 51>);
}

TEST_CASE("container-set-data round-trips against the golden")
{
    bp::ContainerSetDataPacket packet;
    packet.container_id = static_cast<bp::ContainerID>(5);
    packet.id = 1;
    packet.value = 200;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::ContainerSetDataPacket>(golden);
    REQUIRE(back.container_id == static_cast<bp::ContainerID>(5));
    REQUIRE(back.id == 1);
    REQUIRE(back.value == 200);
}

TEST_CASE("the container id keeps its sign in one byte and the value is a zigzag varint")
{
    bp::ContainerSetDataPacket packet;
    packet.container_id = bp::ContainerID::None;
    packet.id = 4;
    packet.value = -1;
    REQUIRE(encode(packet) == golden_none);

    const auto back = decode<bp::ContainerSetDataPacket>(golden_none);
    REQUIRE(back.container_id == bp::ContainerID::None);
    REQUIRE(back.id == 4);
    REQUIRE(back.value == -1);
}

TEST_CASE("a negative id does not run into a two-byte value")
{
    bp::ContainerSetDataPacket packet;
    packet.container_id = bp::ContainerID::Inventory;
    packet.id = -1;
    packet.value = 300;
    REQUIRE(encode(packet) == golden_wide);

    const auto back = decode<bp::ContainerSetDataPacket>(golden_wide);
    REQUIRE(back.container_id == bp::ContainerID::Inventory);
    REQUIRE(back.id == -1);
    REQUIRE(back.value == 300);
}
