#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("UpdateSoftEnumPacket: id + round-trip with two values + ADD action")
{
    STATIC_REQUIRE(bp::UpdateSoftEnumPacket::Id == 114);

    bp::UpdateSoftEnumPacket pkt;
    pkt.enum_name = "tags";
    pkt.values = {"a", "b"};
    pkt.type = bp::SoftEnumUpdateType::Add;

    // generated by gophertunnel:
    // packet.UpdateSoftEnum{EnumType: "tags", Options: []string{"a", "b"}, ActionType: 0}
    const std::vector<std::uint8_t> golden{
        0x04, 0x74, 0x61, 0x67, 0x73, 0x02, 0x01, 0x61, 0x01, 0x62, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::UpdateSoftEnumPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->enum_name == "tags");
    REQUIRE(rt->values.size() == 2);
    REQUIRE(rt->values[0] == "a");
    REQUIRE(rt->type == bp::SoftEnumUpdateType::Add);
}
