#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("SetHudPacket: id + round-trip with two elements hidden")
{
    STATIC_REQUIRE(bp::SetHudPacket::Id == 308);

    bp::SetHudPacket pkt;
    // each element is a varint32; values match HudElement enum members
    pkt.elements = {static_cast<std::int32_t>(bp::HudElement::HotBar),
                    static_cast<std::int32_t>(bp::HudElement::Health)};
    pkt.visibility = bp::HudVisibility::Hide;

    // generated by gophertunnel:
    // packet.SetHud{Elements: [HudElementHotBar=5, HudElementHealth=6],
    //   Visibility: HudVisibilityHide=0}
    const std::vector<std::uint8_t> golden{
        0x02, 0x0A, 0x0C, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::SetHudPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->elements.size() == 2);
    REQUIRE(rt->visibility == bp::HudVisibility::Hide);
}
