#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("SetLocalPlayerAsInitializedPacket: round-trip")
{
    STATIC_REQUIRE(bp::SetLocalPlayerAsInitializedPacket::Id == 113);

    bp::SetLocalPlayerAsInitializedPacket pkt;
    pkt.player_id = static_cast<bp::ActorRuntimeID>(1234);

    // generated by gophertunnel:
    // packet.SetLocalPlayerAsInitialised{EntityRuntimeID: 1234}
    const std::vector<std::uint8_t> golden{
        0xD2, 0x09,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::SetLocalPlayerAsInitializedPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->player_id == static_cast<bp::ActorRuntimeID>(1234));
}
