#include <string>

#include <bedrock/protocol/crafting.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.UnlockedRecipes{UnlockType:
// packet.UnlockedRecipesTypeNewlyUnlocked, Recipes: []string{"minecraft:stick",
// "minecraft:torch"}}
const std::string golden = bytes({
    0x02, 0x00, 0x00, 0x00, 0x02, 0x0f, 0x6d, 0x69, 0x6e, 0x65, 0x63, 0x72,
    0x61, 0x66, 0x74, 0x3a, 0x73, 0x74, 0x69, 0x63, 0x6b, 0x0f, 0x6d, 0x69,
    0x6e, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74, 0x3a, 0x74, 0x6f, 0x72, 0x63,
    0x68,
});

// generated by gophertunnel: &packet.UnlockedRecipes{UnlockType:
// packet.UnlockedRecipesTypeRemoveAllUnlocked}
const std::string golden_remove_all = bytes({
    0x04, 0x00, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 199")
{
    STATIC_REQUIRE(bp::UnlockedRecipesPacket::Id == 199);
    STATIC_REQUIRE(bp::has_packet_v<1001, 199>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 199>);
}

TEST_CASE("unlocked recipes round-trips against the golden")
{
    bp::UnlockedRecipesPacket packet;
    packet.packet_type = bp::UnlockedRecipesPacket::PacketType::NewlyUnlockedRecipes;
    packet.unlocked_recipes = {"minecraft:stick", "minecraft:torch"};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::UnlockedRecipesPacket>(golden);
    REQUIRE(back.packet_type == bp::UnlockedRecipesPacket::PacketType::NewlyUnlockedRecipes);
    REQUIRE(back.unlocked_recipes.size() == 2);
    REQUIRE(back.unlocked_recipes[0] == "minecraft:stick");
    REQUIRE(back.unlocked_recipes[1] == "minecraft:torch");
}

TEST_CASE("the unlocked-recipes packet type is four fixed bytes ahead of an empty list")
{
    bp::UnlockedRecipesPacket packet;
    packet.packet_type = bp::UnlockedRecipesPacket::PacketType::RemoveAllUnlockedRecipes;
    REQUIRE(encode(packet) == golden_remove_all);
    REQUIRE(encode(packet).size() == 5);

    const auto back = decode<bp::UnlockedRecipesPacket>(golden_remove_all);
    REQUIRE(back.packet_type == bp::UnlockedRecipesPacket::PacketType::RemoveAllUnlockedRecipes);
    REQUIRE(back.unlocked_recipes.empty());
}
