#include <string>

#include <bedrock/protocol/actor.h>
#include <bedrock/protocol/inventory.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.UpdateTrade{WindowID: 1, WindowType: 15,
// Size: 3, TradeTier: 2, VillagerUniqueID: 42, EntityUniqueID: 7,
// DisplayName: "entity.villager.farmer", NewTradeUI: true,
// DemandBasedPrices: false, SerialisedOffers: nbt.MarshalEncoding(
// map[string]any{"TierExpRequirements": int32(5)}, nbt.NetworkLittleEndian)}
const std::string golden = bytes({
    0x01, 0x0f, 0x06, 0x04, 0x54, 0x0e, 0x16, 0x65, 0x6e, 0x74, 0x69, 0x74,
    0x79, 0x2e, 0x76, 0x69, 0x6c, 0x6c, 0x61, 0x67, 0x65, 0x72, 0x2e, 0x66,
    0x61, 0x72, 0x6d, 0x65, 0x72, 0x01, 0x00, 0x0a, 0x00, 0x03, 0x13, 0x54,
    0x69, 0x65, 0x72, 0x45, 0x78, 0x70, 0x52, 0x65, 0x71, 0x75, 0x69, 0x72,
    0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x0a, 0x00,
});

// generated by gophertunnel: &packet.UpdateTrade{WindowID: 0xff,
// WindowType: 0xf7, Size: -1, TradeTier: -1, VillagerUniqueID: -1,
// EntityUniqueID: -1, DisplayName: "", NewTradeUI: false,
// DemandBasedPrices: true, SerialisedOffers: nbt.MarshalEncoding(
// map[string]any{}, nbt.NetworkLittleEndian)}
const std::string golden_none = bytes({
    0xff, 0xf7, 0x01, 0x01, 0x01, 0x01, 0x00, 0x00, 0x01, 0x0a, 0x00, 0x00,
});

// generated by gophertunnel: &packet.UpdateTrade{WindowID: 1, WindowType: 15,
// Size: 300, TradeTier: 0, VillagerUniqueID: 0, EntityUniqueID: 0,
// DisplayName: "", NewTradeUI: false, DemandBasedPrices: false,
// SerialisedOffers: nbt.MarshalEncoding(map[string]any{},
// nbt.NetworkLittleEndian)}
const std::string golden_wide = bytes({
    0x01, 0x0f, 0xd8, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x00,
    0x00,
});

}  // namespace

TEST_CASE("packet id is 80")
{
    STATIC_REQUIRE(bp::UpdateTradePacket_<2168>::Id == 80);
    STATIC_REQUIRE(bp::has_packet_v<1001, 80>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 80>);
}

TEST_CASE("update-trade round-trips against the golden")
{
    bp::UpdateTradePacket_<2168> packet;
    packet.container_id = bp::ContainerID::First;
    packet.type = bp::ContainerType_<2168>::Trade;
    packet.size = 3;
    packet.trader_tier = 2;
    packet.entity_unique_id = bp::ActorUniqueID{42};
    packet.last_trading_player = bp::ActorUniqueID{7};
    packet.display_name = "entity.villager.farmer";
    packet.use_new_trade_screen = true;
    packet.using_economy_trade = false;
    packet.data = bp::CompoundTag{{"TierExpRequirements", bp::IntTag{5}}};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::UpdateTradePacket_<2168>>(golden);
    REQUIRE(back.container_id == bp::ContainerID::First);
    REQUIRE(back.type == bp::ContainerType_<2168>::Trade);
    REQUIRE(back.size == 3);
    REQUIRE(back.trader_tier == 2);
    REQUIRE(back.entity_unique_id == bp::ActorUniqueID{42});
    REQUIRE(back.last_trading_player == bp::ActorUniqueID{7});
    REQUIRE(back.display_name == "entity.villager.farmer");
    REQUIRE(back.use_new_trade_screen);
    REQUIRE_FALSE(back.using_economy_trade);
    REQUIRE(back.data.at("TierExpRequirements").get<bp::IntTag>().value() == 5);
}

TEST_CASE("a trade with no container writes one signed byte per sentinel and zigzags every id")
{
    bp::UpdateTradePacket_<2168> packet;
    packet.container_id = bp::ContainerID::None;
    packet.type = bp::ContainerType_<2168>::None;
    packet.size = -1;
    packet.trader_tier = -1;
    packet.entity_unique_id = bp::ActorUniqueID{-1};
    packet.last_trading_player = bp::ActorUniqueID{-1};
    packet.display_name = "";
    packet.use_new_trade_screen = false;
    packet.using_economy_trade = true;
    REQUIRE(encode(packet) == golden_none);

    const auto back = decode<bp::UpdateTradePacket_<2168>>(golden_none);
    REQUIRE(back.container_id == bp::ContainerID::None);
    REQUIRE(back.type == bp::ContainerType_<2168>::None);
    REQUIRE(back.size == -1);
    REQUIRE(back.trader_tier == -1);
    REQUIRE(back.entity_unique_id == bp::ActorUniqueID{-1});
    REQUIRE(back.last_trading_player == bp::ActorUniqueID{-1});
    REQUIRE(back.display_name.empty());
    REQUIRE_FALSE(back.use_new_trade_screen);
    REQUIRE(back.using_economy_trade);
    REQUIRE(back.data.empty());
}

TEST_CASE("a trade size above 127 widens to a two-byte varint")
{
    bp::UpdateTradePacket_<2168> packet;
    packet.container_id = bp::ContainerID::First;
    packet.type = bp::ContainerType_<2168>::Trade;
    packet.size = 300;
    REQUIRE(encode(packet) == golden_wide);

    const auto back = decode<bp::UpdateTradePacket_<2168>>(golden_wide);
    REQUIRE(back.size == 300);
    REQUIRE(back.trader_tier == 0);
}
