#include <optional>
#include <string>

#include <bedrock/protocol/actor.h>

#include "fixture.hpp"

namespace {

// AddItemActorPacket cerealised at 2168; r26_u3 carries no AddItemActorPacket.json.
// gophertunnel's add_item_actor.go and CloudburstMC's AddItemEntitySerializer_v291
// (which v2168 does not override) hold the same seven fields in the same order as the
// r26_u4 dump, so the wire delta is entirely in the closure: the entity data list and
// the item descriptor.
template <class Item>
Item stone()
{
    Item item;
    item.id = 5;
    item.stack_size = 1;
    item.aux_value = 0;
    item.block_runtime_id = 0;
    item.user_data_buffer = empty_item_blob();
    return item;
}

template <class Packet>
void fill(Packet &packet)
{
    packet.id = bp::ActorUniqueID{1};
    packet.runtime_id = bp::ActorRuntimeID{2};
    packet.item = stone<decltype(packet.item)>();
    packet.pos = {.x = 1.0f, .y = 2.0f, .z = 3.0f};
    packet.velocity = {.x = 4.0f, .y = 5.0f, .z = 6.0f};
    packet.is_from_fishing = true;
}

}  // namespace

TEST_CASE("packet id is 15 at both versions")
{
    STATIC_REQUIRE(bp::AddItemActorPacket_<1001>::Id == 15);
    STATIC_REQUIRE(bp::AddItemActorPacket_<2168>::Id == 15);
}

TEST_CASE("AddItemActorPacket: v2168 round-trip")
{
    using Packet = bp::AddItemActorPacket_<2168>;

    Packet pkt;
    fill(pkt);
    pkt.data.data.push_back(
        {.id = 38, .payload = bp::DataItemFloatPayload_<2168>{.type = bp::DataItemType::Float, .value = 0.5f}});

    // generated by CloudburstMC Bedrock_v2168:
    // AddItemEntityPacket{uniqueEntityId: 1, runtimeEntityId: 2,
    //   itemInHand: ItemData(minecraft:stone runtimeId 5, count 1, damage 0),
    //   position: (1, 2, 3), motion: (4, 5, 6), metadata: {SCALE: 0.5f},
    //   fromFishing: true}
    const std::string golden = bytes({
        0x02, 0x02, 0x05, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x0A, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3F,
        0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x80, 0x40,
        0x00, 0x00, 0xA0, 0x40, 0x00, 0x00, 0xC0, 0x40, 0x01, 0x26, 0x03, 0x03,
        0x00, 0x00, 0x00, 0x3F, 0x01,
    });

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.id == bp::ActorUniqueID{1});
    REQUIRE(rt.item.id == 5);
    REQUIRE(rt.item.stack_size == 1);
    REQUIRE(rt.item.user_data_buffer == empty_item_blob());
    REQUIRE(rt.data.data.size() == 1);
    REQUIRE(std::get<3>(rt.data.data[0].payload).type == bp::DataItemType::Float);
    REQUIRE(rt.is_from_fishing);
}

TEST_CASE("AddItemActorPacket: v1001 round-trip")
{
    using Packet = bp::AddItemActorPacket_<1001>;

    Packet pkt;
    fill(pkt);
    pkt.data.data.push_back({.id = 38, .payload = bp::DataItemFloatPayload_<1001>{.value = 0.5f}});

    // generated by gophertunnel:
    // packet.AddItemActor{EntityUniqueID: 1, EntityRuntimeID: 2, Item:
    //   protocol.ItemInstance{Stack: {ItemType: {NetworkID: 5}, Count: 1}},
    //   Position: (1, 2, 3), Velocity: (4, 5, 6), EntityMetadata: {38: float32(0.5)},
    //   FromFishing: true}
    const std::string golden = bytes({
        0x02, 0x02, 0x0a, 0x01, 0x00, 0x00, 0x00, 0x00, 0x0a, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3f, 0x00,
        0x00, 0x00, 0x40, 0x00, 0x00, 0x40, 0x40, 0x00, 0x00, 0x80, 0x40, 0x00,
        0x00, 0xa0, 0x40, 0x00, 0x00, 0xc0, 0x40, 0x01, 0x26, 0x03, 0x00, 0x00,
        0x00, 0x3f, 0x01,
    });

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.item.id == 5);
    REQUIRE_FALSE(rt.item.net_id.has_value());
    REQUIRE(rt.data.data.size() == 1);
    REQUIRE(std::get<3>(rt.data.data[0].payload).value == 0.5f);
    REQUIRE(rt.is_from_fishing);

    bp::AddItemActorPacket_<2168> newer;
    fill(newer);
    newer.data.data.push_back(
        {.id = 38, .payload = bp::DataItemFloatPayload_<2168>{.type = bp::DataItemType::Float, .value = 0.5f}});
    REQUIRE(golden.size() + 2 == encode(newer).size());

    // The legacy id is a varint where the cereal form spells a fixed int16, so a 2168 body
    // desynchronises inside the item and the frame runs long.
    const auto wrong = decode_partial<Packet>(encode(newer));
    REQUIRE(wrong.item.stack_size != 1);

    REQUIRE(rejects<bp::AddItemActorPacket_<2168>>(golden));
}
