#include <cstdint>
#include <map>
#include <string>
#include <vector>

#include <bedrock/protocol/common.h>
#include <bedrock/protocol/skin.h>

#include "fixture.hpp"

namespace {

using Packet1001 = bp::PlayerSkinPacket_<1001>;
using Packet2168 = bp::PlayerSkinPacket_<2168>;

const bp::UUID kPlayer{0x9E688C58A5483B8EULL, 0xAF69C9E1005AD0BFULL};
const bp::UUID kPack{0x55A54008AD1B3589ULL, 0xAA210D2629C1DF41ULL};

bp::SkinImage image(const char *raw)
{
    return {.width = 1, .height = 1, .image_bytes = std::string(raw, 4)};
}

std::vector<bp::AnimatedImageData> animations()
{
    return {{.image = image("\x09\x0A\x0B\x0C"),
             .type = bp::AnimatedTextureType::FACE,
             .frames = 1.0f,
             .animation_expression = bp::AnimationExpression::LINEAR}};
}

std::vector<bp::SerializedPersonaPieceHandle> pieces()
{
    return {{.piece_id = "p1",
             .piece_type = bp::PieceType::SKELETON,
             .pack_id = kPack,
             .is_default_piece = true,
             .product_id = "prod"}};
}

std::map<bp::PieceType, bp::TintMapColor> tints()
{
    return {{bp::PieceType::SKELETON,
             bp::TintMapColor{.colors = {bp::Color{1}, bp::Color{2},
                                         bp::Color{3}, bp::Color{4}}}}};
}

Packet1001 fill_v1001()
{
    Packet1001 packet;
    packet.uuid = kPlayer;
    packet.skin = {.id = "sid",
                   .play_fab_id = "pfid",
                   .resource_patch = "patch",
                   .image_data = image("\x01\x02\x03\x04"),
                   .animated_image_data = animations(),
                   .cape_image_data = image("\x05\x06\x07\x08"),
                   .geometry_data = "geo",
                   .geometry_data_min_engine_version = "gev",
                   .animation_data = "anim",
                   .cape_id = "cape",
                   .full_id = "full",
                   .arm_size = bp::ArmSizeType::WIDE,
                   .skin_color = bp::Color{0x04030201},
                   .persona_pieces = pieces(),
                   .piece_tint_colors = tints(),
                   .is_premium = true,
                   .is_persona = false,
                   .is_persona_cape_on_classic_skin = false,
                   .is_primary_user = true,
                   .overrides_player_appearance = true,
                   .trusted_skin_flag = bp::TrustedSkinFlag::FALSE};
    packet.localized_new_skin_name = "new";
    packet.localized_old_skin_name = "old";
    return packet;
}

Packet2168 fill_v2168()
{
    Packet2168 packet;
    packet.uuid = kPlayer;
    packet.skin = {.id = "sid",
                   .play_fab_id = "pfid",
                   .resource_patch = "patch",
                   .image_data = image("\x01\x02\x03\x04"),
                   .animated_image_data = animations(),
                   .cape_image_data = image("\x05\x06\x07\x08"),
                   .geometry_data = "geo",
                   .geometry_data_min_engine_version = "gev",
                   .animation_data = "anim",
                   .cape_id = "cape",
                   .full_id = "full",
                   .arm_size = bp::ArmSizeType::WIDE,
                   .skin_color = bp::Color{0x04030201},
                   .persona_pieces = pieces(),
                   .piece_tint_colors = tints(),
                   .is_premium = true,
                   .is_persona = false,
                   .is_persona_cape_on_classic_skin = false,
                   .is_primary_user = true,
                   .overrides_player_appearance = true,
                   .trusted_skin_flag = bp::TrustedSkinFlag::FALSE,
                   .profile_hash = "hash"};
    packet.localized_new_skin_name = "new";
    packet.localized_old_skin_name = "old";
    return packet;
}

// generated by CloudburstMC Bedrock_v2168. Its "skeleton" and "false" are what BDS
// writes: cereal binds the piece type "Skeleton" and the flag "False" and folds both at
// bind time, so the binding's casing never reaches the wire.
// PlayerSkinPacket{uuid: 9e688c58-a548-3b8e-af69-c9e1005ad0bf,
//   skin: SerializedSkin.of("sid", "pfid", "patch", ImageData.of(1, 1, {1,2,3,4}),
//     [AnimationData(ImageData.of(1, 1, {9,10,11,12}), FACE, 1.0, LINEAR)],
//     ImageData.of(1, 1, {5,6,7,8}), "geo", "gev", "anim", true, false, false, true,
//     "cape", "full", "wide", new Color(0x04030201, true),
//     [PersonaPieceData("p1", SKELETON, 55a54008-ad1b-3589-aa21-0d2629c1df41, true, "prod")],
//     [PersonaPieceTintData(SKELETON, [1, 2, 3, 4])], true, false, "hash"),
//   newSkinName: "new", oldSkinName: "old"}
const std::string golden_v2168 = bytes({
    0x8E, 0x3B, 0x48, 0xA5, 0x58, 0x8C, 0x68, 0x9E, 0xBF, 0xD0, 0x5A, 0x00,
    0xE1, 0xC9, 0x69, 0xAF, 0x03, 0x73, 0x69, 0x64, 0x04, 0x70, 0x66, 0x69,
    0x64, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x01, 0x00, 0x00, 0x00, 0x01,
    0x00, 0x00, 0x00, 0x04, 0x01, 0x02, 0x03, 0x04, 0x01, 0x01, 0x00, 0x00,
    0x00, 0x01, 0x00, 0x00, 0x00, 0x04, 0x09, 0x0A, 0x0B, 0x0C, 0x01, 0x00,
    0x00, 0x80, 0x3F, 0x00, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00,
    0x04, 0x05, 0x06, 0x07, 0x08, 0x03, 0x67, 0x65, 0x6F, 0x03, 0x67, 0x65,
    0x76, 0x04, 0x61, 0x6E, 0x69, 0x6D, 0x04, 0x63, 0x61, 0x70, 0x65, 0x04,
    0x66, 0x75, 0x6C, 0x6C, 0x01, 0x01, 0x02, 0x03, 0x04, 0x01, 0x02, 0x70,
    0x31, 0x01, 0x00, 0x00, 0x00, 0x89, 0x35, 0x1B, 0xAD, 0x08, 0x40, 0xA5,
    0x55, 0x41, 0xDF, 0xC1, 0x29, 0x26, 0x0D, 0x21, 0xAA, 0x01, 0x04, 0x70,
    0x72, 0x6F, 0x64, 0x01, 0x08, 0x73, 0x6B, 0x65, 0x6C, 0x65, 0x74, 0x6F,
    0x6E, 0x01, 0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x03, 0x00, 0x00,
    0x00, 0x04, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x01, 0x05, 0x66,
    0x61, 0x6c, 0x73, 0x65, 0x04, 0x68, 0x61, 0x73, 0x68, 0x03, 0x6E, 0x65,
    0x77, 0x03, 0x6F, 0x6C, 0x64,
});

// TODO: no golden for v1001, and confirm against BDS. Packet 93 was already
// cerealised at 1001, so r26_u3's SerializedSkinRef.json is its 1001 shape -- but
// gophertunnel's Skin and CloudburstMC's pre-v2168 helper both still write the
// pre-cereal, all-strings skin (arm size, skin colour, piece type, pack id and tint
// colours as text, uint32 counts, no trusted flag) and append a trailing
// bool isTrustedSkin the dump does not have. Neither codec can produce the 1001
// bytes the dump describes, so the v1001 case is asserted structurally instead.

}  // namespace

TEST_CASE("PlayerSkinPacket: id")
{
    STATIC_REQUIRE(bp::PlayerSkinPacket_<975>::Id == 93);
    STATIC_REQUIRE(bp::PlayerSkinPacket_<1001>::Id == 93);
    STATIC_REQUIRE(bp::PlayerSkinPacket_<2168>::Id == 93);
}

TEST_CASE("PlayerSkinPacket: v2168 round-trip")
{
    REQUIRE(encode(fill_v2168()) == golden_v2168);

    const auto rt = decode<Packet2168>(golden_v2168);
    REQUIRE(rt.skin.id == "sid");
    REQUIRE(rt.skin.animated_image_data.size() == 1);
    REQUIRE(rt.skin.animated_image_data[0].type == bp::AnimatedTextureType::FACE);
    REQUIRE(rt.skin.persona_pieces[0].pack_id.least_significant_bits == kPack.least_significant_bits);
    REQUIRE(rt.skin.piece_tint_colors.at(bp::PieceType::SKELETON).colors.size() == 4);
    REQUIRE(rt.skin.trusted_skin_flag == bp::TrustedSkinFlag::FALSE);
    REQUIRE(rt.skin.profile_hash == "hash");
    REQUIRE(rt.localized_old_skin_name == "old");
}

// 2168's only change to this packet is the trailing ProfileHash on SerializedSkinRef,
// so the 1001 body is the 2168 one less exactly that length-prefixed string.
TEST_CASE("PlayerSkinPacket: the v1001 body is the v2168 one less the profile hash")
{
    const auto encoded = encode(fill_v1001());
    REQUIRE(encoded.size() + 5 == golden_v2168.size());

    const auto rt = decode<Packet1001>(encoded);
    REQUIRE(rt.skin.id == "sid");
    REQUIRE(rt.skin.arm_size == bp::ArmSizeType::WIDE);
    REQUIRE(rt.localized_new_skin_name == "new");
}

// The appended hash sits ahead of the two skin names, so a 2168 body read as 1001
// slides the hash into the new-name slot rather than running short.
TEST_CASE("PlayerSkinPacket: a v2168 body does not decode as a v1001 one")
{
    const auto wrong = decode_partial<Packet1001>(golden_v2168);
    REQUIRE(wrong.localized_new_skin_name == "hash");
    REQUIRE(wrong.localized_old_skin_name == "new");

    REQUIRE(rejects<Packet2168>(encode(fill_v1001())));
}
