#include <string>

#include <bedrock/protocol/game.h>
#include <bedrock/protocol/input.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.UpdateClientInputLocks{Locks:
// packet.ClientInputLockCamera | packet.ClientInputLockMovement | packet.ClientInputLockJump}
const std::string golden = bytes({
    0x46,
});

// generated by gophertunnel: &packet.UpdateClientInputLocks{Locks: 8190}
const std::string golden_all_categories = bytes({
    0xfe, 0x3f,
});

// generated by gophertunnel: &packet.UpdateClientInputLocks{Locks: 0xffffffff}
const std::string golden_max = bytes({
    0xff, 0xff, 0xff, 0xff, 0x0f,
});

// generated by gophertunnel (924): &packet.UpdateClientInputLocks{Locks: 6,
// Position: mgl32.Vec3{1, 2, 3}}
const std::string golden_v924 = bytes({
    0x06, 0x00, 0x00, 0x80, 0x3f, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x40,
    0x40,
});

}  // namespace

TEST_CASE("packet id is 196")
{
    STATIC_REQUIRE(bp::UpdateClientInputLocksPacket::Id == 196);
    STATIC_REQUIRE(bp::has_packet_v<1001, 196>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 196>);
}

// 944 dropped the trailing server position, so the pre-944 body is the same
// varint followed by three floats.
TEST_CASE("update-client-input-locks carries a server position until 944")
{
    using Packet = bp::UpdateClientInputLocksPacket_<924>;

    Packet packet;
    packet.input_lock_component_data = 6;
    packet.server_pos = {.x = 1.0f, .y = 2.0f, .z = 3.0f};
    REQUIRE(encode(packet) == golden_v924);

    const auto back = decode<Packet>(golden_v924);
    REQUIRE(back.input_lock_component_data == 6);
    REQUIRE(back.server_pos.y == 2.0f);

    bp::UpdateClientInputLocksPacket_<944> after;
    after.input_lock_component_data = 6;
    REQUIRE(encode(after).size() + 12 == golden_v924.size());
}

TEST_CASE("update-client-input-locks round-trips against the golden")
{
    bp::UpdateClientInputLocksPacket packet;
    packet.input_lock_component_data = 70;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::UpdateClientInputLocksPacket>(golden);
    REQUIRE(back.input_lock_component_data == 70);
}

TEST_CASE("the lock data is an unsigned varint, not a zigzag one or a fixed uint32")
{
    bp::UpdateClientInputLocksPacket packet;
    packet.input_lock_component_data = 8190;
    REQUIRE(encode(packet) == golden_all_categories);

    REQUIRE(decode<bp::UpdateClientInputLocksPacket>(golden_all_categories).input_lock_component_data == 8190);
}

TEST_CASE("a lock set with the top bit set survives the round trip unsigned")
{
    bp::UpdateClientInputLocksPacket packet;
    packet.input_lock_component_data = 0xffffffff;
    REQUIRE(encode(packet) == golden_max);

    REQUIRE(decode<bp::UpdateClientInputLocksPacket>(golden_max).input_lock_component_data == 0xffffffff);
}
