#include <string>
#include <variant>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.PlayerUpdateEntityOverrides{
// EntityUniqueID: 7, PropertyIndex: 2,
// Type: packet.PlayerUpdateEntityOverridesTypeClearAll}
const std::string golden_v1001_clear = bytes({
    0x0e, 0x02, 0x00,
});

// generated by gophertunnel: the same packet with
// Type: packet.PlayerUpdateEntityOverridesTypeInt, IntValue: 42
const std::string golden_v1001_int = bytes({
    0x0e, 0x02, 0x02, 0x2a, 0x00, 0x00, 0x00,
});

// generated by gophertunnel: the same packet with
// Type: packet.PlayerUpdateEntityOverridesTypeFloat, FloatValue: 0.5
const std::string golden_v1001_float = bytes({
    0x0e, 0x02, 0x03, 0x00, 0x00, 0x00, 0x3f,
});

// TODO: confirm against BDS. There is no v2168 golden. The r26_u4 dump types each
// payload's restated discriminator as a name-coded string
// ("type": "string", "enum": "UpdateType"), which is what the schema encodes and
// what CloudburstMC itself writes for the two closest siblings
// (SetScoreSerializer_v2168, ResourcePackClientResponseSerializer_v2168). Its own
// PlayerUpdateEntityOverridesSerializer_v2168 writes a single byte there instead --
// 0x0e 0x02 0x02 0x02 0x2a 00 00 00 for the int case -- so it cannot serve as a
// golden for this shape. The dump wins; the assertions below are structural, and
// the leading two bytes are the ones the v1001 goldens above prove.
const std::string prefix_v2168 = golden_v1001_clear.substr(0, 2);

}  // namespace

TEST_CASE("packet id is 325 at both versions")
{
    STATIC_REQUIRE(bp::PlayerUpdateEntityOverridesPacket_<1001>::Id == 325);
    STATIC_REQUIRE(bp::PlayerUpdateEntityOverridesPacket_<2168>::Id == 325);
}

TEST_CASE("player-update-entity-overrides v1001 writes no payload for a clear")
{
    using Packet = bp::PlayerUpdateEntityOverridesPacket_<1001>;

    Packet packet;
    packet.id = static_cast<bp::ActorUniqueID>(7);
    packet.property_index = 2;
    packet.update_type = bp::UpdateType::CLEAR_OVERRIDES;
    packet.int_value = 42;
    packet.float_value = 0.5F;
    REQUIRE(encode(packet) == golden_v1001_clear);

    const auto back = decode<Packet>(golden_v1001_clear);
    REQUIRE(back.id == static_cast<bp::ActorUniqueID>(7));
    REQUIRE(back.property_index == 2);
    REQUIRE(back.update_type == bp::UpdateType::CLEAR_OVERRIDES);
}

TEST_CASE("player-update-entity-overrides v1001 gates the payload on the update type")
{
    using Packet = bp::PlayerUpdateEntityOverridesPacket_<1001>;

    Packet packet;
    packet.id = static_cast<bp::ActorUniqueID>(7);
    packet.property_index = 2;
    packet.update_type = bp::UpdateType::SET_INT_OVERRIDE;
    packet.int_value = 42;
    packet.float_value = 0.5F;
    REQUIRE(encode(packet) == golden_v1001_int);
    REQUIRE(decode<Packet>(golden_v1001_int).int_value == 42);

    packet.update_type = bp::UpdateType::SET_FLOAT_OVERRIDE;
    REQUIRE(encode(packet) == golden_v1001_float);
    REQUIRE(decode<Packet>(golden_v1001_float).float_value == 0.5F);
}

TEST_CASE("player-update-entity-overrides v2168 round-trips through its own serializer")
{
    using Packet = bp::PlayerUpdateEntityOverridesPacket_<2168>;
    using IntOverride = bp::v2168::PlayerUpdateEntityOverridesPacket::IntOverride;

    Packet packet;
    packet.id = static_cast<bp::ActorUniqueID>(7);
    packet.property_index = 2;
    packet.update = IntOverride{.update_type = bp::UpdateType::SET_INT_OVERRIDE, .value = 42};

    const auto encoded = encode(packet);
    REQUIRE(encoded.substr(0, 2) == prefix_v2168);
    REQUIRE(encoded[2] == '\x02');

    const auto back = decode<Packet>(encoded);
    REQUIRE(back.id == static_cast<bp::ActorUniqueID>(7));
    REQUIRE(std::holds_alternative<IntOverride>(back.update));
    REQUIRE(std::get<IntOverride>(back.update).value == 42);
}

TEST_CASE("player-update-entity-overrides v2168 keeps a payload-less case in the union")
{
    using Packet = bp::PlayerUpdateEntityOverridesPacket_<2168>;
    using ClearOverride = bp::v2168::PlayerUpdateEntityOverridesPacket::ClearOverride;
    using FloatOverride = bp::v2168::PlayerUpdateEntityOverridesPacket::FloatOverride;

    Packet packet;
    packet.id = static_cast<bp::ActorUniqueID>(7);
    packet.property_index = 2;
    packet.update = ClearOverride{.update_type = bp::UpdateType::CLEAR_OVERRIDES};

    const auto encoded = encode(packet);
    REQUIRE(encoded[2] == '\x00');
    REQUIRE(std::holds_alternative<ClearOverride>(decode<Packet>(encoded).update));

    packet.update = FloatOverride{.update_type = bp::UpdateType::SET_FLOAT_OVERRIDE, .value = 0.5F};
    const auto floats = encode(packet);
    REQUIRE(floats[2] == '\x03');
    REQUIRE(std::get<FloatOverride>(decode<Packet>(floats).update).value == 0.5F);
}

// The single type byte became a variant index plus the payload's own restated
// type, so no v1001 frame is a valid v2168 one.
TEST_CASE("a v1001 entity-overrides body does not decode as a v2168 one")
{
    REQUIRE(rejects<bp::PlayerUpdateEntityOverridesPacket_<2168>>(golden_v1001_clear));
    REQUIRE(rejects<bp::PlayerUpdateEntityOverridesPacket_<2168>>(golden_v1001_int));

    bp::PlayerUpdateEntityOverridesPacket_<2168> packet;
    packet.id = static_cast<bp::ActorUniqueID>(7);
    packet.property_index = 2;
    packet.update = bp::v2168::PlayerUpdateEntityOverridesPacket::ClearOverride{
        .update_type = bp::UpdateType::CLEAR_OVERRIDES};
    REQUIRE(encode(packet).size() > golden_v1001_clear.size());
    REQUIRE(decode_partial<bp::PlayerUpdateEntityOverridesPacket_<1001>>(encode(packet)).property_index == 2);
}
