#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("LabTablePacket: id + round-trip")
{
    STATIC_REQUIRE(bp::LabTablePacket::Id == 109);

    bp::LabTablePacket pkt;
    pkt.type = bp::LabTablePacketType::StartCombine;
    pkt.pos = bp::BlockPos{4, 5, 6};
    pkt.reaction = bp::LabTableReactionType::IceBomb;

    // generated by gophertunnel:
    // packet.LabTable{ActionType: LabTableActionCombine,
    //   Position: protocol.BlockPos{4,5,6}, ReactionType: 1}
    const std::vector<std::uint8_t> golden{
        0x00, 0x08, 0x0A, 0x0C, 0x01,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::LabTablePacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->type == bp::LabTablePacketType::StartCombine);
    REQUIRE(rt->pos.x == 4);
    REQUIRE(rt->reaction == bp::LabTableReactionType::IceBomb);
}
