#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ResourcePacksInfoPacket: round-trip with one texture pack entry")
{
    STATIC_REQUIRE(bp::ResourcePacksInfoPacket::Id == 6);

    bp::ResourcePacksInfoPacket pkt;
    pkt.resource_pack_required = true;
    pkt.has_addon_packs = false;
    pkt.has_scripts = true;
    pkt.force_disable_vibrant_visuals = false;
    pkt.world_template_id = bp::UUID{0x1122334455667788ULL, 0x99AABBCCDDEEFF00ULL};
    pkt.world_template_version = "1.0";

    bp::PackInfoData entry;
    entry.pack_id = bp::UUID{0xAABBCCDDEEFF0011ULL, 0x2233445566778899ULL};
    entry.pack_version = "1.2.3";
    entry.pack_size = 1024;
    entry.content_key = "";
    entry.sub_pack_name = "sub";
    entry.content_identity = "";
    entry.has_scripts = false;
    entry.is_addon_pack = false;
    entry.is_ray_tracing_capable = false;
    entry.cdn_url = "";
    pkt.resource_packs.push_back(entry);

    // generated by gophertunnel:
    // packet.ResourcePacksInfo{
    //   TexturePackRequired: true, HasAddons: false, HasScripts: true,
    //   ForceDisableVibrantVisuals: false,
    //   WorldTemplateUUID: 11223344-5566-7788-99AA-BBCCDDEEFF00,
    //   WorldTemplateVersion: "1.0",
    //   TexturePacks: [{UUID: AABBCCDD-EEFF-0011-2233-445566778899,
    //                   Version: "1.2.3", Size: 1024, SubPackName: "sub"}]}
    const std::vector<std::uint8_t> golden{
        0x01, 0x00, 0x01, 0x00, 0x88, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11,
        0x00, 0xFF, 0xEE, 0xDD, 0xCC, 0xBB, 0xAA, 0x99, 0x03, 0x31, 0x2E, 0x30,
        0x01, 0x00, 0x11, 0x00, 0xFF, 0xEE, 0xDD, 0xCC, 0xBB, 0xAA, 0x99, 0x88,
        0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x05, 0x31, 0x2E, 0x32, 0x2E, 0x33,
        0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x73, 0x75,
        0x62, 0x00, 0x00, 0x00, 0x00, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ResourcePacksInfoPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->resource_pack_required == true);
    REQUIRE(rt->has_scripts == true);
    REQUIRE(rt->world_template_version == "1.0");
    REQUIRE(rt->resource_packs.size() == 1);
    REQUIRE(rt->resource_packs[0].pack_version == "1.2.3");
    REQUIRE(rt->resource_packs[0].pack_size == 1024);
    REQUIRE(rt->resource_packs[0].sub_pack_name == "sub");
}
