#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("BossEventPacket: id + round-trip with Remove event (empty payload)")
{
    STATIC_REQUIRE(bp::BossEventPacket::Id == 74);

    bp::BossEventPacket pkt;
    pkt.boss_id = static_cast<bp::ActorUniqueID>(-3);
    pkt.event_type = bp::BossEventUpdateType::Remove;

    // generated by gophertunnel:
    // packet.BossEvent{BossEntityUniqueID: -3, EventType: BossEventHide}
    const std::vector<std::uint8_t> golden{0x05, 0x02};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::BossEventPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->boss_id == static_cast<bp::ActorUniqueID>(-3));
    REQUIRE(rt->event_type == bp::BossEventUpdateType::Remove);
}
