#include <string>

#include <bedrock/protocol/edu.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.EducationResourceURI{Resource:
// protocol.EducationSharedResourceURI{ButtonName: "btn", LinkURI: "https://x"}}
const std::string golden = bytes({
    0x03, 0x62, 0x74, 0x6e, 0x09, 0x68, 0x74, 0x74, 0x70, 0x73, 0x3a, 0x2f,
    0x2f, 0x78,
});

}  // namespace

TEST_CASE("packet id is 170")
{
    STATIC_REQUIRE(bp::EduUriResourcePacket_<2168>::Id == 170);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 170>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 170>);
}

TEST_CASE("edu uri resource round-trips against the golden")
{
    bp::EduUriResourcePacket_<2168> packet;
    packet.edu_shared_uri_resource = {.button_name = "btn", .link_uri = "https://x"};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::EduUriResourcePacket_<2168>>(golden);
    REQUIRE(back.edu_shared_uri_resource.button_name == "btn");
    REQUIRE(back.edu_shared_uri_resource.link_uri == "https://x");
}

TEST_CASE("both strings are length-prefixed, so an empty resource is two zero bytes")
{
    REQUIRE(encode(bp::EduUriResourcePacket_<2168>{}) == bytes({0x00, 0x00}));
}
