#include <string>
#include <variant>
#include <vector>

#include <bedrock/protocol/text.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel:
// &packet.Text{TextType: packet.TextTypeObjectAnnouncement, Message: "{}"}
const std::string golden_message_only = bytes({
    0x00, 0x00, 0x0b, 0x02, 0x7b, 0x7d, 0x00, 0x00, 0x00,
});

// generated by gophertunnel:
// &packet.Text{TextType: packet.TextTypeChat, SourceName: "Steve", Message: "hello",
// XUID: "2535400000000000", PlatformChatID: "switch-1",
// FilteredMessage: protocol.Option("h***o")}
const std::string golden_author_and_message = bytes({
    0x00, 0x01, 0x01, 0x05, 0x53, 0x74, 0x65, 0x76, 0x65, 0x05, 0x68, 0x65,
    0x6c, 0x6c, 0x6f, 0x10, 0x32, 0x35, 0x33, 0x35, 0x34, 0x30, 0x30, 0x30,
    0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x30, 0x08, 0x73, 0x77, 0x69,
    0x74, 0x63, 0x68, 0x2d, 0x31, 0x01, 0x05, 0x68, 0x2a, 0x2a, 0x2a, 0x6f,
});

// generated by gophertunnel:
// &packet.Text{NeedsTranslation: true, TextType: packet.TextTypeTranslation,
// Message: "chat.type.text", Parameters: []string{"Alex", "hi"}}
const std::string golden_message_and_params = bytes({
    0x01, 0x02, 0x02, 0x0e, 0x63, 0x68, 0x61, 0x74, 0x2e, 0x74, 0x79, 0x70,
    0x65, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x02, 0x04, 0x41, 0x6c, 0x65, 0x78,
    0x02, 0x68, 0x69, 0x00, 0x00, 0x00,
});

// generated by gophertunnel:
// &packet.Text{TextType: packet.TextTypePopup, Message: "popup"}
const std::string golden_no_params = bytes({
    0x00, 0x02, 0x03, 0x05, 0x70, 0x6f, 0x70, 0x75, 0x70, 0x00, 0x00, 0x00,
    0x00,
});

// generated by gophertunnel (898): &packet.Text{TextType: packet.TextTypeRaw,
// Message: "hi", XUID: "x", PlatformChatID: "p"}
const std::string golden_v898_raw = bytes({
    0x00, 0x00, 0x03, 0x72, 0x61, 0x77, 0x03, 0x74, 0x69, 0x70, 0x0d, 0x73,
    0x79, 0x73, 0x74, 0x65, 0x6d, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
    0x11, 0x74, 0x65, 0x78, 0x74, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x57,
    0x68, 0x69, 0x73, 0x70, 0x65, 0x72, 0x16, 0x74, 0x65, 0x78, 0x74, 0x4f,
    0x62, 0x6a, 0x65, 0x63, 0x74, 0x41, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63,
    0x65, 0x6d, 0x65, 0x6e, 0x74, 0x0a, 0x74, 0x65, 0x78, 0x74, 0x4f, 0x62,
    0x6a, 0x65, 0x63, 0x74, 0x00, 0x02, 0x68, 0x69, 0x01, 0x78, 0x01, 0x70,
    0x00,
});

// generated by gophertunnel (898): &packet.Text{
// TextType: packet.TextTypeChat, SourceName: "s", Message: "hi", XUID: "x",
// PlatformChatID: "p"}
const std::string golden_v898_chat = bytes({
    0x00, 0x01, 0x04, 0x63, 0x68, 0x61, 0x74, 0x07, 0x77, 0x68, 0x69, 0x73,
    0x70, 0x65, 0x72, 0x0c, 0x61, 0x6e, 0x6e, 0x6f, 0x75, 0x6e, 0x63, 0x65,
    0x6d, 0x65, 0x6e, 0x74, 0x01, 0x01, 0x73, 0x02, 0x68, 0x69, 0x01, 0x78,
    0x01, 0x70, 0x00,
});

}  // namespace

TEST_CASE("packet id is 9")
{
    STATIC_REQUIRE(bp::TextPacket::Id == 9);
    STATIC_REQUIRE(bp::has_packet_v<1001, 9>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 9>);
}

TEST_CASE("text round-trips against the goldens")
{
    bp::TextPacket message_only;
    message_only.body = bp::TextPacket::MessageOnly{
        .type = bp::TextPacketType::TextObjectAnnouncement,
        .message = "{}",
    };
    REQUIRE(encode(message_only) == golden_message_only);

    bp::TextPacket author_and_message;
    author_and_message.body = bp::TextPacket::AuthorAndMessage{
        .type = bp::TextPacketType::Chat,
        .author = "Steve",
        .message = "hello",
    };
    author_and_message.xuid = "2535400000000000";
    author_and_message.platform_id = "switch-1";
    author_and_message.filtered_message = "h***o";
    REQUIRE(encode(author_and_message) == golden_author_and_message);

    bp::TextPacket message_and_params;
    message_and_params.localize = true;
    message_and_params.body = bp::TextPacket::MessageAndParams{
        .type = bp::TextPacketType::Translate,
        .message = "chat.type.text",
        .params = {"Alex", "hi"},
    };
    REQUIRE(encode(message_and_params) == golden_message_and_params);

    const auto raw = decode<bp::TextPacket>(golden_message_only);
    REQUIRE_FALSE(raw.localize);
    REQUIRE(raw.body.index() == 0);
    REQUIRE(std::get<0>(raw.body).type == bp::TextPacketType::TextObjectAnnouncement);
    REQUIRE(std::get<0>(raw.body).message == "{}");
    REQUIRE(raw.xuid.empty());
    REQUIRE(raw.platform_id.empty());
    REQUIRE_FALSE(raw.filtered_message.has_value());

    const auto chat = decode<bp::TextPacket>(golden_author_and_message);
    REQUIRE_FALSE(chat.localize);
    REQUIRE(chat.body.index() == 1);
    REQUIRE(std::get<1>(chat.body).type == bp::TextPacketType::Chat);
    REQUIRE(std::get<1>(chat.body).author == "Steve");
    REQUIRE(std::get<1>(chat.body).message == "hello");
    REQUIRE(chat.xuid == "2535400000000000");
    REQUIRE(chat.platform_id == "switch-1");
    REQUIRE(chat.filtered_message == "h***o");

    const auto translated = decode<bp::TextPacket>(golden_message_and_params);
    REQUIRE(translated.localize);
    REQUIRE(translated.body.index() == 2);
    REQUIRE(std::get<2>(translated.body).type == bp::TextPacketType::Translate);
    REQUIRE(std::get<2>(translated.body).message == "chat.type.text");
    REQUIRE(std::get<2>(translated.body).params == std::vector<std::string>{"Alex", "hi"});
}

TEST_CASE("an empty parameter list still writes its count")
{
    bp::TextPacket packet;
    packet.body = bp::TextPacket::MessageAndParams{
        .type = bp::TextPacketType::Popup,
        .message = "popup",
    };
    REQUIRE(encode(packet) == golden_no_params);

    const auto back = decode<bp::TextPacket>(golden_no_params);
    REQUIRE(back.body.index() == 2);
    REQUIRE(std::get<2>(back.body).params.empty());
}

TEST_CASE("an empty filtered message is not an absent one")
{
    bp::TextPacket absent;
    absent.body = bp::TextPacket::MessageOnly{
        .type = bp::TextPacketType::Raw,
        .message = "x",
    };

    bp::TextPacket empty = absent;
    empty.filtered_message = "";

    REQUIRE(encode(empty).size() == encode(absent).size() + 1);
    REQUIRE(decode<bp::TextPacket>(encode(empty)).filtered_message == "");
    REQUIRE_FALSE(decode<bp::TextPacket>(encode(absent)).filtered_message.has_value());
}

// 898 broke cereal into writing each variant case's bound enumerator names ahead
// of its tag -- six constant strings on a raw message, 74 of the packet's 85
// bytes. 924 fixed it. The window is exactly [898, 924).
TEST_CASE("text v898 carries the enumerator names cereal wrote by mistake")
{
    using Packet = bp::TextPacket_<898>;

    Packet packet;
    packet.localize = false;
    packet.body = Packet::MessageOnly{.type = bp::TextPacketType::Raw, .message = "hi"};
    packet.xuid = "x";
    packet.platform_id = "p";
    REQUIRE(encode(packet) == golden_v898_raw);
    REQUIRE(encode(packet).size() == 85);

    const auto back = decode<Packet>(golden_v898_raw);
    REQUIRE(std::get<0>(back.body).message == "hi");
    REQUIRE(back.platform_id == "p");
}

TEST_CASE("each text v898 case writes its own run of constants")
{
    using Packet = bp::TextPacket_<898>;

    Packet packet;
    packet.localize = false;
    packet.body = Packet::AuthorAndMessage{
        .type = bp::TextPacketType::Chat, .author = "s", .message = "hi"};
    packet.xuid = "x";
    packet.platform_id = "p";
    REQUIRE(encode(packet) == golden_v898_chat);

    REQUIRE(decode<Packet>(golden_v898_chat).body.index() == 1);
}

// The constants are gone either side of the window: 924 fixed the bug, and the
// era below 898 never had it.
TEST_CASE("the text constants sit only in the 898 window")
{
    bp::TextPacket_<897> before;
    before.localize = false;
    before.body = bp::TextPacket_<897>::MessageOnly{.type = bp::TextPacketType::Raw, .message = "hi"};
    before.xuid = "x";
    before.platform_id = "p";

    bp::TextPacket_<924> after;
    after.localize = false;
    after.body = bp::TextPacket_<924>::MessageOnly{.type = bp::TextPacketType::Raw, .message = "hi"};
    after.xuid = "x";
    after.platform_id = "p";

    REQUIRE(encode(before) == encode(after));
    REQUIRE(encode(before).size() + 74 == golden_v898_raw.size());
}
