#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("AnvilDamagePacket: id + round-trip")
{
    STATIC_REQUIRE(bp::AnvilDamagePacket::Id == 141);

    bp::AnvilDamagePacket pkt;
    pkt.damage = 7;
    pkt.position = bp::BlockPos{1, 2, 3};

    // generated by gophertunnel:
    // packet.AnvilDamage{Damage: 7, AnvilPosition: protocol.BlockPos{1, 2, 3}}
    const std::vector<std::uint8_t> golden{
        0x07, 0x02, 0x04, 0x06,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::AnvilDamagePacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->damage == 7);
    REQUIRE(rt->position.x == 1);
    REQUIRE(rt->position.y == 2);
    REQUIRE(rt->position.z == 3);
}
