#include <optional>
#include <string>

#include "fixture.hpp"

namespace {

using Packet1001 = bp::SetScoreboardIdentityPacket_<1001>;
using Packet2168 = bp::SetScoreboardIdentityPacket_<2168>;

// generated by gophertunnel:
// packet.SetScoreboardIdentity{ActionType: packet.ScoreboardIdentityActionRegister,
//   Entries: []protocol.ScoreboardIdentityEntry{{EntryID: 1, EntityUniqueID: 7},
//     {EntryID: 2, EntityUniqueID: 8}}}
const std::string golden_v1001_update = bytes({
    0x00, 0x02, 0x02, 0x0E, 0x04, 0x10,
});

// generated by gophertunnel:
// packet.SetScoreboardIdentity{ActionType: packet.ScoreboardIdentityActionClear,
//   Entries: []protocol.ScoreboardIdentityEntry{{EntryID: 1}}}
const std::string golden_v1001_remove = bytes({
    0x01, 0x01, 0x02,
});

// generated by CloudburstMC Bedrock_v2168:
// SetScoreboardIdentityPacket{action: ADD, entries: [Entry(1, 7), Entry(2, 8)]}
const std::string golden_v2168_update = bytes({
    0x00, 0x02, 0x02, 0x01, 0x0E, 0x04, 0x01, 0x10,
});

// generated by CloudburstMC Bedrock_v2168:
// SetScoreboardIdentityPacket{action: REMOVE, entries: [Entry(1, 0)]}
const std::string golden_v2168_remove = bytes({
    0x01, 0x01, 0x02, 0x00,
});

}  // namespace

TEST_CASE("SetScoreboardIdentityPacket: id")
{
    STATIC_REQUIRE(bp::SetScoreboardIdentityPacket_<975>::Id == 112);
    STATIC_REQUIRE(bp::SetScoreboardIdentityPacket_<1001>::Id == 112);
    STATIC_REQUIRE(bp::SetScoreboardIdentityPacket_<2168>::Id == 112);
}

TEST_CASE("SetScoreboardIdentityPacket: v1001 round-trip")
{
    Packet1001 update;
    update.type = bp::ScoreboardIdentityPacketType::UPDATE;
    update.identity_info = {
        {.scoreboard_id = {.raw_id = 1}, .player_id = {.actor_unique_id = 7}},
        {.scoreboard_id = {.raw_id = 2}, .player_id = {.actor_unique_id = 8}},
    };
    REQUIRE(encode(update) == golden_v1001_update);

    Packet1001 remove;
    remove.type = bp::ScoreboardIdentityPacketType::REMOVE;
    remove.removed_identity_info = {{.raw_id = 1}};
    REQUIRE(encode(remove) == golden_v1001_remove);

    const auto rt = decode<Packet1001>(golden_v1001_update);
    REQUIRE(rt.identity_info.size() == 2);
    REQUIRE(rt.identity_info[1].player_id.actor_unique_id == 8);
    REQUIRE(rt.removed_identity_info.empty());
}

TEST_CASE("SetScoreboardIdentityPacket: v2168 round-trip")
{
    Packet2168 update;
    update.type = bp::ScoreboardIdentityPacketType::UPDATE;
    update.identity_info = {
        {.scoreboard_id = {.raw_id = 1}, .player_id = bp::PlayerScoreboardId{.actor_unique_id = 7}},
        {.scoreboard_id = {.raw_id = 2}, .player_id = bp::PlayerScoreboardId{.actor_unique_id = 8}},
    };
    REQUIRE(encode(update) == golden_v2168_update);

    Packet2168 remove;
    remove.type = bp::ScoreboardIdentityPacketType::REMOVE;
    remove.identity_info = {{.scoreboard_id = {.raw_id = 1}, .player_id = std::nullopt}};
    REQUIRE(encode(remove) == golden_v2168_remove);

    const auto rt = decode<Packet2168>(golden_v2168_remove);
    REQUIRE(rt.identity_info.size() == 1);
    REQUIRE_FALSE(rt.identity_info[0].player_id.has_value());
}

// 1001 drove the per-entry player id off the packet-level action -- one entry shape
// for UPDATE, another for REMOVE -- so a removal entry was a bare scoreboard id and
// carried no room for a player id at all. 2168 gives every entry one shape with an
// explicit presence byte.
TEST_CASE("SetScoreboardIdentityPacket: the v2168 entry costs one flag per entry")
{
    REQUIRE(golden_v2168_update.size() == golden_v1001_update.size() + 2);
    REQUIRE(golden_v2168_remove.size() == golden_v1001_remove.size() + 1);
}

TEST_CASE("SetScoreboardIdentityPacket: a v1001 body does not decode as a v2168 one")
{
    REQUIRE(rejects<Packet2168>(golden_v1001_update));

    const auto wrong = decode_partial<Packet1001>(golden_v2168_update);
    REQUIRE(wrong.identity_info.size() == 2);
    REQUIRE(wrong.identity_info[0].player_id.actor_unique_id == -1);
}
