#include <string>

#include <bedrock/protocol/crafting.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.PlayerEnchantOptions{Options:
// []protocol.EnchantmentOption{{Cost: 200, Enchantments: protocol.ItemEnchantments{Slot: 2,
// Enchantments: [3][]protocol.EnchantmentInstance{{{Type: 9, Level: 5}, {Type: 36, Level: 1}},
// {}, {{Type: 43, Level: 255}}}}, Name: "animal imbue range", RecipeNetworkID: 300}, {Cost: 0,
// Enchantments: protocol.ItemEnchantments{Slot: -1}, Name: "z", RecipeNetworkID: 1}}}
const std::string golden = bytes({
    0x02, 0xc8, 0x02, 0x00, 0x00, 0x00, 0x02, 0x09, 0x05, 0x24, 0x01, 0x00,
    0x01, 0x2b, 0xff, 0x12, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x20, 0x69,
    0x6d, 0x62, 0x75, 0x65, 0x20, 0x72, 0x61, 0x6e, 0x67, 0x65, 0xac, 0x02,
    0x00, 0xff, 0xff, 0xff, 0xff, 0x00, 0x00, 0x00, 0x01, 0x7a, 0x01,
});

// generated by gophertunnel: &packet.PlayerEnchantOptions{}
const std::string golden_empty = bytes({
    0x00,
});

}  // namespace

TEST_CASE("packet id is 146")
{
    STATIC_REQUIRE(bp::PlayerEnchantOptionsPacket_<2168>::Id == 146);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 146>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 146>);
}

TEST_CASE("player-enchant-options round-trips against the golden")
{
    bp::ItemEnchantOption first;
    first.cost = 200;
    first.enchants.slot = 2;
    first.enchants.item_enchants[0] = {
        {.enchant_type = bp::Enchant::Type::SHARPNESS, .level = 5},
        {.enchant_type = bp::Enchant::Type::SOUL_SPEED, .level = 1},
    };
    first.enchants.item_enchants[2] = {
        {.enchant_type = bp::Enchant::Type::INVALID_ENCHANTMENT, .level = 255},
    };
    first.enchant_name = "animal imbue range";
    first.enchant_net_id = {.raw_id = 300};

    bp::ItemEnchantOption second;
    second.enchants.slot = -1;
    second.enchant_name = "z";
    second.enchant_net_id = {.raw_id = 1};

    bp::PlayerEnchantOptionsPacket_<2168> packet;
    packet.options = {first, second};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::PlayerEnchantOptionsPacket_<2168>>(golden);
    REQUIRE(back.options.size() == 2);
    REQUIRE(back.options[0].cost == 200);
    REQUIRE(back.options[0].enchants.slot == 2);
    REQUIRE(back.options[0].enchants.item_enchants[0].size() == 2);
    REQUIRE(back.options[0].enchants.item_enchants[0][0].enchant_type == bp::Enchant::Type::SHARPNESS);
    REQUIRE(back.options[0].enchants.item_enchants[0][0].level == 5);
    REQUIRE(back.options[0].enchants.item_enchants[0][1].enchant_type == bp::Enchant::Type::SOUL_SPEED);
    REQUIRE(back.options[0].enchants.item_enchants[0][1].level == 1);
    REQUIRE(back.options[0].enchants.item_enchants[1].empty());
    REQUIRE(back.options[0].enchants.item_enchants[2].size() == 1);
    REQUIRE(back.options[0].enchants.item_enchants[2][0].enchant_type == bp::Enchant::Type::INVALID_ENCHANTMENT);
    REQUIRE(back.options[0].enchants.item_enchants[2][0].level == 255);
    REQUIRE(back.options[0].enchant_name == "animal imbue range");
    REQUIRE(back.options[0].enchant_net_id.raw_id == 300);
    REQUIRE(back.options[1].cost == 0);
    REQUIRE(back.options[1].enchants.slot == -1);
    REQUIRE(back.options[1].enchants.item_enchants[0].empty());
    REQUIRE(back.options[1].enchant_name == "z");
    REQUIRE(back.options[1].enchant_net_id.raw_id == 1);
}

TEST_CASE("an empty player-enchant-options body is a lone zero count")
{
    bp::PlayerEnchantOptionsPacket_<2168> packet;
    REQUIRE(encode(packet) == golden_empty);
    REQUIRE(decode<bp::PlayerEnchantOptionsPacket_<2168>>(golden_empty).options.empty());
}

TEST_CASE("an enchant option's cost is one byte and its slot a fixed int32")
{
    bp::ItemEnchantOption option;
    option.cost = 200;
    option.enchants.slot = -1;

    bp::PlayerEnchantOptionsPacket_<2168> packet;
    packet.options = {option};

    const auto wire = encode(packet);
    REQUIRE(wire.size() == 11);

    const auto back = decode<bp::PlayerEnchantOptionsPacket_<2168>>(wire);
    REQUIRE(back.options[0].cost == 200);
    REQUIRE(back.options[0].enchants.slot == -1);
}
