#include <cstdint>
#include <string>

#include <bedrock/protocol/attribute.h>
#include <bedrock/protocol/player.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.SetSpawnPosition{SpawnType: packet.SpawnTypeWorld,
// Position: protocol.BlockPos{1, 2, 3}, Dimension: 1,
// SpawnPosition: protocol.BlockPos{4, 5, 6}}
const std::string golden = bytes({
    0x02, 0x02, 0x04, 0x06, 0x02, 0x08, 0x0a, 0x0c,
});

// generated by gophertunnel: &packet.SetSpawnPosition{SpawnType: packet.SpawnTypePlayer,
// Position: protocol.BlockPos{-1, -64, 300}, Dimension: 2,
// SpawnPosition: protocol.BlockPos{-2147483648, -2147483648, -2147483648}}
const std::string golden_negative = bytes({
    0x00, 0x01, 0x7f, 0xd8, 0x04, 0x04, 0xff, 0xff, 0xff, 0xff, 0x0f, 0xff,
    0xff, 0xff, 0xff, 0x0f, 0xff, 0xff, 0xff, 0xff, 0x0f,
});

}  // namespace

TEST_CASE("packet id is 43")
{
    STATIC_REQUIRE(bp::SetSpawnPositionPacket_<2168>::Id == 43);
    STATIC_REQUIRE(bp::has_packet_v<1001, 43>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 43>);
}

TEST_CASE("set-spawn-position round-trips against the golden")
{
    bp::SetSpawnPositionPacket_<2168> packet;
    packet.spawn_pos_type = bp::SpawnPositionType::WORLD_SPAWN;
    packet.pos = {.x = 1, .y = 2, .z = 3};
    packet.dimension_type = bp::DimensionType{1};
    packet.spawn_block_pos = {.x = 4, .y = 5, .z = 6};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::SetSpawnPositionPacket_<2168>>(golden);
    REQUIRE(back.spawn_pos_type == bp::SpawnPositionType::WORLD_SPAWN);
    REQUIRE(back.pos.x == 1);
    REQUIRE(back.pos.y == 2);
    REQUIRE(back.pos.z == 3);
    REQUIRE(back.dimension_type == bp::DimensionType{1});
    REQUIRE(back.spawn_block_pos.x == 4);
    REQUIRE(back.spawn_block_pos.y == 5);
    REQUIRE(back.spawn_block_pos.z == 6);
}

TEST_CASE("set-spawn-position writes every block coordinate as a signed varint")
{
    bp::SetSpawnPositionPacket_<2168> packet;
    packet.spawn_pos_type = bp::SpawnPositionType::PLAYER_RESPAWN;
    packet.pos = {.x = -1, .y = -64, .z = 300};
    packet.dimension_type = bp::DimensionType{2};
    packet.spawn_block_pos = {.x = INT32_MIN, .y = INT32_MIN, .z = INT32_MIN};
    REQUIRE(encode(packet) == golden_negative);

    const auto back = decode<bp::SetSpawnPositionPacket_<2168>>(golden_negative);
    REQUIRE(back.pos.x == -1);
    REQUIRE(back.pos.y == -64);
    REQUIRE(back.pos.z == 300);
    REQUIRE(back.dimension_type == bp::DimensionType{2});
    REQUIRE(back.spawn_block_pos.x == INT32_MIN);
    REQUIRE(back.spawn_block_pos.z == INT32_MIN);
}
