#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("SpawnParticleEffectPacket: id + round-trip with no molang variables")
{
    STATIC_REQUIRE(bp::SpawnParticleEffectPacket::Id == 118);

    bp::SpawnParticleEffectPacket pkt;
    pkt.vanilla_dimension_id = 0;
    pkt.actor_id = static_cast<bp::ActorUniqueID>(-1);
    pkt.pos = bp::Vec3{1.0f, 2.0f, 3.0f};
    pkt.effect_name = "minecraft:explosion";
    pkt.molang_variables = std::nullopt;

    // generated by gophertunnel:
    // packet.SpawnParticleEffect{Dimension: 0, EntityUniqueID: -1,
    //   Position: mgl32.Vec3{1,2,3}, ParticleName: "minecraft:explosion"}
    const std::vector<std::uint8_t> golden{
        0x00, 0x01, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00,
        0x40, 0x40, 0x13, 0x6D, 0x69, 0x6E, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74,
        0x3A, 0x65, 0x78, 0x70, 0x6C, 0x6F, 0x73, 0x69, 0x6F, 0x6E, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::SpawnParticleEffectPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->vanilla_dimension_id == 0);
    REQUIRE(rt->actor_id == static_cast<bp::ActorUniqueID>(-1));
    REQUIRE(rt->effect_name == "minecraft:explosion");
    REQUIRE_FALSE(rt->molang_variables.has_value());
}
