#include <string>

#include <bedrock/protocol/ui.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ServerSettingsResponse{FormID: 300,
// FormData: []byte(`{"type":"custom_form"}`)}
const std::string golden = bytes({
    0xac, 0x02, 0x16, 0x7b, 0x22, 0x74, 0x79, 0x70, 0x65, 0x22, 0x3a, 0x22,
    0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x22,
    0x7d,
});

// generated by gophertunnel: &packet.ServerSettingsResponse{FormID: 0, FormData: nil}
const std::string golden_empty = bytes({
    0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 103")
{
    STATIC_REQUIRE(bp::ServerSettingsResponsePacket_<2168>::Id == 103);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 103>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 103>);
}

TEST_CASE("server-settings-response round-trips against the golden")
{
    bp::ServerSettingsResponsePacket_<2168> packet;
    packet.form_id = 300;
    packet.form_json = R"({"type":"custom_form"})";
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::ServerSettingsResponsePacket_<2168>>(golden);
    REQUIRE(back.form_id == 300);
    REQUIRE(back.form_json == R"({"type":"custom_form"})");
}

TEST_CASE("an empty form json is still a length prefix")
{
    bp::ServerSettingsResponsePacket_<2168> packet;
    REQUIRE(encode(packet) == golden_empty);
    REQUIRE(decode<bp::ServerSettingsResponsePacket_<2168>>(golden_empty).form_json.empty());
}

TEST_CASE("a form json longer than 127 bytes takes a two-byte length prefix")
{
    bp::ServerSettingsResponsePacket_<2168> packet;
    packet.form_json = std::string(200, 'a');
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 203);
    REQUIRE(decode<bp::ServerSettingsResponsePacket_<2168>>(wire).form_json == std::string(200, 'a'));
}
