#include <string>

#include <bedrock/protocol/edu.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.CodeBuilderSource{Operation:
// packet.CodeBuilderOperationReset, Category: packet.CodeBuilderCategoryInstantiation,
// CodeStatus: packet.CodeBuilderStatusSucceeded}
const std::string golden = bytes({
    0x03, 0x02, 0x05,
});

// generated by gophertunnel: &packet.CodeBuilderSource{Operation:
// packet.CodeBuilderOperationNone, Category: packet.CodeBuilderCategoryNone,
// CodeStatus: packet.CodeBuilderStatusNone}
const std::string golden_all_none = bytes({
    0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 178")
{
    STATIC_REQUIRE(bp::CodeBuilderSourcePacket_<2168>::Id == 178);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 178>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 178>);
}

TEST_CASE("code-builder source round-trips against the golden")
{
    bp::CodeBuilderSourcePacket_<2168> packet;
    packet.operation = bp::Operation::RESET;
    packet.category = bp::Category::INSTANTIATION;
    packet.code_status = bp::CodeStatus::SUCCEEDED;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::CodeBuilderSourcePacket_<2168>>(golden);
    REQUIRE(back.operation == bp::Operation::RESET);
    REQUIRE(back.category == bp::Category::INSTANTIATION);
    REQUIRE(back.code_status == bp::CodeStatus::SUCCEEDED);
}

TEST_CASE("a code-builder source body still writes three bytes with every field None")
{
    bp::CodeBuilderSourcePacket_<2168> packet;
    packet.operation = bp::Operation::NONE;
    packet.category = bp::Category::NONE;
    packet.code_status = bp::CodeStatus::NONE;
    REQUIRE(encode(packet) == golden_all_none);

    const auto back = decode<bp::CodeBuilderSourcePacket_<2168>>(golden_all_none);
    REQUIRE(back.operation == bp::Operation::NONE);
    REQUIRE(back.category == bp::Category::NONE);
    REQUIRE(back.code_status == bp::CodeStatus::NONE);
}

TEST_CASE("a code-builder source operation above 127 stays a single byte")
{
    bp::CodeBuilderSourcePacket_<2168> packet;
    packet.operation = static_cast<bp::Operation>(200);
    packet.category = bp::Category::CODE_STATUS;
    packet.code_status = bp::CodeStatus::IN_PROGRESS;
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 3);

    const auto back = decode<bp::CodeBuilderSourcePacket_<2168>>(wire);
    REQUIRE(back.operation == static_cast<bp::Operation>(200));
    REQUIRE(back.category == bp::Category::CODE_STATUS);
    REQUIRE(back.code_status == bp::CodeStatus::IN_PROGRESS);
    REQUIRE(rejects<bp::CodeBuilderSourcePacket_<2168>>(wire.substr(0, 2)));
}
