#include <bitset>
#include <cstddef>
#include <initializer_list>
#include <optional>
#include <string>
#include <vector>

#include "fixture.hpp"

namespace {

using Older = bp::PlayerAuthInputPacket_<1001>;
using Newer = bp::PlayerAuthInputPacket_<2168>;
using OldFlag = Older::InputData;
using NewFlag = Newer::InputData;

Older fill_v1001()
{
    Older packet;
    packet.rot = {.x = 1.0f, .y = 2.0f};
    packet.pos = {.x = 4.0f, .y = 5.0f, .z = 6.0f};
    packet.move = {.x = 7.0f, .y = 8.0f};
    packet.y_head_rot = 3.0f;
    packet.input_mode = bp::InputMode::TOUCH;
    packet.play_mode = bp::ClientPlayMode::NORMAL;
    packet.new_interaction_model = bp::NewInteractionModel::CROSSHAIR;
    packet.interact_rotation = {.x = 9.0f, .y = 10.0f};
    packet.client_tick = static_cast<bp::PlayerInputTick>(200);
    packet.pos_delta = {.x = 11.0f, .y = 12.0f, .z = 13.0f};
    packet.analog_move_vector = {.x = 14.0f, .y = 15.0f};
    packet.camera_orientation = {.x = 16.0f, .y = 17.0f, .z = 18.0f};
    packet.raw_move_vector = {.x = 19.0f, .y = 20.0f};
    return packet;
}

Newer fill_v2168()
{
    Newer packet;
    packet.rot = {.x = 1.0f, .y = 2.0f};
    packet.pos = {.x = 4.0f, .y = 5.0f, .z = 6.0f};
    packet.move = {.x = 7.0f, .y = 8.0f};
    packet.y_head_rot = 3.0f;
    packet.input_mode = bp::InputMode::TOUCH;
    packet.play_mode = bp::ClientPlayMode::NORMAL;
    packet.new_interaction_model = bp::NewInteractionModel::CROSSHAIR;
    packet.interact_rotation = {.x = 9.0f, .y = 10.0f};
    packet.client_tick = static_cast<bp::PlayerInputTick>(200);
    packet.pos_delta = {.x = 11.0f, .y = 12.0f, .z = 13.0f};
    packet.analog_move_vector = {.x = 14.0f, .y = 15.0f};
    packet.camera_orientation = {.x = 16.0f, .y = 17.0f, .z = 18.0f};
    packet.raw_move_vector = {.x = 19.0f, .y = 20.0f};
    return packet;
}

// The width is INPUT_NUM, so it moves with the enum: 65 at 1001, 66 once
// InternalUpdate lands at 2168.
template <std::size_t N, typename Flag>
std::bitset<N> flags(std::initializer_list<Flag> set)
{
    std::bitset<N> out;
    for (Flag f : set) {
        out.set(static_cast<std::size_t>(f));
    }
    return out;
}

}  // namespace

TEST_CASE("PlayerAuthInputPacket: id")
{
    STATIC_REQUIRE(bp::PlayerAuthInputPacket_<975>::Id == 144);
    STATIC_REQUIRE(bp::PlayerAuthInputPacket_<1001>::Id == 144);
    STATIC_REQUIRE(bp::PlayerAuthInputPacket_<2168>::Id == 144);
}

TEST_CASE("PlayerAuthInputPacket: v1001 round-trip with no gated payload")
{
    Older packet = fill_v1001();
    packet.input_data = flags<65>({OldFlag::ASCEND});

    // generated by gophertunnel:
    // packet.PlayerAuthInput{Pitch: 1, Yaw: 2, Position: {4, 5, 6}, MoveVector: {7, 8},
    //   HeadYaw: 3, InputData: NewBitset(65) with InputFlagAscend set, InputMode: 2,
    //   PlayMode: 0, InteractionModel: 1, InteractPitch: 9, InteractYaw: 10, Tick: 200,
    //   Delta: {11, 12, 13}, AnalogueMoveVector: {14, 15},
    //   CameraOrientation: {16, 17, 18}, RawMoveVector: {19, 20}}
    const std::string golden = bytes({
    0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x80, 0x40,
    0x00, 0x00, 0xA0, 0x40, 0x00, 0x00, 0xC0, 0x40, 0x00, 0x00, 0xE0, 0x40,
    0x00, 0x00, 0x00, 0x41, 0x00, 0x00, 0x40, 0x40, 0x01, 0x02, 0x00, 0x01,
    0x00, 0x00, 0x10, 0x41, 0x00, 0x00, 0x20, 0x41, 0xC8, 0x01, 0x00, 0x00,
    0x30, 0x41, 0x00, 0x00, 0x40, 0x41, 0x00, 0x00, 0x50, 0x41, 0x00, 0x00,
    0x60, 0x41, 0x00, 0x00, 0x70, 0x41, 0x00, 0x00, 0x80, 0x41, 0x00, 0x00,
    0x88, 0x41, 0x00, 0x00, 0x90, 0x41, 0x00, 0x00, 0x98, 0x41, 0x00, 0x00,
    0xA0, 0x41,
});

    REQUIRE(encode(packet) == golden);

    const auto back = decode<Older>(golden);
    REQUIRE(back.input_data.test(static_cast<std::size_t>(OldFlag::ASCEND)));
    REQUIRE(back.input_data.count() == 1);
    REQUIRE(back.client_tick == 200);
}

// The gated arms write in declaration order -- stack request, block actions, then the
// vehicle pair -- which is not flag order. Bit 64 rides along to prove the bitset
// survives past a 64-bit integer.
TEST_CASE("PlayerAuthInputPacket: v1001 round-trip with every modelled arm taken")
{
    Older packet = fill_v1001();
    packet.input_data =
        flags<65>({OldFlag::ASCEND, OldFlag::PERFORM_BLOCK_ACTIONS, OldFlag::PERFORM_ITEM_STACK_REQUEST,
                   OldFlag::IS_IN_CLIENT_PREDICTED_VEHICLE, OldFlag::SNEAK_CURRENT_RAW});
    packet.item_stack_request.client_request_id = {.id = -2};
    packet.player_block_actions = {{.player_action_type = bp::PlayerActionType_<1001>::START_DESTROY_BLOCK,
                                    .pos = {.x = 21, .y = 22, .z = 23},
                                    .facing = 4}};
    packet.vehicle_rot = {.x = 24.0f, .y = 25.0f};
    packet.client_predicted_vehicle = static_cast<bp::ActorUniqueID>(26);

    // generated by gophertunnel:
    // packet.PlayerAuthInput{Pitch: 1, Yaw: 2, Position: {4, 5, 6}, MoveVector: {7, 8},
    //   HeadYaw: 3, InputData: NewBitset(65) with InputFlagAscend,
    //   InputFlagPerformBlockActions, InputFlagPerformItemStackRequest,
    //   InputFlagClientPredictedVehicle and InputFlagSneakCurrentRaw set, InputMode: 2,
    //   PlayMode: 0, InteractionModel: 1, InteractPitch: 9, InteractYaw: 10, Tick: 200,
    //   Delta: {11, 12, 13},
    //   ItemStackRequest: protocol.ItemStackRequest{RequestID: -2},
    //   BlockActions: []protocol.PlayerBlockAction{{Action: protocol.PlayerActionStartBreak,
    //     BlockPos: protocol.BlockPos{21, 22, 23}, Face: 4}},
    //   VehicleRotation: {24, 25}, ClientPredictedVehicle: 26,
    //   AnalogueMoveVector: {14, 15}, CameraOrientation: {16, 17, 18},
    //   RawMoveVector: {19, 20}}
    const std::string golden = bytes({
    0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x80, 0x40,
    0x00, 0x00, 0xA0, 0x40, 0x00, 0x00, 0xC0, 0x40, 0x00, 0x00, 0xE0, 0x40,
    0x00, 0x00, 0x00, 0x41, 0x00, 0x00, 0x40, 0x40, 0x81, 0x80, 0x80, 0x80,
    0x80, 0x83, 0x88, 0x80, 0x80, 0x02, 0x02, 0x00, 0x01, 0x00, 0x00, 0x10,
    0x41, 0x00, 0x00, 0x20, 0x41, 0xC8, 0x01, 0x00, 0x00, 0x30, 0x41, 0x00,
    0x00, 0x40, 0x41, 0x00, 0x00, 0x50, 0x41, 0x03, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x02, 0x00, 0x2A, 0x2C, 0x2E, 0x08, 0x00, 0x00, 0xC0, 0x41,
    0x00, 0x00, 0xC8, 0x41, 0x34, 0x00, 0x00, 0x60, 0x41, 0x00, 0x00, 0x70,
    0x41, 0x00, 0x00, 0x80, 0x41, 0x00, 0x00, 0x88, 0x41, 0x00, 0x00, 0x90,
    0x41, 0x00, 0x00, 0x98, 0x41, 0x00, 0x00, 0xA0, 0x41,
});

    REQUIRE(encode(packet) == golden);

    const auto back = decode<Older>(golden);
    REQUIRE(back.input_data.test(static_cast<std::size_t>(OldFlag::SNEAK_CURRENT_RAW)));
    REQUIRE(back.input_data.count() == 5);
    REQUIRE(back.item_stack_request.client_request_id.id == -2);
    REQUIRE(back.player_block_actions.size() == 1);
    REQUIRE(back.player_block_actions[0].facing == 4);
    REQUIRE(back.client_predicted_vehicle == 26);
}

// The transaction this arm carries keeps the pre-cereal framing the packet still writes at
// 1001 -- no member-present markers, the legacy slots gated on the request id, and `face` a
// varint32 -- over leaves that cerealised with everything else, so the actions inside it do
// carry their markers.
TEST_CASE("PlayerAuthInputPacket: v1001 round-trip with the item interaction arm taken")
{
    using Transaction = bp::legacy::ItemUseInventoryTransaction_<1001>;
    using Use = bp::ItemUseInventoryTransaction_<1001>;

    Older packet = fill_v1001();
    packet.input_data = flags<65>({OldFlag::ASCEND, OldFlag::PERFORM_ITEM_INTERACTION});
    packet.item_use_transaction.id = -4;
    packet.item_use_transaction.slots = {
        {.container_enum = bp::ContainerEnumName::COMBINED_HOTBAR_AND_INVENTORY_CONTAINER, .slots = "\x01\x02\x03"}};

    bp::InventoryAction_<1001> action;
    action.source.type = bp::InventorySourceType::CONTAINER_INVENTORY;
    action.source.container_id = static_cast<bp::ContainerID>(7);
    action.slot = 5;

    packet.item_use_transaction.transaction = Transaction{.actions = {action},
                                                          .action_type = Use::ActionType::USE,
                                                          .trigger_type = Use::TriggerType::PLAYER_INPUT,
                                                          .pos = {.x = 21, .y = 22, .z = 23},
                                                          .face = 4,
                                                          .slot = 5,
                                                          .from_pos = {.x = 27.0f, .y = 28.0f, .z = 29.0f},
                                                          .click_pos = {.x = 30.0f, .y = 31.0f, .z = 32.0f},
                                                          .target_block_id = 33,
                                                          .client_predicted_result = Use::PredictedResult::SUCCESS,
                                                          .client_cooldown_state = Use::ClientCooldownState::ON};

    // generated by gophertunnel:
    // packet.PlayerAuthInput{Pitch: 1, Yaw: 2, Position: {4, 5, 6}, MoveVector: {7, 8},
    //   HeadYaw: 3, InputData: NewBitset(65) with InputFlagAscend and
    //   InputFlagPerformItemInteraction set, InputMode: 2, PlayMode: 0,
    //   InteractionModel: 1, InteractPitch: 9, InteractYaw: 10, Tick: 200,
    //   Delta: {11, 12, 13},
    //   ItemInteractionData: protocol.UseItemTransactionData{LegacyRequestID: -4,
    //     LegacySetItemSlots: []protocol.LegacySetItemSlot{{ContainerID: 12,
    //       Slots: []byte{1, 2, 3}}},
    //     Actions: []protocol.InventoryAction{{SourceType: 0, WindowID: 7,
    //       InventorySlot: 5}},
    //     ActionType: 1, TriggerType: 1, BlockPosition: protocol.BlockPos{21, 22, 23},
    //     BlockFace: 4, HotBarSlot: 5, Position: {27, 28, 29},
    //     ClickedPosition: {30, 31, 32}, BlockRuntimeID: 33, ClientPrediction: 1,
    //     ClientCooldownState: 1},
    //   AnalogueMoveVector: {14, 15}, CameraOrientation: {16, 17, 18},
    //   RawMoveVector: {19, 20}}
    const std::string golden = bytes({
    0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x80, 0x40,
    0x00, 0x00, 0xA0, 0x40, 0x00, 0x00, 0xC0, 0x40, 0x00, 0x00, 0xE0, 0x40,
    0x00, 0x00, 0x00, 0x41, 0x00, 0x00, 0x40, 0x40, 0x81, 0x80, 0x80, 0x80,
    0x40, 0x02, 0x00, 0x01, 0x00, 0x00, 0x10, 0x41, 0x00, 0x00, 0x20, 0x41,
    0xC8, 0x01, 0x00, 0x00, 0x30, 0x41, 0x00, 0x00, 0x40, 0x41, 0x00, 0x00,
    0x50, 0x41, 0x07, 0x01, 0x0C, 0x03, 0x01, 0x02, 0x03, 0x01, 0x00, 0x01,
    0x01, 0x07, 0x01, 0x00, 0x05, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x01, 0x2A,
    0x2C, 0x2E, 0x08, 0x0A, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0xD8, 0x41, 0x00, 0x00, 0xE0, 0x41, 0x00, 0x00, 0xE8, 0x41,
    0x00, 0x00, 0xF0, 0x41, 0x00, 0x00, 0xF8, 0x41, 0x00, 0x00, 0x00, 0x42,
    0x21, 0x01, 0x01, 0x00, 0x00, 0x60, 0x41, 0x00, 0x00, 0x70, 0x41, 0x00,
    0x00, 0x80, 0x41, 0x00, 0x00, 0x88, 0x41, 0x00, 0x00, 0x90, 0x41, 0x00,
    0x00, 0x98, 0x41, 0x00, 0x00, 0xA0, 0x41,
});

    REQUIRE(encode(packet) == golden);

    const auto back = decode<Older>(golden);
    REQUIRE(back.item_use_transaction.id == -4);
    REQUIRE(back.item_use_transaction.slots.size() == 1);
    REQUIRE(back.item_use_transaction.slots[0].slots == "\x01\x02\x03");
    REQUIRE(back.item_use_transaction.transaction.actions.size() == 1);
    REQUIRE(back.item_use_transaction.transaction.actions[0].source.container_id == static_cast<bp::ContainerID>(7));
    REQUIRE_FALSE(back.item_use_transaction.transaction.actions[0].source.flags.has_value());
    REQUIRE(back.item_use_transaction.transaction.face == 4);
    REQUIRE(back.item_use_transaction.transaction.target_block_id == 33);
}

// A request id the gate rejects leaves the slots off the wire, and the read leaves them
// empty -- the id is the only thing that says whether they are there.
TEST_CASE("PlayerAuthInputPacket: the v1001 legacy slots ride on the request id")
{
    Older packet = fill_v1001();
    packet.input_data = flags<65>({OldFlag::PERFORM_ITEM_INTERACTION});
    packet.item_use_transaction.slots = {
        {.container_enum = bp::ContainerEnumName::COMBINED_HOTBAR_AND_INVENTORY_CONTAINER, .slots = "\x01\x02\x03"}};

    packet.item_use_transaction.id = -3;  // odd
    const auto odd = encode(packet);
    packet.item_use_transaction.id = -4;  // negative and even
    REQUIRE(encode(packet).size() == odd.size() + 6);

    REQUIRE(decode<Older>(odd).item_use_transaction.slots.empty());
}

// An untaken arm costs nothing at 1001: no marker, no flag, just the missing payload.
// The top bit is set throughout so that setting the vehicle flag does not also lengthen
// the bitset -- only the arm's own nine bytes move.
TEST_CASE("PlayerAuthInputPacket: a v1001 arm the flags do not take writes no bytes")
{
    Older packet = fill_v1001();
    packet.input_data = flags<65>({OldFlag::ASCEND, OldFlag::SNEAK_CURRENT_RAW});
    packet.vehicle_rot = {.x = 24.0f, .y = 25.0f};
    packet.client_predicted_vehicle = static_cast<bp::ActorUniqueID>(26);
    const auto untaken = encode(packet);

    packet.input_data.set(static_cast<std::size_t>(OldFlag::IS_IN_CLIENT_PREDICTED_VEHICLE));
    REQUIRE(encode(packet).size() == untaken.size() + 9);
}

TEST_CASE("PlayerAuthInputPacket: v2168 round-trip with every optional absent")
{
    Newer packet = fill_v2168();
    packet.input_data = flags<66>({NewFlag::ASCEND});

    // generated by CloudburstMC Bedrock_v2168, with the input_data run replaced by the
    // bitset dump: Cloudburst models the field as a list of set flags, BDS keeps the
    // bitset it always had and cerealises only what surrounds it.
    // PlayerAuthInputPacket{rotation: (1, 2, 3), position: (4, 5, 6), motion: (7, 8),
    //   inputData: [ASCEND], inputMode: TOUCH, playMode: NORMAL,
    //   inputInteractionModel: CROSSHAIR, interactRotation: (9, 10), tick: 200,
    //   delta: (11, 12, 13), itemUseTransaction: null, itemStackRequest: null,
    //   playerActions: [], vehicleRotation: null, predictedVehicle: 0,
    //   analogMoveVector: (14, 15), cameraOrientation: (16, 17, 18),
    //   rawMoveVector: (19, 20)}
    const std::string golden = bytes({
    0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x80, 0x40,
    0x00, 0x00, 0xA0, 0x40, 0x00, 0x00, 0xC0, 0x40, 0x00, 0x00, 0xE0, 0x40,
    0x00, 0x00, 0x00, 0x41, 0x00, 0x00, 0x40, 0x40, 0x01, 0x01, 0x02, 0x00,
    0x02, 0x00, 0x00, 0x10, 0x41, 0x00, 0x00, 0x20, 0x41, 0xC8, 0x01, 0x00,
    0x00, 0x30, 0x41, 0x00, 0x00, 0x40, 0x41, 0x00, 0x00, 0x50, 0x41, 0x01,
    0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x60,
    0x41, 0x00, 0x00, 0x70, 0x41, 0x00, 0x00, 0x80, 0x41, 0x00, 0x00, 0x88,
    0x41, 0x00, 0x00, 0x90, 0x41, 0x00, 0x00, 0x98, 0x41, 0x00, 0x00, 0xA0,
    0x41,
});

    REQUIRE(encode(packet) == golden);

    const auto back = decode<Newer>(golden);
    REQUIRE(back.input_data.test(static_cast<std::size_t>(NewFlag::ASCEND)));
    REQUIRE(back.input_data.count() == 1);
    REQUIRE(back.client_tick == 200);
    REQUIRE_FALSE(back.item_use_transaction.has_value());
    REQUIRE_FALSE(back.item_stack_request.has_value());
    REQUIRE_FALSE(back.player_block_actions.has_value());
    REQUIRE_FALSE(back.vehicle_rot.has_value());
    REQUIRE_FALSE(back.client_predicted_vehicle.has_value());
}

// Bit 64 rides along again: the width is 66 here, so the dump runs ten bytes and the
// top flag lands in the last one.
TEST_CASE("PlayerAuthInputPacket: v2168 round-trip with block actions and a vehicle")
{
    Newer packet = fill_v2168();
    packet.input_data = flags<66>({NewFlag::ASCEND, NewFlag::PERFORM_BLOCK_ACTIONS,
                                   NewFlag::IS_IN_CLIENT_PREDICTED_VEHICLE, NewFlag::SNEAK_CURRENT_RAW});
    packet.player_block_actions = std::vector<bp::PlayerBlockActionData_<2168>>{
        {.player_action_type = bp::PlayerActionType_<2168>::START_DESTROY_BLOCK,
         .pos = {.x = 21, .y = 22, .z = 23},
         .facing = 4}};
    packet.vehicle_rot = bp::Vec2{.x = 24.0f, .y = 25.0f};
    packet.client_predicted_vehicle = static_cast<bp::ActorUniqueID>(26);

    // generated by CloudburstMC Bedrock_v2168:
    // PlayerAuthInputPacket{rotation: (1, 2, 3), position: (4, 5, 6), motion: (7, 8),
    //   inputData: [ASCEND, PERFORM_BLOCK_ACTIONS, IN_CLIENT_PREDICTED_IN_VEHICLE,
    //   SNEAK_CURRENT_RAW], inputMode: TOUCH, playMode: NORMAL,
    //   inputInteractionModel: CROSSHAIR, interactRotation: (9, 10), tick: 200,
    //   delta: (11, 12, 13), itemUseTransaction: null, itemStackRequest: null,
    //   playerActions: [PlayerBlockActionData(START_BREAK, (21, 22, 23), 4)],
    //   vehicleRotation: (24, 25), predictedVehicle: 26,
    //   analogMoveVector: (14, 15), cameraOrientation: (16, 17, 18),
    //   rawMoveVector: (19, 20)}
    const std::string golden = bytes({
    0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x80, 0x40,
    0x00, 0x00, 0xA0, 0x40, 0x00, 0x00, 0xC0, 0x40, 0x00, 0x00, 0xE0, 0x40,
    0x00, 0x00, 0x00, 0x41, 0x00, 0x00, 0x40, 0x40, 0x01, 0x81, 0x80, 0x80,
    0x80, 0x80, 0x81, 0x88, 0x80, 0x80, 0x02, 0x02, 0x00, 0x02, 0x00, 0x00,
    0x10, 0x41, 0x00, 0x00, 0x20, 0x41, 0xC8, 0x01, 0x00, 0x00, 0x30, 0x41,
    0x00, 0x00, 0x40, 0x41, 0x00, 0x00, 0x50, 0x41, 0x01, 0x00, 0x01, 0x00,
    0x01, 0x01, 0x01, 0x00, 0x2A, 0x2C, 0x2E, 0x08, 0x01, 0x01, 0x00, 0x00,
    0xC0, 0x41, 0x00, 0x00, 0xC8, 0x41, 0x01, 0x01, 0x34, 0x00, 0x00, 0x60,
    0x41, 0x00, 0x00, 0x70, 0x41, 0x00, 0x00, 0x80, 0x41, 0x00, 0x00, 0x88,
    0x41, 0x00, 0x00, 0x90, 0x41, 0x00, 0x00, 0x98, 0x41, 0x00, 0x00, 0xA0,
    0x41,
});

    REQUIRE(encode(packet) == golden);

    const auto back = decode<Newer>(golden);
    REQUIRE(back.input_data.test(static_cast<std::size_t>(NewFlag::SNEAK_CURRENT_RAW)));
    REQUIRE(back.input_data.count() == 4);
    REQUIRE(back.player_block_actions.has_value());
    REQUIRE(back.player_block_actions->size() == 1);
    REQUIRE((*back.player_block_actions)[0].facing == 4);
    REQUIRE(back.vehicle_rot.has_value());
    REQUIRE(back.client_predicted_vehicle.has_value());
    REQUIRE(*back.client_predicted_vehicle == 26);
}

// Each of the six cereal member-present markers costs a byte the payload flag then
// repeats, so five absent optionals are ten bytes at 2168 where 1001 spent none.
TEST_CASE("PlayerAuthInputPacket: an absent v2168 optional is a marker plus a flag")
{
    Newer packet = fill_v2168();
    packet.input_data = flags<66>({NewFlag::ASCEND});
    const auto absent = encode(packet);

    packet.vehicle_rot = bp::Vec2{.x = 24.0f, .y = 25.0f};
    REQUIRE(encode(packet).size() == absent.size() + 8);
}

// The bitset survived the cerealisation; the markers around it did not. The 1001
// reader takes the marker for a one-bit bitset and runs on one byte out of step, so
// every field after it lands on the wrong bytes.
TEST_CASE("PlayerAuthInputPacket: a v1001 body does not decode as a v2168 one")
{
    Older older = fill_v1001();
    older.input_data = flags<65>({OldFlag::ASCEND});

    Newer newer = fill_v2168();
    newer.input_data = flags<66>({NewFlag::ASCEND});

    const auto old_bytes = encode(older);
    const auto new_bytes = encode(newer);
    REQUIRE(old_bytes.size() + 11 == new_bytes.size());
    REQUIRE(rejects<Newer>(old_bytes));

    const auto wrong = decode_partial<Older>(new_bytes);
    REQUIRE(wrong.input_data.count() == 1);
    REQUIRE(wrong.input_mode == bp::InputMode::MOUSE);
}

// gophertunnel gates the position and the face on the action at 1001; 2168 writes
// them unconditionally, so the two forms differ in length for a stop action.
TEST_CASE("PlayerBlockActionData: the pre-2168 form gates its position on the action")
{
    using Data = bp::PlayerBlockActionData_<1001>;
    using Action = bp::PlayerActionType_<1001>;

    // generated by gophertunnel:
    // protocol.PlayerBlockAction{Action: protocol.PlayerActionStartBreak,
    //   BlockPos: protocol.BlockPos{21, 22, 23}, Face: 4}
    const std::string start = bytes({
    0x00, 0x2A, 0x2C, 0x2E, 0x08,
});

    // generated by gophertunnel:
    // protocol.PlayerBlockAction{Action: protocol.PlayerActionStopBreak,
    //   BlockPos: protocol.BlockPos{21, 22, 23}, Face: 4}
    const std::string stop = bytes({
    0x04,
});

    Data began{.player_action_type = Action::START_DESTROY_BLOCK, .pos = {.x = 21, .y = 22, .z = 23}, .facing = 4};
    REQUIRE(encode(began) == start);

    Data stopped{.player_action_type = Action::STOP_DESTROY_BLOCK, .pos = {.x = 21, .y = 22, .z = 23}, .facing = 4};
    REQUIRE(encode(stopped) == stop);

    const auto back = decode<Data>(start);
    REQUIRE(back.pos.x == 21);
    REQUIRE(back.facing == 4);
}

TEST_CASE("PlayerBlockActionData: the 2168 form always writes its position")
{
    using Data = bp::PlayerBlockActionData_<2168>;
    using Action = bp::PlayerActionType_<2168>;

    Data stopped{.player_action_type = Action::STOP_DESTROY_BLOCK, .pos = {.x = 0, .y = 0, .z = 0}, .facing = 0};
    REQUIRE(encode(stopped) == bytes({0x04, 0x00, 0x00, 0x00, 0x00}));

    REQUIRE(rejects<Data>(bytes({0x04})));
}

// 2168 renumbered nothing, but InternalUpdate took 38 and pushed the count sentinel
// off it. The input flags gained the same member at 65.
TEST_CASE("PlayerActionType: the count sentinel moved at 2168")
{
    STATIC_REQUIRE(static_cast<int>(bp::PlayerActionType_<1001>::COUNT) == 38);
    STATIC_REQUIRE(static_cast<int>(bp::PlayerActionType_<2168>::COUNT) == 39);
    STATIC_REQUIRE(static_cast<int>(bp::PlayerActionType_<2168>::INTERNAL_UPDATE) == 38);
    STATIC_REQUIRE(static_cast<int>(NewFlag::INTERNAL_UPDATE) == 65);
}

// input_data is `bitset[InputData.INPUT_NUM]`, so the width is whatever the sentinel
// is at that version rather than a number repeated in two places.
TEST_CASE("PlayerAuthInputPacket: the bitset is as wide as the input count")
{
    STATIC_REQUIRE(decltype(Older::input_data){}.size() == static_cast<std::size_t>(OldFlag::INPUT_NUM));
    STATIC_REQUIRE(decltype(Newer::input_data){}.size() == static_cast<std::size_t>(NewFlag::INPUT_NUM));
    STATIC_REQUIRE(decltype(Older::input_data){}.size() == 65);
    STATIC_REQUIRE(decltype(Newer::input_data){}.size() == 66);
}
