#include <string>

#include <bedrock/protocol/chunk.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.NetworkChunkPublisherUpdate{Position:
// protocol.BlockPos{1, -2, 3}, Radius: 160,
// SavedChunks: []protocol.ChunkPos{{0, 0}, {-1, 5}}}
const std::string golden = bytes({
    0x02, 0x03, 0x06, 0xa0, 0x01, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
    0x0a,
});

// generated by gophertunnel: &packet.NetworkChunkPublisherUpdate{Position:
// protocol.BlockPos{0, 0, 0}, Radius: 0}
const std::string golden_empty = bytes({
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 121")
{
    STATIC_REQUIRE(bp::NetworkChunkPublisherUpdatePacket_<2168>::Id == 121);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 121>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 121>);
}

TEST_CASE("network-chunk-publisher-update round-trips against the golden")
{
    bp::NetworkChunkPublisherUpdatePacket_<2168> packet;
    packet.position = {.x = 1, .y = -2, .z = 3};
    packet.radius = 160;
    packet.server_built_chunks = {
        {.x = 0, .z = 0},
        {.x = -1, .z = 5},
    };
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::NetworkChunkPublisherUpdatePacket_<2168>>(golden);
    REQUIRE(back.position.x == 1);
    REQUIRE(back.position.y == -2);
    REQUIRE(back.position.z == 3);
    REQUIRE(back.radius == 160);
    REQUIRE(back.server_built_chunks.size() == 2);
    REQUIRE(back.server_built_chunks[0].x == 0);
    REQUIRE(back.server_built_chunks[0].z == 0);
    REQUIRE(back.server_built_chunks[1].x == -1);
    REQUIRE(back.server_built_chunks[1].z == 5);
}

TEST_CASE("an empty server-built chunk list still writes a four-byte count")
{
    bp::NetworkChunkPublisherUpdatePacket_<2168> packet;
    packet.position = {.x = 0, .y = 0, .z = 0};
    packet.radius = 0;
    const auto wire = encode(packet);
    REQUIRE(wire == golden_empty);
    REQUIRE(wire.size() == 8);
    REQUIRE(decode<bp::NetworkChunkPublisherUpdatePacket_<2168>>(golden_empty).server_built_chunks.empty());
    REQUIRE(rejects<bp::NetworkChunkPublisherUpdatePacket_<2168>>(golden_empty.substr(0, 5)));
}
