#include <string>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

namespace {

template <class T>
std::string encode(const T &value)
{
    std::string buffer;
    bp::BinaryWriter writer{buffer};
    bp::Serializer<T>::serialize(writer, value);
    return buffer;
}

std::string bytes(std::initializer_list<int> raw)
{
    std::string out;
    for (int b : raw) {
        out.push_back(static_cast<char>(b));
    }
    return out;
}

using PacketV975 = bp::InventoryContentPacket_<bp::ProtocolVersion::V975>;
using PacketV1001 = bp::InventoryContentPacket_<bp::ProtocolVersion::V1001>;

std::string empty_item_blob()
{
    return std::string(10, '\0');
}

// A dynamic cursor container holding one stone stack and one empty slot.
template <class Packet, class Item>
Packet sample()
{
    Item stone;
    stone.id = 1;
    stone.stack_size = 64;
    stone.block_runtime_id = 7;
    stone.user_data_buffer = empty_item_blob();

    Packet packet;
    packet.inventory_id = static_cast<bp::ContainerID>(12);
    packet.slots = {stone, Item{}};
    packet.full_container_name.name = bp::ContainerEnumName::CURSOR_CONTAINER;
    packet.full_container_name.dynamic_id = 3;
    return packet;
}

// generated by gophertunnel at 6353c49^ (de090ae, the last pre-1.26.30 commit):
// packet.InventoryContent{WindowID: 12, Content: []protocol.ItemInstance{stone, {}},
//   Container: protocol.FullContainerName{ContainerID: 59,
//   DynamicContainerID: Option[uint32](3)}, StorageItem: protocol.ItemInstance{}}
const std::string golden_v975 = bytes({
    0x0c,        // inventory_id = 12 (uvarint32, though BDS holds a ContainerID)
    0x02,        // slots: count = 2
    0x02,        //   [0].id = 1 (varint32 zigzag)
    0x40, 0x00,  //   [0].stack_size = 64 (uint16)
    0x00,        //   [0].aux_value = 0
    0x00,        //   [0].net_id absent
    0x0e,        //   [0].block_runtime_id = 7 (varint32 zigzag)
    0x0a,        //   [0].user_data_buffer length = 10
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00,        //   [1] = air (a lone zero byte)
    0x3b,        // full_container_name.name = CURSOR_CONTAINER (uint8)
    0x01,        // full_container_name.dynamic_id present
    0x03, 0x00, 0x00, 0x00,  //   = 3 (uint32)
    0x00,        // storage_item = air
});

// generated by gophertunnel (654cd5f): the same packet, with 1001's item form under
// both the slots and the storage item.
const std::string golden_v1001 = bytes({
    0x0c,        // inventory_id = 12 (uvarint32)
    0x02,        // slots: count = 2
    0x01, 0x00,  //   [0].id = 1 (int16)
    0x40, 0x00,  //   [0].stack_size = 64 (uint16)
    0x00,        //   [0].aux_value = 0
    0x00,        //   [0].net_id absent
    0x07,        //   [0].block_runtime_id = 7 (uvarint32)
    0x0a,        //   [0].user_data_buffer length = 10
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  //   [1] = air (eight bytes)
    0x3b,        // full_container_name.name = CURSOR_CONTAINER (uint8)
    0x01,        // full_container_name.dynamic_id present
    0x03, 0x00, 0x00, 0x00,  //   = 3 (uint32)
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // storage_item = air
});

}  // namespace

TEST_CASE("packet id is 49 at both eras")
{
    STATIC_REQUIRE(PacketV975::Id == 49);
    STATIC_REQUIRE(PacketV1001::Id == 49);
}

TEST_CASE("inventory-content v975 round-trips against the golden")
{
    auto packet = sample<PacketV975, bp::base::SerializedNetworkItemStackDescriptor>();
    REQUIRE(encode(packet) == golden_v975);

    bp::BinaryReader reader{golden_v975};
    auto back = bp::Serializer<PacketV975>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->inventory_id == static_cast<bp::ContainerID>(12));
    REQUIRE(back->slots.size() == 2);
    REQUIRE(back->slots[0].block_runtime_id == 7);
    REQUIRE(back->slots[1].id == 0);
    REQUIRE(back->full_container_name.name == bp::ContainerEnumName::CURSOR_CONTAINER);
    REQUIRE(back->full_container_name.dynamic_id == 3);
    REQUIRE(back->storage_item.id == 0);
}

// 1001 cerealised the packet, but its own shape held still: only the item form under
// the slots and the storage item moved.
TEST_CASE("inventory-content v1001 round-trips against the golden")
{
    auto packet = sample<PacketV1001, bp::v1001::SerializedNetworkItemStackDescriptor>();
    REQUIRE(encode(packet) == golden_v1001);

    bp::BinaryReader reader{golden_v1001};
    auto back = bp::Serializer<PacketV1001>::deserialize(reader);
    REQUIRE(back.has_value());
    REQUIRE(reader.getUnreadLength() == 0);
    REQUIRE(back->slots.size() == 2);
    REQUIRE(back->slots[0].id == 1);
    REQUIRE(back->slots[0].block_runtime_id == 7);
    REQUIRE(back->full_container_name.dynamic_id == 3);
}

// A non-dynamic container leaves the id absent, one byte either era.
TEST_CASE("inventory-content omits an absent dynamic container id")
{
    PacketV1001 packet;
    packet.full_container_name.name = bp::ContainerEnumName::INVENTORY_CONTAINER;
    REQUIRE(encode(packet) == bytes({
                                  0x00,  // inventory_id = 0
                                  0x00,  // slots: count = 0
                                  0x1d,  // name = INVENTORY_CONTAINER (29)
                                  0x00,  // dynamic_id absent
                                  0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,  // storage_item = air
                              }));
}
