#include <string>

#include <bedrock/protocol/nbt.hpp>
#include <bedrock/protocol/actor.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.SyncActorProperty{PropertyData: map[string]any{"id": int32(7)}}
const std::string golden = bytes({
    0x0a, 0x00, 0x03, 0x02, 0x69, 0x64, 0x0e, 0x00,
});

}  // namespace

TEST_CASE("packet id is 165")
{
    STATIC_REQUIRE(bp::SyncActorPropertyPacket_<2168>::Id == 165);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 165>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 165>);
}

TEST_CASE("sync actor property round-trips against the golden")
{
    bp::SyncActorPropertyPacket_<2168> packet;
    packet.property_data = bp::CompoundTag{{"id", bp::IntTag{7}}};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::SyncActorPropertyPacket_<2168>>(golden);
    REQUIRE(back.property_data.at("id").get<bp::IntTag>().value() == 7);
}

TEST_CASE("an empty property tag is a rooted three-byte compound")
{
    REQUIRE(encode(bp::SyncActorPropertyPacket_<2168>{}) == bytes({0x0a, 0x00, 0x00}));
}
