#include <type_traits>
#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("UpdateBlockPacket: BlockPos replaces NetworkBlockPos at v944")
{
    STATIC_REQUIRE(bp::UpdateBlockPacket_<0>::Id == 21);
    STATIC_REQUIRE(std::is_same_v<bp::UpdateBlockPacket_<943>,
                                  bp::UpdateBlockPacket_<0>>);
    STATIC_REQUIRE(!std::is_same_v<bp::UpdateBlockPacket_<943>,
                                   bp::UpdateBlockPacket_<944>>);
}

TEST_CASE("UpdateBlockPacket: id + round-trip with v944 signed BlockPos")
{
    bp::UpdateBlockPacket_<975> pkt;
    pkt.pos = bp::BlockPos{1, 64, -3};
    pkt.runtime_id = static_cast<bp::BlockRuntimeId>(42);
    pkt.update_flags = 3;
    pkt.layer = 0;

    // generated by gophertunnel:
    // packet.UpdateBlock{Position: protocol.BlockPos{1, 64, -3}, NewBlockRuntimeID: 42, Flags: 3, Layer: 0}
    const std::vector<std::uint8_t> golden{
        0x02, 0x80, 0x01, 0x05, 0x2A, 0x03, 0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::UpdateBlockPacket_<975>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->pos.x == 1);
    REQUIRE(rt->pos.y == 64);
    REQUIRE(rt->pos.z == -3);
    REQUIRE(rt->runtime_id == static_cast<bp::BlockRuntimeId>(42));
    REQUIRE(rt->update_flags == 3);
}
