#include <string>

#include <protocol/agent.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.AgentAction{Identifier: "req-1",
// Action: packet.AgentActionTypeTransferItemTo, Response: []byte("{\"ok\":true}")}
const std::string golden = bytes({
    0x05, 0x72, 0x65, 0x71, 0x2d, 0x31, 0x11, 0x00, 0x00, 0x00, 0x0b, 0x7b,
    0x22, 0x6f, 0x6b, 0x22, 0x3a, 0x74, 0x72, 0x75, 0x65, 0x7d,
});

// generated by gophertunnel: &packet.AgentAction{Action: packet.AgentActionTypeAttack}
const std::string golden_empty = bytes({
    0x00, 0x01, 0x00, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 181")
{
    STATIC_REQUIRE(bp::AgentActionEventPacket_<2168>::Id == 181);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 181>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 181>);
}

TEST_CASE("agent action event round-trips against the golden")
{
    bp::AgentActionEventPacket_<2168> packet;
    packet.request_id = "req-1";
    packet.action = bp::AgentActionType::TRANSFER_ITEM_TO;
    packet.response = R"({"ok":true})";
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::AgentActionEventPacket_<2168>>(golden);
    REQUIRE(back.request_id == "req-1");
    REQUIRE(back.action == bp::AgentActionType::TRANSFER_ITEM_TO);
    REQUIRE(back.response == R"({"ok":true})");
}

TEST_CASE("the agent action is four fixed bytes between two empty strings")
{
    bp::AgentActionEventPacket_<2168> packet;
    packet.action = bp::AgentActionType::ATTACK;
    REQUIRE(encode(packet) == golden_empty);

    const auto back = decode<bp::AgentActionEventPacket_<2168>>(golden_empty);
    REQUIRE(back.request_id.empty());
    REQUIRE(back.action == bp::AgentActionType::ATTACK);
    REQUIRE(back.response.empty());
}
