#include <string>
#include <type_traits>

#include <bedrock/protocol/item.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.TrimData{Patterns:
// []protocol.TrimPattern{{ItemName: "item_a", PatternID: "pat_a"}},
// Materials: []protocol.TrimMaterial{{MaterialID: "mat_a", Colour: "c",
// ItemName: "item_b"}}}
const std::string golden = bytes({
    0x01, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x61, 0x05, 0x70, 0x61, 0x74,
    0x5f, 0x61, 0x01, 0x05, 0x6d, 0x61, 0x74, 0x5f, 0x61, 0x01, 0x63, 0x06,
    0x69, 0x74, 0x65, 0x6d, 0x5f, 0x62,
});

using Packet = bp::TrimDataPacket;

Packet make()
{
    Packet packet;
    packet.trim_patterns.push_back({.item_name = "item_a", .pattern_id = "pat_a"});
    packet.trim_materials.push_back({.material_id = "mat_a", .color = "c", .item_name = "item_b"});
    return packet;
}

}  // namespace

TEST_CASE("packet id is 302")
{
    STATIC_REQUIRE(Packet::Id == 302);
}

TEST_CASE("trim-data round-trips against the golden")
{
    REQUIRE(encode(make()) == golden);

    const auto back = decode<Packet>(golden);
    REQUIRE(back.trim_patterns.size() == 1);
    REQUIRE(back.trim_patterns[0].item_name == "item_a");
    REQUIRE(back.trim_patterns[0].pattern_id == "pat_a");
    REQUIRE(back.trim_materials.size() == 1);
    REQUIRE(back.trim_materials[0].material_id == "mat_a");
    REQUIRE(back.trim_materials[0].color == "c");
    REQUIRE(back.trim_materials[0].item_name == "item_b");
}

// One declaration spans both eras: the 2168 dump and the 1001 codecs agree field
// for field, so every snapshot resolves to the same type.
TEST_CASE("the v2168 form is the v1001 form")
{
    STATIC_REQUIRE(std::is_same_v<bp::packet_of_t<1001, 302>, Packet>);
    STATIC_REQUIRE(std::is_same_v<bp::packet_of_t<2168, 302>, Packet>);
}

TEST_CASE("an empty trim-data body is two zero counts")
{
    REQUIRE(encode(Packet{}) == bytes({0x00, 0x00}));
}
