#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("AnimateEntityPacket: id + round-trip with a length-prefixed list")
{
    STATIC_REQUIRE(bp::AnimateEntityPacket::Id == 158);

    bp::AnimateEntityPacket pkt;
    pkt.stop_expression_version = bp::MolangVersion::BeforeVersioning;
    pkt.blend_out_time = 0.0f;
    pkt.runtime_ids = {static_cast<bp::ActorRuntimeID>(1), static_cast<bp::ActorRuntimeID>(2)};

    // generated by gophertunnel:
    // packet.AnimateEntity{EntityRuntimeIDs: []uint64{1, 2}}
    const std::vector<std::uint8_t> golden{
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x01, 0x02,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::AnimateEntityPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->runtime_ids.size() == 2);
    REQUIRE(rt->runtime_ids[1] == static_cast<bp::ActorRuntimeID>(2));
}
