#include <optional>
#include <string>

#include <bedrock/protocol/actor.h>
#include <bedrock/protocol/structure.h>

#include "fixture.hpp"

namespace {

using Packet1001 = bp::StructureBlockUpdatePacket_<1001>;
using Packet2168 = bp::StructureBlockUpdatePacket_<2168>;

bp::StructureSettings settings()
{
    return {.palette_name = "default",
            .ignore_entities = true,
            .ignore_blocks = false,
            .allow_non_ticking_player_and_ticking_area_chunks = true,
            .structure_size = {.x = 1, .y = 2, .z = 3},
            .structure_offset = {.x = 4, .y = 5, .z = 6},
            .last_touched_by_player = bp::ActorUniqueID{7},
            .rotation = bp::Rotation::ROTATE_90,
            .mirror = bp::Mirror::X,
            .animation_mode = bp::AnimationMode::BLOCKS,
            .animation_seconds = 0.5f,
            .integrity_value = 1.0f,
            .integrity_seed = bp::RandomSeed{9},
            .pivot = {.x = 0.0f, .y = 1.0f, .z = 2.0f}};
}

Packet1001 fill_v1001()
{
    Packet1001 packet;
    packet.block_pos = {.x = 1, .y = 2, .z = 3};
    packet.data = {.structure_name = {.unredacted_string = "name", .redacted_string = ""},
                   .data_field = "df",
                   .include_players = true,
                   .show_bounding_box = false,
                   .type = bp::StructureBlockType::SAVE,
                   .settings = settings(),
                   .redstone_save_mode = bp::StructureRedstoneSaveMode::SAVES_TO_DISK};
    packet.trigger = true;
    packet.is_waterlogged = false;
    return packet;
}

Packet2168 fill_v2168()
{
    Packet2168 packet;
    packet.block_pos = {.x = 1, .y = 2, .z = 3};
    packet.data = {.structure_name = {.unredacted_string = "name", .redacted_string = std::nullopt},
                   .data_field = "df",
                   .include_players = true,
                   .show_bounding_box = false,
                   .type = bp::StructureBlockType::SAVE,
                   .settings = settings(),
                   .redstone_save_mode = bp::StructureRedstoneSaveMode::SAVES_TO_DISK};
    packet.trigger = true;
    packet.is_waterlogged = false;
    return packet;
}

// generated by gophertunnel:
// packet.StructureBlockUpdate{Position: protocol.BlockPos{1, 2, 3},
//   StructureName: "name", FilteredStructureName: "", DataField: "df",
//   IncludePlayers: true, ShowBoundingBox: false, StructureBlockType: 1,
//   Settings: protocol.StructureSettings{PaletteName: "default", IgnoreEntities: true,
//     IgnoreBlocks: false, AllowNonTickingChunks: true, Size: protocol.BlockPos{1, 2, 3},
//     Offset: protocol.BlockPos{4, 5, 6}, LastEditingPlayerUniqueID: 7, Rotation: 1,
//     Mirror: 1, AnimationMode: 2, AnimationDuration: 0.5, Integrity: 1.0, Seed: 9,
//     Pivot: mgl32.Vec3{0, 1, 2}},
//   RedstoneSaveMode: 1, ShouldTrigger: true, Waterlogged: false}
const std::string golden_v1001 = bytes({
    0x02, 0x04, 0x06, 0x04, 0x6E, 0x61, 0x6D, 0x65, 0x00, 0x02, 0x64, 0x66,
    0x01, 0x00, 0x02, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6C, 0x74, 0x01,
    0x00, 0x01, 0x02, 0x04, 0x06, 0x08, 0x0A, 0x0C, 0x0E, 0x01, 0x01, 0x02,
    0x00, 0x00, 0x00, 0x3F, 0x00, 0x00, 0x80, 0x3F, 0x09, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40,
    0x02, 0x01, 0x00,
});

// The r26_u4 dump types the structure name as Bedrock::Safety::RedactableString, so its
// redacted half is an optional string and costs a presence byte; CloudburstMC
// StructureBlockUpdateSerializer_v2168 still writes a plain filteredName. The literal below is where the two readings coincide:
// an absent redacted name and an empty filteredName are both a single 0x00.
//
// generated by CloudburstMC Bedrock_v2168:
// StructureBlockUpdatePacket{blockPosition: (1, 2, 3),
//   editorData: StructureEditorData("name", "", "df", true, false, SAVE,
//     StructureSettings("default", true, false, true, (1, 2, 3), (4, 5, 6), 7,
//       ROTATE_90, X, BLOCKS, 0.5, 1.0, 9, (0, 1, 2)),
//     SAVES_TO_DISK),
//   powered: true, waterlogged: false}
const std::string golden_v2168 = bytes({
    0x02, 0x04, 0x06, 0x04, 0x6E, 0x61, 0x6D, 0x65, 0x00, 0x02, 0x64, 0x66,
    0x01, 0x00, 0x02, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6C, 0x74, 0x01,
    0x00, 0x01, 0x02, 0x04, 0x06, 0x08, 0x0A, 0x0C, 0x0E, 0x01, 0x01, 0x02,
    0x00, 0x00, 0x00, 0x3F, 0x00, 0x00, 0x80, 0x3F, 0x09, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x40,
    0x01, 0x01, 0x00,
});

}  // namespace

TEST_CASE("StructureBlockUpdatePacket: id")
{
    STATIC_REQUIRE(bp::StructureBlockUpdatePacket_<975>::Id == 90);
    STATIC_REQUIRE(bp::StructureBlockUpdatePacket_<1001>::Id == 90);
    STATIC_REQUIRE(bp::StructureBlockUpdatePacket_<2168>::Id == 90);
}

TEST_CASE("StructureBlockUpdatePacket: v1001 round-trip")
{
    REQUIRE(encode(fill_v1001()) == golden_v1001);

    const auto rt = decode<Packet1001>(golden_v1001);
    REQUIRE(rt.data.structure_name.unredacted_string == "name");
    REQUIRE(rt.data.settings.palette_name == "default");
    REQUIRE(rt.data.settings.rotation == bp::Rotation::ROTATE_90);
    REQUIRE(rt.data.redstone_save_mode == bp::StructureRedstoneSaveMode::SAVES_TO_DISK);
    REQUIRE(rt.trigger);
}

TEST_CASE("StructureBlockUpdatePacket: v2168 round-trip")
{
    REQUIRE(encode(fill_v2168()) == golden_v2168);

    const auto rt = decode<Packet2168>(golden_v2168);
    REQUIRE(rt.data.structure_name.unredacted_string == "name");
    REQUIRE_FALSE(rt.data.structure_name.redacted_string.has_value());
    REQUIRE(rt.data.settings.integrity_seed == bp::RandomSeed{9});
    REQUIRE(rt.data.redstone_save_mode == bp::StructureRedstoneSaveMode::SAVES_TO_DISK);
}

// A present redacted name is a shape the 1001 form cannot express: there the
// filtered name is always on the wire, so "no filtered name" and the empty string
// are the same bytes. No codec models the present case, so it is asserted
// structurally.
TEST_CASE("StructureBlockUpdatePacket: a present v2168 redacted name costs its own string")
{
    auto packet = fill_v2168();
    packet.data.structure_name.redacted_string = "redacted";
    REQUIRE(encode(packet).size() == golden_v2168.size() + 9);

    const auto rt = decode<Packet2168>(encode(packet));
    REQUIRE(rt.data.structure_name.redacted_string == "redacted");
}

// The cerealisation narrowed the redstone save mode from a varint32 to its uint8_t
// underlying. The bodies are the same length for this literal, so the 1001 bytes
// still parse as 2168 -- and land SAVES_TO_DISK's zigzagged 0x02 on an enumerator
// StructureRedstoneSaveMode does not have.
TEST_CASE("StructureBlockUpdatePacket: a v1001 body decodes as a v2168 one and is wrong")
{
    REQUIRE(golden_v1001.size() == golden_v2168.size());
    REQUIRE(golden_v1001 != golden_v2168);

    const auto wrong = decode<Packet2168>(golden_v1001);
    REQUIRE(static_cast<int>(wrong.data.redstone_save_mode) == 2);
}
