#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("LoginPacket: id + big-endian version with connection request blob")
{
    STATIC_REQUIRE(bp::LoginPacket::Id == 1);

    bp::LoginPacket pkt{975, "hello"};  // aggregate init of the generated struct

    // generated by gophertunnel:
    // packet.Login{ClientProtocol: 975, ConnectionRequest: []byte("hello")}
    const std::vector<std::uint8_t> golden{
        0x00, 0x00, 0x03, 0xCF, 0x05, 0x68, 0x65, 0x6C, 0x6C, 0x6F,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::LoginPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->client_network_version == 975);
    REQUIRE(rt->connection_request == "hello");
}

TEST_CASE("PlayStatusPacket: id + big-endian enum status round-trip")
{
    STATIC_REQUIRE(bp::PlayStatusPacket::Id == 2);

    bp::PlayStatusPacket pkt{bp::PlayStatus::PlayerSpawn};

    // generated by gophertunnel:
    // packet.PlayStatus{Status: 3}
    const std::vector<std::uint8_t> golden{0x00, 0x00, 0x00, 0x03};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::PlayStatusPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->status == bp::PlayStatus::PlayerSpawn);
}

TEST_CASE("PlayStatus: editor-mismatch statuses gated at v534")
{
    REQUIRE(static_cast<int>(bp::PlayStatus_<527>::PlayerSpawn) == 3);
    REQUIRE(static_cast<int>(bp::PlayStatus::LoginFailedEditorMismatchEditorToVanilla) == 8);
}

TEST_CASE("SubClientLoginPacket: id + connection-request blob round-trip")
{
    STATIC_REQUIRE(bp::SubClientLoginPacket::Id == 94);

    bp::SubClientLoginPacket pkt{"hello"};

    // generated by gophertunnel:
    // packet.SubClientLogin{ConnectionRequest: []byte("hello")}
    const std::vector<std::uint8_t> golden{0x05, 0x68, 0x65, 0x6C, 0x6C, 0x6F};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::SubClientLoginPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->sub_client_connection_request == "hello");
}
