#include <type_traits>
#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("DisconnectFailReason: version-gated enumerators")
{
    REQUIRE(static_cast<int>(bp::DisconnectFailReason_<622>::Unknown) == 0);
    REQUIRE(static_cast<int>(bp::DisconnectFailReason_<622>::Kicked) == 55);
    REQUIRE(static_cast<int>(bp::DisconnectFailReason::DenyListed) == 135);
}

TEST_CASE("DisconnectPacketMessages: filtered_message added at v712")
{
    bp::DisconnectPacketMessages_<700> pre{"kicked"};
    REQUIRE(pre.message == "kicked");

    bp::DisconnectPacketMessages_<712> post{"kicked", "***"};
    REQUIRE(post.filtered_message == "***");

    // Unchanged versions alias to one type; a change-point forks a fresh one.
    STATIC_REQUIRE(std::is_same_v<bp::DisconnectPacketMessages_<622>,
                                  bp::DisconnectPacketMessages_<700>>);
    STATIC_REQUIRE(!std::is_same_v<bp::DisconnectPacketMessages_<700>,
                                   bp::DisconnectPacketMessages_<712>>);
}

TEST_CASE("DisconnectPacket: id + round-trip without messages")
{
    STATIC_REQUIRE(bp::DisconnectPacket_<622>::Id == 5);

    bp::DisconnectPacket pkt;
    pkt.reason = bp::DisconnectFailReason::Kicked;

    // generated by gophertunnel:
    // packet.Disconnect{Reason: 55, HideDisconnectionScreen: true}
    const std::vector<std::uint8_t> golden{0x6E, 0x01};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::DisconnectPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->reason == bp::DisconnectFailReason::Kicked);
    REQUIRE_FALSE(rt->messages.has_value());
}

TEST_CASE("DisconnectPacket: round-trip with messages")
{
    bp::DisconnectPacket pkt;
    pkt.reason = bp::DisconnectFailReason::Kicked;
    pkt.messages = bp::DisconnectPacketMessages{"bye", "***"};

    // generated by gophertunnel:
    // packet.Disconnect{Reason: 55, Message: "bye", FilteredMessage: "***"}
    const std::vector<std::uint8_t> golden{
        0x6E, 0x00, 0x03, 0x62, 0x79, 0x65, 0x03, 0x2A, 0x2A, 0x2A,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::DisconnectPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->messages->message == "bye");
    REQUIRE(rt->messages->filtered_message == "***");
}

TEST_CASE("DisconnectPacket: v975 NonceMissing reason round-trips with the uvarint switch")
{
    bp::DisconnectPacket_<975> pkt;
    pkt.reason = bp::DisconnectFailReason_<975>::NonceMissing;
    pkt.messages = bp::DisconnectPacketMessages_<975>{"bye", "***"};

    // generated by gophertunnel:
    // packet.Disconnect{Reason: 136, Message: "bye", FilteredMessage: "***"}
    const std::vector<std::uint8_t> golden{
        0x90, 0x02, 0x00, 0x03, 0x62, 0x79, 0x65, 0x03, 0x2A, 0x2A, 0x2A,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::DisconnectPacket_<975>>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->reason == bp::DisconnectFailReason_<975>::NonceMissing);
    REQUIRE(rt->messages->filtered_message == "***");
}
