#include <optional>
#include <string>

#include <bedrock/protocol/structure.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.StructureTemplateDataResponse{StructureName: "mystructure",
// Success: true, StructureTemplate: map[string]any{"format_version": int32(1)},
// ResponseType: packet.StructureTemplateResponseQuery}
const std::string golden = bytes({
    0x0b, 0x6d, 0x79, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65,
    0x01, 0x0a, 0x00, 0x03, 0x0e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x5f,
    0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x02, 0x00, 0x02,
});

// generated by gophertunnel: &packet.StructureTemplateDataResponse{StructureName: "mystructure",
// Success: false, ResponseType: packet.StructureTemplateResponseExport}
const std::string golden_absent_tag = bytes({
    0x0b, 0x6d, 0x79, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65,
    0x00, 0x01,
});

// generated by gophertunnel: &packet.StructureTemplateDataResponse{StructureName: "",
// Success: true, ResponseType: 0}
const std::string golden_empty_tag = bytes({
    0x00, 0x01, 0x0a, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 133")
{
    STATIC_REQUIRE(bp::StructureTemplateDataResponsePacket::Id == 133);
    STATIC_REQUIRE(bp::has_packet_v<1001, 133>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 133>);
}

TEST_CASE("structure-template-data-response round-trips against the golden")
{
    bp::StructureTemplateDataResponsePacket packet;
    packet.structure_name = "mystructure";
    packet.structure_tag = bp::CompoundTag{{"format_version", bp::IntTag{1}}};
    packet.response_type = bp::StructureTemplateResponseType::Query;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::StructureTemplateDataResponsePacket>(golden);
    REQUIRE(back.structure_name == "mystructure");
    REQUIRE(back.structure_tag.has_value());
    REQUIRE(back.structure_tag->size() == 1);
    REQUIRE(back.structure_tag->at("format_version").get<bp::IntTag>().value() == 1);
    REQUIRE(back.response_type == bp::StructureTemplateResponseType::Query);
}

TEST_CASE("an absent structure template leaves only its presence byte")
{
    bp::StructureTemplateDataResponsePacket packet;
    packet.structure_name = "mystructure";
    packet.structure_tag = std::nullopt;
    packet.response_type = bp::StructureTemplateResponseType::Export;
    REQUIRE(encode(packet) == golden_absent_tag);

    const auto back = decode<bp::StructureTemplateDataResponsePacket>(golden_absent_tag);
    REQUIRE(back.structure_name == "mystructure");
    REQUIRE_FALSE(back.structure_tag.has_value());
    REQUIRE(back.response_type == bp::StructureTemplateResponseType::Export);
}

TEST_CASE("a present but empty structure template is not an absent one")
{
    bp::StructureTemplateDataResponsePacket packet;
    packet.structure_tag = bp::CompoundTag{};
    packet.response_type = bp::StructureTemplateResponseType::None;
    REQUIRE(encode(packet) == golden_empty_tag);
    REQUIRE(golden_empty_tag.size() == 6);

    const auto back = decode<bp::StructureTemplateDataResponsePacket>(golden_empty_tag);
    REQUIRE(back.structure_name.empty());
    REQUIRE(back.structure_tag.has_value());
    REQUIRE(back.structure_tag->empty());
    REQUIRE(back.response_type == bp::StructureTemplateResponseType::None);
}
