#include <string>
#include <type_traits>
#include <variant>

#include "fixture.hpp"

namespace {

bp::SerializedSkinRef_<2168> skin()
{
    bp::SerializedSkinRef_<2168> out;
    out.id = "sid";
    out.play_fab_id = "pfid";
    out.resource_patch = "patch";
    out.image_data = {.width = 1, .height = 1, .image_bytes = std::string(4, '\0')};
    out.cape_image_data = {.width = 1, .height = 1, .image_bytes = std::string(4, '\0')};
    out.geometry_data = "geo";
    out.geometry_data_min_engine_version = "1.0.0";
    out.animation_data = "anim";
    out.cape_id = "cid";
    out.full_id = "fid";
    out.arm_size = bp::ArmSizeType::WIDE;
    out.skin_color = static_cast<bp::Color>(0x01020304);
    out.is_premium = true;
    out.is_persona = false;
    out.is_persona_cape_on_classic_skin = false;
    out.is_primary_user = true;
    out.overrides_player_appearance = false;
    out.trusted_skin_flag = bp::TrustedSkinFlag::TRUE;
    out.profile_hash = "hash";
    return out;
}

bp::PlayerListPacket_<2168> fill()
{
    bp::PlayerListPacket_<2168> pkt;

    bp::PlayerListPacket_<2168>::AddEntry add;
    add.action = bp::PlayerListPacketType::ADD;
    add.uuid = {.most_significant_bits = 0, .least_significant_bits = 1};
    add.id = static_cast<bp::ActorUniqueID>(7);
    add.name = "Steve";
    add.xuid = "xuid";
    add.platform_online_id = "pcid";
    add.build_platform = bp::BuildPlatform::WIN32;
    add.skin = skin();
    add.is_teacher = false;
    add.is_host = true;
    add.is_sub_client = false;
    add.color = static_cast<bp::Color>(0x05060708);
    pkt.entries.emplace_back(add);

    bp::PlayerListPacket_<2168>::RemoveEntry remove;
    remove.action = bp::PlayerListPacketType::REMOVE;
    remove.uuid = {.most_significant_bits = 0, .least_significant_bits = 2};
    pkt.entries.emplace_back(remove);

    return pkt;
}

bp::legacy::SerializedSkinRef legacy_skin()
{
    bp::legacy::SerializedSkinRef out;
    out.id = "sid";
    out.play_fab_id = "pfid";
    out.resource_patch = "patch";
    out.image_width = 1;
    out.image_height = 1;
    out.image_bytes = std::string(4, '\0');
    out.cape_image_width = 1;
    out.cape_image_height = 1;
    out.cape_image_bytes = std::string(4, '\0');
    out.geometry_data = "geo";
    out.geometry_data_min_engine_version = "1.0.0";
    out.animation_data = "anim";
    out.cape_id = "cid";
    out.full_id = "fid";
    out.arm_size = bp::ArmSizeType::WIDE;
    out.skin_color = "#010203";
    out.is_premium = true;
    out.is_persona = false;
    out.is_persona_cape_on_classic_skin = false;
    out.is_primary_user = true;
    out.overrides_player_appearance = false;
    return out;
}

bp::PlayerListPacket_<1001> fill_v1001()
{
    bp::PlayerListPacket_<1001> pkt;
    pkt.action = bp::PlayerListPacketType::ADD;

    bp::PlayerListEntry_<1001> entry;
    entry.uuid = {.most_significant_bits = 0, .least_significant_bits = 1};
    entry.id = static_cast<bp::ActorUniqueID>(7);
    entry.name = "Steve";
    entry.xuid = "xuid";
    entry.platform_online_id = "pcid";
    entry.build_platform = bp::BuildPlatform::WIN32;
    entry.skin = legacy_skin();
    entry.is_teacher = false;
    entry.is_host = true;
    entry.is_sub_client = false;
    entry.color = static_cast<bp::Color>(0x05060708);
    pkt.entries.push_back(entry);
    pkt.trusted_skins.push_back(true);

    return pkt;
}

}  // namespace

TEST_CASE("PlayerListPacket: id")
{
    STATIC_REQUIRE(bp::PlayerListPacket_<1001>::Id == 63);
    STATIC_REQUIRE(bp::PlayerListPacket_<2168>::Id == 63);
}

// 2168 cerealised the packet: the action moves from a packet-level byte into every
// entry, the entries become a union over two payloads, and the trailing trusted run
// folds into the skin as TrustedSkinFlag.
TEST_CASE("PlayerListPacket: 1001 and 2168 are different shapes")
{
    STATIC_REQUIRE_FALSE(std::is_same_v<bp::PlayerListPacket_<1001>, bp::PlayerListPacket_<2168>>);
    STATIC_REQUIRE_FALSE(std::is_same_v<bp::legacy::SerializedSkinRef, bp::SerializedSkinRef_<1001>>);
}

TEST_CASE("PlayerListPacket: v1001 add round-trip")
{
    using Packet = bp::PlayerListPacket_<1001>;

    const Packet pkt = fill_v1001();

    // generated by gophertunnel v1.57.1 (protocol 1001):
    // PlayerList{ActionType: PlayerListActionAdd, Entries: [{UUID: uuid.UUID{15: 1},
    //   EntityUniqueID: 7, Username: "Steve", XUID: "xuid", PlatformChatID: "pcid",
    //   BuildPlatform: 8, Teacher: false, Host: true, SubClient: false,
    //   PlayerColour: color.RGBA{A: 8, R: 7, G: 6, B: 5},
    //   Skin: Skin{SkinID: "sid", PlayFabID: "pfid", SkinResourcePatch: "patch",
    //     SkinImageWidth: 1, SkinImageHeight: 1, SkinData: 4 zero bytes,
    //     CapeImageWidth: 1, CapeImageHeight: 1, CapeData: 4 zero bytes,
    //     SkinGeometry: "geo", GeometryDataEngineVersion: "1.0.0",
    //     AnimationData: "anim", CapeID: "cid", FullID: "fid", ArmSize: "wide",
    //     SkinColour: "#010203", PremiumSkin: true, PersonaSkin: false,
    //     PersonaCapeOnClassicSkin: false, PrimaryUser: true,
    //     OverrideAppearance: false, Trusted: true}}]}
    // The arm size is name-coded, so the four bytes at offset 108 read "wide" there and
    // "WIDE" here: BDS lowercases before the lookup, and SLIM / WIDE carry no separator.
    const std::string golden = bytes({
    0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0E, 0x05, 0x53, 0x74, 0x65, 0x76,
    0x65, 0x04, 0x78, 0x75, 0x69, 0x64, 0x04, 0x70, 0x63, 0x69, 0x64, 0x08,
    0x00, 0x00, 0x00, 0x03, 0x73, 0x69, 0x64, 0x04, 0x70, 0x66, 0x69, 0x64,
    0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x01, 0x00, 0x00, 0x00, 0x01, 0x00,
    0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
    0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00,
    0x03, 0x67, 0x65, 0x6F, 0x05, 0x31, 0x2E, 0x30, 0x2E, 0x30, 0x04, 0x61,
    0x6E, 0x69, 0x6D, 0x03, 0x63, 0x69, 0x64, 0x03, 0x66, 0x69, 0x64, 0x04,
    0x57, 0x49, 0x44, 0x45, 0x07, 0x23, 0x30, 0x31, 0x30, 0x32, 0x30, 0x33,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01,
    0x00, 0x00, 0x01, 0x00, 0x08, 0x07, 0x06, 0x05, 0x01,
});

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.action == bp::PlayerListPacketType::ADD);
    REQUIRE(rt.entries.size() == 1);
    REQUIRE(rt.removed_entries.empty());
    REQUIRE(rt.entries[0].name == "Steve");
    REQUIRE(rt.entries[0].build_platform == bp::BuildPlatform::WIN32);
    REQUIRE(rt.entries[0].skin.arm_size == bp::ArmSizeType::WIDE);
    REQUIRE(rt.entries[0].skin.skin_color == "#010203");
    REQUIRE(rt.trusted_skins == std::vector<bool>{true});
}

TEST_CASE("PlayerListPacket: v1001 remove round-trip")
{
    using Packet = bp::PlayerListPacket_<1001>;

    Packet pkt;
    pkt.action = bp::PlayerListPacketType::REMOVE;
    pkt.removed_entries.push_back({.most_significant_bits = 0, .least_significant_bits = 2});

    // generated by gophertunnel v1.57.1 (protocol 1001):
    // PlayerList{ActionType: PlayerListActionRemove,
    //   Entries: [{UUID: uuid.UUID{15: 2}}]}
    const std::string golden = bytes({
    0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.action == bp::PlayerListPacketType::REMOVE);
    REQUIRE(rt.entries.empty());
    REQUIRE(rt.removed_entries.size() == 1);
    REQUIRE(rt.removed_entries[0].least_significant_bits == 2);
    REQUIRE(rt.trusted_skins.empty());
}

// The trusted run shares the entry count and nothing on the wire repeats it, so the
// add golden carries one bool for one entry and the remove case carries none at all.
TEST_CASE("PlayerListPacket: the trusted run rides the entry count")
{
    const auto one = encode(fill_v1001());

    bp::PlayerListPacket_<1001> pkt = fill_v1001();
    pkt.entries.push_back(pkt.entries[0]);
    pkt.trusted_skins = {true, false};
    const auto two = encode(pkt);

    // the one-entry body is the action, the count, one entry and one trusted bool
    REQUIRE(two.size() - one.size() == (one.size() - 3) + 1);
    REQUIRE(static_cast<unsigned char>(two[1]) == 2);
    REQUIRE(static_cast<unsigned char>(two.back()) == 0);
}

TEST_CASE("PlayerListPacket: v2168 round-trip")
{
    using Packet = bp::PlayerListPacket_<2168>;

    const Packet pkt = fill();

    // generated by CloudburstMC Bedrock_v2168:
    // PlayerListPacket{entries: [
    //   Entry(action ADD, uuid 0-1, entityId 7, name "Steve", xuid "xuid",
    //     platformChatId "pcid", buildPlatform WIN32, teacher false, host true,
    //     subClient false, color 0x05060708,
    //     skin SerializedSkin(skinId "sid", playFabId "pfid", skinResourcePatch "patch",
    //       skinData 1x1, animations [], capeData 1x1, geometryData "geo",
    //       geometryDataEngineVersion "1.0.0", animationData "anim", capeId "cid",
    //       fullSkinId "fid", armSize "wide", color 0x01020304, personaPieces [],
    //       tintColors [], premium true, persona false, capeOnClassic false,
    //       primaryUser true, overridingPlayerAppearance false, trusted true,
    //       profileHash "hash")),
    //   Entry(action REMOVE, uuid 0-2)]}
    // The trusted-skin flag is name-coded: Cloudburst writes Boolean.toString, so the
    // four payload bytes read "true" there and "TRUE" here.
    const std::string golden = bytes({
    0x02, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x0E, 0x05, 0x53, 0x74, 0x65,
    0x76, 0x65, 0x04, 0x78, 0x75, 0x69, 0x64, 0x04, 0x70, 0x63, 0x69, 0x64,
    0x08, 0x00, 0x00, 0x00, 0x03, 0x73, 0x69, 0x64, 0x04, 0x70, 0x66, 0x69,
    0x64, 0x05, 0x70, 0x61, 0x74, 0x63, 0x68, 0x01, 0x00, 0x00, 0x00, 0x01,
    0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00, 0x00,
    0x00, 0x01, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00, 0x03, 0x67,
    0x65, 0x6F, 0x05, 0x31, 0x2E, 0x30, 0x2E, 0x30, 0x04, 0x61, 0x6E, 0x69,
    0x6D, 0x03, 0x63, 0x69, 0x64, 0x03, 0x66, 0x69, 0x64, 0x01, 0x04, 0x03,
    0x02, 0x01, 0x00, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, 0x04, 0x54, 0x52,
    0x55, 0x45, 0x04, 0x68, 0x61, 0x73, 0x68, 0x00, 0x01, 0x00, 0x08, 0x07,
    0x06, 0x05, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.entries.size() == 2);

    const auto &add = std::get<bp::PlayerListPacket_<2168>::AddEntry>(rt.entries[0]);
    REQUIRE(add.action == bp::PlayerListPacketType::ADD);
    REQUIRE(add.name == "Steve");
    REQUIRE(add.build_platform == bp::BuildPlatform::WIN32);
    REQUIRE(add.skin.profile_hash == "hash");

    const auto &remove = std::get<bp::PlayerListPacket_<2168>::RemoveEntry>(rt.entries[1]);
    REQUIRE(remove.action == bp::PlayerListPacketType::REMOVE);
    REQUIRE(remove.uuid.least_significant_bits == 2);
}

// The variant index and the payload's own action member are both on the wire and they
// disagree: index 0 selects RemoveEntry, whose action is Remove = 1, and index 1
// selects AddEntry, whose action is Add = 0.
TEST_CASE("PlayerListPacket: the variant index is not the action value")
{
    bp::PlayerListPacket_<2168> pkt;
    bp::PlayerListPacket_<2168>::RemoveEntry remove;
    remove.action = bp::PlayerListPacketType::REMOVE;
    remove.uuid = {};
    pkt.entries.emplace_back(remove);

    const auto encoded = encode(pkt);
    REQUIRE(encoded.size() == 19);
    REQUIRE(static_cast<unsigned char>(encoded[0]) == 1);
    REQUIRE(static_cast<unsigned char>(encoded[1]) == 0);
    REQUIRE(static_cast<unsigned char>(encoded[2]) == 1);
}
