#include <string>

#include <bedrock/protocol/command.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel (v1.57.1):
// &packet.SettingsCommand{CommandLine: "gamerule showcoordinates true", SuppressOutput: true}
const std::string golden = bytes({
    0x1d, 0x67, 0x61, 0x6d, 0x65, 0x72, 0x75, 0x6c, 0x65, 0x20, 0x73, 0x68,
    0x6f, 0x77, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x69, 0x6e, 0x61, 0x74, 0x65,
    0x73, 0x20, 0x74, 0x72, 0x75, 0x65, 0x01,
});

// generated by gophertunnel (v1.57.1):
// &packet.SettingsCommand{CommandLine: "", SuppressOutput: false}
const std::string golden_empty = bytes({
    0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 140")
{
    STATIC_REQUIRE(bp::SettingsCommandPacket::Id == 140);
    STATIC_REQUIRE(bp::has_packet_v<1001, 140>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 140>);
}

TEST_CASE("settings-command round-trips against the golden")
{
    bp::SettingsCommandPacket packet;
    packet.command_string = "gamerule showcoordinates true";
    packet.suppress_output = true;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::SettingsCommandPacket>(golden);
    REQUIRE(back.command_string == "gamerule showcoordinates true");
    REQUIRE(back.suppress_output);
}

TEST_CASE("an empty command line is a lone length prefix ahead of the flag")
{
    bp::SettingsCommandPacket packet;
    packet.suppress_output = false;
    REQUIRE(encode(packet) == golden_empty);

    const auto back = decode<bp::SettingsCommandPacket>(golden_empty);
    REQUIRE(back.command_string.empty());
    REQUIRE_FALSE(back.suppress_output);
}

TEST_CASE("the command line's length prefix is a varint")
{
    bp::SettingsCommandPacket packet;
    packet.command_string = std::string(200, 'a');
    packet.suppress_output = false;
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 203);

    const auto back = decode<bp::SettingsCommandPacket>(wire);
    REQUIRE(back.command_string == std::string(200, 'a'));
    REQUIRE_FALSE(back.suppress_output);
}
