#include <string>

#include <bedrock/protocol/edu.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.CodeBuilderSource{Operation:
// packet.CodeBuilderOperationReset, Category: packet.CodeBuilderCategoryInstantiation,
// CodeStatus: packet.CodeBuilderStatusSucceeded}
const std::string golden = bytes({
    0x03, 0x02, 0x05,
});

// generated by gophertunnel: &packet.CodeBuilderSource{Operation:
// packet.CodeBuilderOperationNone, Category: packet.CodeBuilderCategoryNone,
// CodeStatus: packet.CodeBuilderStatusNone}
const std::string golden_all_none = bytes({
    0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 178")
{
    STATIC_REQUIRE(bp::CodeBuilderSourcePacket::Id == 178);
    STATIC_REQUIRE(bp::has_packet_v<1001, 178>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 178>);
}

TEST_CASE("code-builder source round-trips against the golden")
{
    bp::CodeBuilderSourcePacket packet;
    packet.operation = bp::Operation::Reset;
    packet.category = bp::Category::Instantiation;
    packet.code_status = bp::CodeStatus::Succeeded;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::CodeBuilderSourcePacket>(golden);
    REQUIRE(back.operation == bp::Operation::Reset);
    REQUIRE(back.category == bp::Category::Instantiation);
    REQUIRE(back.code_status == bp::CodeStatus::Succeeded);
}

TEST_CASE("a code-builder source body still writes three bytes with every field None")
{
    bp::CodeBuilderSourcePacket packet;
    packet.operation = bp::Operation::None;
    packet.category = bp::Category::None;
    packet.code_status = bp::CodeStatus::None;
    REQUIRE(encode(packet) == golden_all_none);

    const auto back = decode<bp::CodeBuilderSourcePacket>(golden_all_none);
    REQUIRE(back.operation == bp::Operation::None);
    REQUIRE(back.category == bp::Category::None);
    REQUIRE(back.code_status == bp::CodeStatus::None);
}

TEST_CASE("a code-builder source operation above 127 stays a single byte")
{
    bp::CodeBuilderSourcePacket packet;
    packet.operation = static_cast<bp::Operation>(200);
    packet.category = bp::Category::CodeStatus;
    packet.code_status = bp::CodeStatus::InProgress;
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 3);

    const auto back = decode<bp::CodeBuilderSourcePacket>(wire);
    REQUIRE(back.operation == static_cast<bp::Operation>(200));
    REQUIRE(back.category == bp::Category::CodeStatus);
    REQUIRE(back.code_status == bp::CodeStatus::InProgress);
    REQUIRE(rejects<bp::CodeBuilderSourcePacket>(wire.substr(0, 2)));
}
