#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("AgentAnimationPacket: id + round-trip with ARM_SWING animation")
{
    STATIC_REQUIRE(bp::AgentAnimationPacket::Id == 304);

    bp::AgentAnimationPacket pkt;
    pkt.anim = bp::AgentAnimation::ArmSwing;
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(7);

    // generated by gophertunnel:
    // packet.AgentAnimation{Animation: 0, EntityRuntimeID: 7}
    const std::vector<std::uint8_t> golden{0x00, 0x07};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::AgentAnimationPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->anim == bp::AgentAnimation::ArmSwing);
    REQUIRE(rt->runtime_id == 7);
}
