#include <string>

#include <bedrock/protocol/actor.h>
#include <bedrock/protocol/inventory.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.UpdateEquip{WindowID: 1, WindowType: 12,
// Size: 2, EntityUniqueID: 7, SerialisedInventoryData: nbt.MarshalEncoding(
// map[string]any{"Size": int32(2)}, nbt.NetworkLittleEndian)}
const std::string golden = bytes({
    0x01, 0x0c, 0x04, 0x0e, 0x0a, 0x00, 0x03, 0x04, 0x53, 0x69, 0x7a, 0x65,
    0x04, 0x00,
});

// generated by gophertunnel: &packet.UpdateEquip{WindowID: 0xff,
// WindowType: 0xf7, Size: 300, EntityUniqueID: -1, SerialisedInventoryData:
// nbt.MarshalEncoding(map[string]any{}, nbt.NetworkLittleEndian)}
const std::string golden_none = bytes({
    0xff, 0xf7, 0xd8, 0x04, 0x01, 0x0a, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 81")
{
    STATIC_REQUIRE(bp::UpdateEquipPacket_<2168>::Id == 81);
    STATIC_REQUIRE(bp::has_packet_v<1001, 81>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 81>);
}

TEST_CASE("update-equip round-trips against the golden")
{
    bp::UpdateEquipPacket_<2168> packet;
    packet.container_id = bp::ContainerID::FIRST;
    packet.type = bp::ContainerType_<2168>::HORSE;
    packet.size = 2;
    packet.entity_unique_id = bp::ActorUniqueID{7};
    packet.data = bp::CompoundTag{{"Size", bp::IntTag{2}}};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::UpdateEquipPacket_<2168>>(golden);
    REQUIRE(back.container_id == bp::ContainerID::FIRST);
    REQUIRE(back.type == bp::ContainerType_<2168>::HORSE);
    REQUIRE(back.size == 2);
    REQUIRE(back.entity_unique_id == bp::ActorUniqueID{7});
    REQUIRE(back.data.size() == 1);
    REQUIRE(back.data.at("Size").get<bp::IntTag>().value() == 2);
}

TEST_CASE("update-equip keeps its container id and type to one signed byte")
{
    bp::UpdateEquipPacket_<2168> packet;
    packet.container_id = bp::ContainerID::NONE;
    packet.type = bp::ContainerType_<2168>::NONE;
    packet.size = 300;
    packet.entity_unique_id = bp::ActorUniqueID{-1};
    REQUIRE(encode(packet) == golden_none);

    const auto back = decode<bp::UpdateEquipPacket_<2168>>(golden_none);
    REQUIRE(back.container_id == bp::ContainerID::NONE);
    REQUIRE(back.type == bp::ContainerType_<2168>::NONE);
    REQUIRE(back.size == 300);
    REQUIRE(back.entity_unique_id == bp::ActorUniqueID{-1});
    REQUIRE(back.data.empty());
}
