#include <string>
#include <type_traits>

#include <bedrock/protocol/player.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.PlayerArmourDamage{List:
// []protocol.PlayerArmourDamageEntry{{ArmourSlot: 1, Damage: 3},
// {ArmourSlot: 4, Damage: -300}}}
const std::string golden = bytes({
    0x02, 0x02, 0x03, 0x00, 0x08, 0xd4, 0xfe,
});

// generated by gophertunnel: &packet.PlayerArmourDamage{}
const std::string golden_empty = bytes({
    0x00,
});


// generated by gophertunnel at d6ce91a (the 827 bump): &packet.PlayerArmourDamage{
// Bitset: Helmet|Body, HelmetDamage: 3, BootsDamage: -2} -- a flags byte, then one
// zigzag varint per set bit in bit order.
const std::string golden_v827 = bytes({
    0x09, 0x06, 0x03,
});

}  // namespace

TEST_CASE("packet id is 149")
{
    STATIC_REQUIRE(bp::PlayerArmorDamagePacket::Id == 149);
    STATIC_REQUIRE(bp::has_packet_v<1001, 149>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 149>);
}

TEST_CASE("player-armor-damage round-trips against the golden")
{
    bp::PlayerArmorDamagePacket packet;
    packet.slot_and_damage_pairs.push_back({.armor_slot = bp::ArmorSlot::Torso, .damage = 3});
    packet.slot_and_damage_pairs.push_back({.armor_slot = bp::ArmorSlot::Body, .damage = -300});
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::PlayerArmorDamagePacket>(golden);
    REQUIRE(back.slot_and_damage_pairs.size() == 2);
    REQUIRE(back.slot_and_damage_pairs.at(0).armor_slot == bp::ArmorSlot::Torso);
    REQUIRE(back.slot_and_damage_pairs.at(0).damage == 3);
    REQUIRE(back.slot_and_damage_pairs.at(1).armor_slot == bp::ArmorSlot::Body);
    REQUIRE(back.slot_and_damage_pairs.at(1).damage == -300);
}

TEST_CASE("an empty armor damage pair list is a lone zero length prefix")
{
    bp::PlayerArmorDamagePacket packet;
    REQUIRE(encode(packet) == golden_empty);
    REQUIRE(decode<bp::PlayerArmorDamagePacket>(golden_empty).slot_and_damage_pairs.empty());
}

TEST_CASE("an armor damage body running short of its declared pair count is rejected")
{
    REQUIRE(rejects<bp::PlayerArmorDamagePacket>(golden.substr(0, 4)));
}

// Hand-written until 844: a five-bit slot mask with a damage per set bit, rather
// than the length-prefixed pair list BDS moved to.
TEST_CASE("the pre-844 armor damage shape round-trips against the golden")
{
    bp::PlayerArmorDamagePacket_<827> packet;
    packet.slots = 0x09;
    packet.head_damage = 3;
    packet.feet_damage = -2;
    REQUIRE(encode(packet) == golden_v827);

    const auto back = decode<bp::PlayerArmorDamagePacket_<827>>(golden_v827);
    REQUIRE(back.slots == 0x09);
    REQUIRE(back.head_damage == 3);
    REQUIRE(back.feet_damage == -2);
}

// An unset bit writes nothing at all, so an empty mask is a single byte -- where the
// 844 form spends its byte on a zero-length prefix instead.
TEST_CASE("an empty pre-844 slot mask is a lone zero byte")
{
    bp::PlayerArmorDamagePacket_<827> packet;
    packet.slots = 0;
    packet.head_damage = 99;
    REQUIRE(encode(packet) == bytes({0x00}));
}

TEST_CASE("id 149 changes shape at 844")
{
    STATIC_REQUIRE_FALSE(std::is_same_v<bp::PlayerArmorDamagePacket_<827>, bp::PlayerArmorDamagePacket_<844>>);
    STATIC_REQUIRE(std::is_same_v<bp::PlayerArmorDamagePacket_<844>, bp::PlayerArmorDamagePacket_<2168>>);
}
