#include <cstdint>
#include <string>
#include <variant>

#include <bedrock/protocol/actor.h>
#include <bedrock/protocol/attributes.h>
#include <bedrock/protocol/common.h>
#include <bedrock/protocol/shape.h>

#include "fixture.hpp"

namespace {

using PacketV975 = bp::PrimitiveShapesPacket_<975>;
using PacketV1001 = bp::PrimitiveShapesPacket_<1001>;

// mce::Color packs ARGB into an int32: A=0x44, R=0x55, G=0x66, B=0x77.
constexpr auto argb = bp::Color{0x44556677};

// The three shapes below are shaped identically at both eras, so each is built once
// against whichever snapshot's payload the caller wants. The type enum gained members
// at 1001 and the text payload a field at 2192, so both are versioned alongside the
// payload and come from it.
template <class Payload>
using ShapeTypeOf = typename decltype(Payload::shape_type)::value_type;

template <class Payload>
using TextPayloadOf = std::variant_alternative_t<2, decltype(Payload::extra_data_payload)>;

// Every optional left empty: the shape is cleared, and the variant sits on its
// std::monostate case.
template <class Payload>
Payload cleared_shape()
{
    Payload shape;
    shape.network_id = 1;
    return shape;
}

template <class Payload>
Payload sphere_shape()
{
    Payload shape;
    shape.network_id = 3;
    shape.shape_type = ShapeTypeOf<Payload>::SPHERE;
    shape.location = bp::Vec3{.x = 1.0f, .y = 2.0f, .z = 3.0f};
    shape.scale = 0.5f;
    shape.rotation = bp::Vec3{.x = 0.0f, .y = 0.25f, .z = 0.0f};
    shape.time_left_total_sec = 2.0f;
    shape.max_render_distance = 64.0f;
    shape.color = argb;
    shape.dimension_id = bp::DimensionType{1};
    shape.attached_to_id = bp::ActorUniqueID{-7};
    shape.extra_data_payload = bp::SphereDataPayload{.num_segments = 12};
    return shape;
}

template <class Payload>
Payload text_shape()
{
    Payload shape;
    shape.network_id = 4;
    shape.shape_type = ShapeTypeOf<Payload>::TEXT;
    shape.extra_data_payload = TextPayloadOf<Payload>{
        .text = "hi",
        .use_rotation = true,
        .background_color = argb,
        .depth_test = true,
        .show_backface = false,
        .show_text_backface = true,
    };
    return shape;
}

// generated by gophertunnel at 6353c49^ (de090ae, the last pre-1.26.30 commit):
// packet.PrimitiveShapes{Shapes: []protocol.PrimitiveShape{
//   {NetworkID: 1, ExtraShapeData: &protocol.LastShape{}},
//   {NetworkID: 3, Type: Option(PrimitiveShapeSphere), Location: Option(Vec3{1,2,3}),
//    Scale: Option(0.5), Rotation: Option(Vec3{0,0.25,0}), TotalTimeLeft: Option(2),
//    MaxRenderDistance: Option(64), Colour: Option(RGBA{A:0x44,R:0x55,G:0x66,B:0x77}),
//    DimensionID: Option(1), AttachedToEntityID: Option(-7),
//    ExtraShapeData: &protocol.SphereShape{Segments: 12}},
//   {NetworkID: 4, Type: Option(PrimitiveShapeText), ExtraShapeData: &protocol.TextShape{
//    Text: "hi", UseRotation: true, BackgroundColour: Option(argb), DepthTest: true,
//    ShowBackface: false, ShowBackfaceText: true}}}}
const std::string golden_v975 = bytes({
    0x03, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x03, 0x01, 0x02, 0x01, 0x00, 0x00, 0x80, 0x3f, 0x00, 0x00, 0x00, 0x40,
    0x00, 0x00, 0x40, 0x40, 0x01, 0x00, 0x00, 0x00, 0x3f, 0x01, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x80, 0x3e, 0x00, 0x00, 0x00, 0x00, 0x01, 0x00,
    0x00, 0x00, 0x40, 0x01, 0x00, 0x00, 0x80, 0x42, 0x01, 0x77, 0x66, 0x55,
    0x44, 0x01, 0x02, 0x01, 0x0d, 0x05, 0x0c, 0x04, 0x01, 0x04, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0x02, 0x68, 0x69, 0x01, 0x01,
    0x77, 0x66, 0x55, 0x44, 0x01, 0x00, 0x01,
});

// generated by gophertunnel (654cd5f): the three shapes above, plus the two 989 added
// -- a cylinder and a pyramid, at variant indices 6 and 7.
//   {NetworkID: 5, Type: Option(PrimitiveShapeCylinder), ExtraShapeData:
//    &protocol.CylinderShape{RadiusX: Vec2{1,0}, RadiusZ: Vec2{0,1}, Height: 3, NumSegments: 8}},
//   {NetworkID: 6, Type: Option(PrimitiveShapePyramid), ExtraShapeData:
//    &protocol.PyramidShape{Width: 2, Depth: Option(4), Height: 6}}
const std::string golden_v1001_tail = bytes({
    0x05, 0x01, 0x06, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x06,
    0x00, 0x00, 0x80, 0x3f, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x80, 0x3f, 0x00, 0x00, 0x40, 0x40, 0x08, 0x06, 0x01, 0x07,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x07, 0x00, 0x00, 0x00,
    0x40, 0x01, 0x00, 0x00, 0x80, 0x40, 0x00, 0x00, 0xc0, 0x40,
});

// Only the shape count and the appended shapes differ, so the v1001 golden is the
// v975 one with a new count and the two extra bodies.
const std::string golden_v1001 = bytes({0x05}) + golden_v975.substr(1) + golden_v1001_tail;

}  // namespace

TEST_CASE("packet id is 328 at both eras")
{
    STATIC_REQUIRE(PacketV975::Id == 328);
    STATIC_REQUIRE(PacketV1001::Id == 328);
}

TEST_CASE("primitive shapes v975 round-trips against the golden")
{
    using Payload = bp::base::PrimitiveShapeDataPayload;

    PacketV975 packet;
    packet.shapes = {cleared_shape<Payload>(), sphere_shape<Payload>(), text_shape<Payload>()};
    REQUIRE(encode(packet) == golden_v975);

    const auto back = decode<PacketV975>(golden_v975);
    REQUIRE(back.shapes.size() == 3);
    REQUIRE(back.shapes[0].extra_data_payload.index() == 0);  // monostate: shape cleared
    REQUIRE_FALSE(back.shapes[0].shape_type.has_value());
    REQUIRE(back.shapes[1].attached_to_id == bp::ActorUniqueID{-7});
    REQUIRE(back.shapes[1].color == argb);
    REQUIRE(std::get<5>(back.shapes[1].extra_data_payload).num_segments == 12);
    REQUIRE(std::get<2>(back.shapes[2].extra_data_payload).text == "hi");
}

// 989 appended Cylinder, Pyramid, Ellipsoid and Cone to the variant. They take indices
// 6..9, so every earlier case keeps the tag it had at 975.
TEST_CASE("primitive shapes v1001 round-trips against the golden")
{
    using Payload = bp::v1001::PrimitiveShapeDataPayload;

    Payload cylinder;
    cylinder.network_id = 5;
    cylinder.shape_type = bp::ScriptPrimitiveShapeType::CYLINDER;
    cylinder.extra_data_payload = bp::CylinderDataPayload{
        .radius_x = {.x = 1.0f, .y = 0.0f},
        .radius_z = {.x = 0.0f, .y = 1.0f},
        .height = 3.0f,
        .num_segments = 8,
    };

    Payload pyramid;
    pyramid.network_id = 6;
    pyramid.shape_type = bp::ScriptPrimitiveShapeType::PYRAMID;
    pyramid.extra_data_payload = bp::PyramidDataPayload{.width = 2.0f, .depth = 4.0f, .height = 6.0f};

    PacketV1001 packet;
    packet.shapes = {cleared_shape<Payload>(), sphere_shape<Payload>(), text_shape<Payload>(), cylinder, pyramid};
    REQUIRE(encode(packet) == golden_v1001);

    const auto back = decode<PacketV1001>(golden_v1001);
    REQUIRE(back.shapes.size() == 5);
    REQUIRE(std::get<5>(back.shapes[1].extra_data_payload).num_segments == 12);

    const auto &read_cylinder = std::get<6>(back.shapes[3].extra_data_payload);
    REQUIRE(read_cylinder.radius_x.x == 1.0f);
    REQUIRE(read_cylinder.radius_z.y == 1.0f);
    REQUIRE(read_cylinder.height == 3.0f);
    REQUIRE(read_cylinder.num_segments == 8);

    const auto &read_pyramid = std::get<7>(back.shapes[4].extra_data_payload);
    REQUIRE(read_pyramid.width == 2.0f);
    REQUIRE(read_pyramid.depth == 4.0f);
    REQUIRE(read_pyramid.height == 6.0f);
}
