#include <string>

#include <bedrock/protocol/camera.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ClientCameraAimAssist{PresetID: "preset", Action: 1,
// AllowAimAssist: true}
const std::string golden = bytes({
    0x06, 0x70, 0x72, 0x65, 0x73, 0x65, 0x74, 0x01, 0x01,
});

}  // namespace

TEST_CASE("packet id is 321")
{
    STATIC_REQUIRE(bp::ClientCameraAimAssistPacket::Id == 321);
    STATIC_REQUIRE(bp::has_packet_v<1001, 321>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 321>);
}

TEST_CASE("client camera aim assist round-trips against the golden")
{
    bp::ClientCameraAimAssistPacket packet;
    packet.camera_preset_id = "preset";
    packet.action = bp::ClientCameraAimAssistPacketAction::Clear;
    packet.allow_aim_assist = true;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::ClientCameraAimAssistPacket>(golden);
    REQUIRE(back.camera_preset_id == "preset");
    REQUIRE(back.action == bp::ClientCameraAimAssistPacketAction::Clear);
    REQUIRE(back.allow_aim_assist);
}

TEST_CASE("an empty preset id is a lone zero length prefix")
{
    REQUIRE(encode(bp::ClientCameraAimAssistPacket{}) == bytes({0x00, 0x00, 0x00}));
}
