#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ModalFormRequestPacket: id + round-trip with a small JSON body")
{
    STATIC_REQUIRE(bp::ModalFormRequestPacket::Id == 100);

    bp::ModalFormRequestPacket pkt;
    pkt.form_id = 3;
    pkt.form_json = "{\"t\":1}";

    // generated by gophertunnel:
    // packet.ModalFormRequest{FormID: 3, FormData: []byte("{\"t\":1}")}
    const std::vector<std::uint8_t> golden{
        0x03, 0x07, 0x7B, 0x22, 0x74, 0x22, 0x3A, 0x31, 0x7D,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ModalFormRequestPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->form_id == 3);
    REQUIRE(rt->form_json == "{\"t\":1}");
}
