#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("SetTitlePacket: id + round-trip")
{
    STATIC_REQUIRE(bp::SetTitlePacket::Id == 88);

    bp::SetTitlePacket pkt;
    pkt.type = bp::SetTitlePacket::TitleType::Title;
    pkt.title_text = "hello";
    pkt.fade_in_time = 1;
    pkt.stay_time = 2;
    pkt.fade_out_time = 3;
    pkt.xuid = "";
    pkt.platform_online_id = "";
    pkt.filtered_title_text = "";

    // generated by gophertunnel:
    // packet.SetTitle{ActionType: TitleActionSetTitle, Text: "hello",
    //   FadeInDuration: 1, RemainDuration: 2, FadeOutDuration: 3}
    const std::vector<std::uint8_t> golden{
        0x04, 0x05, 0x68, 0x65, 0x6C, 0x6C, 0x6F, 0x02, 0x04, 0x06, 0x00, 0x00,
        0x00,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::SetTitlePacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->type == bp::SetTitlePacket::TitleType::Title);
    REQUIRE(rt->title_text == "hello");
    REQUIRE(rt->fade_in_time == 1);
}
