#include <string>
#include <variant>

#include <bedrock/protocol/map.h>

#include "fixture.hpp"

namespace {

// TODO: confirm against BDS. gophertunnel v1.57.1 marshals a pre-cereal body -- a uint8
// action (Stop 0, Start 1) and, only for Start, the frame rate and file prefix. The r26_u4
// dump and PlayerVideoCapturePacket.h have one uvarint32-indexed variant over
// <StartVideoCapture, StopVideoCapture>, bound twice by
// cerealizer<PlayerVideoCapturePacketPayload>::bind, so two case indices reach the wire.
// The dump and the header win: the action byte becomes case index 0 and a second index
// byte is appended.
//
// generated by gophertunnel: &packet.PlayerVideoCapture{
// Action: packet.PlayerVideoCaptureActionStart, FrameRate: 60, FilePrefix: "clip"}
const std::string golden = bytes({
    0x00,  // TODO: patched, confirm against BDS
    0x3c, 0x00, 0x00, 0x00, 0x04, 0x63, 0x6c, 0x69, 0x70,
    0x01,  // TODO: patched, confirm against BDS
});

}  // namespace

TEST_CASE("packet id is 324")
{
    STATIC_REQUIRE(bp::PlayerVideoCapturePacket::Id == 324);
    STATIC_REQUIRE(bp::has_packet_v<1001, 324>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 324>);
}

TEST_CASE("player-video-capture round-trips against the golden")
{
    bp::PlayerVideoCapturePacket packet;
    packet.start_video_capture =
        bp::PlayerVideoCapturePacket::StartVideoCapture{.frame_rate = 60, .file_prefix = "clip"};
    packet.stop_video_capture = bp::PlayerVideoCapturePacket::StopVideoCapture{};
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::PlayerVideoCapturePacket>(golden);
    REQUIRE(std::holds_alternative<bp::PlayerVideoCapturePacket::StartVideoCapture>(back.start_video_capture));
    REQUIRE(std::get<bp::PlayerVideoCapturePacket::StartVideoCapture>(back.start_video_capture).frame_rate ==
            60);
    REQUIRE(std::get<bp::PlayerVideoCapturePacket::StartVideoCapture>(back.start_video_capture).file_prefix ==
            "clip");
    REQUIRE(std::holds_alternative<bp::PlayerVideoCapturePacket::StopVideoCapture>(back.stop_video_capture));
}

TEST_CASE("both player-video-capture variant fields reach the wire")
{
    bp::PlayerVideoCapturePacket packet;
    packet.start_video_capture = bp::PlayerVideoCapturePacket::StopVideoCapture{};
    packet.stop_video_capture = bp::PlayerVideoCapturePacket::StopVideoCapture{};
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 2);

    const auto back = decode<bp::PlayerVideoCapturePacket>(wire);
    REQUIRE(std::holds_alternative<bp::PlayerVideoCapturePacket::StopVideoCapture>(back.start_video_capture));
    REQUIRE(std::holds_alternative<bp::PlayerVideoCapturePacket::StopVideoCapture>(back.stop_video_capture));
}

TEST_CASE("a player-video-capture frame rate above 127 keeps its four fixed bytes")
{
    bp::PlayerVideoCapturePacket packet;
    packet.start_video_capture = bp::PlayerVideoCapturePacket::StopVideoCapture{};
    packet.stop_video_capture =
        bp::PlayerVideoCapturePacket::StartVideoCapture{.frame_rate = 300, .file_prefix = ""};
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 7);

    const auto back = decode<bp::PlayerVideoCapturePacket>(wire);
    REQUIRE(std::holds_alternative<bp::PlayerVideoCapturePacket::StopVideoCapture>(back.start_video_capture));
    REQUIRE(std::get<bp::PlayerVideoCapturePacket::StartVideoCapture>(back.stop_video_capture).frame_rate ==
            300);
    REQUIRE(
        std::get<bp::PlayerVideoCapturePacket::StartVideoCapture>(back.stop_video_capture).file_prefix.empty());
}
