#include <string>
#include <type_traits>

#include <bedrock/protocol/inventory.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.PlayerHotBar{SelectedHotBarSlot: 300,
// WindowID: 124, SelectHotBarSlot: true}
const std::string golden = bytes({
    0xac, 0x02, 0x7c, 0x01,
});

// generated by gophertunnel: &packet.PlayerHotBar{SelectedHotBarSlot: 0,
// WindowID: 0xff, SelectHotBarSlot: false}
const std::string golden_none = bytes({
    0x00, 0xff, 0x00,
});

}  // namespace

TEST_CASE("packet id is 48")
{
    STATIC_REQUIRE(bp::PlayerHotbarPacket::Id == 48);
    STATIC_REQUIRE(bp::has_packet_v<1001, 48>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 48>);
}

TEST_CASE("player hotbar round-trips against the golden")
{
    bp::PlayerHotbarPacket packet;
    packet.selected_slot = 300;
    packet.container_id = bp::ContainerID::PlayerOnlyUi;
    packet.should_select_slot = true;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::PlayerHotbarPacket>(golden);
    REQUIRE(back.selected_slot == 300);
    REQUIRE(back.container_id == bp::ContainerID::PlayerOnlyUi);
    REQUIRE(back.should_select_slot);
}

TEST_CASE("a NONE container id stays one signed byte")
{
    bp::PlayerHotbarPacket packet;
    packet.selected_slot = 0;
    packet.container_id = bp::ContainerID::None;
    packet.should_select_slot = false;
    REQUIRE(encode(packet) == golden_none);

    const auto back = decode<bp::PlayerHotbarPacket>(golden_none);
    REQUIRE(back.selected_slot == 0);
    REQUIRE(back.container_id == bp::ContainerID::None);
    REQUIRE_FALSE(back.should_select_slot);
}
