#include <string>

#include <protocol/ability.h>
#include <protocol/camera.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.ClientBoundControlSchemeSet{ControlScheme: 3}
const std::string golden = bytes({
    0x03,
});

}  // namespace

TEST_CASE("packet id is 327")
{
    STATIC_REQUIRE(bp::ClientboundControlSchemeSetPacket_<2168>::Id == 327);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 327>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 327>);
}

TEST_CASE("control scheme round-trips against the golden")
{
    bp::ClientboundControlSchemeSetPacket_<2168> packet;
    packet.control_scheme = bp::Scheme::PLAYER_RELATIVE;
    REQUIRE(encode(packet) == golden);
    REQUIRE(decode<bp::ClientboundControlSchemeSetPacket_<2168>>(golden).control_scheme
            == bp::Scheme::PLAYER_RELATIVE);
}

TEST_CASE("the scheme is one byte, so the whole body is one byte")
{
    bp::ClientboundControlSchemeSetPacket_<2168> packet;
    packet.control_scheme = bp::Scheme::PLAYER_RELATIVE_STRAFE;
    REQUIRE(encode(packet) == bytes({0x04}));
    REQUIRE(rejects<bp::ClientboundControlSchemeSetPacket_<2168>>(""));
}
