#include <string>

#include <bedrock/protocol/game.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.MultiPlayerSettings{ActionType: packet.RefreshJoinCode}
const std::string golden = bytes({
    0x04,
});

// generated by gophertunnel: &packet.MultiPlayerSettings{ActionType: packet.DisableMultiPlayer}
const std::string golden_disable = bytes({
    0x02,
});

}  // namespace

TEST_CASE("packet id is 139")
{
    STATIC_REQUIRE(bp::MultiplayerSettingsPacket_<2168>::Id == 139);
    STATIC_REQUIRE(bp::has_packet_v<1001, 139>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 139>);
}

TEST_CASE("multiplayer-settings round-trips against the golden")
{
    bp::MultiplayerSettingsPacket_<2168> packet;
    packet.packet_type = bp::MultiplayerSettingsPacketType::REFRESH_JOINCODE;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::MultiplayerSettingsPacket_<2168>>(golden);
    REQUIRE(back.packet_type == bp::MultiplayerSettingsPacketType::REFRESH_JOINCODE);
}

TEST_CASE("the multiplayer-settings type is a zigzag varint, not a fixed int32")
{
    bp::MultiplayerSettingsPacket_<2168> packet;
    packet.packet_type = bp::MultiplayerSettingsPacketType::DISABLE_MULTIPLAYER;
    REQUIRE(encode(packet) == golden_disable);

    const auto stray = decode_partial<bp::MultiplayerSettingsPacket_<2168>>(bytes({0x02, 0x00, 0x00, 0x00}));
    REQUIRE(stray.packet_type == bp::MultiplayerSettingsPacketType::DISABLE_MULTIPLAYER);
}
