#include <optional>
#include <string>

#include <protocol/actor.h>
#include <protocol/attributes.h>
#include <protocol/common.h>
#include <protocol/ui.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.LocatorBar{Waypoints: []protocol.LocatorBarWaypoint{
// {GroupHandle: uuid.UUID{0x01, 0x23, 0x45, 0x67, 0x89, 0xab, 0xcd, 0xef, 0xfe, 0xdc, 0xba, 0x98,
// 0x76, 0x54, 0x32, 0x10}, Waypoint: protocol.Waypoint{UpdateFlag: 63,
// Visible: protocol.Option(true), WorldPosition: protocol.Option(
// protocol.WaypointWorldPosition{Position: mgl32.Vec3{1, 2, 3}, DimensionID: 1}),
// TexturePath: protocol.Option("textures/ui/waypoint"),
// IconSize: protocol.Option(mgl32.Vec2{16, 16}), Colour: protocol.Option[int32](16744767),
// ClientPositionAuthority: protocol.Option(false), ActorUniqueID: protocol.Option[int64](300)},
// Action: 3}, {GroupHandle: uuid.UUID{0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 2},
// Waypoint: protocol.Waypoint{UpdateFlag: 0}, Action: 2}}}
const std::string golden = bytes({
    0x02, 0xef, 0xcd, 0xab, 0x89, 0x67, 0x45, 0x23, 0x01, 0x10, 0x32, 0x54,
    0x76, 0x98, 0xba, 0xdc, 0xfe, 0x3f, 0x00, 0x00, 0x00, 0x01, 0x01, 0x01,
    0x00, 0x00, 0x80, 0x3f, 0x00, 0x00, 0x00, 0x40, 0x00, 0x00, 0x40, 0x40,
    0x02, 0x01, 0x14, 0x74, 0x65, 0x78, 0x74, 0x75, 0x72, 0x65, 0x73, 0x2f,
    0x75, 0x69, 0x2f, 0x77, 0x61, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x01,
    0x00, 0x00, 0x80, 0x41, 0x00, 0x00, 0x80, 0x41, 0x01, 0x3f, 0x81, 0xff,
    0x00, 0x01, 0x00, 0x01, 0xd8, 0x04, 0x03, 0x01, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02,
});

// generated by gophertunnel: &packet.LocatorBar{}
const std::string golden_empty = bytes({
    0x00,
});

}  // namespace

TEST_CASE("packet id is 341")
{
    STATIC_REQUIRE(bp::LocatorBarPacket_<2168>::Id == 341);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 341>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 341>);
}

TEST_CASE("locator bar round-trips against the golden")
{
    bp::LocatorBarWaypointPayload full;
    full.handle.uuid = {0x0123456789abcdefULL, 0xfedcba9876543210ULL};
    full.payload.update_flag = 63;
    full.payload.is_visible = true;
    full.payload.world_position = bp::WorldPosition{
        .pos = bp::Vec3{.x = 1.0F, .y = 2.0F, .z = 3.0F},
        .dimension_type = bp::DimensionType{1},
    };
    full.payload.texture_path = "textures/ui/waypoint";
    full.payload.icon_size = bp::Vec2{.x = 16.0F, .y = 16.0F};
    full.payload.color = bp::Color{16744767};
    full.payload.client_position_authority = false;
    full.payload.actor_id = bp::ActorUniqueID{300};
    full.action = bp::ServerWaypointGroup::Action::UPDATE;

    bp::LocatorBarWaypointPayload bare;
    bare.handle.uuid = {1ULL, 2ULL};
    bare.payload.update_flag = 0;
    bare.action = bp::ServerWaypointGroup::Action::REMOVE;

    bp::LocatorBarPacket_<2168> packet;
    packet.waypoints.push_back(full);
    packet.waypoints.push_back(bare);
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::LocatorBarPacket_<2168>>(golden);
    REQUIRE(back.waypoints.size() == 2);

    REQUIRE(back.waypoints[0].handle.uuid.most_significant_bits == 0x0123456789abcdefULL);
    REQUIRE(back.waypoints[0].handle.uuid.least_significant_bits == 0xfedcba9876543210ULL);
    REQUIRE(back.waypoints[0].payload.update_flag == 63);
    REQUIRE(back.waypoints[0].payload.is_visible.has_value());
    REQUIRE(*back.waypoints[0].payload.is_visible);
    REQUIRE(back.waypoints[0].payload.world_position.has_value());
    REQUIRE(back.waypoints[0].payload.world_position->pos.x == 1.0F);
    REQUIRE(back.waypoints[0].payload.world_position->pos.y == 2.0F);
    REQUIRE(back.waypoints[0].payload.world_position->pos.z == 3.0F);
    REQUIRE(back.waypoints[0].payload.world_position->dimension_type == bp::DimensionType{1});
    REQUIRE(back.waypoints[0].payload.texture_path.has_value());
    REQUIRE(*back.waypoints[0].payload.texture_path == "textures/ui/waypoint");
    REQUIRE(back.waypoints[0].payload.icon_size.has_value());
    REQUIRE(back.waypoints[0].payload.icon_size->x == 16.0F);
    REQUIRE(back.waypoints[0].payload.icon_size->y == 16.0F);
    REQUIRE(back.waypoints[0].payload.color.has_value());
    REQUIRE(*back.waypoints[0].payload.color == bp::Color{16744767});
    REQUIRE(back.waypoints[0].payload.client_position_authority.has_value());
    REQUIRE_FALSE(*back.waypoints[0].payload.client_position_authority);
    REQUIRE(back.waypoints[0].payload.actor_id.has_value());
    REQUIRE(*back.waypoints[0].payload.actor_id == bp::ActorUniqueID{300});
    REQUIRE(back.waypoints[0].action == bp::ServerWaypointGroup::Action::UPDATE);

    REQUIRE(back.waypoints[1].handle.uuid.most_significant_bits == 1ULL);
    REQUIRE(back.waypoints[1].handle.uuid.least_significant_bits == 2ULL);
    REQUIRE(back.waypoints[1].payload.update_flag == 0);
    REQUIRE_FALSE(back.waypoints[1].payload.is_visible.has_value());
    REQUIRE_FALSE(back.waypoints[1].payload.world_position.has_value());
    REQUIRE_FALSE(back.waypoints[1].payload.texture_path.has_value());
    REQUIRE_FALSE(back.waypoints[1].payload.icon_size.has_value());
    REQUIRE_FALSE(back.waypoints[1].payload.color.has_value());
    REQUIRE_FALSE(back.waypoints[1].payload.client_position_authority.has_value());
    REQUIRE_FALSE(back.waypoints[1].payload.actor_id.has_value());
    REQUIRE(back.waypoints[1].action == bp::ServerWaypointGroup::Action::REMOVE);
}

TEST_CASE("a locator bar carrying no waypoints is a lone count byte")
{
    bp::LocatorBarPacket_<2168> packet;
    REQUIRE(encode(packet) == golden_empty);
    REQUIRE(decode<bp::LocatorBarPacket_<2168>>(golden_empty).waypoints.empty());
}

TEST_CASE("the waypoint update flag is a fixed uint32, not a varint")
{
    bp::LocatorBarPacket_<2168> packet;
    packet.waypoints.emplace_back();
    packet.waypoints[0].handle.uuid = {1ULL, 2ULL};
    packet.waypoints[0].payload.update_flag = 63;
    packet.waypoints[0].action = bp::ServerWaypointGroup::Action::REMOVE;
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 29);

    const auto back = decode<bp::LocatorBarPacket_<2168>>(wire);
    REQUIRE(back.waypoints[0].payload.update_flag == 63);
    REQUIRE(back.waypoints[0].action == bp::ServerWaypointGroup::Action::REMOVE);
}
