#include <string>

#include <bedrock/protocol/diagnostics.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel (924): &packet.EditorNetwork{RouteToManager: true,
// Payload: map[string]any{}}
const std::string golden_v924 = bytes({
    0x01, 0x0a, 0x00, 0x00,
});

// No golden -- gophertunnel never followed the 944 reshape and still writes the
// 924 NBT form, so the dump is the reference. cerealizer<EditorNetworkPacketVariantPayload>::bind
// registers "Route To Manager", "Raw Variant Name", "Raw Variant Data" in that order.
// {RouteToManager: true, RawVariantName: "editor.variant", RawVariantData: "abc"}
const std::string golden = bytes({
    0x01, 0x0e, 0x65, 0x64, 0x69, 0x74, 0x6f, 0x72, 0x2e, 0x76, 0x61, 0x72,
    0x69, 0x61, 0x6e, 0x74, 0x03, 0x61, 0x62, 0x63,
});

// {RouteToManager: false, RawVariantName: "", RawVariantData: ""}
const std::string golden_empty = bytes({
    0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 190 at both versions")
{
    STATIC_REQUIRE(bp::EditorNetworkPacket_<924>::Id == 190);
    STATIC_REQUIRE(bp::EditorNetworkPacket_<944>::Id == 190);
    STATIC_REQUIRE(bp::has_packet_v<924, 190>);
    STATIC_REQUIRE(bp::has_packet_v<1001, 190>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 190>);
}

// 944 replaced the single NBT payload with a variant name and its data; the
// bool ahead of it is all the two shapes share.
TEST_CASE("editor-network v924 carries an NBT payload")
{
    using Packet = bp::EditorNetworkPacket_<924>;

    Packet packet;
    packet.route_to_manager = true;
    REQUIRE(encode(packet) == golden_v924);

    const auto back = decode<Packet>(golden_v924);
    REQUIRE(back.route_to_manager == true);
}

TEST_CASE("editor-network round-trips against the golden")
{
    bp::EditorNetworkPacket packet;
    packet.route_to_manager = true;
    packet.raw_variant_name = "editor.variant";
    packet.raw_variant_data = "abc";
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::EditorNetworkPacket>(golden);
    REQUIRE(back.route_to_manager == true);
    REQUIRE(back.raw_variant_name == "editor.variant");
    REQUIRE(back.raw_variant_data == "abc");
}

TEST_CASE("an empty variant still writes both length prefixes")
{
    bp::EditorNetworkPacket packet;
    packet.route_to_manager = false;
    packet.raw_variant_name = "";
    packet.raw_variant_data = "";
    REQUIRE(encode(packet) == golden_empty);

    const auto back = decode<bp::EditorNetworkPacket>(golden_empty);
    REQUIRE(back.route_to_manager == false);
    REQUIRE(back.raw_variant_name.empty());
    REQUIRE(back.raw_variant_data.empty());
}

TEST_CASE("a variant longer than 127 bytes takes a two-byte length prefix")
{
    bp::EditorNetworkPacket packet;
    packet.route_to_manager = false;
    packet.raw_variant_name = "";
    packet.raw_variant_data = std::string(200, 'x');
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 204);
    REQUIRE(static_cast<unsigned char>(wire[2]) == 0xc8);
    REQUIRE(static_cast<unsigned char>(wire[3]) == 0x01);

    const auto back = decode<bp::EditorNetworkPacket>(wire);
    REQUIRE(back.raw_variant_data == std::string(200, 'x'));
}
