#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("AnimatePacket: id + round-trip with present string-enum swing source")
{
    STATIC_REQUIRE(bp::AnimatePacket::Id == 44);

    bp::AnimatePacket pkt;
    pkt.action = bp::AnimatePacket::Action::MagicCriticalHit;
    pkt.target_runtime_id = static_cast<bp::ActorRuntimeID>(7);
    pkt.data = 1.5f;
    pkt.swing_source = bp::ActorSwingSource::Attack;  // serialized as the name "attack"

    // generated by gophertunnel:
    // packet.Animate{ActionType: 5, EntityRuntimeID: 7, Data: 1.5, SwingSource: AnimateSwingSourceAttack}
    const std::vector<std::uint8_t> golden{
        0x05, 0x07, 0x00, 0x00, 0xC0, 0x3F, 0x01, 0x06, 0x61, 0x74, 0x74, 0x61,
        0x63, 0x6B,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::AnimatePacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->action == bp::AnimatePacket::Action::MagicCriticalHit);
    REQUIRE(rt->target_runtime_id == static_cast<bp::ActorRuntimeID>(7));
    REQUIRE(rt->data == 1.5f);
    REQUIRE(rt->swing_source.has_value());
    REQUIRE(*rt->swing_source == bp::ActorSwingSource::Attack);
}

TEST_CASE("AnimatePacket: round-trip with absent swing source")
{
    bp::AnimatePacket pkt;
    pkt.action = bp::AnimatePacket::Action::Swing;
    pkt.target_runtime_id = static_cast<bp::ActorRuntimeID>(1);
    pkt.data = 0.0f;

    // generated by gophertunnel:
    // packet.Animate{ActionType: 1, EntityRuntimeID: 1}
    const std::vector<std::uint8_t> golden{0x01, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::AnimatePacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE_FALSE(rt->swing_source.has_value());
}

TEST_CASE("AnimateEntityPacket: id + round-trip with a length-prefixed list")
{
    STATIC_REQUIRE(bp::AnimateEntityPacket::Id == 158);

    bp::AnimateEntityPacket pkt;
    pkt.stop_expression_version = 0;
    pkt.blend_out_time = 0.0f;
    pkt.runtime_ids = {static_cast<bp::ActorRuntimeID>(1),
                       static_cast<bp::ActorRuntimeID>(2)};

    // generated by gophertunnel:
    // packet.AnimateEntity{EntityRuntimeIDs: []uint64{1, 2}}
    const std::vector<std::uint8_t> golden{
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x02, 0x01, 0x02,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::AnimateEntityPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->runtime_ids.size() == 2);
    REQUIRE(rt->runtime_ids[1] == static_cast<bp::ActorRuntimeID>(2));
}

TEST_CASE("EmoteListPacket: id + round-trip with a list of uuid.UUID")
{
    STATIC_REQUIRE(bp::EmoteListPacket::Id == 152);

    bp::EmoteListPacket pkt;
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(7);
    pkt.emote_piece_ids = {bp::UUID{0x0102030405060708ULL, 0x090A0B0C0D0E0F10ULL}};

    // generated by gophertunnel:
    // packet.EmoteList{PlayerRuntimeID: 7, EmotePieces: []uuid.UUID{uuid.MustParse("01020304-0506-0708-090a-0b0c0d0e0f10")}}
    const std::vector<std::uint8_t> golden{
        0x07, 0x01, 0x08, 0x07, 0x06, 0x05, 0x04, 0x03, 0x02, 0x01,
        0x10, 0x0F, 0x0E, 0x0D, 0x0C, 0x0B, 0x0A, 0x09,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::EmoteListPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->emote_piece_ids.size() == 1);
    REQUIRE(rt->emote_piece_ids[0].most_significant_bits == 0x0102030405060708ULL);
}

TEST_CASE("UpdateAttributesPacket: id + round-trip with nested attribute list")
{
    STATIC_REQUIRE(bp::UpdateAttributesPacket::Id == 29);

    bp::AttributeData health;
    health.min_value = 0.0f;
    health.max_value = 20.0f;
    health.current_value = 15.0f;
    health.default_min_value = 0.0f;
    health.default_max_value = 20.0f;
    health.default_value = 20.0f;
    health.name = "minecraft:health";
    health.modifiers = {bp::AttributeModifier{
        "id", "nm", 1.0f, bp::AttributeModifierOperation::OperationAddition,
        bp::AttributeOperands::OperandMin, true}};

    bp::UpdateAttributesPacket pkt;
    pkt.runtime_id = static_cast<bp::ActorRuntimeID>(42);
    pkt.attribute_data = {health};
    pkt.tick = 3;

    // generated by gophertunnel:
    // packet.UpdateAttributes{EntityRuntimeID: 42, Attributes: []protocol.Attribute{{AttributeValue: protocol.AttributeValue{Name: "minecraft:health", Min: 0, Max: 20, Value: 15}, DefaultMin: 0, DefaultMax: 20, Default: 20, Modifiers: []protocol.AttributeModifier{{ID: "id", Name: "nm", Amount: 1, Operation: 0, Operand: 0, Serializable: true}}}}, Tick: 3}
    const std::vector<std::uint8_t> golden{
        0x2A, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xA0, 0x41, 0x00, 0x00,
        0x70, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0xA0, 0x41, 0x00, 0x00,
        0xA0, 0x41, 0x10, 0x6D, 0x69, 0x6E, 0x65, 0x63, 0x72, 0x61, 0x66, 0x74,
        0x3A, 0x68, 0x65, 0x61, 0x6C, 0x74, 0x68, 0x01, 0x02, 0x69, 0x64, 0x02,
        0x6E, 0x6D, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
        0x00, 0x00, 0x01, 0x03,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::UpdateAttributesPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->attribute_data.size() == 1);
    REQUIRE(rt->attribute_data[0].name == "minecraft:health");
    REQUIRE(rt->attribute_data[0].modifiers[0].serialize);
    REQUIRE(rt->tick == 3);
}
