#include <string>

#include <protocol/game.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.SetCommandsEnabled{Enabled: true}
const std::string golden = bytes({
    0x01,
});

// generated by gophertunnel: &packet.SetCommandsEnabled{Enabled: false}
const std::string golden_disabled = bytes({
    0x00,
});

}  // namespace

TEST_CASE("packet id is 59")
{
    STATIC_REQUIRE(bp::SetCommandsEnabledPacket_<2168>::Id == 59);
    STATIC_REQUIRE_FALSE(bp::has_packet_v<1001, 59>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 59>);
}

TEST_CASE("set-commands-enabled round-trips against the golden")
{
    bp::SetCommandsEnabledPacket_<2168> packet;
    packet.commands_enabled = true;
    REQUIRE(encode(packet) == golden);

    REQUIRE(decode<bp::SetCommandsEnabledPacket_<2168>>(golden).commands_enabled == true);
}

TEST_CASE("the body is the bool alone, with no member-present byte in front of it")
{
    bp::SetCommandsEnabledPacket_<2168> packet;
    packet.commands_enabled = false;
    REQUIRE(encode(packet) == golden_disabled);

    REQUIRE(decode<bp::SetCommandsEnabledPacket_<2168>>(golden_disabled).commands_enabled == false);
    REQUIRE(rejects<bp::SetCommandsEnabledPacket_<2168>>(std::string{}));
}
