#include <cstdint>
#include <string>

#include <protocol/actor.h>
#include <protocol/movement.h>

#include "fixture.hpp"

namespace {

// MoveActorDeltaPacket cerealised at 2168, and this is the packet where that shows
// most. At 1001 MoveActorDeltaData led with the uint16 Header union bedrock-headers
// declares (mContainsPositionX .. mForceCompletion, ten bits) and wrote only the
// components whose bit was set; gophertunnel and CloudburstMC v419 both write it that
// way. Cerealising dropped the word: each component became a std::optional with its own
// presence byte, and the four booleans became four bytes of their own.
constexpr std::uint16_t HAS_X = 1;
constexpr std::uint16_t HAS_Z = 4;
constexpr std::uint16_t HAS_ROT_Y = 16;
constexpr std::uint16_t ON_GROUND = 64;
constexpr std::uint16_t MOVED = HAS_X | HAS_Z | HAS_ROT_Y | ON_GROUND;

}  // namespace

TEST_CASE("packet id is 111 at both versions")
{
    STATIC_REQUIRE(bp::MoveActorDeltaPacket_<1001>::Id == 111);
    STATIC_REQUIRE(bp::MoveActorDeltaPacket_<2168>::Id == 111);
}

TEST_CASE("MoveActorDeltaPacket: v1001 round-trip")
{
    using Packet = bp::MoveActorDeltaPacket_<1001>;

    Packet pkt;
    pkt.move_data.runtime_id = bp::ActorRuntimeID{2};
    pkt.move_data.header = MOVED;
    pkt.move_data.new_position_x = 1.0f;
    pkt.move_data.new_position_z = 3.0f;
    pkt.move_data.rot_y = 64;

    // generated by gophertunnel:
    // packet.MoveActorDelta{EntityRuntimeID: 2,
    //   Flags: MoveActorDeltaFlagHasX | MoveActorDeltaFlagHasZ |
    //          MoveActorDeltaFlagHasRotY | MoveActorDeltaFlagOnGround,
    //   Position: {1, 0, 3}, Rotation: {0, 90, 0}}
    const std::string golden = bytes({
        0x02, 0x55, 0x00, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x00, 0x40, 0x40, 0x40,
    });

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.move_data.header == MOVED);
    REQUIRE(rt.move_data.new_position_x == 1.0f);
    REQUIRE(rt.move_data.new_position_z == 3.0f);
    REQUIRE(rt.move_data.rot_y == 64);

    // The unset components never reached the wire, so they come back default-constructed.
    REQUIRE(rt.move_data.new_position_y == 0.0f);
    REQUIRE(rt.move_data.rot_x == 0);
    REQUIRE(rt.move_data.rot_y_head == 0);
}

TEST_CASE("MoveActorDeltaPacket: v2168 round-trip")
{
    using Packet = bp::MoveActorDeltaPacket_<2168>;

    Packet pkt;
    pkt.move_data.runtime_id = bp::ActorRuntimeID{2};
    pkt.move_data.new_position_x = 1.0f;
    pkt.move_data.new_position_z = 3.0f;
    pkt.move_data.rot_y = static_cast<std::int8_t>(64);
    pkt.move_data.is_on_ground = true;

    // generated by CloudburstMC Bedrock_v2168:
    // MoveEntityDeltaPacket{runtimeEntityId: 2, flags: [HAS_X, HAS_Z, HAS_YAW],
    //   x: 1, z: 3, yaw: 90, onGround: true, forceMove: false,
    //   forceMoveLocalEntity: false, forceCompletion: false}
    const std::string golden = bytes({
        0x02, 0x01, 0x00, 0x00, 0x80, 0x3F, 0x00, 0x01, 0x00, 0x00, 0x40, 0x40,
        0x00, 0x01, 0x40, 0x00, 0x01, 0x00, 0x00, 0x00,
    });

    REQUIRE(encode(pkt) == golden);

    const auto rt = decode<Packet>(golden);
    REQUIRE(rt.move_data.new_position_x == 1.0f);
    REQUIRE_FALSE(rt.move_data.new_position_y.has_value());
    REQUIRE(rt.move_data.new_position_z == 3.0f);
    REQUIRE_FALSE(rt.move_data.rot_x.has_value());
    REQUIRE(rt.move_data.rot_y == 64);
    REQUIRE_FALSE(rt.move_data.rot_y_head.has_value());
    REQUIRE(rt.move_data.is_on_ground);
    REQUIRE_FALSE(rt.move_data.force_completion);
}

// Six presence bytes plus four booleans replace one two-byte word, so the fully-absent
// body grows from three bytes to eleven while the loaded one grows from twelve to twenty.
TEST_CASE("MoveActorDeltaPacket: the flags word and the presence bytes are a hard break")
{
    bp::MoveActorDeltaPacket_<1001> empty_older;
    empty_older.move_data.runtime_id = bp::ActorRuntimeID{2};
    REQUIRE(encode(empty_older).size() == 3);

    bp::MoveActorDeltaPacket_<2168> empty_newer;
    empty_newer.move_data.runtime_id = bp::ActorRuntimeID{2};
    REQUIRE(encode(empty_newer).size() == 11);

    bp::MoveActorDeltaPacket_<1001> older;
    older.move_data.runtime_id = bp::ActorRuntimeID{2};
    older.move_data.header = MOVED;
    older.move_data.new_position_x = 1.0f;
    older.move_data.new_position_z = 3.0f;
    older.move_data.rot_y = 64;

    bp::MoveActorDeltaPacket_<2168> newer;
    newer.move_data.runtime_id = bp::ActorRuntimeID{2};
    newer.move_data.new_position_x = 1.0f;
    newer.move_data.new_position_z = 3.0f;
    newer.move_data.rot_y = 64;
    newer.move_data.is_on_ground = true;

    REQUIRE(encode(older).size() == 12);
    REQUIRE(encode(newer).size() == 20);
    REQUIRE(rejects<bp::MoveActorDeltaPacket_<2168>>(encode(older)));
}

// 2192 appended a uvarint64 tick count. It has no golden -- gophertunnel stops at
// 2168 -- so the assertions are structural: the body grows by the varint, and a 2168
// one runs short of it.
TEST_CASE("MoveActorDeltaPacket: v2192 appends the tick count")
{
    bp::MoveActorDeltaPacket_<2168> older;
    older.move_data.runtime_id = bp::ActorRuntimeID{2};
    older.move_data.new_position_x = 1.0f;
    older.move_data.is_on_ground = true;

    bp::MoveActorDeltaPacket_<2192> newer;
    newer.move_data.runtime_id = bp::ActorRuntimeID{2};
    newer.move_data.new_position_x = 1.0f;
    newer.move_data.is_on_ground = true;
    newer.move_data.ticks = 7;

    REQUIRE(encode(newer).size() == encode(older).size() + 1);
    REQUIRE(rejects<bp::MoveActorDeltaPacket_<2192>>(encode(older)));
    REQUIRE(decode<bp::MoveActorDeltaPacket_<2192>>(encode(newer)).move_data.ticks == 7);
}

// is_on_ground and the three force flags live in the 1001 header word rather than as
// fields of their own, which is why a translator has to read them out of it: setting
// the bit adds nothing to the body, where the 2168 boolean is a byte.
TEST_CASE("MoveActorDeltaPacket: the 1001 booleans are header bits")
{
    bp::MoveActorDeltaPacket_<1001> pkt;
    pkt.move_data.runtime_id = bp::ActorRuntimeID{2};
    pkt.move_data.header = ON_GROUND;

    const auto encoded = encode(pkt);
    REQUIRE(encoded.size() == 3);
    REQUIRE(decode<bp::MoveActorDeltaPacket_<1001>>(encoded).move_data.header == ON_GROUND);
}
