#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("ResourcePackClientResponsePacket: id + uint16-prefixed string list")
{
    STATIC_REQUIRE(bp::ResourcePackClientResponsePacket::Id == 8);

    bp::ResourcePackClientResponsePacket pkt;
    pkt.response = bp::ResourcePackResponse::DownloadingFinished;
    pkt.downloading_packs = {"pack_1.0.0"};

    // generated by gophertunnel:
    // packet.ResourcePackClientResponse{Response: 3, PacksToDownload: []string{"pack_1.0.0"}}
    const std::vector<std::uint8_t> golden{
        0x03, 0x01, 0x00, 0x0A, 0x70, 0x61, 0x63, 0x6B, 0x5F, 0x31, 0x2E, 0x30,
        0x2E, 0x30,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::ResourcePackClientResponsePacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->response == bp::ResourcePackResponse::DownloadingFinished);
    REQUIRE(rt->downloading_packs.size() == 1);
    REQUIRE(rt->downloading_packs[0] == "pack_1.0.0");
}
