#include <string>
#include <variant>

#include "fixture.hpp"

namespace {

using PacketV2168 = bp::DisconnectPacket_<2168>;
using PacketV2181 = bp::DisconnectPacket_<2181>;

// generated by gophertunnel (218ac3f):
// packet.Disconnect{Reason: 147, HideDisconnectionScreen: false, Message: "bye",
//   FilteredMessage: "b**"}
const std::string golden_shown = bytes({
    0xa6, 0x02, 0x00, 0x03, 0x62, 0x79, 0x65, 0x03, 0x62, 0x2a, 0x2a,
});

// generated by gophertunnel (218ac3f):
// packet.Disconnect{Reason: 147, HideDisconnectionScreen: true}
const std::string golden_hidden = bytes({
    0xa6, 0x02, 0x01,
});

}  // namespace

TEST_CASE("packet id is 5 at both eras")
{
    STATIC_REQUIRE(PacketV2168::Id == 5);
    STATIC_REQUIRE(PacketV2181::Id == 5);
}

// The messages are a cerealised two-case variant, not an optional, so the byte after
// the reason is the case index rather than a presence flag -- and the two invert.
// gophertunnel spells the same byte as HideDisconnectionScreen, which is why its
// bodies are these: false selects case 0 and the messages follow.
TEST_CASE("disconnect round-trips against the golden with its messages")
{
    PacketV2168 packet;
    packet.reason = bp::base::DisconnectFailReason::EDITOR_NOT_ALLOWED;
    packet.messages = bp::DisconnectPacketMessages{.message = "bye", .filtered_message = "b**"};
    REQUIRE(encode(packet) == golden_shown);

    const auto back = decode<PacketV2168>(golden_shown);
    REQUIRE(back.reason == bp::base::DisconnectFailReason::EDITOR_NOT_ALLOWED);
    REQUIRE(back.messages.index() == 0);
    REQUIRE(std::get<0>(back.messages).message == "bye");
    REQUIRE(std::get<0>(back.messages).filtered_message == "b**");
}

TEST_CASE("disconnect round-trips against the golden with no messages")
{
    PacketV2168 packet;
    packet.reason = bp::base::DisconnectFailReason::EDITOR_NOT_ALLOWED;
    packet.messages = std::monostate{};
    REQUIRE(encode(packet) == golden_hidden);

    const auto back = decode<PacketV2168>(golden_hidden);
    REQUIRE(back.messages.index() == 1);
}

// 2181 appends MissingStructureData, which pushes the trailing sentinel up one. The
// reason is a varint of the enumerator, so every value below it is unmoved and the
// two eras share every body the golden covers.
TEST_CASE("disconnect: 2181 appends a fail reason")
{
    STATIC_REQUIRE(static_cast<int>(bp::base::DisconnectFailReason::MAX_DISCONNECT_FAIL_REASON) == 148);
    STATIC_REQUIRE(static_cast<int>(bp::v2181::DisconnectFailReason::MISSING_STRUCTURE_DATA) == 148);
    STATIC_REQUIRE(static_cast<int>(bp::v2181::DisconnectFailReason::MAX_DISCONNECT_FAIL_REASON) == 149);

    PacketV2181 packet;
    packet.reason = bp::v2181::DisconnectFailReason::MISSING_STRUCTURE_DATA;
    packet.messages = std::monostate{};
    REQUIRE(decode<PacketV2181>(encode(packet)).reason == bp::v2181::DisconnectFailReason::MISSING_STRUCTURE_DATA);

    REQUIRE(decode<PacketV2181>(golden_shown).reason == bp::v2181::DisconnectFailReason::EDITOR_NOT_ALLOWED);
    REQUIRE(decode<PacketV2181>(golden_hidden).messages.index() == 1);
}
