#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

namespace {

template <typename T>
std::vector<std::uint8_t> encode(const T &value)
{
    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, value);
    return buf;
}

}  // namespace

TEST_CASE("PlayerEnchantOptionsPacket: id + round-trip with one ItemEnchantOption")
{
    STATIC_REQUIRE(bp::PlayerEnchantOptionsPacket::Id == 146);

    bp::PlayerEnchantOptionsPacket pkt;
    bp::ItemEnchantOption opt;
    opt.cost = 7;
    opt.enchants.slot = 0;
    opt.enchants.enchants_1.push_back(bp::EnchantmentInstance{5, 2});
    opt.enchant_name = "calm imbue range";
    opt.enchant_net_id = 42;
    pkt.options.push_back(opt);

    // generated by gophertunnel:
    // packet.PlayerEnchantOptions{Options: []protocol.EnchantmentOption{{
    //   Cost: 7,
    //   Enchantments: protocol.ItemEnchantments{Slot: 0,
    //     Enchantments: [3][]protocol.EnchantmentInstance{{}, {{Type: 5, Level: 2}}, {}}},
    //   Name: "calm imbue range", RecipeNetworkID: 42}}}
    const std::vector<std::uint8_t> golden{
        0x01, 0x07, 0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x05, 0x02, 0x00, 0x10,
        0x63, 0x61, 0x6C, 0x6D, 0x20, 0x69, 0x6D, 0x62, 0x75, 0x65, 0x20, 0x72,
        0x61, 0x6E, 0x67, 0x65, 0x2A,
    };

    REQUIRE(encode(pkt) == golden);

    bp::BinaryReader in{golden};
    auto rt = bp::deserialize<bp::PlayerEnchantOptionsPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->options.size() == 1);
    REQUIRE(rt->options[0].cost == 7);
    REQUIRE(rt->options[0].enchant_name == "calm imbue range");
    REQUIRE(rt->options[0].enchants.enchants_1.size() == 1);
    REQUIRE(rt->options[0].enchants.enchants_1[0].enchant_type == 5);
    REQUIRE(rt->options[0].enchants.enchants_1[0].level == 2);
}
