#include <string>

#include <bedrock/protocol/pack.h>

#include "fixture.hpp"

namespace {

using PacketV975 = bp::ResourcePacksInfoPacket_<975>;
using PacketV1001 = bp::ResourcePacksInfoPacket_<1001>;
using PacketV2168 = bp::ResourcePacksInfoPacket_<2168>;

bp::PackInfoData entry()
{
    bp::PackInfoData pack;
    pack.pack_id_version.id = {0x0a0b0c0d0e0f1011ULL, 0x1213141516171819ULL};
    pack.pack_id_version.version.version = "2.0.0";
    pack.pack_size = 4096;
    pack.content_key = "key";
    pack.subpack_name = "sub";
    pack.content_identity.identity = "cid";
    pack.has_scripts = true;
    pack.is_ray_tracing_capable = true;
    pack.cdn_url = "http://cdn";
    return pack;
}

template <class Packet>
Packet sample()
{
    Packet packet;
    packet.resource_pack_required = true;
    packet.has_scripts = true;
    packet.world_template_id_and_version.id = {0x0011223344556677ULL, 0x8899aabbccddeeffULL};
    packet.world_template_id_and_version.version.version = "1.2.3";
    packet.resource_packs = {entry()};
    return packet;
}

template <class Packet>
Packet empty()
{
    Packet packet;
    packet.world_template_id_and_version.id = {0x0011223344556677ULL, 0x8899aabbccddeeffULL};
    packet.world_template_id_and_version.version.version = "1.2.3";
    return packet;
}

// generated by gophertunnel, and byte for byte again at de090ae (the last pre-1.26.30
// commit, CurrentProtocol 975):
// packet.ResourcePacksInfo{TexturePackRequired: true, HasScripts: true, WorldTemplateUUID:
//   00112233-4455-6677-8899-aabbccddeeff, WorldTemplateVersion: "1.2.3", TexturePacks:
//   []protocol.TexturePackInfo{{UUID: 0a0b0c0d-0e0f-1011-1213-141516171819, Version: "2.0.0",
//   Size: 4096, ContentKey: "key", SubPackName: "sub", ContentIdentity: "cid", HasScripts: true,
//   RTXEnabled: true, DownloadURL: "http://cdn"}}}
const std::string golden_v1001 = bytes({
    0x01, 0x00, 0x01, 0x00, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11, 0x00,
    0xff, 0xee, 0xdd, 0xcc, 0xbb, 0xaa, 0x99, 0x88, 0x05, 0x31, 0x2e, 0x32,
    0x2e, 0x33, 0x01, 0x00, 0x11, 0x10, 0x0f, 0x0e, 0x0d, 0x0c, 0x0b, 0x0a,
    0x19, 0x18, 0x17, 0x16, 0x15, 0x14, 0x13, 0x12, 0x05, 0x32, 0x2e, 0x30,
    0x2e, 0x30, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x6b,
    0x65, 0x79, 0x03, 0x73, 0x75, 0x62, 0x03, 0x63, 0x69, 0x64, 0x01, 0x00,
    0x01, 0x0a, 0x68, 0x74, 0x74, 0x70, 0x3a, 0x2f, 0x2f, 0x63, 0x64, 0x6e,
});

// generated by gophertunnel, and again at de090ae: the same packet with no texture packs
// and every flag false.
const std::string golden_v1001_empty = bytes({
    0x00, 0x00, 0x00, 0x00, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11, 0x00,
    0xff, 0xee, 0xdd, 0xcc, 0xbb, 0xaa, 0x99, 0x88, 0x05, 0x31, 0x2e, 0x32,
    0x2e, 0x33, 0x00, 0x00,
});

// generated by CloudburstMC Bedrock_v2168:
// ResourcePacksInfoPacket{forcedToAccept: true, scriptingEnabled: true, worldTemplateId:
//   00112233-4455-6677-8899-aabbccddeeff, worldTemplateVersion: "1.2.3", resourcePackInfos:
//   [Entry(0a0b0c0d-0e0f-1011-1213-141516171819, "2.0.0", 4096, "key", "sub", "cid", true,
//   true, false, "http://cdn")]}
const std::string golden_v2168 = bytes({
    0x01, 0x00, 0x01, 0x00, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11, 0x00,
    0xff, 0xee, 0xdd, 0xcc, 0xbb, 0xaa, 0x99, 0x88, 0x05, 0x31, 0x2e, 0x32,
    0x2e, 0x33, 0x01, 0x11, 0x10, 0x0f, 0x0e, 0x0d, 0x0c, 0x0b, 0x0a, 0x19,
    0x18, 0x17, 0x16, 0x15, 0x14, 0x13, 0x12, 0x05, 0x32, 0x2e, 0x30, 0x2e,
    0x30, 0x00, 0x10, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x03, 0x6b, 0x65,
    0x79, 0x03, 0x73, 0x75, 0x62, 0x03, 0x63, 0x69, 0x64, 0x01, 0x00, 0x01,
    0x0a, 0x68, 0x74, 0x74, 0x70, 0x3a, 0x2f, 0x2f, 0x63, 0x64, 0x6e,
});

// generated by CloudburstMC Bedrock_v2168: the same packet with no resource packs.
const std::string golden_v2168_empty = bytes({
    0x00, 0x00, 0x00, 0x00, 0x77, 0x66, 0x55, 0x44, 0x33, 0x22, 0x11, 0x00,
    0xff, 0xee, 0xdd, 0xcc, 0xbb, 0xaa, 0x99, 0x88, 0x05, 0x31, 0x2e, 0x32,
    0x2e, 0x33, 0x00,
});

}  // namespace

TEST_CASE("packet id is 6 at every version")
{
    STATIC_REQUIRE(PacketV975::Id == 6);
    STATIC_REQUIRE(PacketV1001::Id == 6);
    STATIC_REQUIRE(PacketV2168::Id == 6);
}

TEST_CASE("resource-packs-info v975 round-trips against the golden")
{
    REQUIRE(encode(sample<PacketV975>()) == golden_v1001);
    REQUIRE(encode(empty<PacketV975>()) == golden_v1001_empty);
}

TEST_CASE("resource-packs-info v1001 round-trips against the golden")
{
    REQUIRE(encode(sample<PacketV1001>()) == golden_v1001);
    REQUIRE(encode(empty<PacketV1001>()) == golden_v1001_empty);

    const auto back = decode<PacketV1001>(golden_v1001);
    REQUIRE(back.resource_pack_required);
    REQUIRE_FALSE(back.has_addon_packs);
    REQUIRE(back.has_scripts);
    REQUIRE(back.world_template_id_and_version.version.version == "1.2.3");
    REQUIRE(back.resource_packs.size() == 1);
    REQUIRE(back.resource_packs[0].pack_size == 4096);
    REQUIRE(back.resource_packs[0].content_identity.identity == "cid");
    REQUIRE(back.resource_packs[0].cdn_url == "http://cdn");
}

TEST_CASE("resource-packs-info v2168 round-trips against the golden")
{
    REQUIRE(encode(sample<PacketV2168>()) == golden_v2168);
    REQUIRE(encode(empty<PacketV2168>()) == golden_v2168_empty);

    const auto back = decode<PacketV2168>(golden_v2168);
    REQUIRE(back.resource_packs.size() == 1);
    REQUIRE(back.resource_packs[0].pack_id_version.version.version == "2.0.0");
    REQUIRE(back.resource_packs[0].is_ray_tracing_capable);
    REQUIRE_FALSE(back.resource_packs[0].is_addon_pack);
}

// 2168 is the whole packet minus one byte: the pack count went from a fixed uint16 to a
// uvarint32, and nothing else in the closure moved.
TEST_CASE("resource-packs-info differs only in the pack count's width")
{
    REQUIRE(golden_v1001.size() == golden_v2168.size() + 1);
    REQUIRE(golden_v1001_empty.size() == golden_v2168_empty.size() + 1);
    REQUIRE(golden_v1001.substr(0, 26) == golden_v2168.substr(0, 26));
    REQUIRE(golden_v1001.substr(28) == golden_v2168.substr(27));
}

TEST_CASE("resource-packs-info does not decode across the 2168 boundary")
{
    // The count's high byte becomes the first byte of the pack's uuid, and every length
    // prefix after it lands on a payload byte.
    REQUIRE(rejects<PacketV2168>(golden_v1001));

    // The other way the first pack's uuid is read as the count's high byte, which asks for
    // 4353 packs.
    REQUIRE(rejects<PacketV1001>(golden_v2168));
    REQUIRE(rejects<PacketV1001>(golden_v2168_empty));
}

// With no packs the count is a zero either era, so only the trailing byte tells them apart.
TEST_CASE("resource-packs-info leaves a byte over when an empty 1001 body is read at 2168")
{
    REQUIRE(decode_partial<PacketV2168>(golden_v1001_empty).resource_packs.empty());
}
