#include <cstdint>
#include <vector>

#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("MapCreateLockedCopyPacket: id + round-trip with two varint64 map ids")
{
    STATIC_REQUIRE(bp::MapCreateLockedCopyPacket::Id == 131);

    bp::MapCreateLockedCopyPacket pkt;
    pkt.original_map_id = static_cast<bp::ActorUniqueID>(10);
    pkt.new_map_id = static_cast<bp::ActorUniqueID>(11);

    // generated by gophertunnel:
    // packet.MapCreateLockedCopy{OriginalMapID: 10, NewMapID: 11}
    const std::vector<std::uint8_t> golden{0x14, 0x16};

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::MapCreateLockedCopyPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(in.getUnreadLength() == 0);
    REQUIRE(rt->original_map_id == 10);
    REQUIRE(rt->new_map_id == 11);
}
