#include <string>

#include <bedrock/protocol/actor.h>
#include <bedrock/protocol/structure.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.StructureTemplateDataRequest{
//   StructureName: "mystructure", Position: protocol.BlockPos{1, -2, 3},
//   Settings: protocol.StructureSettings{PaletteName: "default", IgnoreEntities: true,
//     IgnoreBlocks: false, AllowNonTickingChunks: true, Size: protocol.BlockPos{5, 6, 7},
//     Offset: protocol.BlockPos{-1, 0, 1}, LastEditingPlayerUniqueID: 300, Rotation: 1,
//     Mirror: 2, AnimationMode: 2, AnimationDuration: 0.5, Integrity: 1.0,
//     Seed: 0xdeadbeef, Pivot: mgl32.Vec3{0.5, 1.5, 2.5}},
//   RequestType: packet.StructureTemplateRequestQuerySavedStructure}
const std::string golden = bytes({
    0x0b, 0x6d, 0x79, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65,
    0x02, 0x03, 0x06, 0x07, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x01,
    0x00, 0x01, 0x0a, 0x0c, 0x0e, 0x01, 0x00, 0x02, 0xd8, 0x04, 0x01, 0x02,
    0x02, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x00, 0x80, 0x3f, 0xef, 0xbe, 0xad,
    0xde, 0x00, 0x00, 0x00, 0x3f, 0x00, 0x00, 0xc0, 0x3f, 0x00, 0x00, 0x20,
    0x40, 0x03,
});

// generated by gophertunnel: &packet.StructureTemplateDataRequest{}
const std::string golden_zeroed = bytes({
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
});

}  // namespace

TEST_CASE("packet id is 132")
{
    STATIC_REQUIRE(bp::StructureTemplateDataRequestPacket::Id == 132);
    STATIC_REQUIRE(bp::has_packet_v<1001, 132>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 132>);
}

TEST_CASE("structure-template-data-request round-trips against the golden")
{
    bp::StructureTemplateDataRequestPacket packet;
    packet.structure_name = "mystructure";
    packet.structure_block_pos = {.x = 1, .y = -2, .z = 3};
    packet.structure_settings = {.palette_name = "default",
                                 .ignore_entities = true,
                                 .ignore_blocks = false,
                                 .allow_non_ticking_player_and_ticking_area_chunks = true,
                                 .structure_size = {.x = 5, .y = 6, .z = 7},
                                 .structure_offset = {.x = -1, .y = 0, .z = 1},
                                 .last_touched_by_player = bp::ActorUniqueID{300},
                                 .rotation = bp::Rotation::Rotate90,
                                 .mirror = bp::Mirror::Z,
                                 .animation_mode = bp::AnimationMode::Blocks,
                                 .animation_seconds = 0.5F,
                                 .integrity_value = 1.0F,
                                 .integrity_seed = bp::RandomSeed{0xdeadbeefU},
                                 .pivot = {.x = 0.5F, .y = 1.5F, .z = 2.5F}};
    packet.request_operation = bp::StructureTemplateRequestOperation::QuerySavedStructure;
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::StructureTemplateDataRequestPacket>(golden);
    REQUIRE(back.structure_name == "mystructure");
    REQUIRE(back.structure_block_pos.x == 1);
    REQUIRE(back.structure_block_pos.y == -2);
    REQUIRE(back.structure_block_pos.z == 3);
    REQUIRE(back.structure_settings.palette_name == "default");
    REQUIRE(back.structure_settings.ignore_entities == true);
    REQUIRE(back.structure_settings.ignore_blocks == false);
    REQUIRE(back.structure_settings.allow_non_ticking_player_and_ticking_area_chunks == true);
    REQUIRE(back.structure_settings.structure_size.x == 5);
    REQUIRE(back.structure_settings.structure_size.y == 6);
    REQUIRE(back.structure_settings.structure_size.z == 7);
    REQUIRE(back.structure_settings.structure_offset.x == -1);
    REQUIRE(back.structure_settings.structure_offset.y == 0);
    REQUIRE(back.structure_settings.structure_offset.z == 1);
    REQUIRE(back.structure_settings.last_touched_by_player == bp::ActorUniqueID{300});
    REQUIRE(back.structure_settings.rotation == bp::Rotation::Rotate90);
    REQUIRE(back.structure_settings.mirror == bp::Mirror::Z);
    REQUIRE(back.structure_settings.animation_mode == bp::AnimationMode::Blocks);
    REQUIRE(back.structure_settings.animation_seconds == 0.5F);
    REQUIRE(back.structure_settings.integrity_value == 1.0F);
    REQUIRE(back.structure_settings.integrity_seed == bp::RandomSeed{0xdeadbeefU});
    REQUIRE(back.structure_settings.pivot.x == 0.5F);
    REQUIRE(back.structure_settings.pivot.y == 1.5F);
    REQUIRE(back.structure_settings.pivot.z == 2.5F);
    REQUIRE(back.request_operation == bp::StructureTemplateRequestOperation::QuerySavedStructure);
}

TEST_CASE("a zeroed structure-template-data-request body carries no presence byte")
{
    bp::StructureTemplateDataRequestPacket packet;
    packet.structure_name = "";
    packet.structure_block_pos = {.x = 0, .y = 0, .z = 0};
    packet.structure_settings = {.palette_name = "",
                                 .ignore_entities = false,
                                 .ignore_blocks = false,
                                 .allow_non_ticking_player_and_ticking_area_chunks = false,
                                 .structure_size = {.x = 0, .y = 0, .z = 0},
                                 .structure_offset = {.x = 0, .y = 0, .z = 0},
                                 .last_touched_by_player = bp::ActorUniqueID{0},
                                 .rotation = bp::Rotation::None,
                                 .mirror = bp::Mirror::None,
                                 .animation_mode = bp::AnimationMode::None,
                                 .animation_seconds = 0.0F,
                                 .integrity_value = 0.0F,
                                 .integrity_seed = bp::RandomSeed{0},
                                 .pivot = {.x = 0.0F, .y = 0.0F, .z = 0.0F}};
    packet.request_operation = bp::StructureTemplateRequestOperation::None;

    const auto wire = encode(packet);
    REQUIRE(wire == golden_zeroed);
    REQUIRE(wire.size() == 43);
    REQUIRE(decode<bp::StructureTemplateDataRequestPacket>(wire).structure_name.empty());
}
