#include <bedrock/protocol.hpp>
#include <catch2/catch_test_macros.hpp>

namespace bp = bedrock::protocol;

TEST_CASE("TrimDataPacket: id + round-trip of pattern and material lists")
{
    STATIC_REQUIRE(bp::TrimDataPacket::Id == 302);

    bp::TrimDataPacket pkt;
    pkt.trim_pattern_list = {bp::TrimPattern{"p_item", "p_id"}};
    pkt.trim_material_list = {bp::TrimMaterial{"m_id", "x", "m_item"}};

    // generated by gophertunnel:
    // packet.TrimData{Patterns: []protocol.TrimPattern{{ItemName: "p_item", PatternID: "p_id"}}, Materials: []protocol.TrimMaterial{{MaterialID: "m_id", Colour: "x", ItemName: "m_item"}}}
    const std::vector<std::uint8_t> golden{
        0x01, 0x06, 0x70, 0x5F, 0x69, 0x74, 0x65, 0x6D, 0x04, 0x70, 0x5F, 0x69,
        0x64, 0x01, 0x04, 0x6D, 0x5F, 0x69, 0x64, 0x01, 0x78, 0x06, 0x6D, 0x5F,
        0x69, 0x74, 0x65, 0x6D,
    };

    std::vector<std::uint8_t> buf;
    bp::BinaryStream out{buf};
    bp::serialize(out, pkt);
    REQUIRE(buf == golden);

    bp::BinaryReader in{buf};
    auto rt = bp::deserialize<bp::TrimDataPacket>(in);
    REQUIRE(rt.has_value());
    REQUIRE(rt->trim_pattern_list.size() == 1);
    REQUIRE(rt->trim_pattern_list[0].pattern_id == "p_id");
    REQUIRE(rt->trim_material_list[0].item_name == "m_item");
}
