#include <string>

#include <bedrock/protocol/actor.h>

#include "fixture.hpp"

namespace {

// generated by gophertunnel: &packet.AddBehaviourTree{BehaviourTree:
// "{\"behaviors\":[\"minecraft:behavior.float\"]}"}
const std::string golden = bytes({
    0x2a, 0x7b, 0x22, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x73,
    0x22, 0x3a, 0x5b, 0x22, 0x6d, 0x69, 0x6e, 0x65, 0x63, 0x72, 0x61, 0x66,
    0x74, 0x3a, 0x62, 0x65, 0x68, 0x61, 0x76, 0x69, 0x6f, 0x72, 0x2e, 0x66,
    0x6c, 0x6f, 0x61, 0x74, 0x22, 0x5d, 0x7d,
});

// generated by gophertunnel: &packet.AddBehaviourTree{BehaviourTree: ""}
const std::string golden_empty = bytes({
    0x00,
});

}  // namespace

TEST_CASE("packet id is 89")
{
    STATIC_REQUIRE(bp::AddBehaviorTreePacket::Id == 89);
    STATIC_REQUIRE(bp::has_packet_v<1001, 89>);
    STATIC_REQUIRE(bp::has_packet_v<2168, 89>);
}

TEST_CASE("add-behavior-tree round-trips against the golden")
{
    bp::AddBehaviorTreePacket packet;
    packet.json_input = R"({"behaviors":["minecraft:behavior.float"]})";
    REQUIRE(encode(packet) == golden);

    const auto back = decode<bp::AddBehaviorTreePacket>(golden);
    REQUIRE(back.json_input == R"({"behaviors":["minecraft:behavior.float"]})");
}

TEST_CASE("an empty behavior tree is a lone length prefix")
{
    bp::AddBehaviorTreePacket packet;
    REQUIRE(encode(packet) == golden_empty);
    REQUIRE(decode<bp::AddBehaviorTreePacket>(golden_empty).json_input.empty());
}

TEST_CASE("the length prefix is a varint, not a byte")
{
    bp::AddBehaviorTreePacket packet;
    packet.json_input = std::string(200, 'a');
    const auto wire = encode(packet);
    REQUIRE(wire.size() == 202);
    REQUIRE(static_cast<unsigned char>(wire[0]) == 0xc8);
    REQUIRE(static_cast<unsigned char>(wire[1]) == 0x01);
    REQUIRE(decode<bp::AddBehaviorTreePacket>(wire).json_input == packet.json_input);
}
