from enum import IntEnum
from typing import Union

from protocol._dsl import enum, field, packet, value
from protocol._primitives import varint32

package = "bedrock.protocol"


@enum(since=622)
class DisconnectFailReason(IntEnum):
    UNKNOWN = 0
    CANT_CONNECT_NO_INTERNET = 1
    NO_PERMISSIONS = 2
    UNRECOVERABLE_ERROR = 3
    THIRD_PARTY_BLOCKED = 4
    THIRD_PARTY_NO_INTERNET = 5
    THIRD_PARTY_BAD_IP = 6
    THIRD_PARTY_NO_SERVER_OR_SERVER_LOCKED = 7
    VERSION_MISMATCH = 8
    SKIN_ISSUE = 9
    INVITE_SESSION_NOT_FOUND = 10
    EDU_LEVEL_SETTINGS_MISSING = 11
    LOCAL_SERVER_NOT_FOUND = 12
    LEGACY_DISCONNECT = 13
    USER_LEAVE_GAME_ATTEMPTED = 14
    PLATFORM_LOCKED_SKINS_ERROR = 15
    REALMS_WORLD_UNASSIGNED = 16
    REALMS_SERVER_CANT_CONNECT = 17
    REALMS_SERVER_HIDDEN = 18
    REALMS_SERVER_DISABLED_BETA = 19
    REALMS_SERVER_DISABLED = 20
    CROSS_PLATFORM_DISALLOWED = 21
    CANT_CONNECT = 22
    SESSION_NOT_FOUND = 23
    CLIENT_SETTINGS_INCOMPATIBLE_WITH_SERVER = 24
    SERVER_FULL = 25
    INVALID_PLATFORM_SKIN = 26
    EDITION_VERSION_MISMATCH = 27
    EDITION_MISMATCH = 28
    LEVEL_NEWER_THAN_EXE_VERSION = 29
    NO_FAIL_OCCURRED = 30
    BANNED_SKIN = 31
    TIMEOUT = 32
    SERVER_NOT_FOUND = 33
    OUTDATED_SERVER = 34
    OUTDATED_CLIENT = 35
    NO_PREMIUM_PLATFORM = 36
    MULTIPLAYER_DISABLED = 37
    NO_WI_FI = 38
    WORLD_CORRUPTION = 39
    NO_REASON = 40
    DISCONNECTED = 41
    INVALID_PLAYER = 42
    LOGGED_IN_OTHER_LOCATION = 43
    SERVER_ID_CONFLICT = 44
    NOT_ALLOWED = 45
    NOT_AUTHENTICATED = 46
    INVALID_TENANT = 47
    UNKNOWN_PACKET = 48
    UNEXPECTED_PACKET = 49
    INVALID_COMMAND_REQUEST_PACKET = 50
    HOST_SUSPENDED = 51
    LOGIN_PACKET_NO_REQUEST = 52
    LOGIN_PACKET_NO_CERT = 53
    MISSING_CLIENT = 54
    KICKED = 55
    KICKED_FOR_EXPLOIT = 56
    KICKED_FOR_IDLE = 57
    RESOURCE_PACK_PROBLEM = 58
    INCOMPATIBLE_PACK = 59
    OUT_OF_STORAGE = 60
    INVALID_LEVEL = 61
    DISCONNECT_PACKET_DEPRECATED = 62
    BLOCK_MISMATCH = 63
    INVALID_HEIGHTS = 64
    INVALID_WIDTHS = 65
    CONNECTION_LOST = 66
    ZOMBIE_CONNECTION = 67
    SHUTDOWN = 68
    REASON_NOT_SET = 69
    LOADING_STATE_TIMEOUT = 70
    RESOURCE_PACK_LOADING_FAILED = 71
    SEARCHING_FOR_SESSION_LOADING_SCREEN_FAILED = 72
    NETHER_NET_PROTOCOL_VERSION = 73
    SUBSYSTEM_STATUS_ERROR = 74
    EMPTY_AUTH_FROM_DISCOVERY = 75
    EMPTY_URL_FROM_DISCOVERY = 76
    EXPIRED_AUTH_FROM_DISCOVERY = 77
    UNKNOWN_SIGNAL_SERVICE_SIGN_IN_FAILURE = 78
    XBL_JOIN_LOBBY_FAILURE = 79
    UNSPECIFIED_CLIENT_INSTANCE_DISCONNECTION = 80
    NETHER_NET_SESSION_NOT_FOUND = 81
    NETHER_NET_CREATE_PEER_CONNECTION = 82
    NETHER_NET_ICE = 83
    NETHER_NET_CONNECT_REQUEST = 84
    NETHER_NET_CONNECT_RESPONSE = 85
    NETHER_NET_NEGOTIATION_TIMEOUT = 86
    NETHER_NET_INACTIVITY_TIMEOUT = 87
    STALE_CONNECTION_BEING_REPLACED = 88
    REALMS_SESSION_NOT_FOUND = 89
    BAD_PACKET = 90
    NETHER_NET_FAILED_TO_CREATE_OFFER = value(91, since=630)
    NETHER_NET_FAILED_TO_CREATE_ANSWER = value(92, since=630)
    NETHER_NET_FAILED_TO_SET_LOCAL_DESCRIPTION = value(93, since=630)
    NETHER_NET_FAILED_TO_SET_REMOTE_DESCRIPTION = value(94, since=630)
    NETHER_NET_NEGOTIATION_TIMEOUT_WAITING_FOR_RESPONSE = value(95, since=630)
    NETHER_NET_NEGOTIATION_TIMEOUT_WAITING_FOR_ACCEPT = value(96, since=630)
    NETHER_NET_INCOMING_CONNECTION_IGNORED = value(97, since=630)
    NETHER_NET_SIGNALING_PARSING_FAILURE = value(98, since=630)
    NETHER_NET_SIGNALING_UNKNOWN_ERROR = value(99, since=630)
    NETHER_NET_SIGNALING_UNICAST_DELIVERY_FAILED = value(100, since=630)
    NETHER_NET_SIGNALING_BROADCAST_DELIVERY_FAILED = value(101, since=630)
    NETHER_NET_SIGNALING_GENERIC_DELIVERY_FAILED = value(102, since=630)
    EDITOR_MISMATCH_EDITOR_WORLD = value(103, since=649)
    EDITOR_MISMATCH_VANILLA_WORLD = value(104, since=649)
    WORLD_TRANSFER_NOT_PRIMARY_CLIENT = value(105, since=649)
    REQUEST_SERVER_SHUTDOWN = value(106, since=649)
    CLIENT_GAME_SETUP_CANCELLED = value(107, since=649)
    CLIENT_GAME_SETUP_FAILED = value(108, since=649)
    NO_VENUE = value(109, since=671)
    NETHER_NET_SIGNALING_SIGNIN_FAILED = value(110, since=671)
    SESSION_ACCESS_DENIED = value(111, since=671)
    SERVICE_SIGNIN_ISSUE = value(112, since=671)
    NETHER_NET_NO_SIGNALING_CHANNEL = value(113, since=671)
    NETHER_NET_NOT_LOGGED_IN = value(114, since=671)
    NETHER_NET_CLIENT_SIGNALING_ERROR = value(115, since=671)
    SUB_CLIENT_LOGIN_DISABLED = value(116, since=712)
    DEEP_LINK_TRYING_TO_OPEN_DEMO_WORLD_WHILE_SIGNED_IN = value(117, since=729)
    ASYNC_JOIN_TASK_DENIED = value(118, since=800)
    REALMS_TIMELINE_REQUIRED = value(119, since=818)
    GUEST_WITHOUT_HOST = value(120, since=818)
    FAILED_TO_JOIN_EXPERIENCE = value(121, since=818)
    NETHER_NET_DATA_CHANNEL_CLOSED = value(123, since=827)
    DISCOVERY_ENVIRONMENT_MISMATCH = value(123, since=859)
    HOST_WITHOUT_KEYS = value(124, since=859)
    HOST_SIGNED_OUT = value(125, since=893)
    SCRIPT_WATCHDOG_EXCEPTION = value(126, since=893)
    SCRIPT_MEMORY_LIMIT_EXCEEDED = value(127, since=893)
    STORAGE_LOW_DURING_GAMEPLAY = value(128, since=893)
    STORAGE_FULL_DURING_GAMEPLAY = value(129, since=893)
    LEVEL_STORAGE_CORRUPTION = value(130, since=893)
    EDITION_MISMATCH_VANILLA_TO_EDU = value(131, since=893)
    EDITION_MISMATCH_EDU_TO_VANILLA = value(132, since=893)
    EDITOR_MISMATCH_EDITOR_TO_VANILLA = value(133, since=893)
    EDITOR_MISMATCH_VANILLA_TO_EDITOR = value(134, since=893)
    DENY_LISTED = value(135, since=893)


class DisconnectPacketMessages:
    message: str
    filtered_message: str = field(since=712)


@packet(id=5)
class DisconnectPacket:
    """Sent from the server to a client to trigger a disconnection."""

    reason: DisconnectFailReason = field(type=varint32, since=622)
    messages: DisconnectPacketMessages | None = field(type=Union)
