from enum import IntEnum, auto
from typing import Union

from protocol import field, int32, packet, value

package = "bedrock.protocol"


class MinecraftPacketIds(IntEnum):
    KEEP_ALIVE = 0
    LOGIN = 1
    PLAY_STATUS = 2
    SERVER_TO_CLIENT_HANDSHAKE = 3
    CLIENT_TO_SERVER_HANDSHAKE = 4
    DISCONNECT = 5
    RESOURCE_PACKS_INFO = 6
    RESOURCE_PACK_STACK = 7
    RESOURCE_PACK_CLIENT_RESPONSE = 8
    TEXT = 9
    SET_TIME = 10
    START_GAME = 11
    ADD_PLAYER = 12
    ADD_ACTOR = 13
    REMOVE_ACTOR = 14
    ADD_ITEM_ACTOR = 15
    SERVER_PLAYER_POST_MOVE_POSITION = 16
    TAKE_ITEM_ACTOR = 17
    MOVE_ABSOLUTE_ACTOR = 18
    MOVE_PLAYER = 19
    PASSENGER_JUMP_DEPRECATED = 20
    UPDATE_BLOCK = 21
    ADD_PAINTING = 22
    TICK_SYNC_DEPRECATED = 23
    LEVEL_SOUND_EVENT_V1_DEPRECATED = 24
    LEVEL_EVENT = 25
    TILE_EVENT = 26
    ACTOR_EVENT = 27
    MOB_EFFECT = 28
    UPDATE_ATTRIBUTES = 29
    INVENTORY_TRANSACTION = 30
    PLAYER_EQUIPMENT = 31
    MOB_ARMOR_EQUIPMENT = 32
    INTERACT = 33
    BLOCK_PICK_REQUEST = 34
    ACTOR_PICK_REQUEST = 35
    PLAYER_ACTION = 36
    ACTOR_FALL_DEPRECATED = 37
    HURT_ARMOR = 38
    SET_ACTOR_DATA = 39
    SET_ACTOR_MOTION = 40
    SET_ACTOR_LINK = 41
    SET_HEALTH = 42
    SET_SPAWN_POSITION = 43
    ANIMATE = 44
    RESPAWN = 45
    CONTAINER_OPEN = 46
    CONTAINER_CLOSE = 47
    PLAYER_HOTBAR = 48
    INVENTORY_CONTENT = 49
    INVENTORY_SLOT = 50
    CONTAINER_SET_DATA = 51
    CRAFTING_DATA = 52
    CRAFTING_EVENT_DEPRECATED = 53
    GUI_DATA_PICK_ITEM = 54
    ADVENTURE_SETTINGS_DEPRECATED = 55
    BLOCK_ACTOR_DATA = 56
    PLAYER_INPUT_DEPRECATED = 57
    FULL_CHUNK_DATA = 58
    SET_COMMANDS_ENABLED = 59
    SET_DIFFICULTY = 60
    CHANGE_DIMENSION = 61
    SET_PLAYER_GAME_TYPE = 62
    PLAYER_LIST = 63
    SIMPLE_EVENT = 64
    LEGACY_TELEMETRY_EVENT = 65
    SPAWN_EXPERIENCE_ORB = 66
    MAP_DATA = 67
    MAP_INFO_REQUEST = 68
    REQUEST_CHUNK_RADIUS = 69
    CHUNK_RADIUS_UPDATED = 70
    ITEM_FRAME_DROP_ITEM_DEPRECATED = 71
    GAME_RULES_CHANGED = 72
    CAMERA = 73
    BOSS_EVENT = 74
    SHOW_CREDITS = 75
    AVAILABLE_COMMANDS = 76
    COMMAND_REQUEST = 77
    COMMAND_BLOCK_UPDATE = 78
    COMMAND_OUTPUT = 79
    UPDATE_TRADE = 80
    UPDATE_EQUIP = 81
    RESOURCE_PACK_DATA_INFO = 82
    RESOURCE_PACK_CHUNK_DATA = 83
    RESOURCE_PACK_CHUNK_REQUEST = 84
    TRANSFER = 85
    PLAY_SOUND = 86
    STOP_SOUND = 87
    SET_TITLE = 88
    ADD_BEHAVIOR_TREE = 89
    STRUCTURE_BLOCK_UPDATE = 90
    SHOW_STORE_OFFER = 91
    PURCHASE_RECEIPT = 92
    PLAYER_SKIN = 93
    SUBCLIENT_LOGIN = 94
    AUTOMATION_CLIENT_CONNECT = 95
    SET_LAST_HURT_BY = 96
    BOOK_EDIT = 97
    NPC_REQUEST = 98
    PHOTO_TRANSFER = 99
    SHOW_MODAL_FORM = 100
    MODAL_FORM_RESPONSE = 101
    SERVER_SETTINGS_REQUEST = 102
    SERVER_SETTINGS_RESPONSE = 103
    SHOW_PROFILE = 104
    SET_DEFAULT_GAME_TYPE = 105
    REMOVE_OBJECTIVE = 106
    SET_DISPLAY_OBJECTIVE = 107
    SET_SCORE = 108
    LAB_TABLE = 109
    UPDATE_BLOCK_SYNCED = 110
    MOVE_DELTA_ACTOR = 111
    SET_SCOREBOARD_IDENTITY = 112
    SET_LOCAL_PLAYER_AS_INIT = 113
    UPDATE_SOFT_ENUM = 114
    PING = 115
    BLOCK_PALETTE_DEPRECATED = 116
    SCRIPT_CUSTOM_EVENT = 117
    SPAWN_PARTICLE_EFFECT = 118
    AVAILABLE_ACTOR_ID_LIST = 119
    LEVEL_SOUND_EVENT_V2_DEPRECATED = 120
    NETWORK_CHUNK_PUBLISHER_UPDATE = 121
    BIOME_DEFINITION_LIST = 122
    LEVEL_SOUND_EVENT = 123
    LEVEL_EVENT_GENERIC = 124
    LECTERN_UPDATE = 125
    VIDEO_STREAM_CONNECT_DEPRECATED = 126
    ADD_ENTITY_DEPRECATED = 127
    REMOVE_ENTITY_DEPRECATED = 128
    CLIENT_CACHE_STATUS = 129
    ON_SCREEN_TEXTURE_ANIMATION = 130
    MAP_CREATE_LOCKED_COPY = 131
    STRUCTURE_TEMPLATE_DATA_EXPORT_REQUEST = 132
    STRUCTURE_TEMPLATE_DATA_EXPORT_RESPONSE = 133
    UNUSED_PLS_USE_ME = 134
    CLIENT_CACHE_BLOB_STATUS_PACKET = 135
    CLIENT_CACHE_MISS_RESPONSE_PACKET = 136
    EDUCATION_SETTINGS_PACKET = 137
    EMOTE = 138
    MULTIPLAYER_SETTINGS_PACKET = 139
    SETTINGS_COMMAND_PACKET = 140
    ANVIL_DAMAGE = 141
    COMPLETED_USING_ITEM = 142
    NETWORK_SETTINGS = 143
    PLAYER_AUTH_INPUT_PACKET = 144
    CREATIVE_CONTENT = 145
    PLAYER_ENCHANT_OPTIONS = 146
    ITEM_STACK_REQUEST = 147
    ITEM_STACK_RESPONSE = 148
    PLAYER_ARMOR_DAMAGE = 149
    CODE_BUILDER_PACKET = 150
    UPDATE_PLAYER_GAME_TYPE = 151
    EMOTE_LIST = 152
    POSITION_TRACKING_DB_SERVER_BROADCAST = 153
    POSITION_TRACKING_DB_CLIENT_REQUEST = 154
    DEBUG_INFO_PACKET = 155
    PACKET_VIOLATION_WARNING = 156
    MOTION_PREDICTION_HINTS = 157
    TRIGGER_ANIMATION = 158
    CAMERA_SHAKE = 159
    PLAYER_FOG_SETTING = 160
    CORRECT_PLAYER_MOVE_PREDICTION_PACKET = 161
    ITEM_REGISTRY_PACKET = 162
    FILTER_TEXT_PACKET_DEPRECATED = 163
    CLIENT_BOUND_DEBUG_RENDERER_PACKET = 164
    SYNC_ACTOR_PROPERTY = 165
    ADD_VOLUME_ENTITY_PACKET = 166
    REMOVE_VOLUME_ENTITY_PACKET = 167
    SIMULATION_TYPE_PACKET = 168
    NPC_DIALOGUE_PACKET = 169
    EDU_URI_RESOURCE_PACKET = 170
    CREATE_PHOTO_PACKET = 171
    UPDATE_SUB_CHUNK_BLOCKS = 172
    PHOTO_INFO_REQUEST_DEPRECATED = 173
    SUB_CHUNK_PACKET = 174
    SUB_CHUNK_REQUEST_PACKET = 175
    PLAYER_START_ITEM_COOLDOWN = 176
    SCRIPT_MESSAGE_PACKET = 177
    CODE_BUILDER_SOURCE_PACKET = 178
    TICKING_AREAS_LOAD_STATUS = 179
    DIMENSION_DATA_PACKET = 180
    AGENT_ACTION = 181
    CHANGE_MOB_PROPERTY = 182
    LESSON_PROGRESS_PACKET = 183
    REQUEST_ABILITY_PACKET = 184
    REQUEST_PERMISSIONS_PACKET = 185
    TOAST_REQUEST = 186
    UPDATE_ABILITIES_PACKET = 187
    UPDATE_ADVENTURE_SETTINGS_PACKET = 188
    DEATH_INFO = 189
    EDITOR_NETWORK_PACKET = 190
    FEATURE_REGISTRY_PACKET = 191
    SERVER_STATS = 192
    REQUEST_NETWORK_SETTINGS = 193
    GAME_TEST_REQUEST_PACKET = 194
    GAME_TEST_RESULTS_PACKET = 195
    PLAYER_CLIENT_INPUT_PERMISSIONS = 196
    CLIENT_CHEAT_ABILITY_PACKET_DEPRECATED = 197
    CAMERA_PRESETS = 198
    UNLOCKED_RECIPES = 199
    TITLE_SPECIFIC_PACKETS_START = 200
    TITLE_SPECIFIC_PACKETS_END = 299
    CAMERA_INSTRUCTION = 300
    COMPRESSED_BIOME_DEFINITION_LIST_DEPRECATED = 301
    TRIM_DATA = 302
    OPEN_SIGN = 303
    AGENT_ANIMATION = 304
    REFRESH_ENTITLEMENTS_PACKET = 305
    PLAYER_TOGGLE_CRAFTER_SLOT_REQUEST_PACKET = 306
    SET_PLAYER_INVENTORY_OPTIONS = 307
    SET_HUD_PACKET = 308
    AWARD_ACHIEVEMENT_PACKET = 309
    CLIENTBOUND_CLOSE_SCREEN = 310
    CLIENTBOUND_LOADING_SCREEN_PACKET_DEPRECATED = 311
    SERVERBOUND_LOADING_SCREEN_PACKET = 312
    JIGSAW_STRUCTURE_DATA_PACKET = 313
    CURRENT_STRUCTURE_FEATURE_PACKET = 314
    SERVERBOUND_DIAGNOSTICS_PACKET = 315
    CAMERA_AIM_ASSIST = 316
    CONTAINER_REGISTRY_CLEANUP = 317
    MOVEMENT_EFFECT = 318
    SET_MOVEMENT_AUTHORITY_MODE_DEPRECATED = 319
    CAMERA_AIM_ASSIST_PRESETS = 320
    CLIENT_CAMERA_AIM_ASSIST = 321
    CLIENT_MOVEMENT_PREDICTION_SYNC_PACKET = 322
    UPDATE_CLIENT_OPTIONS = 323
    PLAYER_VIDEO_CAPTURE_PACKET = 324
    PLAYER_UPDATE_ENTITY_OVERRIDES_PACKET = 325
    PLAYER_LOCATION = 326
    CLIENTBOUND_CONTROL_SCHEME_SET_PACKET = 327
    PRIMITIVE_SHAPES_PACKET = 328
    SERVERBOUND_PACK_SETTING_CHANGE_PACKET = 329
    CLIENTBOUND_DATA_STORE = 330
    GRAPHICS_PARAMETER_OVERRIDE_PACKET = 331
    SERVERBOUND_DATA_STORE = 332
    CLIENTBOUND_DATA_DRIVEN_UI_SHOW_SCREEN = 333
    CLIENTBOUND_DATA_DRIVEN_UI_CLOSE_SCREEN = 334
    CLIENTBOUND_DATA_DRIVEN_UI_RELOAD = 335
    CLIENTBOUND_TEXTURE_SHIFT_PACKET = 336
    VOXEL_SHAPES_PACKET = 337
    CAMERA_SPLINE = 338
    CAMERA_AIM_ASSIST_ACTOR_PRIORITY = 339
    RESOURCE_PACKS_READY_FOR_VALIDATION = 340
    LOCATOR_BAR_PACKET = 341
    PARTY_CHANGED = 342
    SERVERBOUND_DATA_DRIVEN_SCREEN_CLOSED = 343
    SYNC_WORLD_CLOCKS = 344
    CLIENTBOUND_ATTRIBUTE_LAYER_SYNC_PACKET = 345
    SERVER_STORE_INFO = 346
    SERVER_PRESENCE_INFO = 347
    CLIENTBOUND_UPDATE_SOUND_DATA = value(348, since=1001)
    SEND_PARTY_DESTINATION_COOKIE = value(349, since=1001)
    PARTY_DESTINATION_COOKIE_RESPONSE = value(350, since=1001)
    SET_PLAYER_FURNACE_OPTIONS = value(351, since=2187)
    RECORD_STARTED = value(352, since=2187)
    END_ID = auto()


class DisconnectFailReason(IntEnum):
    UNKNOWN = 0
    CANT_CONNECT_NO_INTERNET = 1
    NO_PERMISSIONS = 2
    UNRECOVERABLE_ERROR = 3
    THIRD_PARTY_BLOCKED = 4
    THIRD_PARTY_NO_INTERNET = 5
    THIRD_PARTY_BAD_IP = 6
    THIRD_PARTY_NO_SERVER_OR_SERVER_LOCKED = 7
    VERSION_MISMATCH = 8
    SKIN_ISSUE = 9
    INVITE_SESSION_NOT_FOUND = 10
    EDU_LEVEL_SETTINGS_MISSING = 11
    LOCAL_SERVER_NOT_FOUND = 12
    LEGACY_DISCONNECT = 13
    INTERNAL_USER_LEAVE_GAME_ATTEMPTED = 14
    PLATFORM_LOCKED_SKINS_ERROR = 15
    REALMS_WORLD_UNASSIGNED = 16
    REALMS_SERVER_CANT_CONNECT = 17
    REALMS_SERVER_HIDDEN = 18
    REALMS_SERVER_DISABLED_BETA = 19
    REALMS_SERVER_DISABLED = 20
    CROSS_PLATFORM_DISABLED = 21
    TESTONLY_CANT_CONNECT = 22
    SESSION_NOT_FOUND = 23
    CLIENT_SETTINGS_INCOMPATIBLE_WITH_SERVER = 24
    SERVER_FULL = 25
    INVALID_PLATFORM_SKIN = 26
    EDITION_VERSION_MISMATCH = 27
    EDITION_MISMATCH = 28
    LEVEL_NEWER_THAN_EXE_VERSION = 29
    INTERNAL_NO_FAIL_OCCURRED = 30
    BANNED_SKIN = 31
    TIMEOUT = 32
    SERVER_NOT_FOUND = 33
    OUTDATED_SERVER = 34
    OUTDATED_CLIENT = 35
    NO_PREMIUM_PLATFORM = 36
    MULTIPLAYER_DISABLED = 37
    NO_WI_FI = 38
    WORLD_CORRUPTION = 39
    NO_REASON = 40
    DISCONNECTED = 41
    INVALID_PLAYER = 42
    LOGGED_IN_OTHER_LOCATION = 43
    SERVER_ID_CONFLICT = 44
    NOT_ALLOWED = 45
    NOT_AUTHENTICATED = 46
    INVALID_TENANT = 47
    UNKNOWN_PACKET = 48
    UNEXPECTED_PACKET = 49
    INVALID_COMMAND_REQUEST_PACKET = 50
    HOST_SUSPENDED = 51
    LOGIN_PACKET_NO_REQUEST = 52
    LOGIN_PACKET_NO_CERT = 53
    MISSING_CLIENT = 54
    KICKED = 55
    KICKED_FOR_EXPLOIT = 56
    KICKED_FOR_IDLE = 57
    RESOURCE_PACK_PROBLEM = 58
    INCOMPATIBLE_PACK = 59
    OUT_OF_STORAGE = 60
    INVALID_LEVEL = 61
    DISCONNECT_PACKET = 62
    BLOCK_MISMATCH = 63
    INVALID_HEIGHTS = 64
    INVALID_WIDTHS = 65
    CONNECTION_LOST = 66
    ZOMBIE_CONNECTION = 67
    SHUTDOWN = 68
    REASON_NOT_SET = 69
    LOADING_STATE_TIMEOUT = 70
    RESOURCE_PACK_LOADING_FAILED = 71
    SEARCHING_FOR_SESSION_LOADING_SCREEN_FAILED = 72
    NETHER_NET_PROTOCOL_VERSION = 73
    SUBSYSTEM_STATUS_ERROR = 74
    EMPTY_AUTH_FROM_DISCOVERY = 75
    EMPTY_URL_FROM_DISCOVERY = 76
    EXPIRED_AUTH_FROM_DISCOVERY = 77
    UNKNOWN_SIGNAL_SERVICE_SIGN_IN_FAILURE = 78
    XBL_JOIN_LOBBY_FAILURE = 79
    UNSPECIFIED_CLIENT_INSTANCE_DISCONNECTION = 80
    NETHER_NET_SESSION_NOT_FOUND = 81
    NETHER_NET_CREATE_PEER_CONNECTION = 82
    NETHER_NET_ICE = 83
    NETHER_NET_CONNECT_REQUEST = 84
    NETHER_NET_CONNECT_RESPONSE = 85
    NETHER_NET_NEGOTIATION_TIMEOUT = 86
    NETHER_NET_INACTIVITY_TIMEOUT = 87
    STALE_CONNECTION_BEING_REPLACED = 88
    REALMS_SESSION_NOT_FOUND = 89
    BAD_PACKET = 90
    NETHER_NET_FAILED_TO_CREATE_OFFER = 91
    NETHER_NET_FAILED_TO_CREATE_ANSWER = 92
    NETHER_NET_FAILED_TO_SET_LOCAL_DESCRIPTION = 93
    NETHER_NET_FAILED_TO_SET_REMOTE_DESCRIPTION = 94
    NETHER_NET_NEGOTIATION_TIMEOUT_WAITING_FOR_RESPONSE = 95
    NETHER_NET_NEGOTIATION_TIMEOUT_WAITING_FOR_ACCEPT = 96
    NETHER_NET_INCOMING_CONNECTION_IGNORED = 97
    NETHER_NET_SIGNALING_PARSING_FAILURE = 98
    NETHER_NET_SIGNALING_UNKNOWN_ERROR = 99
    NETHER_NET_SIGNALING_UNICAST_DELIVERY_FAILED = 100
    NETHER_NET_SIGNALING_BROADCAST_DELIVERY_FAILED = 101
    NETHER_NET_SIGNALING_GENERIC_DELIVERY_FAILED = 102
    EDITOR_MISMATCH_EDITOR_WORLD = 103
    EDITOR_MISMATCH_VANILLA_WORLD = 104
    WORLD_TRANSFER_NOT_PRIMARY_CLIENT = 105
    INTERNAL_REQUEST_SERVER_SHUTDOWN = 106
    CLIENT_GAME_SETUP_CANCELLED = 107
    CLIENT_GAME_SETUP_FAILED = 108
    NO_VENUE = 109
    NETHER_NET_SIGNALING_SIGNIN_FAILED = 110
    SESSION_ACCESS_DENIED = 111
    SERVICE_SIGNIN_ISSUE = 112
    NETHER_NET_NO_SIGNALING_CHANNEL = 113
    NETHER_NET_NOT_LOGGED_IN = 114
    NETHER_NET_CLIENT_SIGNALING_ERROR = 115
    SUB_CLIENT_LOGIN_DISABLED = 116
    DEEP_LINK_TRYING_TO_OPEN_DEMO_WORLD_WHILE_SIGNED_IN = 117
    ASYNC_JOIN_TASK_DENIED = 118
    REALMS_TIMELINE_REQUIRED = 119
    GUEST_WITHOUT_HOST = 120
    FAILED_TO_JOIN_EXPERIENCE = 121
    NETHER_NET_DATA_CHANNEL_CLOSED = 122
    DISCOVERY_ENVIRONMENT_MISMATCH = 123
    HOST_WITHOUT_KEYS = 124
    HOST_SIGNED_OUT = 125
    SCRIPT_WATCHDOG_EXCEPTION = 126
    SCRIPT_MEMORY_LIMIT_EXCEEDED = 127
    STORAGE_LOW_DURING_GAMEPLAY = 128
    STORAGE_FULL_DURING_GAMEPLAY = 129
    LEVEL_STORAGE_CORRUPTION = 130
    EDITION_MISMATCH_VANILLA_TO_EDU = 131
    EDITION_MISMATCH_EDU_TO_VANILLA = 132
    EDITOR_MISMATCH_EDITOR_TO_VANILLA = 133
    EDITOR_MISMATCH_VANILLA_TO_EDITOR = 134
    DENY_LISTED = 135
    NONCE_MISSING = 136
    NONCE_NOT_FOUND = 137
    NONCE_EXPIRED = 138
    NONCE_NOT_VALID = 139
    HOST_DISCONNECTED = 140
    EDITOR_JOIN_INTENT_POLICY_FAILURE = 141
    NETHER_NET_IDENTITY_NOT_ALLOWED = 142
    INVALID_NAME = 143
    EXPIRED_TOKEN = 144
    HOST_ACCEPTS_NO_TYPE_OF_AUTH = 145
    NOT_AUTHENTICATED_FAST_FAIL = 146
    EDITOR_NOT_ALLOWED = 147
    MISSING_STRUCTURE_DATA = value(148, since=2187)
    UNSUPPORTED_TRANSPORT = value(149, since=2187)
    MAX_DISCONNECT_FAIL_REASON = auto()


class PacketViolationType(IntEnum):
    UNKNOWN = -1
    PACKET_MALFORMED = 0


class PacketViolationSeverity(IntEnum):
    UNKNOWN = -1
    WARNING = 0
    FINAL_WARNING = 1
    TERMINATING_CONNECTION = 2


@packet(id=1)
class LoginPacket:
    """The client's login, repeating the protocol version it speaks and carrying the
    identity and client data it authenticates with."""

    client_network_version: int32 = field(endian="big")
    connection_request: bytes


class DisconnectPacketMessages:
    message: str
    filtered_message: str


@packet(id=5)
class DisconnectPacket:
    """Ends the connection, naming the reason the client shows and, unless the
    disconnection screen is skipped, the message it shows with it."""

    reason: DisconnectFailReason
    messages: Union[DisconnectPacketMessages, None]


@packet(id=156)
class PacketViolationWarningPacket:
    """Sent by the client when a packet fails to parse, naming the offending packet
    and how the client is reacting to it."""

    violation_type: PacketViolationType
    violation_severity: PacketViolationSeverity
    violating_packet_id: MinecraftPacketIds
    violation_context: str


@packet(id=193)
class RequestNetworkSettingsPacket:
    """The first packet a client sends, carrying the protocol version it speaks so
    the server can answer with its network settings."""

    client_network_version: int32 = field(endian="big")
